### ISSUE TITLE
issue on Metropolis with Theano0.8.0rc1 (master of 20160319) and Pymc3 (master of 20160319) getting_started.ipynb' on Windows

### ISSUE THREAD

**Issue by stonebig** [pymc-devs/pymc#1029]
Hi,

I get the following error on getting_started.ipynb. As I'm new to the module and it's on Python3.4.4 64bit/mingwpy/windows7/latest Theano trunk/no gpu (only cgohlke numpy-mkl), it may or may not be a new error, a bad user error, a Theano error; or a pymc3 error:

```
from pymc3 import Metropolis 

with disaster_model:
    step1 = NUTS([early_rate, late_rate])

    # Use Metropolis for switchpoint, and missing values since it accommodates discrete variables
    step2 = Metropolis([switchpoint, disasters.missing_values[0]] )

    trace = sample(10000, step=[step1, step2])
```

```
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

TypeError: expected type_num 9 (NPY_INT64) got 7

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-19-7d2f5d9a03b4> in <module>()
      7     step2 = Metropolis([switchpoint, disasters.missing_values[0]] )
      8 
----> 9     trace = sample(10000, step=[step1, step2])

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    147         sample_func = _sample
    148 
--> 149     return sample_func(**sample_args)
    150 
    151 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    156     progress = progress_bar(draws)
    157     try:
--> 158         for i, strace in enumerate(sampling):
    159             if progressbar:
    160                 progress.update(i)

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    238         if i == tune:
    239             step = stop_tuning(step)
--> 240         point = step.step(point)
    241         strace.record(point)
    242         yield strace

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    116         bij = DictToArrayBijection(self.ordering, point)
    117 
--> 118         apoint = self.astep(bij.map(point))
    119         return bij.rmap(apoint)
    120 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\metropolis.py in astep(self, q0)
    123             q = q0 + delta
    124 
--> 125         q_new = metrop_select(self.delta_logp(q, q0), q, q0)
    126 
    127         if q_new is q:

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(111,), (2,), (2,)]
Inputs strides: [(8,), (4,), (8,)]
Inputs values: ['not shown', array([0, 0]), array([39, 83], dtype=int64)]
Outputs clients: [[Elemwise{Composite{Switch((i0 * GE(i1, i2)), ((Switch(i3, i4, (i1 * i5)) - scalar_gammaln((i6 + i1))) - i7), i4)}}(Elemwise{ge,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1,) of 0}, InplaceDimShuffle{x}.0, TensorConstant{(1,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-a2c400c3581a>", line 14, in <module>
    disasters = Poisson('disasters', rate, observed=disaster_data)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\distributions\distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 272, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 544, in __init__
    data = as_tensor(data, name,model,distribution.dtype)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 512, in as_tensor
    missing_values)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by stonebig** [comment]
Further down, I get another error:

```
from pymc3 import summary
summary(trace, vars=['x1'])
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-091c903e8cdf> in <module>()
      1 from pymc3 import summary
      2 
----> 3 summary(trace, vars=['x1'])

TypeError: summary() got an unexpected keyword argument 'vars'
```

I think it should rather be

```
 summary(trace, varnames=['x1'])
```

**Comment by twiecki** [comment]
Yes, good catch. Thank you.

**Comment by stonebig** [comment]
fix for `varnames` https://github.com/pymc-devs/pymc3/pull/1030

**Comment by hvasbath** [comment]
The first error is because if this issue:
https://github.com/pymc-devs/pymc3/issues/1005
You might try fixing the line with the line that I suggested there, as the fix is still not in the master branch, because we dont know if it works for all cases. So would be nice if you could try ;) .

**Comment by stonebig** [comment]
Line by line is a bit complicating things. Don't you have a pull request for that ? or a pull request that contains it ?
I personnally don't mind of possible smaller dark corner issues, if the very first show-room getting-started example is fixed.

**Comment by hvasbath** [comment]
I tried to send a seperate pull request for this issue. See the metropolis file there in the disrete index branch. But somehow this got mixed with the ATMCMC stuff although I switched the branch. If someone could explain me why, I would very much appreciate it, I am very new to this git stuff.

**Comment by springcoil** [comment]
What was your remote.
Can you copy and paste your workflow here so we can help you debug?

On Mon, Mar 21, 2016 at 4:04 PM, eigenblutwurst notifications@github.com
wrote:

> I tried to send a seperate pull request for this issue. See the metropolis
> file there in the disrete index branch. But somehow this got mixed with the
> ATMCMC stuff although I switched the branch. If someone could explain me
> why, I would very much appreciate it, I am very new to this git stuff.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/1029#issuecomment-199328659

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by hvasbath** [comment]
Thanks for trying to help!
git branch discrete_index
git checkout discrete_index
did the change in metropolis.py
git add metropolis.py
git commit
git push my_origin discrete_index

**Comment by springcoil** [comment]
Before the final push
do git rebase -i my_origin
And squash your commits together or remove the ones you don't want by hand.

On Mon, Mar 21, 2016 at 4:26 PM, eigenblutwurst notifications@github.com
wrote:

> git branch discrete_index
> git checkout discrete_index
> did the change in metropolis.py
> git add metropolis.py
> git commit
> git push my_origin discrete_index
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/1029#issuecomment-199338709

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by stonebig** [comment]
hum, 

I failed the same, on getting_started.ipynb example...maybe I missed a step, so I will wait for merging

**Comment by fonnesbeck** [comment]
Is this issue ongoing?

**Comment by stonebig** [comment]
let me check (getting_started.ipynb is rather slow on an old pc without cuda)

... currently stopped at this:
![getting_started_pymc3](https://cloud.githubusercontent.com/assets/4312421/18256124/75e36692-73b1-11e6-8637-949b6d8c306d.PNG)

**Comment by stonebig** [comment]
after removing a ")", I fail on next cell:

```
print(len(returns))
```

```
3812
```

![getting_started_pymc3_01](https://cloud.githubusercontent.com/assets/4312421/18256194/5137f32a-73b2-11e6-9922-a28a5f99acfa.PNG)

```
returns.plot(figsize=(10, 6))
plt.ylabel('daily returns in %');
```

```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-dd5647595515> in <module>()
----> 1 returns.plot(figsize=(10, 6))
      2 plt.ylabel('daily returns in %');

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pandas\tools\plotting.py in __call__(self, x, y, kind, ax, subplots, sharex, sharey, layout, figsize, use_index, title, grid, legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize, colormap, table, yerr, xerr, secondary_y, sort_columns, **kwds)
   3738                           fontsize=fontsize, colormap=colormap, table=table,
   3739                           yerr=yerr, xerr=xerr, secondary_y=secondary_y,
-> 3740                           sort_columns=sort_columns, **kwds)
   3741     __call__.__doc__ = plot_frame.__doc__
   3742 

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pandas\tools\plotting.py in plot_frame(data, x, y, kind, ax, subplots, sharex, sharey, layout, figsize, use_index, title, grid, legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize, colormap, table, yerr, xerr, secondary_y, sort_columns, **kwds)
   2612                  yerr=yerr, xerr=xerr,
   2613                  secondary_y=secondary_y, sort_columns=sort_columns,
-> 2614                  **kwds)
   2615 
   2616 

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pandas\tools\plotting.py in _plot(data, x, y, subplots, ax, kind, **kwds)
   2439         plot_obj = klass(data, subplots=subplots, ax=ax, kind=kind, **kwds)
   2440 
-> 2441     plot_obj.generate()
   2442     plot_obj.draw()
   2443     return plot_obj.result

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pandas\tools\plotting.py in generate(self)
   1024     def generate(self):
   1025         self._args_adjust()
-> 1026         self._compute_plot_data()
   1027         self._setup_subplots()
   1028         self._make_plot()

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pandas\tools\plotting.py in _compute_plot_data(self)
   1133         if is_empty:
   1134             raise TypeError('Empty {0!r}: no numeric data to '
-> 1135                             'plot'.format(numeric_data.__class__.__name__))
   1136 
   1137         self.data = numeric_data

TypeError: Empty 'DataFrame': no numeric data to plot
```

**Comment by stonebig** [comment]
then it tells me bad things about S&P500:
![getting_started_pymc3_02](https://cloud.githubusercontent.com/assets/4312421/18256246/f26b8bb2-73b2-11e6-9b51-e2165402537a.PNG)

**Comment by stonebig** [comment]
nota: using pymc3 master of 2016-08-23 (... continuing further, slow pc) .... finaly the same sort of error for Metropolis:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

TypeError: expected type_num 9 (NPY_INT64) got 7

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-13-7d2f5d9a03b4> in <module>()
      7     step2 = Metropolis([switchpoint, disasters.missing_values[0]] )
      8 
----> 9     trace = sample(10000, step=[step1, step2])

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    149         sample_func = _sample
    150 
--> 151     return sample_func(**sample_args)
    152 
    153 

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    158     progress = progress_bar(draws)
    159     try:
--> 160         for i, strace in enumerate(sampling):
    161             if progressbar:
    162                 progress.update(i)

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    240         if i == tune:
    241             step = stop_tuning(step)
--> 242         point = step.step(point)
    243         strace.record(point)
    244         yield strace

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    125         bij = DictToArrayBijection(self.ordering, point)
    126 
--> 127         apoint = self.astep(bij.map(point))
    128         return bij.rmap(apoint)
    129 

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\metropolis.py in astep(self, q0)
    126             q = q0 + delta
    127 
--> 128         q_new = metrop_select(self.delta_logp(q, q0), q, q0)
    129 
    130         if q_new is q:

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(111,), (2,), (2,)]
Inputs strides: [(8,), (4,), (8,)]
Inputs values: ['not shown', array([3, 1]), array([39, 83], dtype=int64)]
Outputs clients: [[Elemwise{Composite{Switch((i0 * EQ(i1, i2)), i2, Switch((i3 * GE(i1, i2)), ((Switch(i0, i4, (i1 * i5)) - scalar_gammaln((i6 + i1))) - i7), i4))}}(Elemwise{eq,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1,) of 0}, Elemwise{ge,no_inplace}.0, TensorConstant{(1,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-a2c400c3581a>", line 14, in <module>
    disasters = Poisson('disasters', rate, observed=disaster_data)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\distributions\distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 306, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 580, in __init__
    data = as_tensor(data, name, model, distribution)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.4\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 547, in as_tensor
    dataTensor = tt.set_subtensor(constant[data.mask.nonzero()], missing_values)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by stonebig** [comment]
... / ... end of test . maybe mingwpy or theano is the problem, or windows

**Comment by fonnesbeck** [comment]
Ah, thanks. All sorts of problems here. I will get a PR up that fixes this.
