### ISSUE TITLE
numpy not listed in module reqs

### ISSUE THREAD

**Issue by SkyLeach** [pymc-devs/pymc#1037]
``` bash
/apps/python3.5/bin/pip install --upgrade pymc
Collecting pymc
  Downloading pymc-2.3.6.tar.gz (348kB)
    100% |████████████████████████████████| 358kB 2.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dxfgcfsw/pymc/setup.py", line 8, in <module>
        from numpy.distutils.misc_util import Configuration
    ImportError: No module named 'numpy'
```

**Comment by twiecki** [comment]
That's a pymc 2 issue: https://github.com/pymc-devs/pymc
