### ISSUE TITLE
Error in assigning step method to variables.

### ISSUE THREAD

**Issue by shobhit6993** [pymc-devs/pymc#1070]
I have a model similar to a Guassian Mixture Model, with the modification that every observation has a separate probability distribution over the clusters (similar to the distribution of words over topics in LDA)

``` .python
k = 3
ndata = 30
alpha =  np.array([0.1] * k)
with pm.Model() as model:
        p = [pm.Dirichlet('p%d' % i, alpha, shape=k) for i in xrange(0, ndata)]

        # Jeffrey's prior for sd
        log_sigma = pm.Uniform('log_sigma', lower=-4, upper=-0.5, shape=k)
        sigma = pm.Deterministic('sigma', pm.exp(log_sigma))

        mu = pm.Normal('mu', mu=10, sd=2, shape=k)

        categ = [pm.Categorical('categ%d' % i, p=p[i]) for i in xrange(0, ndata)]

        obs = [pm.Normal('obs%d' % i,
                      mu=mu[categ[i]],
                      sd=sigma[categ[i]],
                      observed=data[i]) for i in xrange(0, ndata)]

        num_iter = 10000
        num_burn = 5000
        thin = 1

        var_list = [sigma, mu]
        for i in xrange(0, ndata):
            var_list.append(p[i])
            var_list.append(obs[i])

        step1 = pm.Metropolis(vars=var_list)

        categ_list = []
        for i in xrange(0, ndata):
            categ_list.append(categ[i])
        step2 = pm.ElemwiseCategoricalStep(vars=categ_list, values=[0,1,2])

        tr = pm.sample(num_iter, step=[step1, step2])
```

The above code throws the following error:

```
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    tr = pm.sample(num_iter, step=[step1, step2])
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/sampling.py", line 150, in sample
    return sample_func(**sample_args)
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/sampling.py", line 159, in _sample
    for i, strace in enumerate(sampling):
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/sampling.py", line 241, in _iter_sample
    point = step.step(point)
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/step_methods/compound.py", line 14, in step
    point = method.step(point)
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/step_methods/arraystep.py", line 89, in step
    apoint = self.astep(bij.map(point), *inputs)
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/step_methods/gibbs.py", line 40, in astep
    p = array([logp(v * self.sh) for v in self.values])
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/blocking.py", line 119, in __call__
    return self.fa(self.fb(x))
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/blocking.py", line 64, in rmap
    dpt[var] = np.atleast_1d(apt)[slc].reshape(shp).astype(dtyp)
ValueError: total size of new array must be unchanged
```

which presumably indicates that there is some problem with the way I am assigning step methods to variables. Can someone point me to what I might be doing wrong?

**Comment by twiecki** [comment]
Is it possible to vectorize your model? That might make things faster and simpler.

**Comment by shobhit6993** [comment]
The only thing that is forcing me to use list of Stochastics is that I want `ndata` number of independent draws from a `k-`dimensional Dirichlet; how to do that is not immediately clear to me. This seems to be related to #535, in particular [your comment](https://github.com/pymc-devs/pymc3/issues/535#issuecomment-125348101).  I tried the following vectorized model, but the trace for `p` does not seem correct.

``` .python
k = 3
ndata = 6
alpha =  0.1*np.ones((ndata, k))
with pm.Model() as model:
        p = pm.Dirichlet('p', alpha, shape=(ndata, k))

        # Jeffrey's prior for sd
        log_sigma = pm.Uniform('log_sigma', lower=-4, upper=-0.5, shape=k)
        sigma = pm.Deterministic('sigma', pm.exp(log_sigma))

        mu = pm.Normal('mu', mu=10, sd=2, shape=k)

        categ = pm.Categorical('categ', p=p, shape=ndata)

        obs = pm.Normal('obs',
                      mu=mu[categ],
                      sd=sigma[categ],
                      observed=data)

        num_iter = 10000
        num_burn = 5000
        thin = 1

        step1 = pm.Metropolis(vars=[p, sigma, mu, obs])
        step2 = pm.ElemwiseCategoricalStep(vars=[categ], values=[0,1,2])

        tr = pm.sample(num_iter, step=[step1, step2])
        print tr['p'][num_burn + 5, :]
```

The trace for `p` looks like the following, which is not correct, since the elements of `p[i]` do not sum to one.

```
[[ 0.16666667  0.16666667  0.16666667]
 [ 0.16666667  0.16666667  0.16666667]
 [ 0.16666667  0.16666667  0.16666667]
 [ 0.16666667  0.16666667  0.16666667]
 [ 0.16666667  0.16666667  0.16666667]
 [ 0.16666667  0.16666667  0.16666667]]
```

What is the correct way to get `ndata` number of independent draws from a `k-`dimensional Dirichlet? Also, would the `Categorical` be able to correctly parse the `ndata x k` dimensional `p`?

**Comment by shobhit6993** [comment]
Oh, I just noticed that the trace of `p` is not technically incorrect, but looks non-intuitive (at least to me). The elements along `axis=1` (columns) sum to one, which seems to indicate that I ended up getting `k (=3)` number of `ndata-`dimensional (6-dimensional) draws from Dirichlet. Is this the expected behavior (i.e. the elements of one draw from dirichlet are supposed to be along `axis=1`)? Will the `Categorical` correctly parse this? 

Anyway, when I fix the shape argument in `p`, I get new errors (the lines changed are marked by comments)

``` .python
k = 3
ndata = 6
alpha =  0.1*np.ones((k, ndata))   # changed
with pm.Model() as model:
        p = pm.Dirichlet('p', alpha, shape=(k, ndata))  # changed

        log_sigma = pm.Uniform('log_sigma', lower=-4, upper=-0.5, shape=k)
        sigma = pm.Deterministic('sigma', pm.exp(log_sigma))

        mu = pm.Normal('mu', mu=10, sd=2, shape=k)

        # changed from shape=ndata; was throwing following error
        # ValueError: shape mismatch: objects cannot be broadcast to a single shape
        categ = pm.Categorical('categ', p=p, shape=(ndata, 1))

        obs = pm.Normal('obs',
                      mu=mu[categ],
                      sd=sigma[categ],
                      observed=data)

        num_iter = 10000
        num_burn = 5000
        thin = 1

        step1 = pm.Metropolis(vars=[p, sigma, mu, obs])
        step2 = pm.ElemwiseCategoricalStep(vars=[categ])

        tr = pm.sample(num_iter, step=[step1, step2])
        print tr['p'][num_burn + 5, :]
```

The above code throws the following error:

```
log_thunk_trace: There was a problem executing an Op.
Traceback (most recent call last):
  File "test.py", line 102, in <module>
    step2 = pm.ElemwiseCategoricalStep(vars=[categ])
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/step_methods/gibbs.py", line 37, in __init__
    super(ElemwiseCategoricalStep, self).__init__(vars, [elemwise_logp(model, self.var)])
  File "/home/shobhit/.local/lib/python2.7/site-packages/pymc3/step_methods/gibbs.py", line 54, in elemwise_logp
    return model.fn(add(*terms))
  File "/home/shobhit/.local/lib/python2.7/site-packages/theano/gof/op.py", line 668, in __call__
    required = thunk()
  File "/home/shobhit/.local/lib/python2.7/site-packages/theano/gof/op.py", line 883, in rval
    fill_storage()
  File "/home/shobhit/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1707, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "<string>", line 2, in reraise
ValueError: Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 6)

```

Am I using the correct `shape` for Categorical?

**Comment by twiecki** [comment]
I think it's correct that it throws that error:

```
        mu = pm.Normal('mu', mu=10, sd=2, shape=k)

        # changed from shape=ndata; was throwing following error
        # ValueError: shape mismatch: objects cannot be broadcast to a single shape
        categ = pm.Categorical('categ', p=p, shape=(ndata, 1))
```

You're indexing a 3D var with a 6D var.

**Comment by shobhit6993** [comment]
Using the transpose of `p` in the `Categorical` solved the issue.

``` .python
p = pm.Dirichlet('p', alpha, shape=(k, ndata))
mu = pm.Normal('mu', mu=10,  sd=2, shape=k)
categ = pm.Categorical('categ', p=p.T, shape=(1, ndata))   # changed
```

This seems to be an artifact of the way samples from a k-dimensional Dirichlet are generated. The elements of one draw are along `axis=1`, while Categorical seems to expect them to be along `axis=0`. Although this solved the issue, I would like to know if my understanding is correct, and if this indeed is the expected behavior (which seems a little non-intuitive to me).

**Comment by twiecki** [comment]
Thanks for following back up @shobhit6993. Can you open an issue about the inconsistency?

**Comment by shobhit6993** [comment]
@twiecki, sure, I'll leave this closed and open a new issue to avoid clutter.
