### ISSUE TITLE
Multivariate Gaussian Mixture Model with precision prior

### ISSUE THREAD

**Issue by benavente** [pymc-devs/pymc#1112]
Hi, I'm trying to model a multivariate gaussian mixture model with priors on the means and the precisions, similar to https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/gaussian_mixture_model.ipynb

The problem is that it seems that MvNormal does not support passing more than one precision matrix (?).

Here's my code:

``` python
N_COMPONENTS = 5
N_SAMPLES, N_DIMS = target_data.shape

# Dirichilet prior.
ALPHA_0 = np.ones(N_COMPONENTS)
# Component means prior.
MU_0 = np.zeros(N_DIMS)
LAMB_0 = 2. * np.eye(N_DIMS)
# Components precision prior.
BETA_0, BETA_1 = .1, 2.    # Covariance stds prior uniform limits.
L_0 = 5.       # LKJ corr. shape. Larger shape -> more biased to identity.

# In order to convert the upper triangular correlation values to a
# complete correlation matrix, we need to construct an index matrix:
# Source: http://stackoverflow.com/q/29759789/1901296
N_ELEMS = N_DIMS * (N_DIMS - 1) / 2
tri_index = np.zeros([N_DIMS, N_DIMS], dtype=int)
tri_index[np.triu_indices(N_DIMS, k=1)] = np.arange(N_ELEMS)
tri_index[np.triu_indices(N_DIMS, k=1)[::-1]] = np.arange(N_ELEMS)

with pm.Model() as model:
    # Component weight prior.
    pi = pm.Dirichlet('pi', ALPHA_0, testval=np.ones(N_COMPONENTS) / N_COMPONENTS)
    #pi_potential = pm.Potential('pi_potential', tensor.switch(tensor.min(pi) < .01, -np.inf, 0))

    ###################
    # Components plate.
    ###################
    # Component means.
    mus = [pm.MvNormal('mu_{}'.format(i), MU_0, LAMB_0, shape=N_DIMS)
           for i in range(N_COMPONENTS)]

    # Component precisions.
    #lamb = diag(sigma) * corr(corr_shape) * diag(sigma)
    corr_vecs = [
            pm.LKJCorr('corr_vec_{}'.format(i), L_0, N_DIMS)
            for i in range(N_COMPONENTS)
    ]
    # Transform the correlation vector representations to matrices.
    corrs = [
        tensor.fill_diagonal(corr_vecs[i][tri_index], 1.)
        for i in range(N_COMPONENTS)
    ]
    # Stds for the correlation matrices.
    cov_stds = pm.Uniform('cov_stds', BETA_0, BETA_1, shape=(N_COMPONENTS, N_DIMS))
    # Finally re-compose the covariance matrices using diag(sigma) * corr * diag(sigma)
    # Source http://austinrochford.com/posts/2015-09-16-mvn-pymc3-lkj.html
    lambs = []
    for i in range(N_COMPONENTS):
        std_diag = tensor.diag(cov_stds[i])
        cov = std_diag.dot(corrs[i]).dot(std_diag)
        lambs.append(tensor.nlinalg.matrix_inverse(cov))

    stacked_mus = tensor.stack(mus)
    stacked_lambs = tensor.stack(lambs)

    #####################
    # Observations plate.
    #####################
    z = pm.Categorical('z', pi, shape=N_SAMPLES)

    y = pm.MvNormal('y', stacked_mus[z], stacked_lambs[z], observed=target_data)
```

The exception I get:

``` python
Applied stickbreaking-transform to pi and added transformed pi_stickbreaking to model.
Applied interval-transform to cov_stds and added transformed cov_stds_interval to model.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-22-d039ddf4f27a> in <module>()
     60     z = pm.Categorical('z', pi, shape=N_SAMPLES)
     61 
---> 62     y = pm.MvNormal('y', stacked_mus[z], stacked_lambs[z], observed=target_data)

/usr/local/lib/python3.4/dist-packages/pymc3/distributions/distribution.py in __new__(cls, name, *args, **kwargs)
     23             data = kwargs.pop('observed', None)
     24             dist = cls.dist(*args, **kwargs)
---> 25             return model.Var(name, dist, data)
     26         elif name is None:
     27             return object.__new__(cls)  # for pickle

/usr/local/lib/python3.4/dist-packages/pymc3/model.py in Var(self, name, dist, data)
    282                     self.named_vars[v.name] = v
    283         else:
--> 284             var = ObservedRV(name=name, data=data, distribution=dist, model=self)
    285             self.observed_RVs.append(var)
    286             if var.missing_values:

/usr/local/lib/python3.4/dist-packages/pymc3/model.py in __init__(self, type, owner, index, name, data, distribution, model)
    559             self.missing_values = data.missing_values
    560 
--> 561             self.logp_elemwiset = distribution.logp(data)
    562             self.model = model
    563             self.distribution = distribution

/usr/local/lib/python3.4/dist-packages/pymc3/distributions/multivariate.py in logp(self, value)
     66         k = tau.shape[0]
     67 
---> 68         result = k * T.log(2 * np.pi) + T.log(1./det(tau))
     69         result += (delta.dot(tau) * delta).sum(axis=delta.ndim - 1)
     70         return -1/2. * result

/usr/local/lib/python3.4/dist-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    609         """
    610         return_list = kwargs.pop('return_list', False)
--> 611         node = self.make_node(*inputs, **kwargs)
    612 
    613         if config.compute_test_value != 'off':

/usr/local/lib/python3.4/dist-packages/theano/tensor/nlinalg.py in make_node(self, x)
    274     def make_node(self, x):
    275         x = as_tensor_variable(x)
--> 276         assert x.ndim == 2
    277         o = theano.tensor.scalar(dtype=x.dtype)
    278         return Apply(self, [x], [o])

AssertionError: 
```

So it seems the problem is that the precision matrix is not bidimensional.
If I print the precisions I'm passing to MvNormal:

``` python
tensor.printing.Print('PRECISIONS')(stacked_lambs[z])
```

I get:

```
PRECISIONS __str__ = [[[ 0.90702948  0.        ]
  [ 0.          0.90702948]]

 [[ 0.90702948  0.        ]
  [ 0.          0.90702948]]

 [[ 0.90702948  0.        ]
  [ 0.          0.90702948]]

 ..., 
 [[ 0.90702948  0.        ]
  [ 0.          0.90702948]]

 [[ 0.90702948  0.        ]
  [ 0.          0.90702948]]

 [[ 0.90702948  0.        ]
  [ 0.          0.90702948]]]
```

So MvNormal does not allow passing more than one precision matrix?
Is this a bug or is there another way of doing what I want?

I appreciate any help.
Thanks!

**Comment by benavente** [comment]
OK, I read the code for MvNormal and it's clear why it can accept many means, but not precisions. Any suggestions on how to implement this, though?
Thanks!

**Comment by benavente** [comment]
I'm trying now to do it with DensityDist and a custom Op:

``` python
    @theano.as_op(itypes=[tensor.dmatrix, tensor.lvector, tensor.dmatrix, tensor.dtensor3],
                  otypes=[tensor.dscalar])
    def likelihood_op(values, z_values, mu_values, prec_values):
        logp = 0.
        for i in range(N_COMPONENTS):
            indices = z_values == i
            if not indices.any():
                continue

            logp += scipy.stats.multivariate_normal(
                mu_values[i], prec_values[i]).logpdf(values[indices])
        return logp

    def likelihood(values):
        return likelihood_op(values, z, stacked_mus, stacked_lambs)

    y = pm.DensityDist('y', likelihood, observed=target_data)
```

However, I get an error when I try to sample:

``` python
mu_0 = cluster.k_means(target_data, N_COMPONENTS)[0]
start = {'mu_{}'.format(i): mu_0[i] for i in range(N_COMPONENTS)}

with model:  
    step1 = pm.Metropolis(vars=mus + lambs + [pi])
    step2 = pm.ElemwiseCategoricalStep(vars=[z], values=list(range(N_COMPONENTS)))

    trace = pm.sample(100, start=start, step=[step1, step2])
```

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-dddd4278bea8> in <module>()
      5     #start = pm.find_MAP()
      6 
----> 7     step1 = pm.Metropolis(vars=mus + lambs + [y, pi])
      8     step2 = pm.ElemwiseCategoricalStep(vars=[z], values=list(range(N_COMPONENTS)))
      9 

/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/arraystep.py in __new__(cls, *args, **kwargs)
     56                 # If we don't return the instance we have to manually
     57                 # call __init__
---> 58                 step.__init__([var], *args, **kwargs)
     59                 steps.append(step)
     60 

/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/metropolis.py in __init__(self, vars, S, proposal_dist, scaling, tune, tune_interval, model, **kwargs)
     97 
     98         shared = make_shared_replacements(vars, model)
---> 99         self.delta_logp = delta_logp(model.logpt, vars, shared)
    100         super(Metropolis, self).__init__(vars, shared)
    101 

/usr/local/lib/python3.4/dist-packages/pymc3/memoize.py in memoizer(*args, **kwargs)
     12 
     13         if key not in cache:
---> 14             cache[key] = obj(*args, **kwargs)
     15 
     16         return cache[key]

/usr/local/lib/python3.4/dist-packages/pymc3/model.py in logpt(self)
    191     def logpt(self):
    192         """Theano scalar of log-probability of the model"""
--> 193         factors = [var.logpt for var in self.basic_RVs] + self.potentials
    194         return T.add(*map(T.sum, factors))
    195 

/usr/local/lib/python3.4/dist-packages/pymc3/model.py in <listcomp>(.0)
    191     def logpt(self):
    192         """Theano scalar of log-probability of the model"""
--> 193         factors = [var.logpt for var in self.basic_RVs] + self.potentials
    194         return T.add(*map(T.sum, factors))
    195 

/usr/local/lib/python3.4/dist-packages/pymc3/model.py in logpt(self)
    162     def logpt(self):
    163         """Theano scalar of log-probability of the model"""
--> 164         return T.sum(self.logp_elemwiset)
    165 
    166 

/usr/local/lib/python3.4/dist-packages/theano/tensor/basic.py in sum(input, axis, dtype, keepdims, acc_dtype)
   2927     """
   2928 
-> 2929     out = elemwise.Sum(axis=axis, dtype=dtype, acc_dtype=acc_dtype)(input)
   2930 
   2931     if keepdims:

/usr/local/lib/python3.4/dist-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    619             for i, ins in enumerate(node.inputs):
    620                 try:
--> 621                     storage_map[ins] = [self._get_test_value(ins)]
    622                     compute_map[ins] = [True]
    623                 except AttributeError:

/usr/local/lib/python3.4/dist-packages/theano/gof/op.py in _get_test_value(cls, v)
    547             # ensure that the test value is correct
    548             try:
--> 549                 ret = v.type.filter(v.tag.test_value)
    550             except Exception as e:
    551                 # Better error message.

/usr/local/lib/python3.4/dist-packages/theano/tensor/type.py in filter(self, data, strict, allow_downcast)
    175             raise TypeError("Wrong number of dimensions: expected %s,"
    176                             " got %s with shape %s." % (self.ndim, data.ndim,
--> 177                                                         data.shape))
    178         if not data.flags.aligned:
    179             try:

TypeError: For compute_test_value, one input test value does not have the requested type.

Backtrace when that variable is created:
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-a534dd76d419>", line 78, in <module>
    y = pm.DensityDist('y', likelihood, observed=target_data)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/distributions/distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/model.py", line 284, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/model.py", line 561, in __init__
    self.logp_elemwiset = distribution.logp(data)
  File "<ipython-input-23-a534dd76d419>", line 76, in likelihood
    return likelihood_op(values, z, stacked_mus, stacked_lambs)

The error when converting the test value to that variable type:
Wrong number of dimensions: expected 0, got 1 with shape (500,).
```

I'm passing 500 observations in `observed`.

**Comment by twiecki** [comment]
CC @brandonwillard who is working on exactly that.

**Comment by brandonwillard** [comment]
Yes, looks like it.  The changes should make @benavente's initial use of `MvNormal` work.

In the meantime, I hacked up an augmented `MvNormal` implementation that can handle tensor arguments and sampling: [here](https://gist.github.com/brandonwillard/ef4db928eb4c18352eb04e32f3d47002).  It doesn't do all the parameter broadcasting that it needs to, so--to be safe--you might want to make the `mu`s and `tau`s match in shape.

**Comment by benavente** [comment]
Awesome, thanks a lot @brandonwillard!

**Comment by benavente** [comment]
Also, any idea why the DensityDist approach does not work?

Thanks!

**Comment by brandonwillard** [comment]
Hard to tell; could you provide a minimal, self-contained example of your error?  
From the error message and code, I would guess that you need to provide a valid test value to `DensityDist`.

**Comment by benavente** [comment]
Of course:

``` python
import numpy as np
import pymc3 as pm
import scipy
import theano
from theano import tensor


target_data = np.random.random((500, 16))

N_COMPONENTS = 5
N_SAMPLES, N_DIMS = target_data.shape

# Dirichilet prior.
ALPHA_0 = np.ones(N_COMPONENTS)
# Component means prior.
MU_0 = np.zeros(N_DIMS)
LAMB_0 = 1. * np.eye(N_DIMS)
# Components precision prior.
BETA_0, BETA_1 = 0., 1.    # Covariance stds prior uniform limits.
L_0 = 2.       # LKJ corr. shape. Larger shape -> more biased to identity.

# In order to convert the upper triangular correlation values to a
# complete correlation matrix, we need to construct an index matrix:
# Source: http://stackoverflow.com/q/29759789/1901296
N_ELEMS = N_DIMS * (N_DIMS - 1) / 2
tri_index = np.zeros([N_DIMS, N_DIMS], dtype=int)
tri_index[np.triu_indices(N_DIMS, k=1)] = np.arange(N_ELEMS)
tri_index[np.triu_indices(N_DIMS, k=1)[::-1]] = np.arange(N_ELEMS)

with pm.Model() as model:
    # Component weight prior.
    pi = pm.Dirichlet('pi', ALPHA_0, testval=np.ones(N_COMPONENTS) / N_COMPONENTS)
    #pi_potential = pm.Potential('pi_potential', tensor.switch(tensor.min(pi) < .01, -np.inf, 0))

    ###################
    # Components plate.
    ###################
    # Component means.
    mus = [pm.MvNormal('mu_{}'.format(i), MU_0, LAMB_0, shape=N_DIMS)
           for i in range(N_COMPONENTS)]

    # Component precisions.
    #lamb = diag(sigma) * corr(corr_shape) * diag(sigma)
    corr_vecs = [
            pm.LKJCorr('corr_vec_{}'.format(i), L_0, N_DIMS)
            for i in range(N_COMPONENTS)
    ]
    # Transform the correlation vector representations to matrices.
    corrs = [
        tensor.fill_diagonal(corr_vecs[i][tri_index], 1.)
        for i in range(N_COMPONENTS)
    ]
    # Stds for the correlation matrices.
    cov_stds = pm.Uniform('cov_stds', BETA_0, BETA_1, shape=(N_COMPONENTS, N_DIMS))
    # Finally re-compose the covariance matrices using diag(sigma) * corr * diag(sigma)
    # Source http://austinrochford.com/posts/2015-09-16-mvn-pymc3-lkj.html
    lambs = []
    for i in range(N_COMPONENTS):
        std_diag = tensor.diag(cov_stds[i])
        cov = std_diag.dot(corrs[i]).dot(std_diag)
        lambs.append(tensor.nlinalg.matrix_inverse(cov))

    stacked_mus = tensor.stack(mus)
    stacked_lambs = tensor.stack(lambs)

    #####################
    # Observations plate.
    #####################
    z = pm.Categorical('z', pi, shape=N_SAMPLES)

    @theano.as_op(itypes=[tensor.dmatrix, tensor.lvector, tensor.dmatrix, tensor.dtensor3],
                  otypes=[tensor.dscalar])
    def likelihood_op(values, z_values, mu_values, prec_values):
        logp = 0.
        for i in range(N_COMPONENTS):
            indices = z_values == i
            if not indices.any():
                continue

            logp += scipy.stats.multivariate_normal(
                mu_values[i], prec_values[i]).logpdf(values[indices])
        return logp

    def likelihood(values):
        return likelihood_op(values, z, stacked_mus, stacked_lambs)

    y = pm.DensityDist('y', likelihood, observed=target_data)

    step1 = pm.Metropolis(vars=mus + lambs + [pi])
    step2 = pm.ElemwiseCategoricalStep(vars=[z], values=list(range(N_COMPONENTS)))

    trace = pm.sample(100, step=[step1, step2])
```

That's what I thought, too. But since I am passing observed values, do I still need to do that?

**Comment by brandonwillard** [comment]
Theano is asking `likelihood_op` for a test value (from `tag.test_value`) and it's getting a vector (`numpy.array`, really) back, but `likelihood_op` is expected to output `tensor.dscalar`.
Basically, with the current test values, `scipy.stats.multivariate_normal` is returning a vector (`values[indices]` is a matrix), so you probably forgot to sum after each call to it.

**Comment by benavente** [comment]
That's right. Thanks!

**Comment by qazmichaelgw** [comment]
When I change the output to otypes=[tensor.dvector]. I got the new error:
ValueError: the input matrix must be positive semidefinite
Apply node that caused the error: FromFunctionOp{likelihood_op}(TensorConstant{[[ 0.46327..7803277 ]]}, z_shared, Join.0, Join.0)

**Comment by qazmichaelgw** [comment]
I modified the likelihood:

```
             @theano.compile.ops.as_op(itypes=[T.dmatrix, T.lvector, T.dmatrix, T.dtensor3, T.dvector], otypes=[T.dscalar])
             def likelihood(value, z, s_mus, s_lambs, s_dets):
                 mu = s_mus[z]
                 tau = s_lambs[z]

                 print mu.ndim
                 print value.ndim
                 print value
                 print mu
                 delta = value - mu
                 k = tau.shape[0]
                 n = value.shape[0]

                 result = n * k * T.log(2*np.pi) + n * T.log(s_dets[z])
                 result += (delta.T * T.dot(tau, delta.T)).sum()
                 result = -1/2. * result
                 print result.eval()
                 print result.type
                 print T.sum(result).eval()
                 return result

             def logp(value):
                 likelihood(value, C, stacked_mus, stacked_lambs, stacked_dets)
```

But got the error:

```
  step1 = pm.Metropolis(vars=metropolis_vars)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/pymc3/step_methods/arraystep.py", line 58, in __new__
    step.__init__([var], *args, **kwargs)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/pymc3/step_methods/metropolis.py", line 101, in __init__
    self.delta_logp = delta_logp(model.logpt, vars, shared)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/pymc3/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/pymc3/model.py", line 221, in logpt
    factors = [var.logpt for var in self.basic_RVs] + self.potentials
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/pymc3/model.py", line 165, in logpt
    return tt.sum(self.logp_elemwiset)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/theano/tensor/basic.py", line 2929, in sum
    out = elemwise.Sum(axis=axis, dtype=dtype, acc_dtype=acc_dtype)(input)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 1894, in make_node
    input = as_tensor_variable(input)
  File "/home/gaowei/studio/py/local/lib/python2.7/site-packages/theano/tensor/basic.py", line 208, in as_tensor_variable
    raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
theano.tensor.var.AsTensorError: ('Cannot convert None to TensorType', <type 'NoneType'>)
```

**Comment by AngelBerihuete** [comment]
Hi @benavente 
I want to reproduce your code above, but I don't know if you have modified as @brandonwillard said in the last message. I have changed `logp` adding `sum()`, i.e.,

``` python
logp += scipy.stats.multivariate_normal(mu_values[i], prec_values
                [i]).logpdf(values[indices]).sum()
```

and also from this 

```
    step2 = pm.ElemwiseCategoricalStep(vars=[z], values=list(range(N_COMPONENTS)))
```

to this

```
step2 = pm.ElemwiseCategorical(vars=[z], values=list(range(N_COMPONENTS)))
```

But I have obtained the following error (below). Any clue? 

Have you test the @brandonwillard 's  MvNormal extension? Could you show me any example?
I appreciate any help.

Thanks,
Angel

```
ValueError: expected an ndarray
Apply node that caused the error: Elemwise{Composite{((i0 + i1) - (i2 + i3))}}[(0, 0)](Sum{acc_dtype=float64}.0, FromFunctionOp{likelihood_op}.0, Sum{acc_dtype=float64}.0, FromFunctionOp{likelihood_op}.0)
Toposort index: 101
Inputs types: [TensorType(float64, scalar), TensorType(float64, scalar), TensorType(float64, scalar), TensorType(float64, scalar)]
Inputs shapes: [(), (), (), ()]
Inputs strides: [(), (), (), ()]
Inputs values: [array(-127.70516572917249), -13460.012199423296, array(-110.90354888959129), -13234.61313535326]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by twiecki** [comment]
Feel free to reopen if this is still an issue.
