### ISSUE TITLE
IndexError when using Theano function involving `scan` and `ifelse` inside custom `Density` subclass

### ISSUE THREAD

**Issue by Spaak** [pymc-devs/pymc#1299]
To make sure I'm not doing anything very stupid, a bit of background first. I'm trying to model cell X time matrix of neuronal spike times as a function of two parameters: per-cell base firing probability, and between-cell connection strength. I am basing myself largely on [a paper by Rigat et al.](https://github.com/pymc-devs/pymc3/files/434538/Rigat.Gunst.Pelt.2006.Bayesian.Analysis.Bayesian.modelling.and.analysis.of.spatio-temporal.neuronal.networks.pdf) (with a few differences), though I think the details are not important for this issue.

I have defined a custom likelihood which is a function of the full cell X time observable matrix. The likelihood of any individual cell firing at any particular time point is a function of theta, beta, and the network's firing history up to that time point. This aspect of the likelihood means (I think) that the likelihood for the full observable matrix will always involve some looping. I am implementing this looping using `theano.map()`, which is just a thin convenience wrapper around `theano.scan()`. When I execute my function using plain Theano, outside of any PyMC3 code, it works perfectly:

``` python
# imports
import theano
import theano.tensor as T
from theano.ifelse import ifelse
import pymc3 as mc

# some test data
# note: not actually generated by any sensible model, just for technical testing
ncell = 4
ntim = 10

# spikes as binary variable
y_obs = np.random.choice((0,1), p=(0.7,0.3), size=(ncell,ntim)).astype('float32')

# model 'parameters'
# theta: cell-specific base firing rate
theta_true = np.random.random(ncell).astype('float32')
# beta: cell X cell connectivity matrix
beta_true = np.random.random((ncell,ncell)).astype('float32')

# theano.scan() and map() are not comparible with test value debugging,
# so set it to 'warn'. note that 'off' will give an error:
# AttributeError: 'scratchpad' object has no attribute 'test_value'
# in pymc3.distributions.distribution
theano.config.compute_test_value = 'warn'

# the rate term for one cell i and one time point t
def rate(i,t,y,theta,beta):
    # determine previous spike time of cell i
    # known as tau_it in model of Rigat
    last_time = T.flatnonzero(y[i,:t]).astype('uint16')
    # if last_time is not empty (cell i has fired at least once)
    # then use last firing time, otherwise use 0
    last_time = ifelse(
        T.gt(last_time.shape[0], 0),
        # the next line is where the error happens in pymc3 (but not in pure Theano)
        last_time[-1],
        T.constant(0, dtype='uint16')
    )

    # if t == 0 then rate term is simply theta[i]
    # otherwise it's theta[i] plus a weighted sum of all cells' firing
    # history since the last time cell i spiked
    return ifelse(
        T.eq(t, 0),
        theta[i],
        theta[i] + T.sum( beta[:,i] * \
            (T.sum(y[:,last_time:t], axis=-1) / (t-last_time)), axis=0)
    )

# symbolic variables for observed data and parameters
y_theano = T.matrix('y')
theta_theano = T.vector('theta')
beta_theano = T.matrix('beta')

# create flattened indexing grids over which rate() will loop
cgrid, tgrid = T.mgrid[0:ncell, 0:ntim]
cgrid = cgrid.flatten().astype('uint16')
tgrid = tgrid.flatten().astype('uint16')

# call theano.map() which will call rate() for all cells and all time points
rateresult, updates = theano.map(rate,
    sequences=[cgrid, tgrid],
    non_sequences=[y_theano, theta_theano, beta_theano]
)

# reshape back (not needed but was useful in debugging sometimes)
rateresult = T.reshape(rateresult, (ncell, ntim))

# compute log-likelihood based on rate term
logp = T.sum(y_theano * rateresult - T.log1p(T.exp(rateresult)))

# compile function
fun = theano.function(
    inputs=[y_theano, theta_theano, beta_theano],
    outputs=logp
)

# call function and print result
result = fun(y_obs, theta_true, beta_true)
print(result)
```

In other words, I can compute the likelihood for any particular value of `y`, `beta`, and `theta` using my Theano function. The integration of this into PyMC3, however, gives me an error. I use the following custom distribution definition (based on `rate` as defined above):

``` python
class SpikeLikelihood(mc.Discrete):
    """
    The likelihood for spiking as defined in eq. 4 of Rigat et al.
    Redefined this to not depend explicitly on an intermediate computation
    of tau_it.

    theta: ncell, baseline rates
    beta : ncell x ncell, connection strengths
    """

    def __init__(self, theta, beta, ncell, ntim, *args, **kwargs):
        super(SpikeLikelihood, self).__init__(*args, **kwargs)
        self.theta = theta
        self.beta = theta

        # pre-initialize the indexing grid used to implement the loop for
        # computing the rate term
        self._cgrid, self._tgrid = T.mgrid[0:ncell, 0:ntim]
        self._cgrid = self._cgrid.flatten().astype('uint16')
        self._tgrid = self._tgrid.flatten().astype('uint16')
        self._cgrid.name = 'SpikeLikelihood._cgrid'
        self._tgrid.name = 'SpikeLikelihood._tgrid'

    def logp(self, Y):
        # Y will be ncell X time

        # rate can only be computed iteratively per cell and per timepoint
        # so we use theano's scan functionality (accessed here through map())
        # to loop over all time points and cells
        # rate() here is the same theano function as above
        rateresult, updates = theano.map(rate,
            sequences=[self._cgrid, self._tgrid],
            non_sequences=[Y, self.theta, self.beta],
            name='SpikeLikelihood._rate_term')

        # rateresult will give a flattened output, reshape here
        rateresult = T.reshape(rateresult, (self.ncell, self.ntim))

        return T.sum(Y * rateresult - T.log1p(T.exp(rateresult)))
```

and proceed with modelling as follows (note no sampling yet, the error occurs during the model specification stage):

``` python
model = mc.Model()
with model:
    # prior probability of connection on/off, same for all cell pairs
    # exponential with lambda=1 means a connection is a priori unlikely
    alpha_0 = mc.Exponential('alpha_0', lam=1)

    # connections on/off, per cell pair
    nu_ij = mc.Bernoulli('nu_ij', p=alpha_0, shape=(ncell, ncell))

    # s.d. for connection strength, depends on sigma same for all cells and
    # nu_ij per cell. epsilon is shrinkage factor, see Rigat eq. 5.
    epsilon = 0.05
    sigma_squared = mc.Normal('sigma_squared', mu=20, sd=15)
    # warp in mc.Deterministic to give it a name for use in examining the trace etc.
    sigma_ij = mc.Deterministic('sigma_ij', T.sqrt(sigma_squared) * \
        (nu_ij + epsilon * (1 - nu_ij)))

    # actual connection strength
    beta_ij = mc.Normal('beta_ij', mu=0, sd=sigma_ij)

    # baseline rate per cell
    theta_i = mc.Normal('theta_i', mu=20, sd=15, shape=ncell)

    y_modelled = SpikeLikelihood('y_modelled', theta=theta_i, beta=beta_ij,
        ncell=ncell, ntim=ntim, observed=y_obs)
```

The error I'm getting is this:

```
Traceback (most recent call last):
  File "/home/eelke/Dropbox/python/stokes2013-constantinidis/snippets_pymcbugreport.py", line 149, in <module>
    ncell=ncell, ntim=ntim, observed=y_obs)
  File "/home/eelke/repos/pymc3/pymc3/distributions/distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "/home/eelke/repos/pymc3/pymc3/model.py", line 306, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "/home/eelke/repos/pymc3/pymc3/model.py", line 583, in __init__
    self.logp_elemwiset = distribution.logp(data)
  File "/home/eelke/Dropbox/python/stokes2013-constantinidis/snippets_pymcbugreport.py", line 117, in logp
    name='SpikeLikelihood._rate_term')
  File "/home/eelke/repos/Theano/theano/scan_module/scan_views.py", line 70, in map
    name=name)
  File "/home/eelke/repos/Theano/theano/scan_module/scan.py", line 761, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/home/eelke/Dropbox/python/stokes2013-constantinidis/snippets_pymcbugreport.py", line 36, in rate
    last_time[-1],
  File "/home/eelke/repos/Theano/theano/tensor/var.py", line 563, in __getitem__
    lambda entry: isinstance(entry, Variable)))
  File "/home/eelke/repos/Theano/theano/gof/op.py", line 661, in __call__
    required = thunk()
  File "/home/eelke/repos/Theano/theano/gof/op.py", line 879, in rval
    fill_storage()
  File "/home/eelke/repos/Theano/theano/gof/cc.py", line 1698, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/home/eelke/python-venvs/analysis/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
IndexError: index out of bounds
```

Does this mean that Theano is insisting on evaluating the true-branch of the `ifelse` even though the condition might be `false`? And then only when wrapped in PyMC3? This seems like a bug to me, but if it isn't, any pointers on how to achieve what I want would be highly appreciated.

The full script as above is in [this gist](https://gist.github.com/Spaak/f544375d169392e1d0934c57e450b05a).

Edit: oh yes, this is with the latest versions from Github of both Theano and PyMC3:

```
In [18]: theano.__version__
Out[18]: '0.8.0.dev-ab833b1933d339ca4e040769e450195fa61bb958'

In [19]: mc.__version__
Out[19]: '3.0'
```

**Comment by twiecki** [comment]
> Does this mean that Theano is insisting on evaluating the true-branch of the ifelse even though the condition might be false?

Yes, I think that's true, although it seems to depend: http://deeplearning.net/software/theano/tutorial/conditions.html

**Comment by Spaak** [comment]
Thanks a lot. It seems that PyMC3 depends on the Theano test value debugging mechanism in some subtle ways that I had not foreseen. (Theano docs tell me both branches of ifelse will be evaluated when (and only when) using the test value debugging.) I've now added explicit test values to all my variables (with `testval=xxx` in the distribution constructors and `last_time.tag.test_value = np.asarray((0,2), dtype='uint16')` in the intermediate variable in my custom function. The previous error has disappeared, so that's good. However, another very similar one has surfaced, an `IndexError: list assignment index out of range`, for which the stack trace includes some code from Theano's `scan` module (see below for full stack trace).

I am a bit worried that I might not be able to fix this trivially by specifying smart test values. In the [debugging: test values section of Theano docs](http://deeplearning.net/software/theano/tutorial/debug_faq.html#test-values) it's stated that

> This feature is currently incompatible with `Scan` and also with ops which do not implement a `perform` method.

Unfortunately I think my likelihood will always need to depend on `scan`. In plain Theano, this works, because I can disable the test value debugging mechanism using `theano.config.compute_test_value = 'off'`. However, with PyMC3 switching it off entirely gives other errors.

I will continue to investigate.

```
Traceback (most recent call last):
  File "/home/eelke/Dropbox/python/stokes2013-constantinidis/snippets_pymcbugreport.py", line 188, in <module>
    ncell=ncell, ntim=ntim, observed=y_obs.astype(floatX))
  File "/home/eelke/repos/pymc3/pymc3/distributions/distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "/home/eelke/repos/pymc3/pymc3/model.py", line 306, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "/home/eelke/repos/pymc3/pymc3/model.py", line 583, in __init__
    self.logp_elemwiset = distribution.logp(data)
  File "/home/eelke/Dropbox/python/stokes2013-constantinidis/snippets_pymcbugreport.py", line 152, in logp
    name='SpikeLikelihood._rate_term')
  File "/home/eelke/repos/Theano/theano/scan_module/scan_views.py", line 70, in map
    name=name)
  File "/home/eelke/repos/Theano/theano/scan_module/scan.py", line 761, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/home/eelke/Dropbox/python/stokes2013-constantinidis/snippets_pymcbugreport.py", line 109, in rate
    theta[i] + T.sum( beta[:,i] * \
  File "/home/eelke/repos/Theano/theano/tensor/var.py", line 522, in __getitem__
    return self.take(args[axis], axis)
  File "/home/eelke/repos/Theano/theano/tensor/var.py", line 566, in take
    return theano.tensor.subtensor.take(self, indices, axis, mode)
  File "/home/eelke/repos/Theano/theano/tensor/subtensor.py", line 2393, in take
    return take(a, indices.flatten(), axis, mode).reshape(shape, ndim)
  File "/home/eelke/repos/Theano/theano/tensor/subtensor.py", line 2378, in take
    shuffle[axis] = 0
IndexError: list assignment index out of range
```

**Comment by Spaak** [comment]
OK, it seems specifying test values (and keeping the mechanism switched on) did the job here. The error I got later was only incidentally very similar to the original problem, and actually caused by basically a typo (`theta` vs `beta` somewhere). Model specification now runs without issues. I am getting some error during `find_MAP()` though (related to `nan`s I think) but that's a different story, so I'm closing this for now.

**Comment by twiecki** [comment]
Glad it's working.
