### ISSUE TITLE
Missing Data, Masked Array Errors

### ISSUE THREAD

**Issue by zmlabe** [pymc-devs/pymc#1308]
I am very new with Bayesian statistics and using `PyMC`. I am trying to setup a very simple hierarchical model. Observed data arrays are large (32400 elements) with a significant amount of missing data (`nans`). I have tried masking the data and continue to receive the following positive definite error message when running `NUTS`. Any advice would be greatly appreciated. Thanks in advance!

``` python
Applied interval-transform to sigma and added transformed sigma_interval to model.
Traceback (most recent call last):

  File "<ipython-input-3-159c45f11042>", line 1, in <module>
    runfile('/home/zlabe/Desktop/Bay_test/sitmodel_practice/sitmodel_5.py', wdir='/home/zlabe/Desktop/Bay_test/sitmodel_practice')

  File "/home/zlabe/anaconda2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/zlabe/anaconda2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/zlabe/Desktop/Bay_test/sitmodel_practice/sitmodel_5.py", line 61, in <module>
    step = pm.NUTS(state=start)

  File "/home/zlabe/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/nuts.py", line 78, in __init__
    self.potential = quad_potential(scaling, is_cov, as_cov=False)

  File "/home/zlabe/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/quadpotential.py", line 35, in quad_potential
    partial_check_positive_definite(C)

  File "/home/zlabe/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/quadpotential.py", line 58, in partial_check_positive_definite
    "Simple check failed. Diagonal contains negatives", i)

PositiveDefiniteError: Simple check failed. Diagonal contains negatives
```

**Comment by fonnesbeck** [comment]
You need to provide initial values such that the scaling is positive definite; in your case, the default values do not work. This is a bit of an art, but you can specify them either using `testval` arguments on the variables or passing a `start` dict to the `sample` call.

**Comment by fonnesbeck** [comment]
Did you get this sorted?

**Comment by zmlabe** [comment]
Ah sorry, thank you for checking. Unfortunately, I tried following your suggestion of providing initial values and received a similar error. I have switched back to PyMC2, and it is working much better for my purposes. Thanks!
