### ISSUE TITLE
TypeError ... Types work well using CPUs but not with GPUs

### ISSUE THREAD

**Issue by AngelBerihuete** [pymc-devs/pymc#1349]
Dear pymc3 users, here is my issue:

```
TypeError: We expected inputs of types '[TensorType(float64, vector), CudaNdarrayType(float32, vector), CudaNdarrayType(float32, vector)]' but got types '[TensorType(float32, vector), TensorType(float32, vector), TensorType(float32, vector)]'
```

I have a function inside my model in order to transform cartesian to spherical coordinates by using `SkyCoord` function in `Astropy`module:

``` python
@as_op(itypes=[T.fvector, T.fvector, T.fvector], otypes=[T.fmatrix])
def spherical2cartesian(r_dist, l_gal, b_gal):
    ''' Transform spherical to cartesian '''
    c = SkyCoord(l=l_gal*u.degree, b=b_gal*u.degree, distance=r_dist*u.pc, frame='galactic')
    return np.stack((c.cartesian._x.value, c.cartesian._y.value, c.cartesian._z.value), axis=-1)
```

Variables `l_gal` and `b_gal` are constant values with size `N_SAMPLES` but, if I understood well,  in order to use GPUs is better to [share them](http://deeplearning.net/software/theano/tutorial/using_gpu.html?highlight=shared) and get some speed (avoiding transfer information between CPU and GPU)

``` python
 # Defining the transformation from spherical to cartesian coordinates
    r = pm.Uniform('r', 1,1000, shape = N_SAMPLES)
    # Use longitude from dataset, convert into theano variable. OBtable is a dataset
    l_obs = theano.shared(np.asarray(OBtable['GAL_LONG'],
       dtype=theano.config.floatX),
        name='l_obs')
    # Use latitude from dataset, convert into theano variable
    b_obs = theano.shared(np.asarray(OBtable['GAL_LAT'],
       dtype=theano.config.floatX),
        name='b_obs')
    xyz_coord = spherical2cartesian(r, l_obs, b_obs)
```

If I execute the code in my desktop (8 cores) I have no problem at all. But using GPUs I have the issue. 

Any help will be welcome!

Notes:
- `pymc3.__version__`
  '3.0'
- `theano.__version__`
  '0.8.2'

This is the script to execute the code:

`THEANO_FLAGS='mode=FAST_RUN,device=gpu,floatX=float32, cuda.root=/apps/cuda-5.5/' python pymc3Model2.py`

**Comment by raymond-mead** [comment]
You could try setting `dtype='float32'` for `pm.Uniform`. I think pymc3 defaults to `float64`. I think that there are also other issues with float types in pymc3 since it doesn't always default to floatX.

**Comment by AngelBerihuete** [comment]
Thanks raymead.

The problem persists with `CudaNdarrayType` , but `pm.Uniform` changed to `float32` which is good.

``` bash
Traceback (most recent call last):
  File "pymc3Model2.py", line 154, in <module>
    xyz_coord = spherical2cartesian(r, l_obs, b_obs)
  File "/home/est/u20252421/.local/lib/python2.7/site-packages/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/est/u20252421/.local/lib/python2.7/site-packages/theano/gof/op.py", line 993, in make_node
    (str([inp.type for inp in inputs]), str(self.itypes)))
TypeError: We expected inputs of types '[TensorType(float32, vector), CudaNdarrayType(float32, vector), CudaNdarrayType(float32, vector)]' but got types '[TensorType(float32, vector), TensorType(float32, vector), TensorType(float32, vector)]'
```

**Comment by raymond-mead** [comment]
Since they are constants, you could try to use `const_var = tt.as_tensor_variable(your_const)`. I don't know exactly what the problem is with the `CudaNdarray`.

**Comment by AngelBerihuete** [comment]
Thanks again raymead! 

Definitely your solution works for this issue. Now I have another error, but I guess it is due to types related to `int32` inside `trace = pm.sample(niter, step=[step1, step2])`.

If you (or someone else) have some suggestion about it I'll keep this issue open, if not I'll close it. 

``` bash
Using gpu device 0: Tesla K20m (CNMeM is disabled, cuDNN not available)
Applied log-transform to alpha and added transformed alpha_log to model.
Applied logodds-transform to beta and added transformed beta_logodds to model.
Applied interval-transform to sigma and added transformed sigma_interval to model.
Applied interval-transform to r and added transformed r_interval to model.
Traceback (most recent call last):
  File "pymc3Model2.py", line 169, in <module>
    trace = pm.sample(niter, step=[step1, step2])
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/sampling.py", line 150, in sample
    return sample_func(**sample_args)
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/sampling.py", line 159, in _sample
    for i, strace in enumerate(sampling):
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/sampling.py", line 241, in _iter_sample
    point = step.step(point)
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/compound.py", line 14, in step
    point = method.step(point)
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/compound.py", line 14, in step
    point = method.step(point)
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/arraystep.py", line 127, in step
    apoint = self.astep(bij.map(point))
  File "/apps/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/metropolis.py", line 127, in astep
    q_new = metrop_select(self.delta_logp(q, q0), q, q0)
  File "/home/est/u20252421/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/est/u20252421/.local/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/est/u20252421/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
TypeError: Argument not a CudaNdarray
Apply node that caused the error: GpuElemwise{scalar_sigmoid,no_inplace}(beta_logodds__shared)
Toposort index: 45
Inputs types: [CudaNdarrayType(float32, vector)]
Inputs shapes: [(10,)]
Inputs strides: [(4,)]
Inputs values: ['not shown']
Outputs clients: [[HostFromGpu(GpuElemwise{scalar_sigmoid,no_inplace}.0), GpuElemwise{mul,no_inplace}(GpuElemwise{second,no_inplace}.0, GpuElemwise{scalar_sigmoid,no_inplace}.0), GpuElemwise{second,no_inplace}(GpuElemwise{scalar_sigmoid,no_inplace}.0, CudaNdarrayConstant{[ 1.]}), GpuElemwise{log,no_inplace}(GpuElemwise{scalar_sigmoid,no_inplace}.0), GpuElemwise{sub,no_inplace}(CudaNdarrayConstant{[ 1.]}, GpuElemwise{scalar_sigmoid,no_inplace}.0)]]

Debugprint of the apply node: 
GpuElemwise{scalar_sigmoid,no_inplace} [id A] <CudaNdarrayType(float32, vector)> ''   
 |beta_logodds__shared [id B] <CudaNdarrayType(float32, vector)>

Storage map footprint:
 - inarray1, Input, Shape: (3533,), ElemSize: 8 Byte(s), TotalSize: 28264 Byte(s)
 - component_shared, Shared Input, Shape: (3533,), ElemSize: 8 Byte(s), TotalSize: 28264 Byte(s)
 - inarray, Input, Shape: (3533,), ElemSize: 8 Byte(s), TotalSize: 28264 Byte(s)
 - TensorConstant{[ 0.205425...59171963]}, Shape: (3533,), ElemSize: 4 Byte(s), TotalSize: 14132 Byte(s)
 - TensorConstant{[ 112.0900...30029297]}, Shape: (3533,), ElemSize: 4 Byte(s), TotalSize: 14132 Byte(s)
 - TensorConstant{[-22.92756...70576477]}, Shape: (3533,), ElemSize: 4 Byte(s), TotalSize: 14132 Byte(s)
 - TensorConstant{[ -7.71604...86419487]}, Shape: (3533,), ElemSize: 4 Byte(s), TotalSize: 14132 Byte(s)
 - TensorConstant{[ 2.259999...73999977]}, Shape: (3533,), ElemSize: 4 Byte(s), TotalSize: 14132 Byte(s)
 - TensorConstant{(3533,) of 1}, Shape: (3533,), ElemSize: 1 Byte(s), TotalSize: 3533 Byte(s)
 - sigma_interval__shared, Shared Input, Shape: (10, 3), ElemSize: 4 Byte(s), TotalSize: 120 Byte(s)
 - TensorConstant{[0 0 1 0 0 2 1 2 0]}, Shape: (9,), ElemSize: 8 Byte(s), TotalSize: 72 Byte(s)
 - TensorConstant{[[ 10.   0.. 0.  10.]]}, Shape: (3, 3), ElemSize: 8 Byte(s), TotalSize: 72 Byte(s)
 - beta_logodds__shared, Shared Input, Shape: (10,), ElemSize: 4 Byte(s), TotalSize: 40 Byte(s)
 - corr_vec_9_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_7_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_2_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_2_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - TensorConstant{(3,) of 0.0}, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_0_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_5_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_1_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_5_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_1_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_3_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_7_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_8_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_6_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_4_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - corr_vec_0_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_9_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_8_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_6_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_4_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - mu_3_shared, Shared Input, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - TensorConstant{(2,) of 3}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - Constant{3}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of 1}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{1.0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1, 1) of 1.0}, Shape: (1, 1), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{1.0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{3533}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of 3533}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{-1.39412441198}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{-1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{-0.722021019821}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{8}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{6}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{4}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{2}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of -1}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - Constant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{9}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of 9}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - Constant{7}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of 3533}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - Constant{5}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1, 1) of -inf}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1,) of 2.0}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{4.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{(1, 1) of 2.0}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[ 0.]}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[ 999.]}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1,) of -inf}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[[ 0.1]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - HostFromGpu.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{0.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - HostFromGpu.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{[[ 1.]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[ 1.]}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{9.99999974738e-06}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-0.5}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{[[ 1.89999998]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{-inf}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{(1, 1) of 0.1}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{[-inf]}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of -0.641854}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - alpha_log__shared, Shared Input, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-inf}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{(1,) of -6.90675}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1,) of 1000}, Shape: (1,), ElemSize: 2 Byte(s), TotalSize: 2 Byte(s)
 - TensorConstant{(1,) of 0}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - TensorConstant{(1,) of 2}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - TensorConstant{(1, 1) of 1}, Shape: (1, 1), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - TensorConstant{-1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{(1,) of 1}, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - TensorConstant{(1, 1) of -1}, Shape: (1, 1), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{0}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 TotalSize: 160091.0 Byte(s) 0.000 GB
 TotalSize inputs: 160083.0 Byte(s) 0.000 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
```

**Comment by raymond-mead** [comment]
At this point, the problem is that parts of the metropolis sampler weren't built with theano, so they would have to be re-implemented.

**Comment by twiecki** [comment]
I have tried to make the samplers use the dtype of theano here: https://github.com/pymc-devs/pymc3/pull/1338

Unfortunately, this causes some unanticipated problems when running on the CPU, but you can try if it helps in your case and maybe we can fix it.

**Comment by AngelBerihuete** [comment]
Thanks twiecki and raymead. 

Unfortunately the machine having the GPUs is controlled by other people, and try to explain how to change to the branch `use_theano_float_type2` will be a nightmare. If you know how to do this quickly, please share with me.

**Comment by twiecki** [comment]
How about:

`pip install -U --no-deps git+https://github.com/pymc-devs/pymc3@use_theano_float_type2`

**Comment by AngelBerihuete** [comment]
Working on it. I'll keep informed you.

**Comment by twiecki** [comment]
@AngelBerihuete any update?
