### ISSUE TITLE
Out-of-range value for uniform prior

### ISSUE THREAD

**Issue by sebp** [pymc-devs/pymc#1501]
# Problem Description

While attempting to port code related to [Bayesian estimation of the correlation coefficient](http://www.philippsinger.info/?p=581) from PyMC2 and PyMC3, I noticed that `rho` (the correlation coefficient) can be out of range, which in turn causes NaN in the multivariate normal distribution when taking the log of a negative value ([line 117](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L117) of pymc3/distributions/multivariate.py).

The model is defined as below:
```python
from theano.printing import Print
import theano.tensor as T
import pymc3 as pm
import numpy as np


def covariance(sigma, rho):
    C = T.fill_diagonal(T.alloc(rho, 2, 2), 1.)
    S = T.diag(sigma)
    M = S.dot(C).dot(S)
    return M


def analyze_robust(data):
    with pm.Model() as model:
        # priors
        sigma = pm.Uniform('sigma', lower=0, upper=1000, shape=2,
                           testval=[0.133434, 5.9304],  # init with mad
                           transform=None)
        rho = pm.Uniform('r', lower=-1, upper=1,
                         testval=-0.2144021,  # init with Spearman's correlation
                         transform=None)

        # print values for debugging
        rho_p = Print('rho')(rho)
        sigma_p = Print('sigma')(sigma)

        cov = pm.Deterministic('cov', covariance(sigma_p, rho_p))
        cov_p = Print('cov')(cov)

        mult_norm = pm.MvNormal('mult_norm', mu=[10.1, 79.],  # set mu to median
                                cov=cov_p, observed=data.T)

    return model


s = [9.92, 94, 9.94, 79, 9.97, 78, 9.93, 83, 9.90, 77, 9.93, 76, 10.00, 74, 9.97, 87, 10.00, 86, 10.01,
     83, 10.08, 75, 10.09, 74, 10.15, 92, 10.15, 69, 10.17, 79, 10.17, 71, 10.19, 80, 10.30, 80, 10.31,
     77, 10.34, 87]
x = [float(a) for i, a in enumerate(s) if i % 2 == 0]
y = [float(a) for i, a in enumerate(s) if i % 2 != 0]
data = np.array([x, y])

x.append(9.5)
y.append(115.)

robust_model = analyze_robust(data)
with robust_model:
    robust_trace = pm.sample(500, tune=250, step=pm.Metropolis(),
                             random_seed=21412, progressbar=False)
```

Notice that the prior on `rho` is uniform between -1 and 1.

## Result

Running the code with Theano's [NanGuardMode](http://deeplearning.net/software/theano/library/compile/nanguardmode.html) enabled results in NaN after a couple of iterations:

```
rho __str__ = -0.2144021
sigma __str__ = [ 0.133434  5.9304  ]
cov __str__ = [[  1.78046324e-02  -1.69660025e-01]
 [ -1.69660025e-01   3.51696442e+01]]
sigma __str__ = [ 0.133434  5.9304  ]
rho __str__ = -0.2144021
sigma __str__ = [ 0.133434  5.9304  ]
rho __str__ = -0.2144021
rho __str__ = -0.6753367200324893
cov __str__ = [[  1.78046324e-02  -1.69660025e-01]
 [ -1.69660025e-01   3.51696442e+01]]
cov __str__ = [[  1.78046324e-02  -5.34405423e-01]
 [ -5.34405423e-01   3.51696442e+01]]
rho __str__ = -0.2144021
sigma __str__ = [ 0.133434  5.9304  ]
sigma __str__ = [-0.08992942  6.58322907]
cov __str__ = [[  1.78046324e-02  -1.69660025e-01]
 [ -1.69660025e-01   3.51696442e+01]]
cov __str__ = [[  8.08730093e-03   1.26931614e-01]
 [  1.26931614e-01   4.33389049e+01]]
sigma __str__ = [ 0.133434  5.9304  ]
rho __str__ = -0.2144021
sigma __str__ = [ 0.133434  5.9304  ]
rho __str__ = -0.2144021
rho __str__ = -1.3866936871442477
cov __str__ = [[  1.78046324e-02  -1.69660025e-01]
 [ -1.69660025e-01   3.51696442e+01]]
cov __str__ = [[  1.78046324e-02  -1.09731428e+00]
 [ -1.09731428e+00   3.51696442e+01]]
Traceback (most recent call last):
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/gof/link.py", line 1012, in f
    wrapper(i, node, *thunks)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/compile/nanguardmode.py", line 307, in nan_check
    do_check_on(x[0], node, fn, False)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/compile/nanguardmode.py", line 272, in do_check_on
    raise AssertionError(msg)
AssertionError: NaN detected
NanGuardMode found an error in the output of a node in this variable:
Elemwise{log,no_inplace} [id A] ''   
 |Elemwise{true_div,no_inplace} [id B] ''   
   |TensorConstant{1.0} [id C]
   |Det [id D] ''   
     |MatrixInverse [id E] ''   
       |Print{message='cov', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id F] ''   
         |Dot22 [id G] 'cov'   
           |Dot22 [id H] ''   
           | |Diag [id I] ''   
           | | |Print{message='sigma', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id J] ''   
           | |   |sigma_shared [id K]
           | |FillDiagonal [id L] ''   
           |   |Alloc [id M] ''   
           |   | |Print{message='rho', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id N] ''   
           |   | | |Subtensor{int64} [id O] ''   
           |   | |   |Subtensor{int64:int64:} [id P] ''   
           |   | |   | |inarray1 [id Q]
           |   | |   | |Constant{0} [id R]
           |   | |   | |Constant{1} [id S]
           |   | |   |Constant{0} [id R]
           |   | |TensorConstant{2} [id T]
           |   | |TensorConstant{2} [id T]
           |   |TensorConstant{1.0} [id U]
           |Diag [id I] ''   



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebp/Projekte/bayesian/robust_cor.py", line 49, in <module>
    robust_trace = pm.sample(500, tune=250, step=pm.Metropolis(), random_seed=21412, progressbar=False)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/sampling.py", line 157, in sample
    return sample_func(**sample_args)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/sampling.py", line 167, in _sample
    for strace in sampling:
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/sampling.py", line 249, in _iter_sample
    point = step.step(point)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/step_methods/compound.py", line 16, in step
    point = method.step(point)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/step_methods/arraystep.py", line 142, in step
    apoint = self.astep(bij.map(point))
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/step_methods/metropolis.py", line 137, in astep
    q_new = metrop_select(self.delta_logp(q, q0), q, q0)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/gof/link.py", line 1014, in f
    raise_with_op(node, *thunks)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/gof/link.py", line 1012, in f
    wrapper(i, node, *thunks)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/compile/nanguardmode.py", line 307, in nan_check
    do_check_on(x[0], node, fn, False)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/theano/compile/nanguardmode.py", line 272, in do_check_on
    raise AssertionError(msg)
AssertionError: NaN detected
NanGuardMode found an error in the output of a node in this variable:
Elemwise{log,no_inplace} [id A] ''   
 |Elemwise{true_div,no_inplace} [id B] ''   
   |TensorConstant{1.0} [id C]
   |Det [id D] ''   
     |MatrixInverse [id E] ''   
       |Print{message='cov', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id F] ''   
         |Dot22 [id G] 'cov'   
           |Dot22 [id H] ''   
           | |Diag [id I] ''   
           | | |Print{message='sigma', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id J] ''   
           | |   |sigma_shared [id K]
           | |FillDiagonal [id L] ''   
           |   |Alloc [id M] ''   
           |   | |Print{message='rho', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id N] ''   
           |   | | |Subtensor{int64} [id O] ''   
           |   | |   |Subtensor{int64:int64:} [id P] ''   
           |   | |   | |inarray1 [id Q]
           |   | |   | |Constant{0} [id R]
           |   | |   | |Constant{1} [id S]
           |   | |   |Constant{0} [id R]
           |   | |TensorConstant{2} [id T]
           |   | |TensorConstant{2} [id T]
           |   |TensorConstant{1.0} [id U]
           |Diag [id I] ''   


Apply node that caused the error: Elemwise{log,no_inplace}(Elemwise{true_div,no_inplace}.0)
Toposort index: 58
Inputs types: [TensorType(float64, scalar)]
Inputs shapes: [()]
Inputs strides: [()]
Inputs values: [array(-0.5779160437553532)]
Outputs clients: [[Elemwise{add,no_inplace}(Elemwise{mul,no_inplace}.0, Elemwise{log,no_inplace}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/sebp/Projekte/bayesian/robust_cor.py", line 47, in <module>
    robust_model = analyze_robust(data)
  File "/home/sebp/Projekte/bayesian/robust_cor.py", line 32, in analyze_robust
    cov=cov_p, observed=data.T)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/distributions/distribution.py", line 27, in __new__
    return model.Var(name, dist, data)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/model.py", line 309, in Var
    distribution=dist, model=self)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/model.py", line 592, in __init__
    self.logp_elemwiset = distribution.logp(data)
  File "/home/sebp/miniconda3/envs/pymc3/lib/python3.5/site-packages/pymc3/distributions/multivariate.py", line 117, in logp
    result = k * tt.log(2 * np.pi) + tt.log(1. / det(tau))

Debugprint of the apply node: 
Elemwise{log,no_inplace} [id A] <TensorType(float64, scalar)> ''   
 |Elemwise{true_div,no_inplace} [id B] <TensorType(float64, scalar)> ''   
   |TensorConstant{1.0} [id C] <TensorType(float32, scalar)>
   |Det [id D] <TensorType(float64, scalar)> ''   
     |MatrixInverse [id E] <TensorType(float64, matrix)> ''   
       |Print{message='cov', attrs=('__str__',), global_fn=<function _print_fn at 0x7fa10a171ea0>} [id F] <TensorType(float64, matrix)> ''   
         |Dot22 [id G] <TensorType(float64, matrix)> 'cov'   
```

Eventually, `rho` becomes less than -1 (**rho __str__ = -1.3866936871442477**) and the computed covariance matrix is not positive definite anymore, thus its determinate is negative, which causes log to produce NaN.

Given a uniform prior between -1 and 1, I would expect that a value smaller -1 would be impossible.

## Enabling NanGuardMode

You need to modify the `theano.function` call in [pymc3.step_methods.metropolis.delta_logp](pymc3/step_methods/metropolis.py) to use Theano's `NanGuardMode` class:
```python
from theano.compile.nanguardmode import NanGuardMode
f = theano.function([inarray1, inarray0], logp1 - logp0,
                    mode=NanGuardMode(True, False, False))  # only raise error on NaN, not Inf or big value
```

## Setup
Anaconda on Fedora 24 with

- Python 3.5.2
- pymc3 3.0.rc2
- numpy: 1.11.2
- scipy: 0.18.1
- theano 0.8.2

**Comment by twiecki** [comment]
Well the sampler is free to suggest values anywhere, they will just lead to -inf logp. What happens when you turn off the nan guard? I suppose we should interpret that as -inf too, and maybe we already do.

**Comment by sebp** [comment]
You are correct, NaNs are handled in the [metrop_select function](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/arraystep.py#L150), not sure about other samplers, though.

Ignoring NaNs makes tracking down bugs very difficult I have to admit. It should at least display a warning (for instance, as STAN does) to make people aware that there could be an issue in the code. Same applies when a parameter becomes Inf, which probably points to a problem as well.

**Comment by twiecki** [comment]
Good point. How do they warn about it?

**Comment by sebp** [comment]
For the same model in STAN, it prints the following warning:

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
validate transformed params: T is not symmetric. T[1,2] = inf, but T[2,1] = inf
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```

and

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 26: multi_normal_log: LDLT_Factor of covariance parameter is not positive definite. last conditional variance is -nan.
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```

**Comment by twiecki** [comment]
I see, those are very useful and I think we should include them.

**Comment by fonnesbeck** [comment]
It would be cool to enable NanGuardMode as an argument to `sample`. It would involve adding arguments to the main `function` calls throughout, though.

**Comment by fonnesbeck** [comment]
Does this example now work with current master?

**Comment by sebp** [comment]
The NaN issue is still a problem if out-of-range values for rho are proposed. For the standard model using `MvNormal` the posterior of rho still looks good in the end, but for the robust model, using `MvStudentT`, the posterior covers almost the entire range from -1 to 1.

See https://gist.github.com/sebp/3644e2e9cc3050a5b439d56dd8ccce7d for code and output.

Please let me know which additional information I can provide to help.

FWIW, STAN returns a reasonable posterior.

**Comment by twiecki** [comment]
Why do you not transform the variable? Stan I think does the same.

**Comment by sebp** [comment]
I disabled transforms for debugging purposes. If I enable them, there's no NaN value anymore, but the robust model moves towards very large sigma values, which eventually results in infinity values in the covariance matrix.

**Comment by twiecki** [comment]
I think we understand the nan problem, not sure there is much to be done about that, the transformation is the right fix.

I think the MultivariateT is a separate problem, perhaps an issue with the likelihood? I know I tried it in the past as well and couldn't get it to work. I think your nu might be too small which causes a very wide distribution. What happens if you fix it to e.g. 100?

**Comment by sebp** [comment]
Following @fonnesbeck's [suggestion](https://github.com/pymc-devs/pymc3/issues/1501#issuecomment-261326343) is probably the way to go, add a class similar to NanGuardMode that warns about NaN values, but does not exit the application.

Regarding MultivariateT, I tried what you suggested by fixing `nu` to  100 and running the sampler for 50000 iterations. I don't get an error (or NaN values), but the posteriors for `sigma` and `r` cover almost the complete range. From what I can tell, the implementation of the log-likelihood of the MultivariateT distribution looks okay.

**Comment by twiecki** [comment]
I'm not quite sure how to best approach this. Perhaps plotting the MultivariateT likelihood in 2D and comparing to the MultivariateNormal? With nu->inf the two should converge.
