### ISSUE TITLE
Running advi_minibatch twice in succession results in DisconnectedInputError

### ISSUE THREAD

**Issue by Spaak** [pymc-devs/pymc#1598]
With standard `advi`, the following can be used (relevant part at the end, calling `advi` twice in succession with differing `learning_rate`):

```
import pymc3 as mc
import theano.tensor as T

# make some data
ntri = 200
nvar = 5
x = np.random.normal(size=(nvar, ntri)).astype('float32')

weights = np.random.normal(size=nvar)

y = (np.dot(weights, x) + np.random.normal(size=ntri)/2).astype('float32')

model = mc.Model()
with model:
    beta = mc.Normal('beta', mu=0, sd=10, shape=nvar,
        testval=np.random.normal(size=nvar).astype('float32'),
        dtype='float32')
    intercept = mc.Normal('intercept', mu=0, sd=10,
        testval=np.asarray(0, dtype='float32'),
        dtype='float32')
    
    ypred = intercept + T.dot(beta, x)
    residual = mc.HalfNormal('residual', sd=10,
        testval=np.asarray(1, dtype='float32'),
        dtype='float32')
    y_modelled = mc.Normal('y_modelled', mu=ypred, sd=residual, observed=y)

    params = mc.advi(n=10000, start=model.test_point, learning_rate=0.1)
    params = mc.advi(n=10000, start=params.means, learning_rate=0.01)
```

but whenever I try something similar with `advi_minibatch`:

```
import pymc3 as mc
import theano.tensor as T

# make some data
ntri = 200
nvar = 5
x = np.random.normal(size=(nvar, ntri)).astype('float32')

weights = np.random.normal(size=nvar)

y = (np.dot(weights, x) + np.random.normal(size=ntri)/2).astype('float32')

def gen_minibatches(x, y, minibatch_size=50):
    rng = np.random.RandomState(0)

    while True:
        inds = rng.randint(len(y), size=minibatch_size)
        yield x[:,inds], y[inds]

model = mc.Model()
with model:
    beta = mc.Normal('beta', mu=0, sd=10, shape=nvar,
        testval=np.random.normal(size=nvar).astype('float32'),
        dtype='float32')
    intercept = mc.Normal('intercept', mu=0, sd=10,
        testval=np.asarray(0, dtype='float32'),
        dtype='float32')
    
    T_x = T.matrix('T_x', dtype='float32')
    T_x.tag.test_value = np.random.normal(size=(nvar, 50)).astype('float32')
    T_y = T.vector('T_y', dtype='float32')
    T_y.tag.test_value = np.random.normal(size=50).astype('float32')
    
    ypred = intercept + T.dot(beta, T_x)
    residual = mc.HalfNormal('residual', sd=10,
        testval=np.asarray(1, dtype='float32'),
        dtype='float32')
    y_modelled = mc.Normal('y_modelled', mu=ypred, sd=residual, observed=T_y)

    minibatch_tensors = [T_x, T_y]
    minibatches = gen_minibatches(x, y)
    
    params = mc.advi_minibatch(n=10000, minibatch_tensors=minibatch_tensors,
        minibatch_RVs=[y_modelled], minibatches=minibatches,
        total_size=len(y), start=model.test_point, learning_rate=0.1)
    
    params = mc.advi_minibatch(n=10000, minibatch_tensors=minibatch_tensors,
        minibatch_RVs=[y_modelled], minibatches=minibatches,
        total_size=len(y), start=params.means, learning_rate=0.01)
```

The first call runs through fine, but the second one raises a `DisconnectedInputError`:

```
Traceback (most recent call last):
  File "<...>/playground_advi_minibatch.py", line 181, in <module>
    total_size=len(y), start=params.means, learning_rate=0.01)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi_minibatch.py", line 384, in advi_minibatch
    updates = OrderedDict(optimizer(loss=-1 * elbo, param=params))
  File "/home/eelke/repos/pymc3/pymc3/variational/advi.py", line 259, in optimizer
    grad = tt.grad(loss, param_)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 537, in grad
    handle_disconnected(elem)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 524, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError:  
Backtrace when that variable is created:

  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/guiintegration.py", line 424, in run
    self._QtGui.real_QApplication.exec_()
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 566, in process_commands
    self._process_commands()
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 659, in _process_commands
    self.runlargecode(msg)
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 825, in runlargecode
    self.execcode(code)
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 930, in execcode
    exec(code, self.locals)
  File "<...>/playground_advi_minibatch.py+131", line 46, in <module>
    total_size=len(y), start=model.test_point, learning_rate=0.1)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi_minibatch.py", line 357, in advi_minibatch
    global_order)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi_minibatch.py", line 75, in _init_uw_global_shared
    uw_global_shared = theano.shared(uw_start, 'uw_global_shared')
```

**Comment by twiecki** [comment]
CC @taku-y @ferrine

**Comment by ferrine** [comment]
[first](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/advi_minibatch.py#L209) - mutable default value
[second](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/advi_minibatch.py#L383) - mutable is modified
On the second run it will cause Disconnected Input Error

**Comment by Spaak** [comment]
@ferrine A classic! :) Well spotted. My PR #1599 fixes this.
