### ISSUE TITLE
ImportError: No module named 'pymc3.external'

### ISSUE THREAD

**Issue by fretchen** [pymc-devs/pymc#1663]
Hi, 

I wanted to take a look into the  MvGaussianRandomWalk in the 3.1 branch. 

I tried to install the dev branch via:

`pip install git+https://github.com/pymc-devs/pymc3@3.1  `

As I run

`import pymc3 ` 

I obtain the following weird error:

```
---------------------------------------------------------------------------  
ImportError                               Traceback (most recent call last)  
<ipython-input-2-94d4d415559e> in <module>()  
----> 1 import pymc3 as pm

retDevEnv/lib/python3.5/site-packages/pymc3/__init__.py in <module>()  
      3 from .blocking import *  
      4 from .distributions import *  
----> 5 from .external import *  
      6 from .math import logsumexp, logit, invlogit  
      7 from .model import *

ImportError: No module named 'pymc3.external'  
```

If this is a problem with the way I obtained the branch, I am happy to change this.

**Comment by twiecki** [comment]
Should be fixed with https://github.com/pymc-devs/pymc3/commit/ee03c405c3e48200be268824c7238e690d8ced72. Can you try to reinstall with the same command?

**Comment by ferrine** [comment]
what about using `setuptools.find_packages` there?

**Comment by fretchen** [comment]
Uninstall and ran:

`pip install git+https://github.com/pymc-devs/pymc3@3.1`

 and now I obtained:

```
Collecting git+https://github.com/pymc-devs/pymc3@3.1
  Cloning https://github.com/pymc-devs/pymc3 (to 3.1) to /private/var/folders/24/01049y555lj8yjg0sfy8dp540000gn/T/pip-iy9mro8u-build
    Complete output from command python setup.py egg_info:
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    running egg_info
    creating pip-egg-info/pymc3.egg-info
    writing dependency_links to pip-egg-info/pymc3.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/pymc3.egg-info/requires.txt
    writing top-level names to pip-egg-info/pymc3.egg-info/top_level.txt
    writing pip-egg-info/pymc3.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/pymc3.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'pymc3/externals' does not exist
```

**Comment by twiecki** [comment]
Ugh, my bad. Should be fixed now.

**Comment by fretchen** [comment]
Ok, now the install works, but I get the new one here:

```
> import pymc3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fnj/retDevEnv/lib/python3.5/site-packages/pymc3/__init__.py", line 9, in <module>
    from .sampling import *
  File "/Users/fnj/retDevEnv/lib/python3.5/site-packages/pymc3/sampling.py", line 11, in <module>
    from .step_methods import (NUTS, HamiltonianMC, Metropolis, BinaryMetropolis,
  File "/Users/fnj/retDevEnv/lib/python3.5/site-packages/pymc3/step_methods/__init__.py", line 3, in <module>
    from .hmc import HamiltonianMC, NUTS
ImportError: No module named 'pymc3.step_methods.hmc'
```

**Comment by twiecki** [comment]
@fretchen, sorry about that, can you retry?

**Comment by fretchen** [comment]
Awesome. I would like to close this one now.
