### ISSUE TITLE
Cannot instantiate multivariate normal random variable

### ISSUE THREAD

**Issue by g-bassetto** [pymc-devs/pymc#1708]
Hi there,

I am having a problem when using multivariate normal random variables in my code.
If I try to run the following statements
```python
import numpy as np
from pymc3 import Model, MvNormal
m = Model()
with m:
    s = MvNormal('s',np.array([0.,0.]),np.diag([1.,1.]))
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/giacomo/environments/maprf/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-41-443b70e25de3>", line 2, in <module>
    s = MvNormal('s',np.array([0.,0.]),np.diag([1.,1.]))
  File "/home/giacomo/environments/maprf/lib/python3.5/site-packages/pymc3/distributions/distribution.py", line 31, in __new__
    return model.Var(name, dist, data)
  File "/home/giacomo/environments/maprf/lib/python3.5/site-packages/pymc3/model.py", line 280, in Var
    var = FreeRV(name=name, distribution=dist, model=self)
  File "/home/giacomo/environments/maprf/lib/python3.5/site-packages/pymc3/model.py", line 508, in __init__
    self.logp_elemwiset = distribution.logp(self)
  File "/home/giacomo/environments/maprf/lib/python3.5/site-packages/pymc3/distributions/multivariate.py", line 114, in logp
    delta = value - mu
  File "/home/giacomo/environments/maprf/lib/python3.5/site-packages/theano/tensor/var.py", line 147, in __sub__
    return theano.tensor.basic.sub(self, other)
```
I tried to look into theano's code to understand what may go wrong, but I couldn't figure it out. Any help would be appreciated, thanks.

**Comment by twiecki** [comment]
This is a bit clunky but you have to specify the shape: `s = MvNormal('s',np.array([0.,0.]),np.diag([1.,1.]), shape=2)`
