### ISSUE TITLE
Problem with Theano head

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#1754]
```
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'distutils')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/__init__.py", line 5, in <module>
    from .distributions import *
  File "/home/travis/build/pymc-devs/pymc3/pymc3/distributions/__init__.py", line 1, in <module>
    from . import timeseries
  File "/home/travis/build/pymc-devs/pymc3/pymc3/distributions/timeseries.py", line 1, in <module>
    import theano.tensor as tt
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/__init__.py", line 66, in <module>
    from theano.compile import (
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/vm.py", line 663, in <module>
    from . import lazylinker_c
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2237, in compile_str
    include_dirs = include_dirs + std_include_dirs()
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1581, in std_include_dirs
    numpy_inc_dirs = np.distutils.misc_util.get_numpy_include_dirs()
AttributeError: 'module' object has no attribute 'distutils'
```

**Comment by twiecki** [comment]
We're not alone: https://groups.google.com/forum/#!topic/theano-users/ks1KRzKUj-k

**Comment by fonnesbeck** [comment]
Shouldn't this be titled "Problem with Theano"?

**Comment by ColCarroll** [comment]
Can fix by pinning to the last working version, and keep an eye on https://github.com/Theano/Theano/issues/5491

**Comment by twiecki** [comment]
Seems like the fix was merged. Restarted travis.
