### ISSUE TITLE
pm.df_summary thinks MultiTrace is an numpy array

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1840]
After creating a `MultiTrace` object (which looks legit to me), calling `pm.df_summary()` raises the following error: 
```
Traceback (most recent call last):
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 28, in wrapped_f
    vars = kwargs.pop('vars',  pymc3_obj.varnames)
AttributeError: 'numpy.ndarray' object has no attribute 'varnames'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 28, in wrapped_f
    vars = kwargs.pop('vars',  pymc3_obj.varnames)
AttributeError: 'numpy.ndarray' object has no attribute 'varnames'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model.py", line 352, in <module>
    main()
  File "model.py", line 345, in main
    summarise(model_name, trace)
  File "model.py", line 303, in summarise
    df = pm.df_summary(trace)
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 623, in df_summary
    var_df = pd.concat([f(flat_vals) for f in stat_funcs], axis=1)
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 623, in <listcomp>
    var_df = pd.concat([f(flat_vals) for f in stat_funcs], axis=1)
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 611, in <lambda>
    lambda x: pd.Series(mc_error(x, batches), name='mc_error'),
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 32, in wrapped_f
    return f(pymc3_obj, *args, **kwargs)
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 471, in mc_error
    return np.reshape([mc_error(t, batches) for t in trace], dims[1:])
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 471, in <listcomp>
    return np.reshape([mc_error(t, batches) for t in trace], dims[1:])
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 32, in wrapped_f
    return f(pymc3_obj, *args, **kwargs)
  File "/net/lustre/home/smathias/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 478, in mc_error
    batched_traces = np.resize(x, (batches, int(len(x) / batches)))
ZeroDivisionError: division by zero
```

**Comment by junpenglao** [comment]
Hi @sammosummo, I think there might be problems with your setup. Please install the newest theano and pymc3, and there shouldn't be any problem anymore.
