### ISSUE TITLE
`MvNormal` problem:cov_matrix shape and input_data shape  not aligned 

### ISSUE THREAD

**Issue by KarlQu1990** [pymc-devs/pymc#1851]
Hi, 
When I run the following example in the `pymc3` documentation [(here):](http://pymc-devs.github.io/pymc3/notebooks/LKJ.html)

```
import numpy as np
import pymc3 as pm
import scipy as sp
import seaborn as sns
from theano import tensor as tt

N = 100
mu_actual = sp.stats.uniform.rvs(-5, 10, size=2)
cov_actual_sqrt = sp.stats.uniform.rvs(0, 2, size=(2, 2))
cov_actual = np.dot(cov_actual_sqrt.T, cov_actual_sqrt)

x = sp.stats.multivariate_normal.rvs(mu_actual, cov_actual, size=N)
init_sigma = np.std(x, axis=0)
init_corr = np.corrcoef(x, rowvar=0)[0, 1]

with pm.Model() as model:
    sigma = pm.Lognormal('sigma', np.zeros(2), np.ones(2), shape=2, testval=init_sigma)
    nu = pm.Uniform('nu', 0, 5)
    C_triu = pm.LKJCorr('C_triu', nu, 2, testval=init_corr)

    C = pm.Deterministic('C', tt.fill_diagonal(C_triu[np.zeros((2, 2), dtype=np.int64)], 1.))
    sigma_diag = pm.Deterministic('sigma_mat', tt.nlinalg.diag(sigma))
    cov = pm.Deterministic('cov', tt.nlinalg.matrix_dot(sigma_diag, C, sigma_diag))

    mu = pm.MvNormal('mu', 0, cov, shape=2, testval=np.mean(x, axis=0))
    x_ = pm.MvNormal('x', mu, cov, observed=x)
```
It raises a ValueError:
```
--------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-7-89c95d0bd03e>", line 2, in <module>
    x_ = pm.MvNormal('x', mu, cov, observed=x)

  File "build/bdist.linux-x86_64/egg/pymc3/distributions/distribution.py", line 35, in __new__
    return model.Var(name, dist, data, total_size)

  File "build/bdist.linux-x86_64/egg/pymc3/model.py", line 527, in Var
    total_size=total_size, model=self)

  File "build/bdist.linux-x86_64/egg/pymc3/model.py", line 849, in __init__
    self.logp_elemwiset = distribution.logp(data)

  File "build/bdist.linux-x86_64/egg/pymc3/distributions/multivariate.py", line 132, in logp
    result += (tt.dot(tau, delta) * delta).sum(axis=delta.ndim - 1)

  File "/home/qukaiyi/.local/lib/python2.7/site-packages/theano/tensor/basic.py", line 5969, in dot
    return _dot(a, b)

  File "/home/qukaiyi/.local/lib/python2.7/site-packages/theano/gof/op.py", line 663, in __call__
    required = thunk()

  File "/home/qukaiyi/.local/lib/python2.7/site-packages/theano/gof/op.py", line 861, in rval
    r = p(n, [x[0] for x in i], o)

  File "/home/qukaiyi/.local/lib/python2.7/site-packages/theano/tensor/basic.py", line 5787, in perform
    z[0] = numpy.asarray(numpy.dot(x, y))

ValueError: shapes (2,2) and (100,2) not aligned: 2 (dim 1) != 100 (dim 0)
``` 
My package environment:
```
python=2.7.13
theano=0.9.0rc2.dev-RELEASE
numpy=1.12.0
pymc3=3.0
```
It seams that `theano` results the problem.

**Comment by fonnesbeck** [comment]
I cannot replicate this here. I am running Python 3.6, Theano 0.9.0rc1, numpy 1.13 and the current master of PyMC3.

Can you replicate if you downgrade Theano?

**Comment by KarlQu1990** [comment]
@fonnesbeck  thanks. 
But it still raise the problem when I downgrage `theano` to 0.9.0rc1 and even when I run it in `python 3.6`.
So I try to reinstall `PyMC3` use `conda` both in my `python 2.7` and `python 3.6` env:
```
conda install -c conda-forge pymc3
```
It install theano=0.8.2 and the current master of PyMC3. And the problem never raise.
interestingly, when I upgrade theano using `pip install theano==0.9.0rc1` , the problem never raise.
So I think there is something wrong when I use 'pip install' to install `PyMC3` in the first place:
 ```
    git clone https://github.com/pymc-devs/pymc3
    cd pymc3
    pip install -r requirements.txt
    python setup.py install 
```
Anyway, there is no probem now, thanks again @fonnesbeck.
