### ISSUE TITLE
Travis unhappy for Python 3

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#1908]
```
======================================================================
ERROR: pymc3.tests.test_starting.test_find_MAP
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_starting.py", line 74, in test_find_MAP
    map_est1 = starting.find_MAP()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tuning/starting.py", line 94, in find_MAP
    start), fprime=grad_logp_o, *args, **kwargs)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 859, in fmin_bfgs
    res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 920, in _minimize_bfgs
    old_fval = f(x0)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tuning/starting.py", line 85, in logp_o
    return nan_to_high(-logp(point))
  File "/home/travis/build/pymc-devs/pymc3/pymc3/blocking.py", line 131, in __call__
    return self.fa(self.fb(x))
  File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 756, in __call__
    return self.f(**state)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/theano/compile/function_module.py", line 779, in __call__
    raise TypeError("Too many parameter passed to theano function")
TypeError: Too many parameter passed to theano function
```

**Comment by twiecki** [comment]
I love it when a problem resolves itself.
