### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by tdhopper** [pymc-devs/pymc#1991]
Often when I'm running something like this with pymc3 3.0: 
```
with Model() as first_model_glm:
    patsy_model = 'is_viol ~ ' + " + ".join(model_vars)
    glm.glm(patsy_model, 
            df.assign(is_viol=df_train.is_viol), family=glm.families.Binomial())
    first_trace_glm = sample(5000, step=Metropolis())
```
I get an error like this:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/tdhopper/miniconda2/envs/env/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/Users/tdhopper/miniconda2/envs/env/lib/python3.4/site-packages/tqdm/_tqdm.py", line 103, in run
    for instance in self.tqdm_cls._instances:
  File "/Users/tdhopper/miniconda2/envs/env/lib/python3.4/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

It's not obviously reproducible. I can re-run it and it'll run without error.

**Comment by twiecki** [comment]
can you upgrade to 3.1rc2?

**Comment by aseyboldt** [comment]
This happens when the tqdm progress bar is not closed. We fixed a couple of those cases (I hope all of them) since the last release.

**Comment by twiecki** [comment]
@tdhopper Does that fix it?

**Comment by tdhopper** [comment]
@twiecki I haven't been able to try it yet, sorry.
