### ISSUE TITLE
Some models will only run on CPU

### ISSUE THREAD

**Issue by kpfoley** [pymc-devs/pymc#2192]
I've been playing around with PyMc3 and on several occasions have run into a problem I don't understand: some models will run on the cpu but not on the GPU. I'm not sure if this is a bug or the result of some mistake in how I've set up the model. Any idea why this is happening?

I've tried this on two different nvidia GPUs, and with PyMc3 versions 3.0 and 3.1rc3. Theano is version 0.9. (FWIW I had another GPU-specific problem, see issue #[2138](https://github.com/pymc-devs/pymc3/issues/2138))

Here's an example of a hierarchical regression model with an LKJ prior on the covariance matrix of the regression coefficients:

```python
import numpy as np
import pymc3 as pm
from pymc3.variational.advi import sample_vp
import theano.tensor as tt
from scipy.stats import invwishart

# simulate data

N = 10000
D = 5
n_groups = 3
G = np.random.randint(0,n_groups,N)
X = np.random.uniform(0,10,(N,D))
mu_ = np.random.uniform(-10,10,D)
A_ = np.random.uniform(5,10)
cov_ = np.zeros((n_groups,D,D))
B_   = np.zeros((n_groups,D))
Y    = np.zeros(N)
cov_ = invwishart.rvs(D, np.eye(D),1)
for i in range(n_groups):
    B_[i]   = np.random.multivariate_normal(mu_, cov_)
    Y[G==i] = np.dot(X[G==i],B_[i])

Y   += A_

# set up the model, with LKJ prior implemented based on these examples:
# https://pymc-devs.github.io/pymc3/notebooks/LKJ.html
# http://stackoverflow.com/questions/29759789/modified-bpmf-in-pymc3-using-lkjcorr-priors-positivedefiniteerror-using-nuts


n_elem = D * (D - 1) / 2
tri_index = np.zeros([D, D], dtype=int)
tri_index[np.triu_indices(D, k=1)] = np.arange(n_elem)
tri_index[np.triu_indices(D, k=1)[::-1]] = np.arange(n_elem)

with pm.Model() as model:
    sigma = pm.Lognormal('sigma', tt.zeros(D),
        tt.ones(D), shape=D, testval=np.random.uniform(0,2,D))
    nu = pm.Uniform('nu', 0, 5)
    corr_triangle = pm.LKJCorr('corr_triangle', nu, D)
    corr_matrix = corr_triangle[tri_index]
    corr_matrix = tt.fill_diagonal(corr_matrix, 1)
    cov   = pm.Deterministic('cov', tt.diag(sigma).dot(corr_matrix.dot(tt.diag(sigma))) )
    A     = pm.Normal('A', 0,10)
    B     = pm.MvNormal('B', tt.zeros(D), cov, shape=(n_groups,D))
    mu    = pm.Deterministic('mu_'+str(i),A + tt.sum(X*B[G],1))
    sd    = pm.HalfCauchy('sd', 1)
    Y_obs = pm.Normal('Y_obs', mu, sd, observed=Y)

with model:
    params = pm.variational.advi(
        n=5000, learning_rate=2e-2, epsilon=0.1)
    samples    = sample_vp(params, draws=1000)
```

On the cpu, this runs fine (but gets NaN elbo values). On the GPU I get the following output:

```
$ THEANO_FLAGS='device=cuda0' python -i testLKJ.py
Using cuDNN version 5105 on context None
Mapped name None to device cuda0: GeForce GTX 1060 6GB (0000:01:00.0)
Traceback (most recent call last):
  File "testLKJ.py", line 52, in <module>
    n=5000, learning_rate=2e-2, epsilon=0.1)
  File "projects/pmstm/src/pymc3/pymc3/variational/advi.py", line 153, in advi
    f = theano.function([], [uw_shared, elbo], updates=updates, mode=mode)
  File "venv/pymc3/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "venv/pymc3/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "venv/pymc3/lib/python3.5/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "venv/pymc3/lib/python3.5/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/vm.py", line 1047, in make_all
    impl=impl))
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "venv/pymc3/lib/python3.5/site-packages/theano/gof/cc.py", line 1603, in cthunk_factory
    *(in_storage + out_storage + orphd))
RuntimeError: ('The following error happened while compiling the node', GpuElemwise{Psi}[(0, 0)]<gpuarray>(GpuElemwise{add,no_inplace}.0), '\n', 'Could not initialize elemwise support')
```

**Comment by kyleabeauchamp** [comment]
We are in the process of fixing GPU support.  I recommend that you update to the latest master of pymc3 and theano.

In particular, the ElemWise Psi issue looks similar to something that we already fixed in master of Theano+pymc3.

**Comment by kyleabeauchamp** [comment]
Are you running with float32 or float64?  Under CUDA + float64 I get "FloatingPointError: NaN occurred in ADVI optimization" while CUDA + float32 gives me the below log.  My conclusion is that the NaN error needs to be fixed on CPU first, then fix the model on GPU with latest master.  

```
TypeError: For compute_test_value, one input test value does not have the requested type.

The error when converting the test value to that variable type:
TensorType(float32, vector) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([ 1.65682483,  1.92289163,  1.29177028,  1.33340427,  1.94166752])"
```

**Comment by kpfoley** [comment]
OK, thanks! I'm running with float64. After upgrading to the latest master of Theano I get the same errors as you did.

**Comment by twiecki** [comment]
@kpfoley Try casting your testval settings with `pm.floatX()`:
```
    sigma = pm.Lognormal('sigma', tt.zeros(D),
        tt.ones(D), shape=D, testval=pm.floatX(np.random.uniform(0,2,D)))
```

**Comment by ferrine** [comment]
> TypeError: For compute_test_value, one input test value does not have the requested type.
> 
> The error when converting the test value to that variable type:
TensorType(float32, vector) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([ 1.65682483,  1.92289163,  1.29177028,  1.33340427,  1.94166752])"

I had the same traceback in my local test environment. #2207 is to fix it

**Comment by ferrine** [comment]
We for sure need some tests in float32 mode to be confident that "it works"

**Comment by twiecki** [comment]
@kyleabeauchamp made some progress here: https://github.com/pymc-devs/pymc3/issues/2053 but a lot of work remains.

One thing we should definitely do is auto-cast the test-values.

**Comment by kpfoley** [comment]
OK, this seems now to be three separate issues - getting NaN errors from `pm.variational.advi`, which seems to be due to the LKJcorr. I assume this is the same problem as #1852? 

The second issue (maybe my own inexperience with pymc3) is that even when casting everything as float32 and setting floatX to float32, I still get errors reporting some values are float64. When I check the random number generator of a pymc3 model parameter, i.e.:
```python
sigma.random().dtype
```
returns `float64`. I'm not sure if that could be the source of the error?

The third issue is the GPU issue, which occurred before I upgraded to the latest theano master. **Should I repost this issue to restate the problem as a dtype problem?**

Here's the code above, recast into float32:

```python
import theano
theano.config.floatX = 'float32'
import numpy as np
import pymc3 as pm
from pymc3.variational.advi import sample_vp
import theano.tensor as tt
from scipy.stats import invwishart

# simulate data

N = 10000
D = 5
n_groups = 3
G = np.random.randint(0,n_groups,N)
X = np.random.uniform(0,10,(N,D)).astype(theano.config.floatX)
mu_ = np.random.uniform(-10,10,D).astype(theano.config.floatX)
A_ = np.random.uniform(5,10)
cov_ = np.zeros((n_groups,D,D)).astype(theano.config.floatX)
B_   = np.zeros((n_groups,D)).astype(theano.config.floatX)
Y    = np.zeros(N).astype(theano.config.floatX)
cov_ = invwishart.rvs(D, np.eye(D),1).astype(theano.config.floatX)
for i in range(n_groups):
    B_[i]   = np.random.multivariate_normal(mu_, cov_).astype(theano.config.floatX)
    Y[G==i] = np.dot(X[G==i],B_[i]).astype(theano.config.floatX)

Y   += A_

# set up the model, with LKJ prior implemented based on these examples:
# https://pymc-devs.github.io/pymc3/notebooks/LKJ.html
# http://stackoverflow.com/questions/29759789/modified-bpmf-in-pymc3-using-lkjcorr-priors-positivedefiniteerror-using-nuts


n_elem = D * (D - 1) / 2
tri_index = np.zeros([D, D], dtype=int)
tri_index[np.triu_indices(D, k=1)] = np.arange(n_elem)
tri_index[np.triu_indices(D, k=1)[::-1]] = np.arange(n_elem)

with pm.Model() as model:
    sigma = pm.Lognormal('sigma', tt.zeros(D), tt.ones(D), shape=D, dtype='float32', testval=pm.floatX(np.random.uniform(0,2,D)))
    nu = pm.Uniform('nu', 0, 5)
    corr_triangle = pm.LKJCorr('corr_triangle', nu, D)
    corr_matrix = corr_triangle[tri_index]
    corr_matrix = tt.fill_diagonal(corr_matrix, 1)
    cov   = pm.Deterministic('cov', tt.diag(sigma).dot(corr_matrix.dot(tt.diag(sigma))) )
    A     = pm.Normal('A', 0,10)
    B     = pm.MvNormal('B', tt.zeros(D), cov, shape=(n_groups,D))
    mu    = pm.Deterministic('mu_',pm.floatX(A + tt.sum(X*B[G],1)))
    sd    = pm.HalfCauchy('sd', 1)
    Y_obs = pm.Normal('Y_obs', mu, sd, observed=Y)

with model:
    params = pm.variational.advi(
        n=5000, learning_rate=2e-2, epsilon=0.1)
    samples    = sample_vp(params, draws=1000)
```

And here's the error I get, running with floatX=float32 and device=cpu:
```
$python testLKJ.py
  0%|                                                                                    | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
TypeError: expected type_num 11 (NPY_FLOAT32) got 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testLKJ.py", line 53, in <module>
    n=5000, learning_rate=2e-2, epsilon=0.1)
  File "/home/kfoley/projects/pmstm/src/pymc3/pymc3/variational/advi.py", line 164, in advi
    uw_i, elbo_current = f()
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
TypeError: expected type_num 11 (NPY_FLOAT32) got 12
Apply node that caused the error: Elemwise{gt,no_inplace}(ExtractDiag{view=False}.0, TensorConstant{(1,) of 0})
Toposort index: 116
Inputs types: [TensorType(float32, vector), TensorType(int8, (True,))]
Inputs shapes: [(5,), (1,)]
Inputs strides: [(8,), (1,)]
Inputs values: [array([ nan,   1.,   1.,   1.,   1.]), array([0], dtype=int8)]
Outputs clients: [[All(Elemwise{gt,no_inplace}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "testLKJ.py", line 46, in <module>
    B     = pm.MvNormal('B', tt.zeros(D), cov, shape=(n_groups,D))
  File "/home/kfoley/projects/pmstm/src/pymc3/pymc3/distributions/distribution.py", line 38, in __new__
    return model.Var(name, dist, data, total_size)
  File "/home/kfoley/projects/pmstm/src/pymc3/pymc3/model.py", line 525, in Var
    total_size=total_size, model=self)
  File "/home/kfoley/projects/pmstm/src/pymc3/pymc3/model.py", line 817, in __init__
    self.logp_elemwiset = distribution.logp(self)
  File "/home/kfoley/projects/pmstm/src/pymc3/pymc3/distributions/multivariate.py", line 184, in logp
    return self._logp_cov(delta)
  File "/home/kfoley/projects/pmstm/src/pymc3/pymc3/distributions/multivariate.py", line 214, in _logp_cov
    ok = tt.all(diag > 0)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
