### ISSUE TITLE
NUTS error on linear regression example

### ISSUE THREAD

**Issue by antoinebaker** [pymc-devs/pymc#2372]
Hello,

I got an error when fitting NUTS on the linear regression model, following the [Getting started guide](http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Model-fitting)

```python
from scipy import optimize

with basic_model:
    # draw 500 posterior samples
    trace = pm.sample()
```

```python-traceback
Auto-assigning NUTS sampler...
Initializing NUTS using ADVI...
Average Loss = 156.23:   5%|▌         | 10799/200000 [00:01<00:22, 8400.60it/s]
Convergence archived at 11100
Interrupted at 11,100 [5%]: Average Loss = 237.04

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/d589618/anaconda/lib/python3.6/site-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    624                 try:
--> 625                     storage_map[ins] = [self._get_test_value(ins)]
    626                     compute_map[ins] = [True]

/Users/d589618/anaconda/lib/python3.6/site-packages/theano/gof/op.py in _get_test_value(cls, v)
    580         detailed_err_msg = utils.get_variable_trace_string(v)
--> 581         raise AttributeError('%s has no test value %s' % (v, detailed_err_msg))
    582 

AttributeError: Elemwise{add,no_inplace}.0 has no test value  
Backtrace when that variable is created:

  File "/Users/d589618/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-1ce76f284421>", line 1, in <module>
    map_estimate = pm.find_MAP(model=basic_model)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/tuning/starting.py", line 64, in find_MAP
    model.fastdlogp(vars)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/model.py", line 177, in fastdlogp
    return self.model.fastfn(gradient(self.logpt, vars))
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/memoize.py", line 16, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/model.py", line 459, in logpt
    return tt.add(*map(tt.sum, factors))


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-24-5200ec36cae7> in <module>()
      1 with basic_model:
      2     # draw 500 posterior samples
----> 3     trace = pm.sample()

/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain, njobs, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, **kwargs)
    238         start_, step = init_nuts(init=init, njobs=njobs, n_init=n_init,
    239                                  model=model, random_seed=random_seed,
--> 240                                  progressbar=progressbar, **args)
    241         if start is None:
    242             start = start_

/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/sampling.py in init_nuts(init, njobs, n_init, model, random_seed, progressbar, **kwargs)
    627         raise NotImplementedError('Initializer {} is not supported.'.format(init))
    628 
--> 629     step = pm.NUTS(scaling=cov, is_cov=True, **kwargs)
    630 
    631     return start, step

/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py in __init__(self, vars, Emax, target_accept, gamma, k, t0, adapt_step_size, max_treedepth, on_error, **kwargs)
    147         `pm.sample` to the desired number of tuning steps.
    148         """
--> 149         super(NUTS, self).__init__(vars, use_single_leapfrog=True, **kwargs)
    150 
    151         self.Emax = Emax

/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/step_methods/hmc/base_hmc.py in __init__(self, vars, scaling, step_scale, is_cov, model, blocked, use_single_leapfrog, potential, integrator, **theano_kwargs)
     62 
     63         self.H, self.compute_energy, self.compute_velocity, self.leapfrog, self.dlogp = get_theano_hamiltonian_functions(
---> 64             vars, shared, model.logpt, self.potential, use_single_leapfrog, integrator, **theano_kwargs)
     65 
     66         super(BaseHMC, self).__init__(vars, shared, blocked=blocked)

/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/step_methods/hmc/trajectory.py in get_theano_hamiltonian_functions(model_vars, shared, logpt, potential, use_single_leapfrog, integrator, **theano_kwargs)
    122     """
    123     H, q, dlogp = _theano_hamiltonian(model_vars, shared, logpt, potential)
--> 124     energy_function, p = _theano_energy_function(H, q, **theano_kwargs)
    125     velocity_function = _theano_velocity_function(H, p, **theano_kwargs)
    126     if use_single_leapfrog:

/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/step_methods/hmc/trajectory.py in _theano_energy_function(H, q, **theano_kwargs)
     51     p = tt.vector('p')
     52     p.tag.test_value = q.tag.test_value
---> 53     total_energy = H.pot.energy(p) - H.logp(q)
     54     energy_function = theano.function(inputs=[q, p], outputs=total_energy, **theano_kwargs)
     55     energy_function.trust_input = True

/Users/d589618/anaconda/lib/python3.6/site-packages/theano/tensor/var.py in __sub__(self, other)
    145         # and the return value in that case
    146         try:
--> 147             return theano.tensor.basic.sub(self, other)
    148         except (NotImplementedError, AsTensorError):
    149             return NotImplemented

/Users/d589618/anaconda/lib/python3.6/site-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    637                         raise ValueError(
    638                             'Cannot compute test value: input %i (%s) of Op %s missing default value. %s' %
--> 639                             (i, ins, node, detailed_err_msg))
    640                     elif config.compute_test_value == 'ignore':
    641                         # silently skip test

ValueError: Cannot compute test value: input 1 (Elemwise{add,no_inplace}.0) of Op Elemwise{sub,no_inplace}(Elemwise{mul,no_inplace}.0, Elemwise{add,no_inplace}.0) missing default value.  
Backtrace when that variable is created:

  File "/Users/d589618/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-1ce76f284421>", line 1, in <module>
    map_estimate = pm.find_MAP(model=basic_model)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/tuning/starting.py", line 64, in find_MAP
    model.fastdlogp(vars)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/model.py", line 177, in fastdlogp
    return self.model.fastfn(gradient(self.logpt, vars))
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/memoize.py", line 16, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/Users/d589618/anaconda/lib/python3.6/site-packages/pymc3/model.py", line 459, in logpt
    return tt.add(*map(tt.sum, factors))
```

 On python 3, theano 0.9.0 and pymc3 3.1rc1

**Comment by denadai2** [comment]
It works to me. I have the last version (from git).
Maybe something wrong with theano.rc config (if you have one)?

**Comment by antoinebaker** [comment]
I don't have any .theanorc config file, but when reinstalling theano, the problem disappeared. It now works.

**Comment by antoinebaker** [comment]
Theano version is now:
0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291

Let me know if I can provide you more information that could be of any help, but I guess that the issue was only my theano install. 

Thanks !
