### ISSUE TITLE
Error running /examples/lasso_missing.py

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2417]
```python
Traceback (most recent call last):

  File "<ipython-input-2-4c84dcf98240>", line 20, in <module>
    observed=masked_values(siblings, value=-999))

  File "/home/laoj/Documents/Github/pymc3/pymc3/distributions/distribution.py", line 36, in __new__
    return model.Var(name, dist, data, total_size)

  File "/home/laoj/Documents/Github/pymc3/pymc3/model.py", line 545, in Var
    total_size=total_size, model=self)

  File "/home/laoj/Documents/Github/pymc3/pymc3/model.py", line 977, in __init__
    data = as_tensor(data, name, model, distribution)

  File "/home/laoj/Documents/Github/pymc3/pymc3/model.py", line 932, in as_tensor
    model=model)

  File "/home/laoj/Documents/Github/pymc3/pymc3/model.py", line 878, in __init__
    distribution.shape, distribution.dtype) * distribution.default()

ValueError: operands could not be broadcast together with shapes (0,) (0,207) 
```

It was fine last time I check (#2254) so likely due to recently introduced changes.

**Comment by junpenglao** [comment]
oops I accidentally pushed to master directly... @twiecki should I reverse and PR properly?

**Comment by twiecki** [comment]
That's fine for a small fix like this.
