### ISSUE TITLE
Library import conflicts with PyMC3

### ISSUE THREAD

**Issue by Aorus42** [pymc-devs/pymc#2437]
I've observed a conflict between PyMC3 and OpenTurns on Windows 7 and 10, 64-bit. If PyMC3 is imported first, OpenTurns fails to import with the following error
```
Traceback (most recent call last):

  File "<ipython-input-3-704e69d30dff>", line 1, in <module>
    import openturns as ot

  File "C:\Anaconda3\lib\site-packages\openturns\__init__.py", line 61, in <module>
    from .common import *

  File "C:\Anaconda3\lib\site-packages\openturns\common.py", line 20, in <module>
    _common = swig_import_helper()

  File "C:\Anaconda3\lib\site-packages\openturns\common.py", line 19, in swig_import_helper
    return importlib.import_module('_common')

  File "C:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_common'
```

If I reverse the import order (i.e., OpenTurns first, then PyMC3), then PymC3 fails to import with
```
Traceback (most recent call last):

  File "<ipython-input-2-e9f7838173a6>", line 5, in <module>
    import pymc3 as pm

  File "C:\Anaconda3\lib\site-packages\pymc3\__init__.py", line 5, in <module>
    from .distributions import *

  File "C:\Anaconda3\lib\site-packages\pymc3\distributions\__init__.py", line 1, in <module>
    from . import timeseries

  File "C:\Anaconda3\lib\site-packages\pymc3\distributions\timeseries.py", line 1, in <module>
    import theano.tensor as tt

  File "C:\Anaconda3\lib\site-packages\theano\__init__.py", line 80, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,

  File "C:\Anaconda3\lib\site-packages\theano\scan_module\__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt

  File "C:\Anaconda3\lib\site-packages\theano\scan_module\scan_opt.py", line 60, in <module>
    from theano import tensor, scalar

  File "C:\Anaconda3\lib\site-packages\theano\tensor\__init__.py", line 9, in <module>
    from theano.tensor.subtensor import *

  File "C:\Anaconda3\lib\site-packages\theano\tensor\subtensor.py", line 26, in <module>
    import theano.gof.cutils  # needed to import cutils_ext

  File "C:\Anaconda3\lib\site-packages\theano\gof\cutils.py", line 320, in <module>
    compile_cutils()

  File "C:\Anaconda3\lib\site-packages\theano\gof\cutils.py", line 285, in compile_cutils
    preargs=args)

  File "C:\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)

  File "C:\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])

ImportError: DLL load failed: The specified procedure could not be found.
```
Both OpenTurns and PyMC3 work fine independently, but having these packages work together would be extremely useful. Any thoughts? Thank you!

**Comment by ColCarroll** [comment]
I can't find python source for open turns, but could you check whether the same problem occurs with `theano` and `openturns`?  Looks like it might be something going on in `C` land.
