### ISSUE TITLE
np.stack error, 'module' object has no attribute 'stack'

### ISSUE THREAD

**Issue by yongsua1989** [pymc-devs/pymc#2556]
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    trace = pm.sample()
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 276, in sample
    return sample_func(**sample_args)[discard:]
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 291, in _sample
    for it, strace in enumerate(sampling):
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 872, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/pymc3/sampling.py", line 409, in _iter_sample
    step.report._finalize(strace)
  File "/usr/local/lib/python2.7/dist-packages/pymc3/step_methods/hmc/nuts.py", line 462, in _finalize
    tuning = strace.get_sampler_stats('tune')
  File "/usr/local/lib/python2.7/dist-packages/pymc3/backends/base.py", line 170, in get_sampler_stats
    vals = np.stack([self._get_sampler_stats(varname, i, burn, thin)
AttributeError: 'module' object has no attribute 'stack'

**Comment by yongsua1989** [comment]
May I know how to solve it? Seems like backend issue.... The problem persists either with Python or iPython's Pylab too.

**Comment by ColCarroll** [comment]
`numpy.stack` was added in numpy version 1.10.0.  Can you post the output of
```
pip freeze | grep "pymc3\|numpy"
```

**Comment by yongsua1989** [comment]
numpy==1.8.2
pymc3==3.1

Ooopppsss... Seems like I am using the old numpy, I thought pymc3 had performed all the necessary installations for the required programs. Anyway, may I know how to appropriately update numpy to latest version? Thanks for the fast reply.

**Comment by ColCarroll** [comment]
We actually don't enforce an installation of numpy or scipy, since there are so many ways to do that, and we count on `theano`'s requirements to supply the proper versions.  

You can upgrade with `pip install -U numpy`, which will bump the numpy version!

**Comment by yongsua1989** [comment]
Thank You very much... Everything works fine now
