### ISSUE TITLE
Get context error when generating a GLM

### ISSUE THREAD

**Issue by roya0045** [pymc-devs/pymc#2568]
I'm using a class to create a GLM that is called with a  `with` statement, the model is created with the `from_xy` method. When I call the method to create the model, the NUTS sampling goes to 100% but after that I get a "No context on stack" error.

This is executed in a jupyther notebook.

I don't know if this can be fixed or if I should just edit out related statements in the source code since it doesn't seem to be useful.

**Comment by junpenglao** [comment]
Could you please provide a bit more information? What kind of statement did you call after sampling?

**Comment by roya0045** [comment]
Here is the code that I am using
```python
def GLM_gen(self, data=None, 
                fract_samp=1.0): 
        if data is None:
            data = self.data
        if self.GLM is None:
            with pm3.Model() as model:
                prior = pm3.distributions.continuous.Uniform
                y = data[[data.columns[-1]]]
                x = data[[data.columns[0]]]
                pm3.glm.glm.from_xy(X=x, y=y)
                self.trace = pm3.sampling.sample(ceil(len(data) * fract_samp), njobs=5)
                self.GLM = model
```

After NUTS fitting, each thread/jobs generate the error saying there is no context.

Maybe I'm missing something.

**Comment by fonnesbeck** [comment]
You say that the error occurs *after* fitting? If that's the case, it is probably occurring outside the scope of this code. What do you do with the model after it is assigned to `self.GLM`? It would be helpful to see the error trace itself.

**Comment by roya0045** [comment]
Nothing else is executed, this is the whole method that is called in my class. The issue happens when the threads are closing. Here are the last two error calls from the full "report".

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[python_path redacted]\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "[python_path redacted]\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "[python_path redacted]\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "[python_path redacted]\lib\site-packages\joblib\pool.py", line 362, in get
    return recv()
  File "[python_path redacted]\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
  File "[python_path redacted]\lib\site-packages\pymc3\step_methods\arraystep.py", line 38, in __new__
    model = modelcontext(kwargs.get('model'))
  File "[python_path redacted]\lib\site-packages\pymc3\model.py", line 131, in modelcontext
    return Model.get_context()
  File "[python_path redacted]\lib\site-packages\pymc3\model.py", line 123, in get_context
    raise TypeError("No context on context stack")
TypeError: No context on context stack
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "[python_path redacted]\lib\site-packages\pymc3\model.py", line 121, in get_context
    return cls.get_contexts()[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[python_path redacted]\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "[python_path redacted]\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "[python_path redacted]\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "[python_path redacted]\lib\site-packages\joblib\pool.py", line 362, in get
    return recv()
  File "[python_path redacted]\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
  File "[python_path redacted]\lib\site-packages\pymc3\step_methods\arraystep.py", line 38, in __new__
    model = modelcontext(kwargs.get('model'))
  File "[python_path redacted]\lib\site-packages\pymc3\model.py", line 131, in modelcontext
    return Model.get_context()
  File "[python_path redacted]\lib\site-packages\pymc3\model.py", line 123, in get_context
    raise TypeError("No context on context stack")
TypeError: No context on context stack

**Comment by fonnesbeck** [comment]
Does it work without multiprocessing, or with a smaller number of cores?

**Comment by roya0045** [comment]
I tried with njob=3, njob=1 and with importing multiprocessing at the start of the method. 

Only njob=1 worked properly.

**Comment by roya0045** [comment]
I updated to the devs version, and what worked properly now just freeze my whole system when executing. I have no clue what is causing this and the only way to solve it is to do a manual restart since even my mouse doesn't respond. 

Was such behaviour documented on the current dev build?

**Comment by fonnesbeck** [comment]
We've never had that behavior reported, no. Sounds like deeper problems with your disk or memory. Is your system low on RAM or disk space? Also, what Python version are you using? Is it Anaconda?

**Comment by roya0045** [comment]
What is strange is that everything worked properly on the pip version of the project on the same setup. Code was executed in a jupyter  notebook with 4gb of ram and plenty of hdd space and python 3.5. It was installed as an environment for TF.

**Comment by twiecki** [comment]
Have you tried clearing the theano cache?

**Comment by roya0045** [comment]
Negative, I did it just now. I'll try to check if that solved it when I get the time to.
