### ISSUE TITLE
Cannot import Pymc3

### ISSUE THREAD

**Issue by iamnotking** [pymc-devs/pymc#2641]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem
Cannot import pymc3

use pycharm as IDE and error happens when import pymc3

Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
import pymc3
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-37bf2a3357ff>", line 1, in <module>
    import pymc3
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pymc3\__init__.py", line 8, in <module>
    from .sampling import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pymc3\sampling.py", line 11, in <module>
    from .step_methods import (NUTS, HamiltonianMC, Metropolis, BinaryMetropolis,
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pymc3\step_methods\__init__.py", line 3, in <module>
    from .hmc import HamiltonianMC
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pymc3\step_methods\hmc\__init__.py", line 1, in <module>
    from .hmc import HamiltonianMC
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pymc3\step_methods\hmc\hmc.py", line 4, in <module>
    from .base_hmc import BaseHMC
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py", line 6, in <module>
    from pymc3.theanof import inputvars, floatX
ImportError: cannot import name 'floatX'

## Versions and main components

* PyMC3 Version: 3.0
* Theano Version: 0.9.0
* Python Version: 3.6.2
* Numpy Version: 1.13.3
* Operating system: win 10 64 bit
* How did you install PyMC3: (conda/pip) conda install pymc3

**Comment by aseyboldt** [comment]
Could you try to update to version 3.2 and see if that fixes the problem? You can update with
```
pip install -U pymc3
```
or
```
conda update -c conda-forge pymc3
```
depending on how you installed it.

**Comment by aseyboldt** [comment]
Could you try to update to pymc3 version 3.2?
