### ISSUE TITLE
Shape error related to #2499

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2644]
Reported by user on discourse: https://discourse.pymc.io/t/multivariate-normal-code-does-not-work-since-version-3-2/456

#2499 somehow breaks the following code:
```python
import numpy as np
import pymc3 as pm

with pm.Model() as model:
    sigma = pm.Lognormal('sigma', mu=np.zeros(2), tau=np.ones(2), shape=2)
    nu = pm.Uniform('nu', 0, 5)
    C_triu = pm.LKJCorr('C_triu', n=nu, p=2)

    trace = pm.sample()
```
Output:
```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
  0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):

  File "<ipython-input-2-3a6b5294a20f>", line 2, in <module>
    trace = pm.sample()

  File "/home/laoj/Documents/Github/pymc3/pymc3/sampling.py", line 286, in sample
    return sample_func(**sample_args)[discard:]

  File "/home/laoj/Documents/Github/pymc3/pymc3/sampling.py", line 333, in _sample
    for it, strace in enumerate(sampling):

  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 872, in __iter__
    for obj in iterable:

  File "/home/laoj/Documents/Github/pymc3/pymc3/sampling.py", line 431, in _iter_sample
    point, states = step.step(point)

  File "/home/laoj/Documents/Github/pymc3/pymc3/step_methods/arraystep.py", line 175, in step
    apoint, stats = self.astep(array)

  File "/home/laoj/Documents/Github/pymc3/pymc3/step_methods/hmc/nuts.py", line 178, in astep
    start = self.integrator.compute_state(q0, p0)

  File "/home/laoj/Documents/Github/pymc3/pymc3/step_methods/hmc/integration.py", line 25, in compute_state
    logp, dlogp = self._logp_dlogp_func(q)

  File "/home/laoj/Documents/Github/pymc3/pymc3/model.py", line 435, in __call__
    logp, dlogp = self._theano_function(array)

  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))

  File "/usr/local/lib/python3.5/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)

  File "/usr/local/lib/python3.5/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)

  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\

ValueError: Input dimension mis-match. (input[0].shape[0] = 2, input[1].shape[0] = 1)
Apply node that caused the error: Elemwise{Composite{((-i0) + i1 + i2)}}(Elemwise{Composite{log(exp(i0))}}.0, TensorConstant{(1,) of -1.0}, TensorConstant{(1,) of 1.0})
Toposort index: 14
Inputs types: [TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, (True,))]
Inputs shapes: [(2,), (1,), (1,)]
Inputs strides: [(8,), (8,), (8,)]
Inputs values: [array([-0.4530229 , -0.29442405]), array([-1.]), array([ 1.])]
Outputs clients: [[IncSubtensor{InplaceInc;int64:int64:}(Alloc.0, (d__logp/dsigma_log__), Constant{2}, Constant{4})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by junpenglao** [comment]
cc @aseyboldt

**Comment by junpenglao** [comment]
Also the above code works changing `sigma` to `sigma = pm.Lognormal('sigma', mu=np.zeros(2), tau=1, shape=2)`, it is actually a bit weird that it works without problem before... Maybe broadcasting the shape as in https://github.com/pymc-devs/pymc3/pull/2623 is a better solution? cc @ColCarroll

**Comment by burnpanck** [comment]
I seem to be observing a similar problem:

On PyMC3 3.4.1 I get a dimension mismatch when the gradient is evaluated in the following MWE (it looks one constant of the Lognormal transform has shape (1,) but is not broadcastable):
```
n = 4
x = np.random.randn(n)
with pymc3.Model() as model:
    a = pymc3.Lognormal('a',tau=x**2+1,mu=x,shape=n)
    b = pymc3.Normal('b',sd=1,mu=x+a,observed=x,shape=n)
pymc3.find_MAP(model=model)
```
Ignore that this model does not make any sense at all, it has been stripped down to a MWE from something useful.
Note that the following doesn't seem to fail, while it did fail with PyMC3 3.3:
```
n = 4
x = np.random.randn(n)
with pymc3.Model() as model:
    a = pymc3.Lognormal('a',tau=x,mu=x,shape=n)
    b = pymc3.Normal('b',sd=1,mu=x+a,observed=x,shape=n)
pymc3.find_MAP(model=model)
```
Possibly, 3.4 included an incomplete fix for the problem I observe?

**Comment by junpenglao** [comment]
Yes this is actually fixed in https://github.com/pymc-devs/pymc3/pull/2949 and https://github.com/pymc-devs/pymc3/pull/2959
Funny enough the error seems to related to Lognormal only.
