### ISSUE TITLE
Sampling Bernoulli indicator variable gives TypeError

### ISSUE THREAD

**Issue by poppymiller** [pymc-devs/pymc#2650]
I am trying to infer an indicator variable to get the probability that a variable is 0. The model compiles, assigns updaters to the parameters, then throws a TypeError error. 

**Model:** 
logit(pi) = alpha * z
z ~ Bernoulli(p)
p ~ Beta(1, 1)
alpha ~ Normal(0, 100)

## Code
```
import numpy as np
import pymc3 as pm
import pandas as pd
import theano as t
import theano.tensor.slinalg as tla
import theano.tensor as tt

def inv_logit(x):
    return np.exp(x) / (1 + np.exp(x))

d = {'n': 5, 'm': np.random.binomial(n = 5, p = inv_logit(0.1), size = 50)}
dataset = pd.DataFrame(d)

def binom_model(n, m):
    n = t.shared(n)
    m = t.shared(m)

    model = pm.Model()

    with model:
        alpha = pm.Normal('alpha', 0., 100., shape = 1, testval=0)
        piz = pm.Beta("piz", 1, 1, shape = 1)
        z = pm.Bernoulli("z", p = piz, shape = 1)
        alphaz = pm.Deterministic("alphaz", z * alpha)
        p = pm.Deterministic("p", inv_logit(alphaz))
        yobs = pm.Binomial('yobs', n = n, p = p, observed=m)
        return model

mod = binom_model(n = np.array(dataset[['n']]).flatten(),
                          m = np.array(dataset[['m']]).flatten())

with mod:
    trace = pm.sample()
```
## Output
```
Assigned NUTS to alpha
Assigned NUTS to piz_logodds__
Assigned BinaryGibbsMetropolis to z
Traceback (most recent call last):
  File "/home/.../zip.py", line 196, in <module>
    trace = pm.sample()
  File "/usr/local/lib/python3.5/dist-packages/pymc3/sampling.py", line 257, in sample
    step = assign_step_methods(model, step, step_kwargs=step_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/sampling.py", line 91, in assign_step_methods
    step = step_class(vars=vars, **args)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/step_methods/hmc/nuts.py", line 155, in __init__
    super(NUTS, self).__init__(vars, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/step_methods/hmc/base_hmc.py", line 46, in __init__
    dtype=dtype, **theano_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/step_methods/arraystep.py", line 168, in __init__
    vars, dtype=dtype, **theano_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/model.py", line 658, in logp_dlogp_function
    return ValueGradFunction(self.logpt, grad_vars, extra_vars, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/model.py", line 405, in __init__
    inputs, [self._cost_joined, grad], givens=givens, **kwargs)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 219, in rebuild_collect_shared
    cloned_v = clone_v_get_shared_updates(v, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 96, in clone_v_get_shared_updates
    [clone_d[i] for i in owner.inputs], strict=rebuild_strict)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/gof/graph.py", line 238, in clone_with_new_inputs
    new_inputs[i] = curr.type.filter_variable(new)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/tensor/type.py", line 235, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(int64, vector) (of Variable z_shared__) into Type TensorType(int64, (True,)). You can try to manually convert z_shared__ into a TensorType(int64, (True,)).

Process finished with exit code 1
```

I have simplified the model to submit the bug. I encountered the error trying to get the probability that a spatial random effect is needed in a model.

logit(pi) = alpha + S
z ~ Bernoulli(p)
p ~ Beta(1, 1)
alpha ~ Normal(0, 100)
S ~ MVN(0, z * sigmasq * Cov)
where Cov is a spatial covariance matrix and sigmasq is the overall variance.

## Versions and main components

* PyMC3 Version: 3.1
* Theano Version: 0.9.0
* Python Version: 3.5.2
* Operating system: Ubuntu 16.04
* How did you install PyMC3: I don't remember- probably using the pycharm gui

**Comment by junpenglao** [comment]
You can remove the `shape=1`.

**Comment by poppymiller** [comment]
Thank you! I also needed to add a testval to the z line to make it work otherwise it gave an error about converting the test value to that variable type. 
```
z = pm.Bernoulli("z", p = piz, testval = 1)
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e7dce5dd49e5>", line 36, in <module>
    m = np.array(dataset[['m']]).flatten())
  File "<ipython-input-2-e7dce5dd49e5>", line 27, in binom_model
    z = pm.Bernoulli("z", p = piz)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/distributions/distribution.py", line 37, in __new__
    return model.Var(name, dist, data, total_size)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/model.py", line 752, in Var
    total_size=total_size, model=self)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/model.py", line 1123, in __init__
    self.logp_elemwiset = distribution.logp(self)
  File "/usr/local/lib/python3.5/dist-packages/pymc3/distributions/discrete.py", line 182, in logp
    tt.switch(value, tt.log(p), tt.log(1 - p)),
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/tensor/elemwise.py", line 578, in make_node
    DimShuffle, *inputs)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/tensor/elemwise.py", line 534, in get_output_info
    ['x'] * difference + list(range(length)))(input))
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/gof/op.py", line 625, in __call__
    storage_map[ins] = [self._get_test_value(ins)]
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/gof/op.py", line 562, in _get_test_value
    ret = v.type.filter(v.tag.test_value)
  File "/home/millerp/.local/lib/python3.5/site-packages/theano/tensor/type.py", line 178, in filter
    data.shape))
TypeError: For compute_test_value, one input test value does not have the requested type.
The error when converting the test value to that variable type:
Wrong number of dimensions: expected 0, got 1 with shape (1,).
```

**Comment by junpenglao** [comment]
Thanks for reporting back. I cannot reproduce that problem - maybe try update to 3.2 and also clear the theano cache (the .theano folder).

**Comment by fonnesbeck** [comment]
I can confirm this bug on master and Python 3.6 on macOS.

**Comment by fonnesbeck** [comment]
The problem is related to giving `z` a shape of 1, which results in a variable shape of `array([1])`. Removing the `shape` argument results in the model running without error.

It also works fine if you make `z` vector-values, for example:

`z = pm.Bernoulli("z", p = piz, shape = m.shape.tag.test_value)`

**Comment by fonnesbeck** [comment]
Should we be squashing  degenerate 1-d shapes to scalars?
