### ISSUE TITLE
TypeError in SMC sampling because step returns tuple

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#2727]
## Description
I wanted to compare SMC with other samplers when I encountered this problem.

```python
import pymc3 as pm

with pm.Model():
    n = pm.Normal('n', mu=0, sd=1)
    trace = pm.sample(step=pm.SMC())
```

This is the traceback I get with the current master version.

```bash
Python 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 13:26:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc3
>>> with pymc3.Model():
...     n = pymc3.Normal('n', mu=0, sd=1)
...     trace = pymc3.sample(step=pymc3.SMC())
...
/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/pymc3/step_methods/smc.py:120: UserWarning: Warning: SMC is an experimental step method, and not yet recommended for use in PyMC3!
  warnings.warn(EXPERIMENTAL_WARNING)
Adding model likelihood to RVs!
  0%|                           | 0/1000 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 350, in __call__
    return self.func(*args, **kwargs)
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/pymc3/sampling.py", line 447, in _sample
    for it, strace in enumerate(sampling):
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/tqdm/_tqdm.py", line 872, in __iter__
    for obj in iterable:
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/pymc3/sampling.py", line 551, in _iter_sample
    strace.record(point)
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/pymc3/backends/ndarray.py", line 95, in record
    for varname, value in zip(self.varnames, self.fn(point)):
  File "/home/bq/miniconda3/envs/venv35/lib/python3.5/site-packages/pymc3/model.py", line 1022, in __call__
    return self.f(**state)
TypeError: Function object argument after ** must be a mapping, not tuple
```

I believe this is because the `ArrayStepSharedLLK` step returns a tuple, which is not correctly handled in the sampling iterators.

**Comment by aloctavodia** [comment]
AFAIK, SMC needs a little bit more care than the rest of the samplers. Try this instead.

```python
from tempfile import mkdtemp
from pymc3.step_methods import smc
test_folder = mkdtemp(prefix='SMC_TEST')

with pm.Model():
    n = pm.Normal('n', mu=0, sd=1)
    trace = smc.sample_smc(n_steps=100, homepath=test_folder)
```

**Comment by michaelosthege** [comment]
looks like you're right. The current implementation seems to be quite incompatible with the usual `pymc3.sample()` methods 😕
