### ISSUE TITLE
Exponential Theano Compilation Time

### ISSUE THREAD

**Issue by eqv** [pymc-devs/pymc#2751]
## Description of your problem
While manually numerically solving an ODE with fixed step size, I encounter very slow model construction and out of memory errors in Theano. It seems that exponentially sized formulars are generated from rather simple models.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
import time

basic_model = pm.Model()

with basic_model:
    print("constructing modell")
    growth_factor = pm.Uniform("growth_factor", lower = 0, upper=2)
    cells = 0.1
    start_constr = time.time()
    for i in xrange(25):
        #cells = cells * growth_factor # this form is fast (hundrets of steps are no problem)
        cells = cells + cells * growth_factor #this form very slow, oom after ~ 25 - 30 steps
    pm.Normal( "final", mu = cells, sd = 1, observed=[3.0])
    print("constructing modell took", time.time()-start_constr)

with basic_model:
    print("build sampler")
    start_constr = time.time()
    step = pm.Metropolis(profile=True)
    print("done compiling sampler, took", time.time() - start_constr)
```
**Please provide the full traceback.**
```
build sampler
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.InplaceElemwiseOptimizer object at 0x7fb2af5fe710>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 372, in apply
    fgraph.validate()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 256, in validate_
    ret = fgraph.execute_callbacks('validate')
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 589, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/destroyhandler.py", line 906, in validate
    ords = self.orderings(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/destroyhandler.py", line 1016, in orderings
    % (app, destroyed_idx, i))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 180, in __str__
    return op_as_string(self.inputs, self)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 1234, in op_as_string
    return node_formatter(op, strs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 1039, in default_node_formatter
    return "%s(%s)" % (op.op, ", ".join(argstrings))
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 589, in __str__
    return "Elemwise{%s}%s" % (self.scalar_op, str(items))
  File "/usr/local/lib/python2.7/dist-packages/theano/scalar/basic.py", line 3682, in __str__
    self.init_name()
  File "/usr/local/lib/python2.7/dist-packages/theano/scalar/basic.py", line 3816, in init_name
    in self.fgraph.outputs])
  File "/usr/local/lib/python2.7/dist-packages/theano/printing.py", line 616, in __call__
    return self.process(*args)
  File "/usr/local/lib/python2.7/dist-packages/theano/printing.py", line 546, in process
    return self.printers_dict[r.owner.op].process(r, pstate)
  File "/usr/local/lib/python2.7/dist-packages/theano/printing.py", line 399, in process
    r = "(%s)" % s
MemoryError
```

**Please provide any additional information below.**
sometimes gigabytes of additions are printed: 
```... (((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) * i9)) + ((((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) + (((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) * i9)) * i9)) + (((((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) + (((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) * i9)) + ((((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) + (((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) * i9)) * i9)) * i9)) + ((((((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) + (((i8 + (i8 * i9)) + ((i8 + (i8 * i9)) * i9)) * i9)) + ((((i8 + (i8 * i9))...```

## Versions and main components

* PyMC3 Version: pymc3 (3.1)
* Theano Version: Theano (0.9.0)
* Python Version: Python 2.7.12
* Operating system: Ubuntu
* How did you install PyMC3: (pip)

**Comment by fonnesbeck** [comment]
You can't build loops with Theano objects. You need to use `scan` (see the [Theano docs](http://deeplearning.net/software/theano/library/scan.html)).
