### ISSUE TITLE
raise ImportError() on calling import pymc3 as pm

### ISSUE THREAD

**Issue by kszynkar** [pymc-devs/pymc#2770]
## Description of my problem

Hi,

When I try to import pymc3 I get an error after installing it. I've tried different combinations of theano and pymc3 versions and using conda and pip to install but have gotten different errors when trying to import pymc3.

To narrow it down. Here's one example.

Here is the code snippet that generates the following error:
	`import pymc3 as pm`

I installed the development version of pymc3 and theano using 
	'>pip install git+https://github.com/pymc-devs/pymc3'
	'>pip install git+https://github.com/Theano/Theano.git#egg=Theano'

Here's the console output and traceback:
C:\Anaconda3\python.exe "C:/Users/kszynkarczuk_stm/PycharmProjects/Bayesian Inference Example/Example.py"

You can find the C code in this temporary file: C:\Users\KSZYNK~1\AppData\Local\Temp\theano_compilation_error_ne_wuil_
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/kszynkarczuk_stm/PycharmProjects/Bayesian Inference Example/Example.py", line 4, in <module>
    import pymc3 as pm
  File "C:\Anaconda3\lib\site-packages\pymc3\__init__.py", line 5, in <module>
    from .distributions import *
  File "C:\Anaconda3\lib\site-packages\pymc3\distributions\__init__.py", line 1, in <module>
    from . import timeseries
  File "C:\Anaconda3\lib\site-packages\pymc3\distributions\timeseries.py", line 1, in <module>
    import theano.tensor as tt
  File "C:\Anaconda3\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Anaconda3\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Anaconda3\lib\site-packages\theano\gof\vm.py", line 673, in <module>
    from . import lazylinker_c
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 

Process finished with exit code 1

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 1.0.1+19.gf62fd39
* Python Version: 3.5.2
* Operating system: Windows 7 x64 Professional SP1
* How did you install PyMC3: pip

Results of '>pip show pymc3 theano pandas patsy numpy scipy'

Name: pymc3
Version: 3.2
Summary: PyMC3
Home-page: http://github.com/pymc-devs/pymc3
Author: PyMC Developers
Author-email: pymc.devs@gmail.com
License: Apache License, Version 2.0
Location: c:\anaconda3\lib\site-packages
Requires: theano, pandas, patsy, joblib, tqdm, six, h5py, enum34
---
Name: Theano
Version: 1.0.1+19.gf62fd39
Summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
Home-page: http://deeplearning.net/software/theano/
Author: LISA laboratory, University of Montreal
Author-email: theano-dev@googlegroups.com
License: BSD
Location: c:\anaconda3\lib\site-packages
Requires: numpy, scipy, six
---
Name: pandas
Version: 0.22.0
Summary: Powerful data structures for data analysis, time series,and statistics
Home-page: http://pandas.pydata.org
Author: The PyData Development Team
Author-email: pydata@googlegroups.com
License: BSD
Location: c:\anaconda3\lib\site-packages
Requires: python-dateutil, pytz, numpy
---
Name: patsy
Version: 0.4.1
Summary: A Python package for describing statistical models and for building design matrices.
Home-page: https://github.com/pydata/patsy
Author: Nathaniel J. Smith
Author-email: njs@pobox.com
License: 2-clause BSD
Location: c:\anaconda3\lib\site-packages
Requires: six, numpy
---
Name: numpy
Version: 1.13.3
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@python.org
License: BSD
Location: c:\anaconda3\lib\site-packages
Requires:
---
Name: scipy
Version: 1.0.0
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: SciPy Developers
Author-email: scipy-dev@python.org
License: BSD
Location: c:\anaconda3\lib\site-packages
Requires:

Can someone help me with this please?

**Comment by ColCarroll** [comment]
This _looks_ like a problem with theano.  Does `import theano.tensor as tt` work for you?

**Comment by kszynkar** [comment]
It does not. Shall I follow up with theano? Here's the full output:

C:\Anaconda3\python.exe "C:/Users/kszynkarczuk_stm/PycharmProjects/Bayesian
Inference Example/Example.py"
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line
75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line
92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/kszynkarczuk_stm/PycharmProjects/Bayesian Inference
Example/Example.py", line 4, in <module>
    import theano.tensor as tt
  File "C:\Anaconda3\lib\site-packages\theano\__init__.py", line 110, in
<module>
    from theano.compile import (
  File "C:\Anaconda3\lib\site-packages\theano\compile\__init__.py", line
12, in <module>
    from theano.compile.mode import *
  File "C:\Anaconda3\lib\site-packages\theano\compile\mode.py", line 11, in
<module>
    import theano.gof.vm
  File "C:\Anaconda3\lib\site-packages\theano\gof\vm.py", line 673, in
<module>

You can find the C code in this temporary file:
C:\Users\KSZYNK~1\AppData\Local\Temp\theano_compilation_error_05fr3mv3
    from . import lazylinker_c
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line
127, in <module>
    preargs=args)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2359,
in compile_str
    (status, compile_stderr.replace('\n', '. ')))
.

Process finished with exit code 1

Thanks
Kamil

**Comment by ColCarroll** [comment]
I do not have a windows machine to try this on, but you might also check out http://deeplearning.net/software/theano_versions/dev/install_windows.html for theano installation instructions. Two things to try are to downgrade `numpy` and `scipy` to the versions they recommend. I am closing this here, since it is a problem with the theano install.  Good luck!
