### ISSUE TITLE
Weird DiscreteUniform behaviour

### ISSUE THREAD

**Issue by rpetit** [pymc-devs/pymc#2826]
Hi,

I just noticed a weird behaviour using DiscreteUniform distribution. I opened a [topic](https://discourse.pymc.io/t/issue-with-discreteuniform-distribution/800) on PyMC DIscourse and was answered that this was probably a bug.

Here is the minimal example that produces the error : 

```
import pymc3 as pm
import theano
import theano.tensor as T

model = pm.Model()

with model:
    X = pm.DiscreteUniform('X', lower=0, upper=1)
    t = T.as_tensor_variable([1, 2])

    mu = t[X]

    Y = pm.Normal('Y', mu=mu, sd=0.01, observed=2)

with model:
    trace = pm.sample()
```

Here is the full traceback : 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
IndexError: index out of bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petit/Documents/python/error.py", line 16, in <module>
    trace1 = pm.sample()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymc3/sampling.py", line 285, in sample
    return sample_func(**sample_args)[discard:]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymc3/sampling.py", line 332, in _sample
    for it, strace in enumerate(sampling):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tqdm/_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymc3/sampling.py", line 430, in _iter_sample
    point, states = step.step(point)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymc3/step_methods/arraystep.py", line 153, in step
    apoint, stats = self.astep(bij.map(point))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymc3/step_methods/metropolis.py", line 156, in astep
    accept = self.delta_logp(q, q0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
IndexError: index out of bounds
Apply node that caused the error: Subtensor{int64}(TensorConstant{[1 2]}, ScalarFromTensor.0)
Toposort index: 9
Inputs types: [TensorType(int64, vector), Scalar(int64)]
Inputs shapes: [(2,), ()]
Inputs strides: [(8,), ()]
Inputs values: [array([1, 2]), 2]
Outputs clients: [[Elemwise{Composite{(i0 * (i1 + (i2 * sqr((i3 - i4)))))}}(TensorConstant{0.5}, TensorConstant{7.372463305566837}, TensorConstant{-10000.0}, TensorConstant{2.0}, Subtensor{int64}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/Users/petit/Documents/python/error.py", line 11, in <module>
    mu = t[X]

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

I am using PyMC3 (v3.2) and Theano (v1.0.1) with Python 3.6.4 on Mac OS X (PyMC3 was installed via pip3).

Thanks in advance !

**Comment by junpenglao** [comment]
Just to explain it further: the default Proposal distribution, in this case, is not good: it makes proposal outside of the supported range. Usually, in Metropoli it is not a big deal because the proposal just gets rejected. However, in this case because it propagates to the next logp evaluation in Normal, where it is trying to index to `t` and cause the error.

It would need some refactoring of Metropolis.py to properly fix it, eg introduce transition kernel which makes working with discrete RV easier.

**Comment by rpetit** [comment]
I am new to PyMC3 but I have some time to dedicate to this issue. Do you think this is something that could be tackled by a beginner ?

**Comment by junpenglao** [comment]
I think it might be a bit tricky: if you have say a Discrete Uniform between [0, 10000] then it is better to use the current implementation. Boundary case is not always easy to tackle.

**Comment by canyon289** [comment]
Seems like the user got what they needed. Closing

**Comment by Tiantian-H** [comment]
Dear all, I'm implementing a very similar idea of using pm.DiscreteUniform to sample indexes from 0-999 and use the indexes to index an array of size 1000. Got the exact same error of index out of bounds. I'm not sure if I've fully understood the answer above. Does that mean even if I state that the bound if the DiscreteUniform is [0,999], it's still possible to get some samples larger than 999?

It will be highly appreciated if you could give a more detailed explanation about how to fix it.

Besides, if I expand the size of my array which I want to index from 1000 to 5000, where the later 4000 elements are all 0 (which means only the first 1000 elements are effective, the later 4000 are only used to avoid the out of bounds error), and then use pm.DiscreteUniform(0,999) to sample the index, will it work? (Or the later 4000 zeros will cause some bad influence on my final result?)

Thank you so much!

**Comment by ricardoV94** [comment]
If you need discrete variables for indexing, the best is to sample a continuous uniform and then discretize it, such as with `tt.round(uniform).astype("int64")`. Due to the automatic transformation on the continuous uniform, no invalid values should ever be proposed
