### ISSUE TITLE
Calling PyMC3 from FLASK REST end point causes numerous errors

### ISSUE THREAD

**Issue by sada-narayanappa** [pymc-devs/pymc#2970]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem

Pymc3 throws lots of errors when called from Flask Rest end point. It works fine with a single call.
However, if two calls are made simultaneously, I get tons of errors.
The errors are random and incomprehensible. I am not sure if pymc3 framework is not intended to work in REST end points! Could some one please review and advise on how to fix this issue. 

I am using Anaconda Python 3.5.3 

**Please provide a minimal, self-contained, and reproducible example.**
\#  A Simple FLASK program to reproduce
\# To run following command
\#         python pymc3WS.py
\# And use snippet at the end of the program to make a call simultaneously

\#  File Name: pymc3WS.py
```python
from flask import Flask, jsonify, request, send_from_directory
from flask_api import status
import json
import pymc3
from pymc3 import Model, Normal, invlogit, Binomial, sample, forestplot, Deterministic, traceplot

app = Flask(__name__)

def genCB(v, rent=500):
    ret = v['Number Of Units'] * rent - v['Operating Cost']
    return ret

def genResults():
    N={}
    with pymc3.Model() as mcmc:
        pymc3.Uniform('Number Of Units', 30, 40);
        pymc3.Normal('Operating Cost', mu=15000, sd=1000 );
        B8 = pymc3.Binomial("Patients Cured", 100,.25); # C8

        for c in mcmc.unobserved_RVs:
            N[str(c)] = c

        ROI = Deterministic('ROI', genCB(N) )

        step = pymc3.Metropolis()
        traced = sample(1000, step)
    
@app.route('/get/<file>/', methods=['GET'])
def get(file):
    return send_from_directory(".", "pymc3WS.py", as_attachment=True)

@app.route('/', methods=['GET', 'POST'])
def RunSimulation():
    filename= "ItDoesntMatter.txt"
    u= request.url
    r= u + "get/"+ filename
    rzip = u + "get/" + filename
    
    r = genResults() 
    return jsonify({'Results': rzip})

from config import *
app.run(host='0.0.0.0', threaded=True)
```
#To test run the following Python program:
#
```
import _thread
import requests
def RunSimulation(tname="THREAD_NAME"):
    r = requests.post('http://localhost:5000')
    print(r.text[0:100])
    print(r)

_thread.start_new_thread( RunSimulation,('TH1',) ) # Calling only one works fines
_thread.start_new_thread( RunSimulation,('TH2',) ) # Calling two simultaneously cause errors
_thread.start_new_thread( RunSimulation,('TH3',) )
```

**Please provide the full traceback.**
Following are the errors I see when I run 3 calls simultaneously.
```shell
127.0.0.1 - - [09/May/2018 12:21:21] "POST / HTTP/1.1" 200 -
[2018-05-09 12:21:54,716] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "pymc3WS.py", line 39, in RunSimulation
    r = genResults()
  File "pymc3WS.py", line 25, in genResults
    step = pymc3.Metropolis()
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/step_methods/arraystep.py", line 65, in __new__
    step.__init__([var], *args, **kwargs)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/step_methods/metropolis.py", line 130, in __init__
    self.delta_logp = delta_logp(model.logpt, vars, shared)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/step_methods/metropolis.py", line 479, in delta_logp
    [logp0], inarray0 = pm.join_nonshared_inputs([logp], vars, shared)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/theanof.py", line 240, in join_nonshared_inputs
    inarray.tag.test_value = joined.tag.test_value
AttributeError: 'scratchpad' object has no attribute 'test_value'
[2018-05-09 12:21:54,758] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "pymc3WS.py", line 39, in RunSimulation
    r = genResults()
  File "pymc3WS.py", line 25, in genResults
    step = pymc3.Metropolis()
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/step_methods/arraystep.py", line 65, in __new__
    step.__init__([var], *args, **kwargs)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/step_methods/metropolis.py", line 130, in __init__
    self.delta_logp = delta_logp(model.logpt, vars, shared)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/step_methods/metropolis.py", line 479, in delta_logp
    [logp0], inarray0 = pm.join_nonshared_inputs([logp], vars, shared)
  File "/Users/e346104/anaconda/lib/python3.5/site-packages/pymc3/theanof.py", line 240, in join_nonshared_inputs
    inarray.tag.test_value = joined.tag.test_value
AttributeError: 'scratchpad' object has no attribute 'test_value'
127.0.0.1 - - [09/May/2018 12:21:54] "POST / HTTP/1.1" 500 -
127.0.0.1 - - [09/May/2018 12:21:54] "POST / HTTP/1.1" 500 -
100%|##############################################################################################| 1500/1500 [00:00<00:00, 3077.21it/s]
127.0.0.1 - - [09/May/2018 12:21:55] "POST / HTTP/1.1" 200 -
```

**Please provide any additional information below.**
Here is a way to test it:
```
import _thread
import requests
def RunSimulation(tname="THREAD_NAME"):
    r = requests.post('http://localhost:5000')
    print(r.text[0:100])
    print(r)

_thread.start_new_thread( RunSimulation,('TH1',) )
_thread.start_new_thread( RunSimulation,('TH2',) )
_thread.start_new_thread( RunSimulation,('TH3',) )
```
## Versions and main components

* PyMC3 Version: 3.2 (How would I check this within python)
* Theano Version:  don't know how to test it
* Python Version:  Python 3.5.2 :: Anaconda custom (64-bit)
* Operating system: It is very similar behavior on Mac and LINUX
* How did you install PyMC3: (conda/pip) pip

**Comment by twiecki** [comment]
Try setting `compute_test_value` to `raise`. http://deeplearning.net/software/theano/library/config.html#config.compute_test_value

**Comment by sada-narayanappa** [comment]
I did try. It emitted lot more errors then it did previously.

Is PYMC3 not compatible to run under threaded environment - I think making this clear would save a lot of time for those like me.

**Comment by twiecki** [comment]
I never heard that it's not supported, or that it is. You might want to look for theano in a threaded environment, instead of pymc3.

**Comment by twiecki** [comment]
Which errors did it yield?

**Comment by sada-narayanappa** [comment]
I think theano may not support threaded environment. Is there a way to switch from theao to tensorflow or something.

The errors shown above in fist post happens if I start two threads;. One thread work with no issues.


The example I provide are easy to reproduce - it don;t need to be Flask - just calling two threads will create the issue.

**Comment by twiecki** [comment]
https://medium.com/@pymc_devs/theano-tensorflow-and-the-future-of-pymc-6c9987bb19d5 :)

**Comment by sada-narayanappa** [comment]
Phewwww!!!! thank you.
Hopefully testing with threaded applications will be part of test with Tensorflow.
Can't wait to see PyMC4 - hopefully faster too

**Comment by springcoil** [comment]
@sada-narayanappa Do you want to make a note of this somewhere in the docs? I think it'd be a useful thing to have in an example - 'currently this doesn't support X'

**Comment by sada-narayanappa** [comment]
Hmmm ... not where which docs and where ... I have provided a small example in the beginning of the post. I can recap - but not sure where to document. This would be the first thing I personally check because it is so critical for RESTFUL end points for light weight faster implementations.
My guess is tensonflow would not have this issue - but we never know;

**Comment by sada-narayanappa** [comment]
Here is my recap with a very simple example.

Problem: Current PyMC3 does not support multithreaded calls, which is essential for RESTFUL endpoints or even utilizing multi core/GPUs
How to reproduce: Run the following program (NOTE: if you run only one thread, it works fine)

```
import pymc3
import _thread
from pymc3 import Model, Normal, Binomial, sample, Deterministic

def genCB(v, rent=500):
    ret = v['Number Of Units'] * rent - v['Operating Cost']
    return ret

def genResults(name="ThreadName "):
    N={}
    with pymc3.Model() as mcmc:
        pymc3.Uniform('Number Of Units', 30, 40);
        pymc3.Normal('Operating Cost', mu=15000, sd=1000 );

        for c in mcmc.unobserved_RVs:
            N[str(c)] = c

        ROI = Deterministic('ROI', genCB(N) )

        step = pymc3.Metropolis()
        traced = sample(1000, step)
    print (name, " Completed;")
    
_thread.start_new_thread( genResults,('TH1',) ) # Calling only one works fine
_thread.start_new_thread( genResults,('TH2',) ) # Calling two or three simultaneously cause errors
#_thread.start_new_thread( genResults,('TH3',) ) # Calling only one works fine
```

Current Work around: DO NOT USE THREADS - instead use "pid1 = os.fork()" (note: DO not call fork in Jupyter notebooks - It may fork a new kernel - use it only in python apps outside of Jupyter) and wait for pymc4 to test if tensorflow handles threads well
