### ISSUE TITLE
Minibatch ADVI TypeError with version 3.3 and up

### ISSUE THREAD

**Issue by parsing-science** [pymc-devs/pymc#2985]
## Minibatch ADVI TypeError
I recently upgraded from from version 3.2 to 3.3 and my existing code for minibatch ADVI fails on a basic logistic regression example.

Specifically, I'm getting this error: ```TypeError: Cannot convert Type TensorType(int64, vector) (of Variable Minibatch) into Type TensorType(float64, vector). You can try to manually convert Minibatch into a TensorType(float64, vector).```.

I was able to get my basic Linear Regression to run so perhaps it's something specific to the Bernoulli distribution?

The same code works if I run with regular ADVI and not minibatch.

Thanks for the help! Please let me know if you need any more info.

### Example code
``` python
import numpy as np
import pymc3 as pm

import theano
import theano.tensor as T

num_samples = 1000
num_pred = 1

def numpy_invlogit(x):
    return 1 / (1 + np.exp(-x))

X = np.random.randn(num_samples, num_pred)
Y = np.random.binomial(1, numpy_invlogit(3 + 4 * X))
Y = np.squeeze(Y)

log_reg_model = pm.Model()

model_input = theano.shared(np.zeros([num_samples, num_pred]))

model_output = theano.shared(np.zeros(num_samples))

with log_reg_model:

    alpha = pm.Normal('alpha', mu=0, sd=100, shape=(1))
    beta = pm.Normal('beta', mu=0, sd=100, shape=(num_pred))
    
    s = pm.HalfNormal('s', tau=1)
    
    temp = alpha + T.sum(beta * model_input, 1)
    
    p = pm.invlogit(temp)

    o = pm.Bernoulli('o', p, observed=model_output)

inference_args = {
    'n': 2000,
    'callbacks': [pm.callbacks.CheckParametersConvergence()]
}

minibatch_size = 100

minibatches = {
    model_input: pm.Minibatch(X, batch_size=minibatch_size),
    model_output: pm.Minibatch(Y, batch_size=minibatch_size)
}

inference_args['more_replacements'] = minibatches

with log_reg_model:
    inference = pm.ADVI()
    approx = pm.fit(method=inference, **inference_args)
```

### Traceback
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-cec2571c5b45> in <module>()
      1 with log_reg_model:
      2     inference = pm.ADVI()
----> 3     approx = pm.fit(method=inference, **inference_args)

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/inference.py in fit(n, local_rv, method, model, random_seed, start, inf_kwargs, **kwargs)
    754                         'or Inference instance' %
    755                         set(_select.keys()))
--> 756     return inference.fit(n, **kwargs)

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/inference.py in fit(self, n, score, callbacks, progressbar, **kwargs)
    130             callbacks = []
    131         score = self._maybe_score(score)
--> 132         step_func = self.objective.step_function(score=score, **kwargs)
    133         with tqdm.trange(n, disable=not progressbar) as progress:
    134             if score:

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/configparser.py in res(*args, **kwargs)
    115         def res(*args, **kwargs):
    116             with self:
--> 117                 return f(*args, **kwargs)
    118         return res
    119 

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/opvi.py in step_function(self, obj_n_mc, tf_n_mc, obj_optimizer, test_optimizer, more_obj_params, more_tf_params, more_updates, more_replacements, total_grad_norm_constraint, score, fn_kwargs)
    314                                more_updates=more_updates,
    315                                more_replacements=more_replacements,
--> 316                                total_grad_norm_constraint=total_grad_norm_constraint)
    317         if score:
    318             step_fn = theano.function(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/opvi.py in updates(self, obj_n_mc, tf_n_mc, obj_optimizer, test_optimizer, more_obj_params, more_tf_params, more_updates, more_replacements, total_grad_norm_constraint)
    218             more_obj_params=more_obj_params,
    219             more_replacements=more_replacements,
--> 220             total_grad_norm_constraint=total_grad_norm_constraint
    221         )
    222         resulting_updates.update(more_updates)

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/opvi.py in add_obj_updates(self, updates, obj_n_mc, obj_optimizer, more_obj_params, more_replacements, total_grad_norm_constraint)
    247         if more_replacements is None:
    248             more_replacements = dict()
--> 249         obj_target = self(obj_n_mc, more_obj_params=more_obj_params, more_replacements=more_replacements)
    250         grads = pm.updates.get_or_compute_grads(obj_target, self.obj_params + more_obj_params)
    251         if total_grad_norm_constraint is not None:

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/configparser.py in res(*args, **kwargs)
    115         def res(*args, **kwargs):
    116             with self:
--> 117                 return f(*args, **kwargs)
    118         return res
    119 

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/opvi.py in __call__(self, nmc, **kwargs)
    355             m = 1.
    356         a = self.op.apply(self.tf)
--> 357         a = self.approx.set_size_and_deterministic(a, nmc, 0, kwargs.get('more_replacements'))
    358         return m * self.op.T(a)
    359 

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/configparser.py in res(*args, **kwargs)
    115         def res(*args, **kwargs):
    116             with self:
--> 117                 return f(*args, **kwargs)
    118         return res
    119 

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/pymc3/variational/opvi.py in set_size_and_deterministic(self, node, s, d, more_replacements)
   1394         flat2rand = self.make_size_and_deterministic_replacements(s, d, more_replacements)
   1395         node = theano.clone(node, optimizations)
-> 1396         node = theano.clone(node, flat2rand)
   1397         try_to_set_test_value(_node, node, s)
   1398         return node

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/scan_module/scan_utils.py in clone(output, replace, strict, share_inputs, copy_inputs)
    245                                         [],
    246                                         strict,
--> 247                                         share_inputs)
    248 
    249     return outs

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in rebuild_collect_shared(outputs, inputs, replace, updates, rebuild_strict, copy_inputs_over, no_default_updates)
    230     else:
    231         if isinstance(outputs, Variable):
--> 232             cloned_v = clone_v_get_shared_updates(outputs, copy_inputs_over)
    233             cloned_outputs = cloned_v
    234             # computed_list.append(cloned_v)

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     91             if owner not in clone_d:
     92                 for i in owner.inputs:
---> 93                     clone_v_get_shared_updates(i, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/compile/pfunc.py in clone_v_get_shared_updates(v, copy_inputs_over)
     94 
     95                 clone_d[owner] = owner.clone_with_new_inputs(
---> 96                     [clone_d[i] for i in owner.inputs], strict=rebuild_strict)
     97                 for old_o, new_o in zip(owner.outputs, clone_d[owner].outputs):
     98                     clone_d.setdefault(old_o, new_o)

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/gof/graph.py in clone_with_new_inputs(self, inputs, strict)
    240                 if strict:
    241                     # If compatible, casts new into curr.type
--> 242                     new_inputs[i] = curr.type.filter_variable(new)
    243                 else:
    244                     remake_node = True

~/repos/personal/pymc3_models/venv/lib/python3.6/site-packages/theano/tensor/type.py in filter_variable(self, other, allow_convert)
    232             dict(othertype=other.type,
    233                  other=other,
--> 234                  self=self))
    235 
    236     def value_validity_msg(self, a):

TypeError: Cannot convert Type TensorType(int64, vector) (of Variable Minibatch) into Type TensorType(float64, vector). You can try to manually convert Minibatch into a TensorType(float64, vector).
```

## Versions and main components

* PyMC3 Version: 3.3 (also fails on 3.4.1)
* Theano Version: 1.0.1
* Python Version: 3.6.3
* Operating system:  Mac
* How did you install PyMC3: pip

**Comment by fonnesbeck** [comment]
What if you explicitly cast `model_output` to int64? I think `numpy.ones` will create floats by default.

**Comment by usptact** [comment]
Here's my error trace under Ubuntu 18.04, Python 3.6, Theano 1.0.1, PyMC3 3.4.1.

```
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.
/snap/pycharm-professional/66/helpers/pydev/_pydev_bundle/pydev_import_hook.py:19: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  module = self._system_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "/snap/pycharm-professional/66/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/66/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/vlad/PycharmProjects/logreg_advi/logreg_advi.py", line 53, in <module>
    approx = pm.fit(method=inference, **inference_args)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/inference.py", line 756, in fit
    return inference.fit(n, **kwargs)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/inference.py", line 132, in fit
    step_func = self.objective.step_function(score=score, **kwargs)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/opvi.py", line 316, in step_function
    total_grad_norm_constraint=total_grad_norm_constraint)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/opvi.py", line 220, in updates
    total_grad_norm_constraint=total_grad_norm_constraint
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/opvi.py", line 249, in add_obj_updates
    obj_target = self(obj_n_mc, more_obj_params=more_obj_params, more_replacements=more_replacements)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/opvi.py", line 357, in __call__
    a = self.approx.set_size_and_deterministic(a, nmc, 0, kwargs.get('more_replacements'))
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/variational/opvi.py", line 1399, in set_size_and_deterministic
    node = theano.clone(node, flat2rand)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/scan_module/scan_utils.py", line 247, in clone
    share_inputs)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/compile/pfunc.py", line 232, in rebuild_collect_shared
    cloned_v = clone_v_get_shared_updates(outputs, copy_inputs_over)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/compile/pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  [Previous line repeated 9 more times]
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/compile/pfunc.py", line 96, in clone_v_get_shared_updates
    [clone_d[i] for i in owner.inputs], strict=rebuild_strict)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/gof/graph.py", line 242, in clone_with_new_inputs
    new_inputs[i] = curr.type.filter_variable(new)
  File "/home/vlad/anaconda3/envs/py36/lib/python3.6/site-packages/theano/tensor/type.py", line 234, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(int64, vector) (of Variable Minibatch) into Type TensorType(float64, vector). You can try to manually convert Minibatch into a TensorType(float64, vector).
```

**Comment by usptact** [comment]
@parsing-science  I changed the `model_output` line to this:
```
model_output = theano.shared(np.zeros(num_samples, dtype=int))
```
and the inference ran successfully.

**Comment by twiecki** [comment]
Thanks @usptact!

**Comment by parsing-science** [comment]
Thanks all! I can change that line in my code, but do you have any idea where this breaking change came from?

I imagine this might affect other people, and it seems like there should be a warning if the API is changed.

**Comment by junpenglao** [comment]
Maybe the error is related to the change in theano version?

**Comment by parsing-science** [comment]
I ran with Theano 1.0.1 and pymc3 3.2 and it works, but fails when I run with Theano 1.0.1 and pymc3 3.3.

**Comment by ferrine** [comment]
Hi, the reason is smart type conversion in Minibatch. It maintains it types

**Comment by twiecki** [comment]
Feel free to reopen if error persists.
