### ISSUE TITLE
FloatingPointError: NaN occurred in optimization.

### ISSUE THREAD

**Issue by marty0801** [pymc-devs/pymc#2989]
I am attempting to fit a binomial mixture model with three components as follows: 

```
import pymc3
import numpy as np

N = 100 # mixture model requires identically-distributed samples!!
n_samps = 10
P = np.random.rand(n_samps)
data = np.random.binomial(N,P)

n_comps = 3

with pymc3.Model() as model:
    w = pymc3.Dirichlet('w', a=np.ones(n_comps))
    psi0 = pymc3.Uniform('psi0',lower=0,upper=0,shape=n_comps)
    dists_ar = pymc3.Binomial.dist(n=N, p=psi0, shape=n_comps)
    mixmod = pymc3.Mixture('mixmodel',w=w,comp_dists=dists_ar,observed=data)

with model:
    # mh = pymc3.Metropolis([w,psi0])
    # s = pymc3.sample(1000,mh)
    approx = pymc3.fit(method='advi')
```

I receive an inscrutable error: 
```
Traceback (most recent call last):
  File "/home/marty/anaconda3/envs/binomix/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6cdd8fe45cdc>", line 21, in <module>
    approx = pymc3.fit(method='advi')
  File "/home/marty/anaconda3/envs/binomix/lib/python3.6/site-packages/pymc3/variational/inference.py", line 756, in fit
    return inference.fit(n, **kwargs)
  File "/home/marty/anaconda3/envs/binomix/lib/python3.6/site-packages/pymc3/variational/inference.py", line 135, in fit
    state = self._iterate_with_loss(0, n, step_func, progress, callbacks)
  File "/home/marty/anaconda3/envs/binomix/lib/python3.6/site-packages/pymc3/variational/inference.py", line 181, in _iterate_with_loss
    raise FloatingPointError('NaN occurred in optimization.')
FloatingPointError: NaN occurred in optimization.
```

Am I doing something wrong?

**Comment by junpenglao** [comment]
`psi0 = pymc3.Uniform('psi0',lower=0,upper=0,shape=n_comps)` the lower and upper are both 0.
For future user question, please post to our discourse: https://discourse.pymc.io/

Closing this for now.

**Comment by marty0801** [comment]
How embarrassing! Thanks; it works now...

**Comment by marty0801** [comment]
Also, my apologies; I was not aware of the 'discourse'. I'll use it in the future. 

Finally, thank you for this amazing tool!!

**Comment by springcoil** [comment]
Can't we have better errors for this?
Your upper and lower are the same?
