### ISSUE TITLE
libav-tools no longer available in the Ubuntu repos that the Docker image uses

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#3003]
`libav-tools` no longer available in the Ubuntu repos that the Docker image uses

**Comment by AustinRochford** [comment]
After removing `libav-tools`:

```+ pip install -e .
Obtaining file:///home/jovyan
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jovyan/setup.py", line 32, in <module>
        with open(join(PROJECT_ROOT, 'README.rst'), encoding='utf-8') as buff:
      File "/opt/conda/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/jovyan/
The command '/bin/sh -c /bin/bash /tmp/create_testenv.sh --global --no-setup' returned a non-zero code: 1```

**Comment by spearsem** [comment]
@AustinRochford Thanks for looking into this -- those are the same two errors that I also experienced (I tried changing libav-tools to ffmpeg, but the second error remains). I was unsure if I am simply invoking the Dockerfile from the wrong directory (I am invoking it from one level up, and using `-f scripts/Dockerfile` in the docker command). If I can try anything to help out, let me know.

**Comment by AustinRochford** [comment]
The problem seems to be that pip 10.* wants `pymc3` shared before running `create_testenv.sh` so it can read the package version.

**Comment by AustinRochford** [comment]
Getting closer, the container builds, but the notebook server fails to launch.

```/usr/local/bin/start-notebook.sh: ignoring /usr/local/bin/start-notebook.d/*

Container must be run with group "root" to update passwd file
Executing the command: jupyter notebook --NotebookApp.token=47b039b2c8402e56a4987d1056ed1bbe4ea25cfd2af6db22
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter", line 6, in <module>
    from jupyter_core.command import main
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/command.py", line 16, in <module>
    from subprocess import Popen
  File "/opt/conda/lib/python3.6/subprocess.py", line 138, in <module>
    import selectors
  File "/opt/conda/lib/python3.6/selectors.py", line 10, in <module>
    import math
  File "/home/jovyan/pymc3/math.py", line 3, in <module>
    import theano.tensor as tt
  File "/opt/conda/lib/python3.6/site-packages/theano/__init__.py", line 88, in <module>
    from theano.configdefaults import config
  File "/opt/conda/lib/python3.6/site-packages/theano/configdefaults.py", line 6, in <module>
    import numpy as np
  File "/opt/conda/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/opt/conda/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/conda/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/conda/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/__init__.py", line 74, in <module>
    from numpy.testing import _numpy_tester
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/decorators.py", line 6, in <module>
    from .nose_tools.decorators import *
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/nose_tools/decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/opt/conda/lib/python3.6/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/opt/conda/lib/python3.6/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log'```
