### ISSUE TITLE
IndexError occurs during Metropolis sampling

### ISSUE THREAD

**Issue by jfparie** [pymc-devs/pymc#3023]
The below code should model the Monty Hall problem according to Metropolis sampling. The occurring _IndexError_ seems comparable with this [#1469](https://github.com/pymc-devs/pymc3/issues/1469) issue. Do you mind to give it a look?

```python
import pymc3 as pm
import theano
import numpy as np 

with pm.Model() as model:
    GuestDoor_prob = np.array([0.33, 0.33, 0.34]) 
    PrizeDoor_prob = np.array([0.33, 0.33, 0.34]) 
    MontyDoor_prob = np.array([[[0.0, 0.5, 0.5], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]],
                              [[0.0, 0.0, 1.0], [0.5, 0.0, 0.5], [1.0, 0.0, 0.0]],
                              [[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.5, 0.5, 0.0]]])

    GuestDoor = pm.Categorical('GuestDoor', p = GuestDoor_prob)
    PrizeDoor = pm.Categorical('PrizeDoor', p = PrizeDoor_prob)

    MontyDoor_prob = theano.shared(MontyDoor_prob)
    MontyDoor_0 = MontyDoor_prob[GuestDoor, PrizeDoor] 
    MontyDoor = pm.Categorical('MontyDoor', p = MontyDoor_0)

    random_number = np.random.randint(1,100000)
    tune = 5000
    # trace = pm.sample(10000, njobs = 1)
    trace = pm.sample(10000, step = [pm.Metropolis([GuestDoor, PrizeDoor])], tune = tune, random_seed = random_number, njobs = 1)

    print(trace)


if __name__ == '__main__':
    print("main") 
```

The error is

```
Sequential sampling (2 chains in 1 job)
CompoundStep
>CompoundStep
>>Metropolis: [PrizeDoor]
>>Metropolis: [GuestDoor]
>CategoricalGibbsMetropolis: [MontyDoor]
  0%|                                                              | 0/15000 [00:00<?, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda12\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    902             outputs =\
--> 903                 self.fn() if output_subset is None else\
    904                 self.fn(output_subset=output_subset)

IndexError: index out of bounds

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
~\Documents\TNOdrive\Jurriaan\GenieParser_PyMC3.py in <module>()
     20     tune = 5000
     21     # trace = pm.sample(10000, njobs = 1)
---> 22     trace = pm.sample(10000, step = [pm.Metropolis([GuestDoor, PrizeDoor])], tune = tune, random_seed = random_number, njobs = 1)
     23
     24     print(trace[0])

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    460             _log.info('Sequential sampling ({} chains in 1 job)'.format(chains))
    461             _print_step_hierarchy(step)
--> 462             trace = _sample_many(**sample_args)
    463
    464     discard = tune if discard_tuned_samples else 0

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\sampling.py in _sample_many(draws, chain, chains, start, random_seed, step, **kwargs)
    508     for i in range(chains):
    509         trace = _sample(draws=draws, chain=chain + i, start=start[i],
--> 510                         step=step, random_seed=random_seed[i], **kwargs)
    511         if trace is None:
    512             if len(traces) == 0:

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\sampling.py in _sample(chain, progressbar, random_seed, start, draws, step, trace, tune, model, live_plot, live_plot_kwargs, **kwargs)
    552     try:
    553         strace = None
--> 554         for it, strace in enumerate(sampling):
    555             if live_plot:
    556                 if live_plot_kwargs is None:

~\AppData\Local\Continuum\anaconda12\lib\site-packages\tqdm\_tqdm.py in __iter__(self)
    928 """, fp_write=getattr(self.fp, 'write', sys.stderr.write))
    929
--> 930             for obj in iterable:
    931                 yield obj
    932                 # Update and possibly print the progressbar.

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    650                 step = stop_tuning(step)
    651             if step.generates_stats:
--> 652                 point, states = step.step(point)
    653                 if strace.supports_sampler_stats:
    654                     strace.record(point, states)

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     22             for method in self.methods:
     23                 if method.generates_stats:
---> 24                     point, state = method.step(point)
     25                     states.extend(state)
     26                 else:

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     22             for method in self.methods:
     23                 if method.generates_stats:
---> 24                     point, state = method.step(point)
     25                     states.extend(state)
     26                 else:

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    160
    161         if self.generates_stats:
--> 162             apoint, stats = self.astep(self.bij.map(point))
    163             return self.bij.rmap(apoint), stats
    164         else:

~\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\step_methods\metropolis.py in astep(self, q0)
    160             q = floatX(q0 + delta)
    161
--> 162         accept = self.delta_logp(q, q0)
    163         q_new, accepted = metrop_select(accept, q, q0)
    164         self.accepted += accepted

~\AppData\Local\Continuum\anaconda12\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    915                     node=self.fn.nodes[self.fn.position_of_error],
    916                     thunk=thunk,
--> 917                     storage_map=getattr(self.fn, 'storage_map', None))
    918             else:
    919                 # old-style linkers raise their own exceptions

~\AppData\Local\Continuum\anaconda12\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    323         # extra long error message in that case.
    324         pass
--> 325     reraise(exc_type, exc_value, exc_trace)
    326
    327

~\AppData\Local\Continuum\anaconda12\lib\site-packages\six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

~\AppData\Local\Continuum\anaconda12\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    901         try:
    902             outputs =\
--> 903                 self.fn() if output_subset is None else\
    904                 self.fn(output_subset=output_subset)
    905         except Exception:

IndexError: index out of bounds
Apply node that caused the error: Subtensor{int64, int64, int64}(<TensorType(float64, 3D)>, ScalarFromTensor.0, ScalarFromTensor.0, ScalarFromTensor.0)
Toposort index: 24
Inputs types: [TensorType(float64, 3D), Scalar(int64), Scalar(int64), Scalar(int64)]
Inputs shapes: [(3, 3, 3), (), (), ()]
Inputs strides: [(72, 24, 8), (), (), ()]
Inputs values: ['not shown', 3, 2, 0]
Outputs clients: [[Elemwise{Composite{Switch(i0, log((i1 / i2)), i3)}}[(0, 2)](Elemwise{Composite{Cast{int8}((GE(i0, i1) * LE(i0, i2)))}}.0, Subtensor{int64, int64, int64}.0, Sum{acc_dtype=float64}.0, TensorConstant{-inf})]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\interactiveshell.py", line 2527, in safe_execfile
    self.compile if shell_futures else None)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\utils\py3compat.py", line 188, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "C:\Users\pariejf\Documents\TNOdrive\Jurriaan\GenieParser_PyMC3.py", line 17, in <module>
    MontyDoor = pm.Categorical('MontyDoor', p = MontyDoor_0)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\distributions\distribution.py", line 37, in __new__
    return model.Var(name, dist, data, total_size)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\model.py", line 802, in Var
    total_size=total_size, model=self)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\model.py", line 1184, in __init__
    self.logp_sum_unscaledt = distribution.logp_sum(self)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\distributions\distribution.py", line 114, in logp_sum
    return tt.sum(self.logp(*args, **kwargs))
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\distributions\discrete.py", line 737, in logp
    a = tt.log(p[value_clip])
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\interactiveshell.py", line 2131, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-61>", line 2, in run
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\magics\execution.py", line 775, in run
    run()
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\magics\execution.py", line 761, in run
    exit_ignore=exit_ignore)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\interactiveshell.py", line 2527, in safe_execfile
    self.compile if shell_futures else None)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\utils\py3compat.py", line 188, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "C:\Users\pariejf\Documents\TNOdrive\Jurriaan\GenieParser_PyMC3.py", line 16, in <module>
    MontyDoor_0 = MontyDoor_prob[GuestDoor, PrizeDoor]
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\magics\execution.py", line 775, in run
    run()
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\magics\execution.py", line 761, in run
    exit_ignore=exit_ignore)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\core\interactiveshell.py", line 2527, in safe_execfile
    self.compile if shell_futures else None)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\IPython\utils\py3compat.py", line 188, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "C:\Users\pariejf\Documents\TNOdrive\Jurriaan\GenieParser_PyMC3.py", line 17, in <module>
    MontyDoor = pm.Categorical('MontyDoor', p = MontyDoor_0)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\distributions\distribution.py", line 36, in __new__
    dist = cls.dist(*args, **kwargs)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\distributions\distribution.py", line 47, in dist
    dist.__init__(*args, **kwargs)
  File "C:\Users\pariejf\AppData\Local\Continuum\anaconda12\lib\site-packages\pymc3\distributions\discrete.py", line 704, in __init__
    self.p = (p.T / tt.sum(p, -1)).T

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node. 
```

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.2+2.gc449c8699
* Python Version: Python 3.6.5 | Anaconda, Inc. 
* Operating system: Microsoft Windows 10 Enterprise
* How did you install PyMC3: pip install pymc3

**Comment by junpenglao** [comment]
Metropolis give an invalid proposal in this case, you should just sample using the default (which PyMC3 assign an appropriate sampler):
```python
trace = pm.sample(10000, tune = tune, random_seed = random_number, njobs = 1)

```

**Comment by jfparie** [comment]
Thanks for your quick response! Do you get why this methods creates so many useless samples? The output now tells me that _The number of effective samples is smaller than 10% for some parameters_.

**Comment by junpenglao** [comment]
> The number of effective samples is smaller than 10% for some parameters.

It means that there is high autocorrelation in your samples - usually, this is an indication of inefficient samples in Metropolis, as in high dimension its proposal gets rejected a lot.

**Comment by jfparie** [comment]
Allright, if you don't mind I have two last questions:
1) do you have any suggestions how to simulate this Monty Hall network more properly ? i.e. to sample more efficiently using the pymc3.sample function.
2) in the end I want to use the pymc3.sample function on a 100+node Bayesian network stored in an xml-structure. Do you know if any parser to pymc3 is available? I couldn't find anything yet online. 

Thanks in advance!

**Comment by junpenglao** [comment]
1. I dont think there is any discrete sampler in PyMC3 that works well in these kinds of high-dimensional problem - you might need to write custom sampler tailor to your model
2. Hmmm I dont think there is an example to do this, you might need to read the structure into python afterall.

**Comment by jfparie** [comment]
Then, I am wondering why [this](https://gist.github.com/cs224/9a19b4ba2c7511e317be90c32a4d40d7#file-pymc3_rain_sprinkler_grass_simple_bayesian_network-py) rain-sprinkler Bayesian network modelled by PyMC3 works well?

**Comment by junpenglao** [comment]
The dimension of the parameter is much smaller.

**Comment by jfparie** [comment]
The dimension of what exactly?
