### ISSUE TITLE
Can't Pickle CVM Objects

### ISSUE THREAD

**Issue by oorc06** [pymc-devs/pymc#3068]
## Description of your problem

I have tried using PyMC3 with various different models, but keep getting the same error : "TypeError: can't pickle CVM objects"

This is the full traceback:
``` python
Traceback (most recent call last):

  File "<ipython-input-4-4b462b460b57>", line 3, in <module>
    trace = pm.sample(500)

  File "/anaconda3/lib/python3.6/site-packages/pymc3/sampling.py", line 442, in sample
    trace = _mp_sample(**sample_args)

  File "/anaconda3/lib/python3.6/site-packages/pymc3/sampling.py", line 982, in _mp_sample
    traces = Parallel(n_jobs=cores, mmap_mode=None)(jobs)

  File "/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 962, in __call__
    self.retrieve()

  File "/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 865, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "/anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 515, in wrap_future_result
    return future.result(timeout=timeout)

  File "/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()

  File "/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception

TypeError: can't pickle CVM objects
```

## Versions and main components

* PyMC3 Version: 3.4.1
* Python Version: 3.6
* Operating system: MacOS High Sierra
* How did you install PyMC3: (conda/pip) conda

**Comment by junpenglao** [comment]
This is now should be fix on master - could you try upgrade to master?

**Comment by oorc06** [comment]
Hi. Thanks for your reply. How do I upgrade to master on conda? I tried using this - ( pip3 install git+https://github.com/pymc-devs/pymc3@master), but it didn't really work. Is there an alternate way to upgrade on conda? Thanks in advance.

**Comment by fonnesbeck** [comment]
`pip3 install -U git+https://github.com/pymc-devs/pymc3.git` will install from themaster branch.

**Comment by oorc06** [comment]
@fonnesbeck, thanks for your reply. The installation was successful. However, when I try importing PyMC3, it displays an error stating that no such module is found. Any suggestions?

**Comment by fonnesbeck** [comment]
It means you probably aren't using the `pip` you think you are; the package got installed into a python `site-packages` that is not the same as the one you are trying to run it in. If you are using conda environments, make sure you have the env loaded.

**Comment by oorc06** [comment]
@fonnesbeck @junpenglao Thanks a lot for your help! It's working fine now.

**Comment by DenValk** [comment]
Sorry to comment on a closed post, but do you know how to install from master using pipenv? I'm running into this issue, and want to implement the fix, but I have to run it in a pipenv virtual environment. 

Edit: Found my own answer. Updating for any other who needs the same.

pipenv install git+https://github.com/pymc-devs/pymc3.git#egg=pymc3

Don't forget the egg at the end.

**Comment by bverhoeff** [comment]
Sorry to have to add this in a closed post:

I still get the error: "TypeError: can't pickle CVM objects"

The code:
```python
import pymc3 as pm

occurrences = stats.bernoulli.rvs(0.05, size=1500)

with pm.Model() as model:
    p = pm.Uniform('p', lower=0, upper=1)

with model:
    obs = pm.Bernoulli("obs", p, observed=occurrences)
    step = pm.Metropolis()
    trace = pm.sample(18000, step=step)
    burned_trace = trace[1000:]
```
Also from "Probabilistic-Programming-and-Bayesian-Methods-for-Hackers-master"

Traceback:
```python
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Bart-Jan\Anaconda3\envs\theano\lib\site-packages\joblib\externals\loky\process_executor.py", line 333, in _sendback_result
    exception=exception))
  File "C:\Users\Bart-Jan\Anaconda3\envs\theano\lib\site-packages\joblib\externals\loky\backend\queues.py", line 233, in put
    obj = CustomizableLokyPickler.dumps(obj, reducers=self._reducers)
  File "C:\Users\Bart-Jan\Anaconda3\envs\theano\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 145, in dumps
    p.dump(obj)
TypeError: can't pickle CVM objects
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-23-6133a454721e> in <module>()
      4     # To be explained in chapter 3
      5     step = pm.Metropolis()
----> 6     trace = pm.sample(18000, step=step)
      7     burned_trace = trace[1000:]

~\Anaconda3\envs\theano\lib\site-packages\pymc3\sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    440         _print_step_hierarchy(step)
    441         try:
--> 442             trace = _mp_sample(**sample_args)
    443         except pickle.PickleError:
    444             _log.warning("Could not pickle model, sampling singlethreaded.")

~\Anaconda3\envs\theano\lib\site-packages\pymc3\sampling.py in _mp_sample(**kwargs)
    980         traces = Parallel(n_jobs=cores)(jobs)
    981     else:
--> 982         traces = Parallel(n_jobs=cores, mmap_mode=None)(jobs)
    983 
    984     return MultiTrace(traces)

~\Anaconda3\envs\theano\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
    960 
    961             with self._backend.retrieval_context():
--> 962                 self.retrieve()
    963             # Make sure that we get a last message telling us we are done
    964             elapsed_time = time.time() - self._start_time

~\Anaconda3\envs\theano\lib\site-packages\joblib\parallel.py in retrieve(self)
    863             try:
    864                 if getattr(self._backend, 'supports_timeout', False):
--> 865                     self._output.extend(job.get(timeout=self.timeout))
    866                 else:
    867                     self._output.extend(job.get())

~\Anaconda3\envs\theano\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    514         try:
--> 515             return future.result(timeout=timeout)
    516         except LokyTimeoutError:
    517             raise TimeoutError()

~\Anaconda3\envs\theano\lib\site-packages\joblib\externals\loky\_base.py in result(self, timeout)
    429                 raise CancelledError()
    430             elif self._state == FINISHED:
--> 431                 return self.__get_result()
    432             else:
    433                 raise TimeoutError()

~\Anaconda3\envs\theano\lib\site-packages\joblib\externals\loky\_base.py in __get_result(self)
    380     def __get_result(self):
    381         if self._exception:
--> 382             raise self._exception
    383         else:
    384             return self._result

TypeError: can't pickle CVM objects
```

used the proposed install-term:
`pip3 install -U git+https://github.com/pymc-devs/pymc3.git`

I'm afraid I'm not familiar enough with the codebase of PyMC3 to come up with any solution. Would anyone know where I should look?

**Comment by oorc06** [comment]
@bverhoeff, as has been pointed out previously in this thread, you may not have installed the master pymc3 package into the right directory. Try specifying the complete location of the pip, as in:

`/anaconda/bin/pip install -U git+https://github.com/pymc-devs/pymc3.git `

**Comment by stnatter** [comment]
I am still getting the same problem after having tried to above solution. Running  pymc3: 3.4.1. Tried pip install and conda install and update.
Grateful for any suggestion how to fix this.

**Comment by oorc06** [comment]
Have you tried uninstalling your current package before installing it again?

**Comment by stnatter** [comment]
sorry for late response too ;-). Yes it did try to uninstall before installing it again.

**Comment by oorc06** [comment]
I’m really sorry, have no idea about what else can be done.
