### ISSUE TITLE
Value error when using Big Data

### ISSUE THREAD

**Issue by urchgene** [pymc-devs/pymc#3178]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

I have a code running very smoothly for small and medium sized datasets (10-20K rows) but when I move to 50K rows I encounter errors which are difficult to understand but are linked to CBLAS via numpy. This does not happen with a subset of same data. The code runs very well with expected results.
**Please provide a minimal, self-contained, and reproducible example.**
```python
   # Expected value of outcome

    a = pm.Deterministic('a', pm.math.dot(pm.math.kronecker(Achol, Gchol), a_tilde))
    a_prime = a.reshape((N, K))

    mu = pm.math.dot(X, beta.T) + a_prime

    Y_obs = pm.MvNormal('Y_obs', mu=mu, chol=Rchol, observed=Y, shape = (N, K), lower=False)

```

**Please provide the full traceback.**
```python
Traceback (most recent call last):
  File "RKHS_MT.py", line 88, in <module>
    a = pm.Deterministic('a', pm.math.dot(pm.math.kronecker(Achol, Gchol), a_tilde))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pymc3/math.py", line 34, in kronecker
    return reduce(tt.slinalg.kron, Ks)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/tensor/slinalg.py", line 473, in kron
    o = tensor.outer(a, b)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/tensor/basic.py", line 6331, in outer
    y.dimshuffle('x', 0))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/tensor/basic.py", line 6086, in dot
    return _dot(a, b)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/gof/op.py", line 674, in __call__
    required = thunk()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/tensor/basic.py", line 5951, in perform
    z[0] = np.asarray(np.dot(x, y))
ValueError: On entry to SGEMM parameter number 4 had an illegal value
```
Sometimes the error shows:

```
Traceback (most recent call last):
  File "../scripts/RKHS_MT.py", line 106, in <module>
    a = pm.Deterministic('a', pm.math.dot(pm.math.kronecker(Achol, Gchol), a_tilde))
  File "/usr/local/lib/python2.7/dist-packages/pymc3/math.py", line 34, in kronecker
    return reduce(tt.slinalg.kron, Ks)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/slinalg.py", line 473, in kron
    o = tensor.outer(a, b)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 6331, in outer
    y.dimshuffle('x', 0))
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 6086, in dot
    return _dot(a, b)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 674, in __call__
    required = thunk()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 5951, in perform
    z[0] = np.asarray(np.dot(x, y))
ValueError: On entry to DGEMM parameter number 4 had an illegal value
```
**Please provide any additional information below.**
Sorry, can't show full model because of place of work policies...

## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.2
* Python Version: Python 3.6.5 |Anaconda, Inc.|
* Operating system: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-1066-aws x86_64)
* How did you install PyMC3: (conda/pip) pip3

**Comment by eigenfoo** [comment]
Thanks for your question @urchgene (and apologies for the year-long response...). We try to keep the GitHub issues for development issues, instead of user support for PyMC3 or modelling questions: since the stack trace doesn't indicate any errors from PyMC3 code, I assume that this isn't a bug with PyMC3. If this is still an issue for you, please check out our Discourse Forums: https://discourse.pymc.io/

Closing now, but feel free to continue the discussion on the forums!
