### ISSUE TITLE
Broken error message when energy is not finite in HMC - raise_ok() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by elfwired** [pymc-devs/pymc#3206]
In this example model is misspecified, and exception should be raised, 
but just before raising an exception something breaks and correct error message is not displayed

**Code example:**
```python
import numpy as np
import theano
import theano.tensor as tt
import pymc3 as pm

def stable_inv_logit(x):
    return 0.5*(1. + np.sign(x)*(2./(1. + np.exp(-np.abs(x))) - 1.))

## generate test data

# True parameter values
beta0_true = -1.5
beta_true = np.array([0.2, 0.3, 0.5])

# Size of dataset
size = 50000
dim = len(beta_true)

# Predictor variable
X_std  = np.array([1, 0.7, 0.3])
X = np.random.randn(size, dim) * X_std

# True parameter values for alpha scale
alpha0_true = 0.5
alpha_coef_true = np.array([0.1, 0.04, 0.08])

Y_m_t = np.exp(beta0_true + X.dot(beta_true))
alpha_t = np.exp(alpha0_true + X.dot(alpha_coef_true))

r_t = 1. / alpha_t
p_t = 1. / (alpha_t * Y_m_t + 1)

Y = np.random.negative_binomial(r_t, p_t)

## building model

X_shared = theano.shared(X)
Y_shared = theano.shared(Y)

pm_model = pm.Model()

with pm_model:
    # Priors for unknown model parameters
    beta0 = pm.Normal('beta0', mu=0., sd=10.)
    beta = pm.Normal('beta', mu=0., sd=10., shape=dim)
    alpha0 = pm.HalfNormal('alpha0', sd=2.)
    alpha_coef = pm.Normal('alpha_coef', mu=0., sd=3., shape=dim)

    # Expected value of outcome
    mu = beta0 + tt.dot(X_shared, beta)
    alpha = alpha0 + tt.dot(X_shared, alpha_coef)

    mu_sum = mu.sum()

    # Likelihood (sampling distribution) of observations
    Y_obs = pm.NegativeBinomial('Y_obs', mu=mu, alpha=alpha, observed=Y_shared)

## fitting model

with pm_model:
    # draw posterior samples
    trace2 = pm.sample(10000, tune=8000, njobs=1, init='advi')
    pm.summary(trace2)

```

**traceback:**
```
Auto-assigning NUTS sampler...
Initializing NUTS using advi...
Average Loss = inf:  18%|█████████▍                                           | 35595/200000 [15:31<1:11:41, 38.22it/s]
Convergence achieved at 35600
Interrupted at 35,599 [17%]: Average Loss = 31,260
Sequential sampling (2 chains in 1 job)
NUTS: [alpha_coef, alpha0, beta, beta0]
  0%|                                                                                        | 0/18000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "minimal_raise_exc.py", line 71, in <module>
    summary2 = pm.summary(trace2)
  File "D:\Anaconda3\lib\site-packages\pymc3\sampling.py", line 469, in sample
    trace = _sample_many(**sample_args)
  File "D:\Anaconda3\lib\site-packages\pymc3\sampling.py", line 515, in _sample_many
    step=step, random_seed=random_seed[i], **kwargs)
  File "D:\Anaconda3\lib\site-packages\pymc3\sampling.py", line 559, in _sample
    for it, strace in enumerate(sampling):
  File "D:\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 933, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\lib\site-packages\pymc3\sampling.py", line 655, in _iter_sample
    point, states = step.step(point)
  File "D:\Anaconda3\lib\site-packages\pymc3\step_methods\arraystep.py", line 247, in step
    apoint, stats = self.astep(array)
  File "D:\Anaconda3\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py", line 115, in astep
    self.potential.raise_ok(self._logp_dlogp_func._ordering.vmap)
TypeError: raise_ok() takes 1 positional argument but 2 were given
```

I think, trace from Jupyter notebook is more informative:
```
Auto-assigning NUTS sampler...
Initializing NUTS using advi...
Average Loss = inf:  17%|█████████▏                                           | 34697/200000 [27:49<2:12:32, 20.79it/s]
Convergence achieved at 34700
Interrupted at 34,699 [17%]: Average Loss = 31,367
Sequential sampling (2 chains in 1 job)
NUTS: [alpha_coef, alpha0, beta, beta0]
  0%|                                                                                        | 0/18000 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>()

D:\Anaconda3\lib\site-packages\pymc3\sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    467                 _log.info('Sequential sampling ({} chains in 1 job)'.format(chains))
    468                 _print_step_hierarchy(step)
--> 469                 trace = _sample_many(**sample_args)
    470 
    471         discard = tune if discard_tuned_samples else 0

D:\Anaconda3\lib\site-packages\pymc3\sampling.py in _sample_many(draws, chain, chains, start, random_seed, step, **kwargs)
    513     for i in range(chains):
    514         trace = _sample(draws=draws, chain=chain + i, start=start[i],
--> 515                         step=step, random_seed=random_seed[i], **kwargs)
    516         if trace is None:
    517             if len(traces) == 0:

D:\Anaconda3\lib\site-packages\pymc3\sampling.py in _sample(chain, progressbar, random_seed, start, draws, step, trace, tune, model, live_plot, live_plot_kwargs, **kwargs)
    557     try:
    558         strace = None
--> 559         for it, strace in enumerate(sampling):
    560             if live_plot:
    561                 if live_plot_kwargs is None:

D:\Anaconda3\lib\site-packages\tqdm\_tqdm.py in __iter__(self)
    931 """, fp_write=getattr(self.fp, 'write', sys.stderr.write))
    932 
--> 933             for obj in iterable:
    934                 yield obj
    935                 # Update and possibly print the progressbar.

D:\Anaconda3\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    653                 step = stop_tuning(step)
    654             if step.generates_stats:
--> 655                 point, states = step.step(point)
    656                 if strace.supports_sampler_stats:
    657                     strace.record(point, states)

D:\Anaconda3\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    245 
    246         if self.generates_stats:
--> 247             apoint, stats = self.astep(array)
    248             point = self._logp_dlogp_func.array_to_full_dict(apoint)
    249             return point, stats

D:\Anaconda3\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py in astep(self, q0)
    113 
    114         if not np.isfinite(start.energy):
--> 115             self.potential.raise_ok(self._logp_dlogp_func._ordering.vmap)
    116             raise ValueError('Bad initial energy: %s. The model '
    117                              'might be misspecified.' % start.energy)

TypeError: raise_ok() takes 1 positional argument but 2 were given

```

* PyMC3 Version: 3.5
* Theano Version: 1.0.3 
* Python Version: 3.6.6
* Operating system: Windows Server 2012
* How did you install PyMC3: pip install https://github.com/pymc-devs/pymc3/archive/master.zip

**Comment by ColCarroll** [comment]
Thanks! Should be a quick fix.

**Comment by junpenglao** [comment]
I cannot reproduce the error.

**Comment by ColCarroll** [comment]
I can - try changing the sampling line to 

```
    trace2 = pm.sample(10000, n_init=8, njobs=1, init='advi')
```
