### ISSUE TITLE
Travis tests fail with joblib 0.13.0

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3255]
It seems like all tests using parallel sampling (which are quite a few) are failing with this:
```
=================================== FAILURES ===================================
________________________________ test_minibatch ________________________________
    def test_minibatch():
        draws = 3000
        mu0 = 1
        sd0 = 1
    
        def f(x, a, b, c):
            return a*x**2 + b*x + c
    
        a, b, c = 1, 2, 3
    
        batch_size = 50
        total_size = batch_size*500
        x_train = np.random.uniform(-10, 10, size=(total_size,)).astype('float32')
        x_obs = pm.data.Minibatch(x_train, batch_size=batch_size)
    
        y_train = f(x_train, a, b, c) + np.random.normal(size=x_train.shape).astype('float32')
        y_obs = pm.data.Minibatch(y_train, batch_size=batch_size)
    
        with Model():
            abc = Normal('abc', mu=mu0, sd=sd0, shape=(3,))
            x = x_obs
            x2 = x**2
            o = tt.ones_like(x)
            X = tt.stack([x2, x, o]).T
            y = X.dot(abc)
            pm.Normal('y', mu=y, observed=y_obs)
    
            step_method = pm.SGFS(batch_size=batch_size, step_size=1., total_size=total_size)
>           trace = pm.sample(draws=draws, step=step_method, init=None, cores=2)
pymc3/tests/test_sgfs.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pymc3/sampling.py:440: in sample
    trace = _mp_sample(**sample_args)
pymc3/sampling.py:1033: in _mp_sample
    traces = Parallel(n_jobs=cores, mmap_mode=None)(jobs)
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/joblib/parallel.py:930: in __call__
    self.retrieve()
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/joblib/parallel.py:833: in retrieve
    self._output.extend(job.get(timeout=self.timeout))
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/joblib/_parallel_backends.py:521: in wrap_future_result
    return future.result(timeout=timeout)
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/joblib/externals/loky/_base.py:433: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <Future at 0x7f24374622d0 state=finished raised BrokenProcessPool>
    def __get_result(self):
        if self._exception:
>           raise self._exception
E           BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
E           
E           This was caused directly by 
E           '''
E           Traceback (most recent call last):
E             File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
E               call_item = call_queue.get(block=True, timeout=timeout)
E             File "/home/travis/miniconda2/envs/testenv/lib/python2.7/multiprocessing/queues.py", line 135, in get
E               res = self._recv()
E             File "/home/travis/build/pymc-devs/pymc3/pymc3/step_methods/arraystep.py", line 39, in __new__
E               model = modelcontext(kwargs.get('model'))
E             File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 191, in modelcontext
E               return Model.get_context()
E             File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 183, in get_context
E               raise TypeError("No context on context stack")
E           TypeError: No context on context stack
E           '''
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/joblib/externals/loky/_base.py:381: BrokenProcessPool
```

I think this is likely due to the new joblib 0.13 release. I opened an issue here: https://github.com/joblib/joblib/issues/810 and tried downgrading here: https://github.com/pymc-devs/pymc3/pull/3254

**Comment by junpenglao** [comment]
It's times like this makes me want to just remove support for py2.7 already.
Oh, and also move away from Travis CI...

**Comment by twiecki** [comment]
For now we are downgraded to <0.13.0. Of course it would be better if we figure out what's going on.

**Comment by Akamoha** [comment]
I also think this is due to the new joblib 0.13 release. The _Latest changes_ section in their docs mentions they have included loky with default serialization with cloudpickle. I believe providing `backend="multiprocessing"` as a parameter to `Parallel` should resolve the issue. However, I haven't tried this yet.

**Comment by twiecki** [comment]
Thanks @Akamoha. Is this an expected breakage or treated like a bug?

**Comment by twiecki** [comment]
@junpenglao Good point, this sunsetting 2.7 is not too far off, maybe we don't need to fix this and just stay on the older version.

**Comment by twiecki** [comment]
Fixed as dependency is removed.
