### ISSUE TITLE
Bug with SQLite as backend when vars specified in backend

### ISSUE THREAD

**Issue by roblem** [pymc-devs/pymc#3256]
Related to #3146 .  This error continues to occur when `vars` is specified.  This works
```python
with model:
    backend = pm3.backends.SQLite('/path/to/database.sqlite')
    # step method
    step = pm3.NUTS([x, y, z])
    trace = pm3.sample(5000, step, trace=backend)
```
but this doesn't
```python
with model:
    # note vars specified for not storing all variables in backend
    backend = pm3.backends.SQLite('/path/to/database.sqlite',
                    vars=[x, y])
    # step method
    step = pm3.NUTS([x, y, z])
    trace = pm3.sample(5000, step, trace=backend)
```
with this error
```
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [x, y, z]
Sampling 4 chains:  Traceback (most recent call last):
  File "~/anaconda/envs/pymc3_master/lib/python3.6/site-packages/pymc3/backends/sqlite.py", line 164, in _execute_queue
    self._queue[varname])
sqlite3.ProgrammingError: Cannot operate on a closed cursor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/anaconda/envs/pymc3_master/lib/python3.6/site-packages/pymc3/sampling.py", line 999, in _mp_sample
    trace.close()
  File "~/anaconda/envs/pymc3_master/lib/python3.6/site-packages/pymc3/backends/sqlite.py", line 170, in close
    self._execute_queue()
  File "~/anaconda/envs/pymc3_master/lib/python3.6/site-packages/pymc3/backends/sqlite.py", line 165, in _execute_queue
    self._queue[varname] = []
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by ndtallant** [comment]
Is this still an issue? I'd like to work on it this weekend if it is open!

**Comment by roblem** [comment]
Still an issue.

**Comment by ColCarroll** [comment]
Contributions would be welcome, but hoping to deprecate most backends #2189
