### ISSUE TITLE
Type Error: No context on context stack

### ISSUE THREAD

**Issue by EPGM-DES** [pymc-devs/pymc#3304]
## Description of your problem
I am trying to perform sample posterior checks. Here the model is initialized and I load a csv of a trace file. I am running an inference on several hundred datasets and saving the traces locally. However the following error appears:

```python
with pm.Model() as model:
     alpha = pm.Normal('alpha', mu = 1., sd = 10.)
     BoundedDelta = pm.Bound(pm.Normal, lower = -1., upper = 1.)
     delta = BoundedDelta('delta', mu = 0.3, sd = 10.)
     var_beta = pm.InverseGamma('var_beta', alpha=.001, beta=.001)
     var_return = pm.InverseGamma('var_return', alpha=.001, beta=.001)
        
     betas = sbeta.StochasticBeta('betas', mu=0., alpha=alpha, delta=delta, var=var_beta, init=pm.Normal.dist(mu=alpha, tau=1/var_beta), shape=len(excess_returns_df['excess_market']))
     r_mu = pm.Deterministic('r_mu',T.prod(betas, excess_returns_df['excess_market'].values))
     observed = pm.Normal('observed', mu=r_mu, tau=1/var_return, observed=excess_returns_df['excess_sym'].values)

trace = pm.backends.text.load(trace_directory, model=model)
```

**Please provide the full traceback.**
```python
Traceback (most recent call last):
  File "/anaconda3/envs/epgriskmodel/lib/python3.7/site-packages/pymc3/model.py", line 180, in get_context
    return cls.get_contexts()[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<path to module>/sampler.py", line 55, in sample_posterior
    sampled_posteriors = pm.sample_ppc(trace=trace[2000:], vars=['observed','betas'], samples=1000)
  File "/anaconda3/envs/epgriskmodel/lib/python3.7/site-packages/pymc3/sampling.py", line 1112, in sample_ppc
    model = modelcontext(model)
  File "/anaconda3/envs/epgriskmodel/lib/python3.7/site-packages/pymc3/model.py", line 190, in modelcontext
    return Model.get_context()
  File "/anaconda3/envs/epgriskmodel/lib/python3.7/site-packages/pymc3/model.py", line 182, in get_context
    raise TypeError("No context on context stack")
TypeError: No context on context stack
```

**Please provide any additional information below.**
I saw other similar issues and tried `theano-cache purge` with no avail. Could I load the trace into a dataframe or other data structure and then calibrate with model?

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.3
* Python Version: 3.7.1
* Operating system: Mac OS Mojave 10.14.1
* How did you install PyMC3: conda

**Comment by junpenglao** [comment]
The error seems to be somewhere else when you call `pm.sample_ppc`
```python
  File "/<path to module>/sampler.py", line 55, in sample_posterior
    sampled_posteriors = pm.sample_ppc(trace=trace[2000:], vars=['observed','betas'], samples=1000)
```
Could you check there instead?

**Comment by lucianopaz** [comment]
Closing as the error is caused when `sample_ppc` is called (probably outside the `model`'s context manager), and is not related to the provided code snippet.
