### ISSUE TITLE
Install error on conda

### ISSUE THREAD

**Issue by Nathan-Furnal** [pymc-devs/pymc#3305]
Hey guys, I was unable to install PyMC3 with conda, on a windows 10 machine.

[Here](https://stackoverflow.com/questions/53635462/anaconda-prompt-closes-immediately-the-system-was-unable-to-find-the-specified) is my post on stackoverflow with pictures and all. 

I can reliably reproduce the error while setting anaconda environments.

What I did is : 

`conda create -n test
`
`activate test
`
`conda install python=3.6
`
`conda install -c conda-forge pymc3
`

The very same error happens with both python 3.6 and python 3.7.

**Comment by nick-macro** [comment]
I am getting the same error using Windows 10.

Below is a list of conda's explicit list of packages in the environment that I used to reproduce this problem.
```
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2018.11.29-ha4d7672_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2019.0.0-h0cc432a_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2019.1-144.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/vs2015_runtime-14.0.25420-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/vs2015_win-64-14.0.25123-h17c34da_3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2018.0.3-1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/vc-14-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/icu-58.2-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jpeg-9c-hfa6e2cd_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libgpuarray-0.7.6-hfa6e2cd_1003.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openssl-1.0.2p-hfa6e2cd_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/python-3.6.6-he025d50_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sqlite-3.26.0-hfa6e2cd_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.11-h2fa13f4_1003.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/certifi-2018.11.29-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.10.4-nompi_hcc15c50_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/joblib-0.13.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/kiwisolver-1.0.1-py36he980bc4_1002.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.36-h7602738_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/markupsafe-1.1.0-py36hfa6e2cd_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.15.4-py36h8128ebf_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyreadline-2.1-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2018.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sip-4.18.1-py36h6538335_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/six-1.12.0-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tornado-5.1.1-py36hfa6e2cd_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.28.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wincertstore-0.2-py36_1002.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freetype-2.9.1-he8b6a0d_1004.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/mako-1.0.7-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.7.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/qt-5.6.2-h2639256_8.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/setuptools-40.6.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyqt-5.6.0-py36h764d66f_1007.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wheel-0.32.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pip-18.1-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/h5py-2.8.0-py36hf098a70_1005.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/matplotlib-3.0.2-py36h8a2030e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/matplotlib-base-3.0.2-py36h3e3dc42_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl_fft-1.0.10-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl_random-1.0.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.15.4-py36ha559c80_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandas-0.23.4-py36h830ac7b_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pygpu-0.7.6-py36h452e1ab_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.1.0-py36h4f6bf74_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/patsy-0.5.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/theano-1.0.3-py36h6538335_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pymc3-3.5-py36_1000.tar.bz2
```

I also have an environment that works on my machine with PyMC3.  However, it is not a minimal reproduction of a working environment because it contains many other packages that are not relevant to PyMC3.
```https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2018.10.15-ha4d7672_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/conda-env-2.6.0-0.tar.bz2
https://conda.anaconda.org/numba/win-64/icc_rt-2018.0.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2018.0.3-0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/msys2-conda-epoch-20160418-1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandoc-2.2.1-hde52d81_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.15.26706-h3a45250_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/winpty-0.4.3-4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/icu-58.1-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc14_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libgpuarray-0.7.6-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libiconv-1.14-vc14_3.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gmp-6.1.0-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-headers-git-5.0.0.4636.c0ad18a-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-isl-0.16.1-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libiconv-1.14-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libmangle-git-5.0.0.4509.2e5a9a2-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-make-4.1.2351.a80a8b8-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-windows-default-manifest-6.4-3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2018.0.3-1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/python-3.6.5-1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/vc-14-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/yaml-0.1.7-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.11-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/asn1crypto-0.24.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/beautifulsoup4-4.6.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/certifi-2018.10.15-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/chardet-3.0.4-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/colorama-0.3.9-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/entrypoints-0.2.3-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/filelock-3.0.4-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.10.2-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/idna-2.6-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipython_genutils-0.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/joblib-0.11-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jsonschema-2.6.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/kiwisolver-1.0.1-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.28-vc14_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libprotobuf-3.5.2-vc14_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libpython-2.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libsodium-1.0.16-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libtiff-4.0.6-vc14_6.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libxml2-2.9.3-vc14_9.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/llvmlite-0.25.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-crt-git-5.0.0.4636.2595836-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-core-5.3.0-7.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-mpfr-3.1.4-4.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-pkg-config-0.29.1-2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/markupsafe-1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mistune-0.8.3-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-1.1.2-py36h57e144c_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.15.2-py36h8128ebf_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openssl-1.0.2p-hfa6e2cd_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandocfilters-1.4.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pickleshare-0.7.4-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pkginfo-1.4.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/psutil-5.4.5-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pycosat-0.6.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pycparser-2.18-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyparsing-2.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyreadline-2.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywin32-221-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyyaml-3.12-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ruamel_yaml-0.15.37-py36hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/simplegeneric-0.8.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sip-4.18-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/six-1.11.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/testpath-0.3.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tornado-5.0.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wcwidth-0.1.7-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/webencodings-0.5.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/win_inet_pton-1.0.1-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wincertstore-0.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cffi-1.11.5-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/conda-verify-2.0.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cycler-0.10.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freetype-2.7-vc14_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-mpc-1.0.3-3.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-winpthreads-git-5.0.0.4634.697f757-2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mako-1.0.7-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/menuinst-1.4.14-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pysocks-1.6.8-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/qt-5.6.2-vc14_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/setuptools-39.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zeromq-4.2.5-vc14_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cryptography-2.2.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/grpcio-1.14.1-py36he089993_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jinja2-2.10-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/protobuf-3.5.2-py36_vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pygments-2.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyqt-5.6.0-py36h764d66f_7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyzmq-17.0.0-py36_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wheel-0.31.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-bzip2-1.0.6-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-tools-git-5.0.0.4592.90b8472-2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pip-9.0.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/prompt_toolkit-1.0.15-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyopenssl-18.0.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywinpty-0.5.3-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-zlib-1.2.8-10.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/terminado-0.8.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/urllib3-1.22-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-binutils-2.25.1-5.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/requests-2.18.4-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-ada-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-fortran-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-objc-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-toolchain-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/absl-py-0.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/asteval-0.9.12-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/astor-0.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports-1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.5-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/conda-4.5.11-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gast-0.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/glob2-0.6-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/html5lib-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/markdown-2.6.11-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/packaging-17.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.2.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.7.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2018.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/termcolor-1.1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.23.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/werkzeug-0.14.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-2.1.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/conda-build-3.10.7-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jedi-0.12.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pillow-4.3.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/traitlets-4.3.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipython-6.4.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_core-4.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jupyter_client-5.2.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/nbformat-4.4.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipykernel-4.8.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbconvert-5.3.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/notebook-5.5.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jupyterlab_launcher-0.10.5-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_server-0.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jupyterlab-0.35.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/bokeh-1.0.1-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/h5py-2.8.0-py36h54c06b0_1003.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/matplotlib-2.1.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/corner-2.0.1-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl_fft-1.0.6-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl_random-1.0.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.15.2-py36ha559c80_0.tar.bz2
https://conda.anaconda.org/numba/win-64/numba-0.41.0dev0-np115py36h6538335_19.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandas-0.23.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pygpu-0.7.6-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.1.0-py36h672f292_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tensorboard-1.9.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/uncertainties-3.0.2-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/lmfit-0.9.10-py36h39e3cac_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/patsy-0.5.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tensorflow-1.9.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/theano-1.0.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pymc3-3.5-py36_1000.tar.bz2
```

I hope that's helpful.  Please let me know if there's anything I can do to help out.

**Comment by Nathan-Furnal** [comment]
Thanks for the quick answer ! I tried using pip to check if the error was reproduceable with it too, and it doesn't cause any error, be it in python 3.6 or 3.7. The import works perfectly in the jupyter notebook with the pip install too.

For some reason it seems to be conda related as far as I understand.

**Comment by EPGM-DES** [comment]
I believe I recreated same error on Mac OS Mojave. I updated conda with `conda update -n base -c defaults conda` and followed the by `conda update -c conda-forge pymc3` which tried to install `pymc3`.  Here is the error:

```python
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 09:50:42) 
[Clang 9.0.0 (clang-900.0.37)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc3 as pm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/riskmodel/lib/python3.7/site-packages/pymc3/__init__.py", line 11, in <module>
    from .stats import *
  File "/anaconda3/envs/riskmodel/lib/python3.7/site-packages/pymc3/stats.py", line 4, in <module>
    import pkg_resources
  File "/anaconda3/envs/riskmodel/lib/python3.7/site-packages/pkg_resources/__init__.py", line 957, in <module>
    class Environment:
  File "/anaconda3/envs/riskmodel/lib/python3.7/site-packages/pkg_resources/__init__.py", line 961, in Environment
    self, search_path=None, platform=get_supported_platform(),
  File "/anaconda3/envs/riskmodel/lib/python3.7/site-packages/pkg_resources/__init__.py", line 188, in get_supported_platform
    plat = get_build_platform()
  File "/anaconda3/envs/riskmodel/lib/python3.7/site-packages/pkg_resources/__init__.py", line 393, in get_build_platform
    plat = get_platform()
  File "/anaconda3/envs/riskmodel/lib/python3.7/sysconfig.py", line 676, in get_platform
    get_config_vars(),
  File "/anaconda3/envs/riskmodel/lib/python3.7/sysconfig.py", line 552, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/anaconda3/envs/riskmodel/lib/python3.7/sysconfig.py", line 423, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_apple_darwin13_4_0'
```
Uninstalling the conda-forge channel distribution and installing using pip solved the import error. Hope this helps others.

**Comment by springcoil** [comment]
Very interesting. Mojave seems to have screwed up a lot of installations. I'll close this for the moment as it looks resolved.
