### ISSUE TITLE
Error in default GP mean_func init, shape only looks at first dimension

### ISSUE THREAD

**Issue by smthzch** [pymc-devs/pymc#3345]
When using the gp.latent model if no mean function is specified the default will not output the correct shape. See this [discourse](https://discourse.pymc.io/t/use-gp-latent-variable-as-input-to-another-function-shape-mismatch/2530)

If I supply `mean_func=tt.zeros_like`, I do not get this error. Just a different one later.

```python
x_ = shared(X, broadcastable=(False,True))
K=5

with pm.Model() as model:
    cov_func = pm.gp.cov.ExpQuad(X.shape[1], ls=0.1)
    gp = pm.gp.Latent(cov_func=cov_func)
    f = gp.prior("f", X=x_, shape=(200,1))
    alpha = pm.Normal('alpha', 0, 10, shape=K)
    beta = pm.Normal('beta', 0., 10., shape=K)
    v = norm_cdf(alpha + beta * f)
    w = pm.Deterministic('w', stick_breaking(v))


with model:
    mu = pm.Normal('mu', 0., 10., shape=K)
    tau = pm.Gamma('tau', 1., 1., shape=K)
    obs = pm.NormalMixture('obs', w, mu, tau=tau, observed=y)
Traceback (most recent call last):

  File "<ipython-input-56-a448c137f94a>", line 10, in <module>
    v = norm_cdf(alpha + beta * f)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\tensor\var.py", line 155, in __mul__
    return theano.tensor.mul(self, other)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\gof\op.py", line 674, in __call__
    required = thunk()

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\gof\op.py", line 862, in rval
    thunk()

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\gof\cc.py", line 1735, in __call__
    reraise(exc_type, exc_value, exc_trace)

  File "C:\Users\zsmith\AppData\Local\conda\conda\envs\pymc3\lib\site-packages\six.py", line 693, in reraise
    raise value

ValueError: Input dimension mis-match. (input[0].shape[1] = 5, input[1].shape[1] = 200)
```

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.3
* Python Version: 3.6
* Operating system: Windows 10 64
* How did you install PyMC3: conda

**Comment by lucianopaz** [comment]
Could you also include the other error and traceback you are getting when you use `mean_func=tt.zeros_like`?

**Comment by smthzch** [comment]
```python
x_ = shared(X, broadcastable=(False,True))
K=5

with pm.Model() as model:
    cov_func = pm.gp.cov.ExpQuad(X.shape[1], ls=0.1)
    gp = pm.gp.Latent(mean_func=tt.zeros_like, cov_func=cov_func)
    f = gp.prior("f", X=x_, shape=(200,1))
    alpha = pm.Normal('alpha', 0, 10, shape=K)
    beta = pm.Normal('beta', 0., 10., shape=K)
    v = norm_cdf(alpha + beta * f)
    w = pm.Deterministic('w', stick_breaking(v))


with model:
    mu = pm.Normal('mu', 0., 10., shape=K)
    tau = pm.Gamma('tau', 1., 1., shape=K)
    obs = pm.NormalMixture('obs', w, mu, tau=tau, observed=y)

SAMPLES = 2000
BURN = 1000

with model:
    step = pm.Metropolis()
    trace = pm.sample(SAMPLES, step, chains=1, tune=BURN)
Sequential sampling (1 chains in 1 job)
CompoundStep
Metropolis: [tau]
Metropolis: [mu]
Metropolis: [beta]
Metropolis: [alpha]
Metropolis: [f_rotated_]
  0%|          | 0/3000 [00:00<?, ?it/s]
Traceback (most recent call last):

  File "<ipython-input-58-b51fd91bdff0>", line 6, in <module>
    trace = pm.sample(SAMPLES, step, chains=1, tune=BURN)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\sampling.py", line 469, in sample
    trace = _sample_many(**sample_args)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\sampling.py", line 515, in _sample_many
    step=step, random_seed=random_seed[i], **kwargs)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\sampling.py", line 559, in _sample
    for it, strace in enumerate(sampling):

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\tqdm\_tqdm.py", line 979, in __iter__
    for obj in iterable:

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\sampling.py", line 655, in _iter_sample
    point, states = step.step(point)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\step_methods\compound.py", line 26, in step
    point, state = method.step(point)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\step_methods\arraystep.py", line 175, in step
    apoint, stats = self.astep(self.bij.map(point))

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\pymc3\step_methods\metropolis.py", line 162, in astep
    accept = self.delta_logp(q, q0)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)

  File "C:\Users\zsmith\AppData\Local\conda\conda\envs\pymc3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)

  File "C:\Users\zsmith\AppData\Roaming\Python\Python36\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\

ValueError: Input dimension mis-match. (input[1].shape[1] = 5, input[3].shape[1] = 1)
Apply node that caused the error: Elemwise{Composite{erfc((i0 * (i1 + (i2 * i3))))}}[(0, 3)](TensorConstant{(1, 1) of ..7106781187}, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0, Dot22.0)
Toposort index: 49
Inputs types: [TensorType(float64, (True, True)), TensorType(float64, row), TensorType(float64, row), TensorType(float64, matrix)]
Inputs shapes: [(1, 1), (1, 5), (1, 5), (200, 1)]
Inputs strides: [(8, 8), (40, 8), (40, 8), (8, 8)]
Inputs values: [array([[-0.70710678]]), array([[ 0.,  0.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.,  0.]]), 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 - (i1 * i2))}}(TensorConstant{(1, 1) of 1.0}, TensorConstant{(1, 1) of 0.5}, Elemwise{Composite{erfc((i0 * (i1 + (i2 * i3))))}}[(0, 3)].0), Elemwise{Mul}[(0, 1)](TensorConstant{(1, 1) of 0.5}, Elemwise{Composite{erfc((i0 * (i1 + (i2 * i3))))}}[(0, 3)].0, Join.0), Elemwise{mul,no_inplace}(Elemwise{Composite{erfc((i0 * (i1 + (i2 * i3))))}}[(0, 3)].0, Join.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.```

**Comment by bwengals** [comment]
Thanks for reporting this.  What are the dimensions of the input data, X and y?  Trying to reproduce.

Also, what size must `v` be?  I see that `f` will be (200, ), while `alpha` and `beta` will be (5, ).  Should it be (200, 5)?

**Comment by smthzch** [comment]
```
X = np.linspace(0,1,200)[:,None] #(200,1)
y = np.ones(200)
```

X is (200,1)
y is (200,)

v, w, alpha, beta, mu are all of size k=5

**Comment by bwengals** [comment]
The problem to me looks to be in `v` and `w`, not the GP mean function, since `f` is the expected dimension given your arguments.  And it looks like the `norm_cdf(alpha + beta*f)` is being properly broadcast to size (200, 5) in your first example.  With `tt.zeros_like`, you get a shape error from `erfc` which would be from the `norm_cdf` step.

Should the rows of `w` sum to one or the columns?  The stickbreaking transform takes a vector of K values between zero and one, and converts them to a K - 1 length vector, looking at its code I'm not sure it is made to handle a multidimensional array.  You may need to apply it separately to each row/column of `v`.  Perhaps someone more familiar with the stickbreaking transform could weigh in.

**Comment by smthzch** [comment]
The thing that trips me up is if you do not use gp, and pass X directly into `v = norm_cdf(alpha + beta * X)`, everything works fine.

**Comment by bwengals** [comment]
Sorry for the slow response, you know, maybe its just a shape issue.  X is (200, 1), so try 

    with pm.Model() as model:
        cov_func = pm.gp.cov.ExpQuad(X.shape[1], ls=0.1)
        gp = pm.gp.Latent(mean_func=tt.zeros_like, cov_func=cov_func)
        f = gp.prior("f", X=X)
        alpha = pm.Normal('alpha', 0, 10, shape=K)
        beta = pm.Normal('beta', 0., 10., shape=K)
        v = norm_cdf(alpha + beta * f[:,None]) # make f have shape (200, 1)
        w = pm.Deterministic('w', stick_breaking(v))

**Comment by smthzch** [comment]
If I take out the mean function declaration in the Latent call I get no more errors. Model is garbage but no errors so thanks!

What causes this behavior?  Shouldn't declaring the shape in the Latent call produce the same output as doing f[:,None]?

**Comment by bwengals** [comment]
Well, the shape argument gets passed as a kwarg to the underlying distribution, so MvNormal here.  If i recall, its (n, n_samples) for the MvNormal shapes.

**Comment by bwengals** [comment]
will mark issue as closed, anyone feel free to reopen if that's too hasty
