### ISSUE TITLE
glm.GLM.from_formula('y ~ x', data) error

### ISSUE THREAD

**Issue by rinabuoy** [pymc-devs/pymc#3379]
Hi Guys, 

I cannot get glm.GLM.from_formula('y ~ x', data) to work. It always throws this error.

I am using PyMC3 v3.6 installed from PIP.

Traceback (most recent call last):
  File "C:\Users\user\Source\repos\NaiveBayesClassifier\NaiveBayesClassifier\pymc.py", line 53, in <module>
    pmc.glm.GLM.from_formula('y ~ x', data)
  File "C:\Users\user\Anaconda3\lib\site-packages\pymc3\glm\linear.py", line 145, in from_formula
    y, x = patsy.dmatrices(formula, data)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\highlevel.py", line 310, in dmatrices
    NA_action, return_type)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\highlevel.py", line 165, in _do_highlevel_design
    NA_action)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\highlevel.py", line 62, in _try_incr_builders
    formula_like = ModelDesc.from_formula(formula_like)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\desc.py", line 164, in from_formula
    tree = parse_formula(tree_or_string)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\parse_formula.py", line 148, in parse_formula
    _atomic_token_types)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\infix_parser.py", line 210, in infix_parse
    for token in token_source:
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\parse_formula.py", line 94, in _tokenize_formula
    yield _read_python_expr(it, end_tokens)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\parse_formula.py", line 44, in _read_python_expr
    for pytype, token_string, origin in it:
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\util.py", line 332, in next
    return six.advance_iterator(self._it)
  File "C:\Users\user\Anaconda3\lib\site-packages\patsy\tokens.py", line 35, in python_tokenize
    assert pytype not in (tokenize.NL, tokenize.NEWLINE)
AssertionError

Can someone please help ?

Thank you

**Comment by fonnesbeck** [comment]
Hi @rinauoy. Can you post a reproducible example?

**Comment by rinabuoy** [comment]
Hi Chris,

Thank you. Here is it:

```python
import pandas as pd
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pymc3 as pmc
print('Running on PyMC3 v{}'.format(pmc.__version__))

pd.set_option('display.notebook_repr_html', False)

plt.style.use('seaborn-white')

size = 20
a = [-0.3, 0.5]
sd = .2
alpha = 2.
beta = 1./(sd**2)


g_min = -1.5
g_max = 1.5
step = 100
xx, yy = np.meshgrid(np.linspace(g_min,g_max,step), np.linspace(g_min,g_max,step))
grid = np.c_[xx.ravel(), yy.ravel()]

x_ = np.linspace(g_min,g_max,step).reshape(-1,1)

x = stats.uniform.rvs(-1, scale=2, size=size)
y_true = a[0] + a[1] * x 

t_n =  y_true + np.random.normal(scale=sd, size=size)


data = pd.DataFrame({'x':x, 'y':t_n})

with pmc.Model() as model:
    
    pmc.glm.GLM.from_formula('y ~ x', data)
    
    trace = pmc.sample(10000, progressbar=True, cores = 1) 
```

**Comment by fonnesbeck** [comment]
Sorry for the late response. I can't replicate the error with the code you posted. I am also running on Windows, using PyMC 3.6 on Python 3.7. the model samples to completion.

**Comment by mmxgn** [comment]
Hi, 

I had the same problem. I solved it with upgrading patsy 

```
pip3 install --upgrade --user patsy
```

Hope this helps.
