### ISSUE TITLE
sample_prior_predictive() fails with bounded variables

### ISSUE THREAD

**Issue by fbartolic** [pymc-devs/pymc#3449]
## Description of your problem
I'm trying to sample the prior predictive distribution for a model containing bounded variables but I'm running into shape handling errors. I've provided a minimal example which reproduces the issue.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
import numpy as np
import theano.tensor as T

with pm.Model():
    BoundedNormal = pm.Bound(pm.Normal, lower=0.0) 
    x = BoundedNormal('x', 
            mu=T.zeros((3, 1)), 
            sd=1*T.ones((3, 1)),
            shape=(3, 1))

    trace = pm.sample_prior_predictive(500)
```

**Please provide the full traceback.**
```python
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "sample_from_prior.py", line 12, in <module>
    trace = pm.sample_prior_predictive(500)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/sampling.py", line 1325, in sample_prior_predictive
    values = draw_values([model[name] for name in names], size=samples)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 369, in draw_values
    size=size)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 463, in _draw_value
    return param.random(point=point, size=size)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/model.py", line 43, in __call__
    return getattr(self.obj, self.method_name)(*args, **kwargs)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/distributions/bound.py", line 80, in random
    size=size)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 592, in generate_samples
    samples = generator(size=size_tup + dist_shape, *args, **kwargs)
  File "/home/star/fb90/anaconda3/lib/python3.6/site-packages/pymc3/distributions/bound.py", line 60, in _random
    samples[i:(i + len(select))] = select[:]
ValueError: could not broadcast input array from shape (2253) into shape (1500)
```

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.4
* Python Version: 3.6.8
* Operating system: Ubuntu 18.04
* How did you install PyMC3: pip

**Comment by fonnesbeck** [comment]
I can confirm this. Note that `BoundedNormal.dist().sample()` and `sample_posterior_predictive` both work.

**Comment by fonnesbeck** [comment]
For some reason, `self._wrapped` in this case is ending up being [3,1].

**Comment by fonnesbeck** [comment]
The PR above fixes this here. Please test.
