### ISSUE TITLE
latest dev branch fails out of the box

### ISSUE THREAD

**Issue by tanmoy7989** [pymc-devs/pymc#3457]
## Description of your problem
I installed the latest dev branch by cloning into the repository and then running
python setup.py develop, but I get an error out of the box:

**Please provide the full traceback.**
Traceback (most recent call last):
  File "./test1.py", line 7, in <module>
    import pymc3 as pm
  File "/home/tsanyal/.local/lib/python2.7/site-packages/pymc3/__init__.py", line 5, in <module>
    from .distributions import *
  File "/home/tsanyal/.local/lib/python2.7/site-packages/pymc3/distributions/__init__.py", line 1, in <module>
    from . import timeseries
  File "/home/tsanyal/.local/lib/python2.7/site-packages/pymc3/distributions/timeseries.py", line 5, in <module>
    from .continuous import get_tau_sigma, Normal, Flat
  File "/home/tsanyal/.local/lib/python2.7/site-packages/pymc3/distributions/continuous.py", line 14, in <module>
    from . import transforms
  File "/home/tsanyal/.local/lib/python2.7/site-packages/pymc3/distributions/transforms.py", line 4, in <module>
    from ..model import FreeRV
  File "/home/tsanyal/.local/lib/python2.7/site-packages/pymc3/model.py", line 546
    class Model(Context, Factor, WithMemoization, metaclass=InitContextMeta):

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.4
* Python Version: 2.7.15
* Operating system: Fedora
* How did you install PyMC3: pip

**Comment by lucianopaz** [comment]
The current master branch does not support python 2.7. The last version that supported both python 2 and 3 was pymc3.6.
