### ISSUE TITLE
Error when Import pymc3

### ISSUE THREAD

**Issue by shenzhuangwudi** [pymc-devs/pymc#3616]
I get error when I want to simply import pymc3.  

Before install pymc3, I clean up all other packages(use pip freeze + pip uninstall) to make sure I have a clean env.  Then I ran "pip install pymc3" to install it. My python is standard CPython 3.6.8 (Not AnaConda). My Installed packages:

C:\Users\zxu14\Desktop\DrillOps\nanzhe>pip list
Package         Version
--------------- -------
h5py            2.9.0
numpy           1.17.1
pandas          0.25.1
patsy           0.5.1
pip             19.2.3
pymc3           3.7
python-dateutil 2.8.0
pytz            2019.2
scipy           1.3.1
setuptools      40.6.2
six             1.12.0
Theano          1.0.4
tqdm            4.35.0

The error I get:

C:\Users\zxu14\Desktop\DrillOps\nanzhe>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc3 as pm

You can find the C code in this temporary file: C:\Users\zxu14\AppData\Local\Temp\theano_compilation_error_crqeh9du
Traceback (most recent call last):
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\pymc3\__init__.py", line 5, in <module>
    from .distributions import *
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\pymc3\distributions\__init__.py", line 1, in <module>
    from . import timeseries
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\pymc3\distributions\timeseries.py", line 1, in <module>
    import theano.tensor as tt
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\vm.py", line 674, in <module>
    from . import lazylinker_c
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "C:\Users\zxu14\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): In file included from C:/MinGW64/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/math.h:36,.                  from C:\Users\zxu14\AppData\Local\Programs\Python\Python36\include/pyport.h:194,.                  from C:\Users\zxu14\AppData\Local\Programs\Python\Python36\include/Python.h:53,.                  from C:\Users\zxu14\AppData\Local\Theano\compiledir_Windows-10-10.0.17134-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.6.8-64\lazylinker_ext\mod.cpp:1:. C:/MinGW64/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/cmath:1121:11: error: '::hypot' has not been declared.    using ::hypot;.            ^~~~~.
>>> exit()

**Comment by ColCarroll** [comment]
hi! this error is actually coming from `theano`, which has windows [installation instructions here](http://deeplearning.net/software/theano/install_windows.html). it is noted that you should probably install with `conda` there, which might be worth a try?

I'm closing since it isn't necessarily an issue with pymc3, but I can try to keep helping if problems persist.

**Comment by shenzhuangwudi** [comment]
@ColCarroll  Hi,  according to http://deeplearning.net/software/theano/install_windows.html   theano only supports below python versions: 
Python == 2.7* or ( >= 3.4 and < 3.6 )

Does it mean,  as a result, pymc3 also can only support these python version?  My python version is 3.6.8, which is declared not supported by theano.

**Comment by ColCarroll** [comment]
We (pymc3) do testing up to 3.7, I believe, but only on linux. Have you
tried using conda? I am interested in whether that works on Windows...
