### ISSUE TITLE
GaussianRandomWalk in GHME example fails

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#3663]
I'm running into some Theano compile issues when running the GHME example. Specifically, `GaussianRandomWalk` instantiation fails:

```
You can find the C code in this temporary file: /var/folders/xc/ctschysn35z4n5k1lxnpqgq40000gn/T/theano_compilation_error_b4yb6c0d
Traceback (most recent call last):
  File "GHME_2013.py", line 48, in <module>
    y = GaussianRandomWalk('y', sigma=coeff_sd, shape=(nknots, ncountries))
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 46, in __new__
    return model.Var(name, dist, data, total_size)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/pymc3/model.py", line 826, in Var
    total_size=total_size, model=self)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/pymc3/model.py", line 1274, in __init__
    self.logp_elemwiset = distribution.logp(self)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/pymc3/distributions/timeseries.py", line 217, in logp
    innov_like = Normal.dist(mu=x_im1 + mu, sigma=sigma).logp(x_i)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/tensor/var.py", line 128, in __add__
    return theano.tensor.basic.add(self, other)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/op.py", line 670, in __call__
    no_recycling=[])
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/cc.py", line 1624, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/cc.py", line 1527, in compile_cmodule
    preargs=preargs)
  File "/Users/cfonnesbeck/anaconda3/envs/bayes_course/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ("Compilation failed (return status=1): /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:510:27: error: non-constant-expression cannot be narrowed from type 'npy_intp' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].     int init_totals[2] = {V3_n0, V3_n1};.                           ^~~~~. /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:510:27: note: insert an explicit cast to silence this issue.     int init_totals[2] = {V3_n0, V3_n1};.                           ^~~~~.                           static_cast<int>( ). /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:510:34: error: non-constant-expression cannot be narrowed from type 'npy_intp' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].     int init_totals[2] = {V3_n0, V3_n1};.                                  ^~~~~. /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:510:34: note: insert an explicit cast to silence this issue.     int init_totals[2] = {V3_n0, V3_n1};.                                  ^~~~~.                                  static_cast<int>( ). /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:522:9: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].         V3_stride0, V3_stride1, .         ^~~~~~~~~~. /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:522:9: note: insert an explicit cast to silence this issue.         V3_stride0, V3_stride1, .         ^~~~~~~~~~.         static_cast<int>( ). /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:522:21: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].         V3_stride0, V3_stride1, .                     ^~~~~~~~~~. /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:522:21: note: insert an explicit cast to silence this issue.         V3_stride0, V3_stride1, .                     ^~~~~~~~~~.                     static_cast<int>( ). /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:524:1: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]. V1_stride0, V1_stride1. ^~~~~~~~~~. /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:524:1: note: insert an explicit cast to silence this issue. V1_stride0, V1_stride1. ^~~~~~~~~~. static_cast<int>( ). /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:524:13: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]. V1_stride0, V1_stride1.             ^~~~~~~~~~. /Users/cfonnesbeck/.theano/compiledir_Darwin-19.0.0-x86_64-i386-64bit-i386-3.6.7-64/tmpm0x85gjz/mod.cpp:524:13: note: insert an explicit cast to silence this issue. V1_stride0, V1_stride1.             ^~~~~~~~~~.             static_cast<int>( ). 6 errors generated.. ", '[Elemwise{add,no_inplace}(<TensorType(float64, matrix)>, <TensorType(float32, (True, True))>)]')
```

Not sure if its a NumPy compatibility issue (NumPy 1.17.2).

Running PyMC3 3.7 on macOS (Python 3.6) and theano installed from conda.

**Comment by fonnesbeck** [comment]
This appears to be system-specific. Another conda env with a different setup runs the example fine.

**Comment by fonnesbeck** [comment]
Even when the error does not appear, the example tends to fail due to zero derivatives. Might be worth revising this example.
