### ISSUE TITLE
some problems when calling theano backend

### ISSUE THREAD

**Issue by siliconMagic** [pymc-devs/pymc#3681]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
when calling theano for sampling, it does not work....

**Please provide a minimal, self-contained, and reproducible example.**
```python
with pm.Model() as model:
        mu = pm.Normal('mu', mu=0, sigma=1)
        obs = pm.Normal('obs', mu=mu, sigma=1, observed=npr.randn(100))
       
        # inference
        trace = pm.sample(1000, tune=500)
```

**Please provide the full traceback.**
```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...

You can find the C code in this temporary file: C:\Users\ADMINI~1.WIN\AppData\Local\Temp\theano_compilation_error_gfdvqh45
Traceback (most recent call last):
  File "e:/python_projects/hp_station/FE_quant_2/fin_model/options_12_statistics_b.py", line 126, in <module>
    Main()
  File "e:/python_projects/hp_station/FE_quant_2/fin_model/options_12_statistics_b.py", line 121, in Main
    pymc3_demo_2()
  File "e:/python_projects/hp_station/FE_quant_2/fin_model/options_12_statistics_b.py", line 76, in pymc3_demo_2
    trace = pm.sample(1000, tune=500)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\sampling.py", line 396, in sample
    progressbar=progressbar, **kwargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\sampling.py", line 1515, in init_nuts
    step = pm.NUTS(potential=potential, model=model, **kwargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\step_methods\hmc\nuts.py", line 152, in __init__
    super().__init__(vars, **kwargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py", line 72, in __init__
    super().__init__(vars, blocked=blocked, model=model, dtype=dtype, **theano_kwargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\step_methods\arraystep.py", line 228, in __init__
    vars, dtype=dtype, **theano_kwargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\model.py", line 723, in logp_dlogp_function
    return ValueGradFunction(self.logpt, grad_vars, extra_vars, **kwargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\pymc3\model.py", line 456, in __init__
    grad = tt.grad(self._cost_joined, self._vars_joined)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 605, in grad
    grad_dict, wrt, cost_name)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1371, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1371, in <listcomp>
    rval = [access_grad_cache(elem) for elem in wrt]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1021, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gradient.py", line 1162, in access_term_cache
    new_output_grads)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\tensor\elemwise.py", line 543, in L_op
    rval = self._bgrad(inputs, outs, ograds)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\tensor\elemwise.py", line 643, in _bgrad
    ret.append(transform(scalar_igrad))
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\tensor\elemwise.py", line 635, in transform
    *[transform(ipt) for ipt in node.inputs])
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\op.py", line 670, in __call__
    no_recycling=[])
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\cc.py", line 1624, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\cc.py", line 1527, in compile_cmodule
    preargs=preargs)
  File "E:\python_projects\v_env_all\v_env_37\lib\site-packages\theano\gof\cmodule.py", line 2399, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('Compilation failed (return status=1): C:\\Users\\ADMINI~1.WIN\\AppData\\Local\\Temp\\cc4SiW20.s: Assembler messages:\r. C:\\Users\\ADMINI~1.WIN\\AppData\\Local\\Temp\\cc4SiW20.s:98: Error: invalid register for .seh_savexmm\r. C:\\Users\\ADMINI~1.WIN\\AppData\\Local\\Temp\\cc4SiW20.s:100: Error: invalid register for .seh_savexmm\r. ', '[Elemwise{Cast{float64}}(<TensorType(int8, (True,))>)]')
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.7
* Theano Version:1.0.4
* Python Version:3.7.3
* Operating system:WinOS
* How did you install PyMC3: conda

**Comment by twiecki** [comment]
Seems like an installation issue, how exactly did you install pymc3?

**Comment by siliconMagic** [comment]
conda by source forge发自我的华为手机-------- 原始邮件 --------主题：Re: [pymc-devs/pymc3] some problems when calling theano backend (#3681)发件人：Thomas Wiecki 收件人：pymc-devs/pymc3 抄送：Linagyu Min ,Author Seems like an installation issue, how exactly did you install pymc3?

**Comment by aakhmetz** [comment]
Yesterday I had something similar, and theano was not installed properly. After following the instructions and installing optional packages, it worked

**Comment by siliconMagic** [comment]
> Yesterday I had something similar, and theano was not installed properly. After following the instructions and installing optional packages, it worked

Could you tell me how to install theano with proper options, PLZ...

**Comment by aakhmetz** [comment]
I followed this http://deeplearning.net/software/theano/install_windows.html

**Comment by siliconMagic** [comment]
ok. thx发自我的华为手机-------- 原始邮件 --------发件人： "Andrei R. Akhmetzhanov" <notifications@github.com>日期： 2019年11月29日周五 下午2:53收件人： pymc-devs/pymc3 <pymc3@noreply.github.com>抄送： Linagyu Min <siliconmagic@126.com>, Author <author@noreply.github.com>主    题： Re: [pymc-devs/pymc3] some problems when calling theano backend (#3681)I follows this http://deeplearning.net/software/theano/install_windows.html

**Comment by eigenfoo** [comment]
Sounds like this was resolved? Closing now, but please feel free to reopen if you disagree.

**Comment by siliconMagic** [comment]
> Sounds like this was resolved? Closing now, but please feel free to reopen if you disagree.

it is still not resolved...
