### ISSUE TITLE
Bounded prior causes Value Error in sample_smc(kernel='ABC')

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3714]
Doing ```sample_smc(kernel='ABC')``` and setting one particular prior from ```Normal``` to the bounded ```Uniform``` causes an error ```setting an array element with a sequence.```

**Please provide a minimal, self-contained, and reproducible example.**
The gist is here: https://gist.github.com/aakhmetz/372d0bb18ea89882437d6c63053f45b8
```python
def _sim(gtmean, gtsd, σ1, ρ, w):
    weights = np.random.dirichlet(w, 1)[0]
    draws = np.random.multinomial(len(ds), weights, size=1)[0]
    # generation time
    α = (gtmean/gtsd)**2
    β = gtsd**2/gtmean
    gt = ss.gamma(α, scale = β)
    # incubation period
    incmean = 12.3; incvar = 12.1
    incα = (incmean**2)/incvar
    incβ = incvar/incmean
    ht = ss.gamma(incα, scale = incβ)
    # Mechanism 1
    res = np.random.normal(0, σ1, draws[0])
    # Mechanism 2
    μ2 = abs(np.random.gamma(α, β, draws[1]) - np.random.gamma(α, β, draws[1]))
    res = np.r_[res,np.random.normal(μ2, 0.5, size=draws[1])]
    # Mechanism 3
    ## incorporating copulas
    ### see https://twiecki.io/blog/2018/05/03/copulas/ for details
    if (draws[2]>=1):
        x = np.random.multivariate_normal([0, 0], [[1., ρ], [ρ, 1.]], draws[2])
        norm = ss.distributions.norm()
        x_unif = norm.cdf(x)
        τ = ht.ppf(x_unif[:, 0]) 
        u = gt.ppf(x_unif[:, 1])
        μ3 = abs(gt.rvs(draws[2]) + u - τ)
        res = np.r_[res, np.random.normal(μ3, 0.5, size=draws[2])]
    # output
    return np.sort(res)

with pm.Model():
    # Generation time interval
    gtmean = pm.HalfNormal('gtmean', sd=20) 
    gtsd = pm.HalfNormal('gtsd', sd=5)
    # for Mechanism 1
    σ1 = pm.HalfNormal('σ1', sd=5, testval=5)
    # corr.coeff. b/w incubation period and serial interval
    ρ = pm.Uniform('ρ', 0, 1, testval=0) ## <- does not work
    ## ρ = pm.Bound(pm.Normal,lower=-1,upper=1)('ρ', 0, 1, testval=0) ## <- does not work
    ## ρ = pm.Normal('ρ', 0, .1, testval=-.5) <- previous variant
    
    w = pm.Dirichlet('w', a=np.array([1, 5, 1]))
    s = pm.Simulator('s', _sim, observed=np.sort([x+0.5 for x in ds]))
    trace = pm.sample_smc(1000, kernel="ABC", epsilon=0.1, parallel=True)
```

**Please provide the full traceback.**
```python
Sample initial stage: ...
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/aakhmetz/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/aakhmetz/anaconda3/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/aakhmetz/anaconda3/lib/python3.6/site-packages/pymc3/smc/smc.py", line 438, in __call__
    sim_data = self.function(**func_parameters)
  File "<ipython-input-16-1302d6d723b0>", line 22, in _sim
    x = np.random.multivariate_normal([0, 0], [[1., ρ], [ρ, 1.]], draws[2])
  File "mtrand.pyx", line 3758, in numpy.random.mtrand.RandomState.multivariate_normal
ValueError: setting an array element with a sequence.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/lib/python3.6/site-packages/pymc3/smc/sample_smc.py in sample_smc(draws, kernel, n_steps, parallel, start, cores, tune_steps, p_acc_rate, threshold, epsilon, dist_func, sum_stat, progressbar, model, random_seed)
    136     smc.initialize_population()
    137     smc.setup_kernel()
--> 138     smc.initialize_logp()
    139 
    140     while smc.beta < 1:

~/anaconda3/lib/python3.6/site-packages/pymc3/smc/smc.py in initialize_logp(self)
    142             priors = self.pool.starmap(self.prior_logp, [(sample,) for sample in self.posterior])
    143             likelihoods = self.pool.starmap(
--> 144                 self.likelihood_logp, [(sample,) for sample in self.posterior]
    145             )
    146         else:

~/anaconda3/lib/python3.6/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    272         `func` and (a, b) becomes func(a, b).
    273         '''
--> 274         return self._map_async(func, iterable, starmapstar, chunksize).get()
    275 
    276     def starmap_async(self, func, iterable, chunksize=None, callback=None,

~/anaconda3/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

ValueError: setting an array element with a sequence.
```

**Please provide any additional information below.**
Because I am new in SMC-ABC, I maybe be wrong in something. Although it seems to me that my code is legit.

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.6.9
* Operating system: ubuntu
* How did you install PyMC3: (conda/pip) latest master version from github

**Comment by aloctavodia** [comment]
Thanks for taking the time to report this, and thanks for the reproducible example. I found the problem and will send a PR to fix it.

**Comment by aakhmetz** [comment]
That's great! Thanks!

**Comment by lucianopaz** [comment]
I'll keep this open until the fix gets merged

**Comment by aakhmetz** [comment]
Ok

**Comment by aakhmetz** [comment]
Thanks, just a quick checked shows that it is working now 

rho is Uniform(-1,1)
![Screenshot from 2019-12-21 02-51-09](https://user-images.githubusercontent.com/2173206/71279795-004b6480-239d-11ea-9c91-a8b857bda904.png)
