### ISSUE TITLE
"observed" keyword later causes error in "traceplot" after using "remove_values"

### ISSUE THREAD

**Issue by rhjohnstone** [pymc-devs/pymc#3728]
I have a random variable `logx`, then a deterministic transformation of that variable `x`. (Ideally, I would only save `x` when sampling as I asked [here](https://discourse.pymc.io/t/save-determinstic-variables-dont-save-original-variables/4212)) for plotting later, but using the `trace` keyword also [doesn't work ](https://github.com/arviz-devs/arviz/issues/395) for this.) My current solution is to save everything, then remove `logx` after sampling by using `remove_values` before plotting anything. This is not a good solution for bigger models with more samples, but anyway...

However, when using the `observed` keyword in another variable, then removing `logx` via `remove_values`, trying to plot the remaining parameter(s) gives an error. If we comment out the `obs` line below (or even just comment out the `observed=` bit), the plotting works fine.

## Reproducible code

```python
import pymc3 as pm
import numpy.random as npr

npr.seed(123)
data = npr.randn(10)

with pm.Model() as model:
    logx = pm.Logistic("logx", mu=0., s=1.)
    x = pm.Deterministic("x", pm.math.exp(logx))
    obs = pm.Normal("y", mu=0., sigma=1., observed=data)  # comment out and the plotting works
    trace = pm.sample(100, tune=100)

trace.remove_values("logx")
tp = pm.traceplot(trace, combined=True)
```

## Traceback

```python
Traceback (most recent call last):
  File "error.py", line 14, in <module>
    tp = pm.traceplot(trace, combined=True)
  File "/home/ross/.local/lib/python3.6/site-packages/pymc3/plots/__init__.py", line 42, in wrapped
    return func(*args, **kwargs)
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/plots/traceplot.py", line 116, in plot_trace
    divergence_data = convert_to_dataset(data, group="sample_stats").diverging
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/converters.py", line 162, in convert_to_dataset
    inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims)
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/converters.py", line 83, in convert_to_inference_data
    return from_pymc3(trace=kwargs.pop(group), **kwargs)
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/io_pymc3.py", line 226, in from_pymc3
    dims=dims,
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/io_pymc3.py", line 210, in to_inference_data
    "sample_stats": self.sample_stats_to_xarray(),
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/base.py", line 32, in wrapped
    return func(cls, *args, **kwargs)
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/io_pymc3.py", line 106, in sample_stats_to_xarray
    log_likelihood, dims = self._extract_log_likelihood()
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/base.py", line 32, in wrapped
    return func(cls, *args, **kwargs)
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/base.py", line 32, in wrapped
    return func(cls, *args, **kwargs)
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/io_pymc3.py", line 83, in _extract_log_likelihood
    log_like = [log_likelihood_vals_point(point) for point in self.trace.points([chain])]
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/io_pymc3.py", line 83, in <listcomp>
    log_like = [log_likelihood_vals_point(point) for point in self.trace.points([chain])]
  File "/home/ross/.local/lib/python3.6/site-packages/arviz/data/io_pymc3.py", line 75, in log_likelihood_vals_point
    log_like_val = utils.one_de(log_like(point))
  File "/home/ross/.local/lib/python3.6/site-packages/pymc3/model.py", line 1186, in __call__
    return self.f(**point)
  File "/home/ross/.local/lib/python3.6/site-packages/theano/compile/function_module.py", line 886, in __call__
    self.inv_finder[c]))
TypeError: Missing required input: logx
```

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.6.7
* Operating system: Ubuntu 18.04.2 LTS via WSL on Windows 10
* How did you install PyMC3: pip

**Comment by rpgoldman** [comment]
This is actually an error in the code that translates the PyMC3 trace into an arviz inference data data structure. So to get the best response you will need to refile this issue with the arviz-devs github group.

You can verify this by looking at the backtrace.
`    inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims) `

**Comment by OriolAbril** [comment]
@rhjohnstone  Upgrading to ArviZ [development version](https://github.com/arviz-devs/arviz#development) should fix the issue.

The workflow I would recommend is one of the following:

```
import pymc3 as pm
import arviz as az

with pm.Model() as model:
   # define model
    trace = pm.sample()  # sample
    # edit trace if needed, e.g. trace.remove_values("logx")
    idata = az.from_pymc3(trace)  # or az.from_pymc3(trace, , log_likelihood=False) if you get a warning

tp = pm.traceplot(idata, combined=True)
```

Using ArviZ inference data objects allows to customize the conversion to better fit your needs and also eliminates the overhead present otherwise because plotting functions have to first convert and then plot. See docs on [`from_pymc3`](https://arviz-devs.github.io/arviz/generated/arviz.from_pymc3.html#arviz.from_pymc3) and [ArviZ Coockbook](https://arviz-devs.github.io/arviz/notebooks/InferenceDataCookbook.html#From-pymc3) for more details or an overview.

**Comment by ricardoV94** [comment]
Should this be closed?
