### ISSUE TITLE
Text backend not importing vector values in PyMC 3.8

### ISSUE THREAD

**Issue by aarmey** [pymc-devs/pymc#3759]
Something changed such that I'm not seeing vector variables imported with the text backend in v3.8. Everything works fine with v3.7. When I create and write a new file, the format is unchanged, so it's not simply a breaking change in the sample file formatting.

**Please provide a minimal, self-contained, and reproducible example.**

If I try to import [this file](https://github.com/meyer-lab/gc-cytokines/blob/master/ckine/data/fits/IL2_model_results/chain-0.csv), it works in PyMC 3.7. In v3.8, I only get the `['Y_15', 'Y_int', 'Y_gc', 'logp']` variables. 

**Please provide the full traceback.**

This is where I see an error in code that worked with v3.7. It's trying to import the `scales` variable.

```python
Traceback (most recent call last):
  File "./genFigures.py", line 19, in <module>
    ff = eval(nameOut + '.makeFigure()')
  File "<string>", line 1, in <module>
  File "/home/asm/gc-cytokines/ckine/figures/figure1.py", line 31, in makeFigure
    unkVec, scales = import_samples_2_15(N=100)  # use these for simulations
  File "/home/asm/gc-cytokines/ckine/imports.py", line 73, in import_samples_2_15
    scales = trace.get_values("scales")
  File "/home/asm/gc-cytokines/venv/lib/python3.7/site-packages/pymc3/backends/base.py", line 473, in get_values
    for chain in chains]
  File "/home/asm/gc-cytokines/venv/lib/python3.7/site-packages/pymc3/backends/base.py", line 473, in <listcomp>
    for chain in chains]
  File "/home/asm/gc-cytokines/venv/lib/python3.7/site-packages/pymc3/backends/text.py", line 137, in get_values
    var_df = self.df[self.flat_names[varname]]
KeyError: 'scales'
```

**Please provide any additional information below.**

Thanks for all the work developing this really useful tool!

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7.5
* Operating system: MacOS or Ubuntu
* How did you install PyMC3: pip

**Comment by aarmey** [comment]
I suspect it is an issue here, but I'm not sure what was intended with this change.

https://github.com/pymc-devs/pymc3/compare/v3.7...v3.8#diff-fc732c79e3ccc80c7f9b300c7cf34d5bR190

**Comment by michaelosthege** [comment]
We have since removed the Text backend, so I'll close this issue.
