### ISSUE TITLE
sprinkler.py not working after installation

### ISSUE THREAD

**Issue by dorondru** [pymc-devs/pymc#3983]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
from pymc3 import Model, Bernoulli, sample, traceplot, BinaryGibbsMetropolis, sampling
from pymc3.math import switch, gt, eq
from matplotlib.pyplot import savefig

Nsamples = 5000#20000

with Model() as sprinkler_model:
    Rain = Bernoulli('Rain', .2)
    pSprinkler = switch( Rain, 0.01, 0.4)
    Sprinkler = Bernoulli('Sprinkler', pSprinkler)
    pWetGrass = switch( eq(Rain, 1),
    #pWetGrass = switch(Rain,
                        switch( Sprinkler, 0.99, 0.8 ),
                        # need to apply some smoothing:
                        switch( Sprinkler, .9, 1/Nsamples ) )
    WetGrass = Bernoulli('WetGrass', pWetGrass, observed=1 )
    _trace = sample(Nsamples, step=[BinaryGibbsMetropolis([Rain, Sprinkler])], tune=5000, random_seed=124)
```

**Please provide the full traceback.**
```python
You can find the C code in this temporary file: /var/folders/f6/_qhvjtgs285ctsyzzvqzld2m0000gn/T/theano_compilation_error_rslyb38e
Traceback (most recent call last):
  File "sprinkler.py", line 14, in <module>
    Rain = Bernoulli('Rain', .2)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 82, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 91, in dist
    dist.__init__(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/distributions/discrete.py", line 320, in __init__
    self._logit_p = logit(p)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/math.py", line 204, in logit
    return tt.log(p / (floatX(1) - p))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/tensor/var.py", line 230, in __rsub__
    return theano.tensor.basic.sub(other, self)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/op.py", line 670, in __call__
    no_recycling=[])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/cc.py", line 1624, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/cc.py", line 1527, in compile_cmodule
    preargs=preargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/theano/gof/cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ("Compilation failed (return status=1): In file included from /Users/dorondru/.theano/compiledir_Darwin-18.7.0-x86_64-i386-64bit-i386-3.7.7-64/tmpwzcggonv/mod.cpp:1:. In file included from /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:25:. /Users/dorondru/opt/miniconda3/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found. #include_next <stdio.h>.               ^~~~~~~~~. 1 error generated.. ", '[Elemwise{sub,no_inplace}(TensorConstant{1.0}, TensorConstant{0.2})]')
```

**Please provide any additional information below.**
For a while it was woking in PyCharm, but not in commandline. I then installed pymc3: I tried all the different ways you suggested on the installation page, last one being: "pip install pymc3"

## Versions and main components

* PyMC3 Version: latest from github
* Theano Version: IDK, shouldn't it be automatically installed as part of pymc3? the os cannot find it
* Python Version: 3.7.7
* Operating system: MC OS
* How did you install PyMC3: (conda/pip) pip install pymc3

**Comment by fonnesbeck** [comment]
If Theano can't be found, that's a bad sign. Does `import theano` return an error? Make sure the pip that you are using to install PyMC3 corresponds to the Python you are intending to use (it looks like you are running from a Homebrew installation). `which pip` should provide this information. If you tried several ways of installing PyMC3 chances are it now lives in multiple places, so you need to be careful about your PYTHONPATH.

I was confused when you said that it was working in PyCharm ... I then installed PyMC3. What was working? If you hadn't yet installed PyMC3, I assume you don't mean the the model?

**Comment by dorondru** [comment]
pip --version

pip 20.1.1 from
/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip
(python 3.7)

**Comment by dorondru** [comment]
import theano works ok:

import theano
from pymc3 import Model, Bernoulli, sample, traceplot,
BinaryGibbsMetropolis, sampling
from pymc3.math import switch, gt, eq
from matplotlib.pyplot import savefig

Nsamples = 5000#20000
"""
with Model() as sprinkler_model:
    Rain = Bernoulli('Rain', .2)
    pSprinkler = switch( Rain, 0.01, 0.4)
    Sprinkler = Bernoulli('Sprinkler', pSprinkler)
    pWetGrass = switch( eq(Rain, 1),
    #pWetGrass = switch(Rain,
                        switch( Sprinkler, 0.99, 0.8 ),
                        # need to apply some smoothing:
                        switch( Sprinkler, .9, 1/Nsamples ) )
    WetGrass = Bernoulli('WetGrass', pWetGrass, observed=1 )
    _trace = sample(Nsamples, step=[BinaryGibbsMetropolis([Rain,
Sprinkler])], tune=5000, random_seed=124)
    traceplot(_trace, ['Rain','Sprinkler'])

"""
print("Bye")

**Comment by dorondru** [comment]
Solved it. Thanks anyway!
