### ISSUE TITLE
Survival Analysis error related to np.greater_equal.outer

### ISSUE THREAD

**Issue by chuymtz** [pymc-devs/pymc#4027]
I'm working through the Example 
https://docs.pymc.io/notebooks/survival_analysis.html

I get an error during data processing while running the line 
```python
exposure = np.greater_equal.outer(df.time, interval_bounds[:-1]) * interval_length
```
The traceback error is 

```python
Traceback (most recent call last):
  File "C:\Users\martinj15\AppData\Local\Continuum\Anaconda3\envs\pysurv\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "c:\users\martinj15\appdata\local\continuum\anaconda3\envs\ptown\lib\site-packages\pandas\core\series.py", line 705, in __array_ufunc__
    return construct_return(result)
  File "c:\users\martinj15\appdata\local\continuum\anaconda3\envs\ptown\lib\site-packages\pandas\core\series.py", line 694, in construct_return
    raise NotImplementedError
NotImplementedError
```

## Versions and main components

* PyMC3 Version: v3.9.2
* Theano Version: 1.0.4
* Python Version: 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] on win32
* Operating system: windows
* How did you install PyMC3: pip

**Comment by AmitKus** [comment]
@chuymtz This notebook needs to be updated. However, for the time-being you can change df.time to df.time.values to move forward.

exposure = np.greater_equal.outer(df.time, interval_bounds[:-1]) * interval_length
to 
exposure = np.greater_equal.outer(df.time.values, interval_bounds[:-1]) * interval_length

**Comment by chuymtz** [comment]
Thank you @AmitKus ! This did the trick and I'm able to move forward. Best wishes
