### ISSUE TITLE
`sample_prior_predictive` doesn't work if there is a dot product in the model

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#4093]
Here is a simple example of a model containing a dot product within a deterministic variable.

```
import pymc3 as pm
import theano.tensor as tt


with pm.Model() as model:

    x = 8
    y = 6
    z = 5

    A = pm.MvNormal("A", mu=tt.zeros(y), cov=tt.eye(y), shape=(x, y))
    B = tt.zeros((z, x))
    C = tt.dot(B, A)  # this works fine
    C = pm.Deterministic("C", tt.dot(B, A))  # produces an error

    pm.sample_prior_predictive()
```

The model samples fine, but `sample_prior_predictive` produces an error.

```
Traceback (most recent call last):
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
AssertionError: Theano Assert failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samuelrobertmathias/PycharmProjects/ForgettingPitchPublic/_test.py", line 16, in <module>
    pm.sample_prior_predictive()
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/pymc3/sampling.py", line 1957, in sample_prior_predictive
    values = draw_values([model[name] for name in names], size=samples)
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 695, in draw_values
    value = _draw_value(param,
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 876, in _draw_value
    output = func(*input_vals)
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2182, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2223, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/theano/compile/function_module.py", line 914, in __call__
    gof.link.raise_with_op(
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Users/samuelrobertmathias/miniconda3/envs/ForgettingPitchPublic/lib/python3.8/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
AssertionError: Theano Assert failed!
Apply node that caused the error: Assert{msg='Theano Assert failed!'}(TensorConstant{0.0}, Elemwise{eq,no_inplace}.0)
Toposort index: 3
Inputs types: [TensorType(float64, scalar), TensorType(bool, scalar)]
Inputs shapes: [(), ()]
Inputs strides: [(), ()]
Inputs values: [array(0.), array(False)]
Outputs clients: [[Alloc(Assert{msg='Theano Assert failed!'}.0, TensorConstant{5}, Shape_i{1}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

What is really irritating about this bug is that it appears if there are any deterministics or observed stochastics that are connected to the variable using a dot product.

**Comment by junpenglao** [comment]
Thanks for reporting, can confirm on HEAD. However it is not immediate obvious to me where is wrong. any idea @lucianopaz ?

**Comment by lucianopaz** [comment]
I don't understand where the `assert` node is coming from. @sammosummo, could you please post the results from `theano.printing.debugprint(C)`?

**Comment by sammosummo** [comment]
How do I do that?

**Comment by lucianopaz** [comment]
Try running this

```python
import pymc3 as pm
import theano.tensor as tt
import theano


with pm.Model() as model:

    x = 8
    y = 6
    z = 5

    A = pm.MvNormal("A", mu=tt.zeros(y), cov=tt.eye(y), shape=(x, y))
    B = tt.zeros((z, x))
    C = tt.dot(B, A)  # this works fine
    C = pm.Deterministic("C", tt.dot(B, A))  # produces an error

    theano.printing.debugprint(C)
```

**Comment by sammosummo** [comment]
Sorry for the delay, here is the output:

```
Elemwise{identity} [id A] 'C'   
 |dot [id B] ''   
   |Alloc [id C] ''   
   | |TensorConstant{0.0} [id D]
   | |TensorConstant{5} [id E]
   | |TensorConstant{8} [id F]
   |A [id G]
```

**Comment by Spaak** [comment]
@sammosummo thanks again for the report. I just tested your simple example with pymc3 HEAD (7ff2f49) and theano-pymc HEAD (0d34af2) and the issue appears solved. Not sure whether it was a pymc or theano fix, but updating both at least should fix this for you (either the latest git dev copy or an upcoming new release). Feel free to reopen if the issue persists on your end.
