### ISSUE TITLE
Interpolated prior fails to generate values for sample_prior_predictive

### ISSUE THREAD

**Issue by hayesdavis** [pymc-devs/pymc#4121]
**Description**
Sampling prior predictive values with a prior using the Interpolated distribution fails due to a missing `point` kwarg in the random method.

**Example**
```python
import numpy as np
import scipy.stats as st
import pymc3 as pm

samples = st.norm.rvs(size=100, random_state=42)

with pm.Model():
    smin, smax = np.min(samples), np.max(samples)
    width = smax - smin
    x = np.linspace(smin, smax, 100)
    y = st.gaussian_kde(samples)(x)
    i = pm.Interpolated('i', x, y)
    trace = pm.sample()
    prior_pred = pm.sample_prior_predictive()

```

**Traceback**
```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...

Multiprocess sampling (4 chains in 4 jobs)
NUTS: [i]
Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 12 seconds. [8000/8000 00:03<00:00 Sampling 4 chains, 0 divergences]
The acceptance probability does not match the target. It is 0.6630224198635148, but should be close to 0.8. Try to increase the number of tuning steps.
The acceptance probability does not match the target. It is 0.6675947179160682, but should be close to 0.8. Try to increase the number of tuning steps.
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/Users/hayes/Projects/[redacted]/explore/.venv/lib/python3.8/site-packages/pymc3/sampling.py", line 1957, in sample_prior_predictive
    values = draw_values([model[name] for name in names], size=samples)
  File "/Users/hayes/Projects/[redacted]/explore/.venv/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 651, in draw_values
    value = _draw_value(next_,
  File "/Users/hayes/Projects/[redacted]/explore/.venv/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 821, in _draw_value
    return param.random(point=point, size=size)
  File "/Users/hayes/Projects/[redacted]/explore/.venv/lib/python3.8/site-packages/pymc3/model.py", line 78, in __call__
    return getattr(self.obj, self.method_name)(*args, **kwargs)
TypeError: random() got an unexpected keyword argument 'point'
```

**Please provide any additional information below.**
It seems pretty clear that [Interpolated.random](https://github.com/pymc-devs/pymc3/blob/67155fa4d000e73f99d761970ece73c2236a97d5/pymc3/distributions/continuous.py#L4102) hasn't been updated to support the point keyword argument.

I'm very new to pymc3 so I'm unsure if this is even a thing that I should be doing but given the fairly common example of bayesian updating [found here](https://docs.pymc.io/notebooks/updating_priors.html), it didn't seem unreasonable.

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version: 3.8.3
* Operating system: macOS Catalina 10.15.6
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
close by #4184
