### ISSUE TITLE
Switch between two multidimensional distributions

### ISSUE THREAD

**Issue by MrNeither** [pymc-devs/pymc#4131]
## Problem
Hello. I'm trying to make a switch between two multidimensional distributions, but I get an error. Could you explain what the problem might be?
**Please provide a minimal, self-contained, and reproducible example.**
```python
 with pm.Model() as model:
        window_features_len = 100
        mu = np.zeros(2)
        sigma = np.eye(2)
        mu_1 = pm.MvNormal('mu_1', mu, sigma, shape=(2, 2))
        mu_2 = pm.MvNormal('mu_2', mu, sigma, shape=(2, 2))
        tau = pm.DiscreteUniform("tau", lower=0, upper=window_features_len - 1)

        idx = np.arange(window_features_len)  # Index
        mu_ = pm.math.switch(tau > idx, mu_1, mu_2)
```

**Please provide the full traceback.**
```python
log_thunk_trace: There was a problem executing an Op.
Traceback (most recent call last):
  File "/home/MrNeither/PycharmProjects/change-detection/analysis.py", line 94, in model_run2d
    mu_ = pm.math.switch(tau > idx, mu_1, mu_2)
  File "/home/MrNeither/anaconda3/lib/python3.8/site-packages/theano/gof/op.py", line 674, in __call__
    required = thunk()
  File "/home/MrNeither/anaconda3/lib/python3.8/site-packages/theano/gof/op.py", line 862, in rval
    thunk()
  File "/home/MrNeither/anaconda3/lib/python3.8/site-packages/theano/gof/cc.py", line 1739, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "/home/MrNeither/anaconda3/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
ValueError: Input dimension mis-match. (input[0].shape[2] = 100, input[1].shape[2] = 2)

Process finished with exit code 1

```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version: python 3.8
* Operating system: Linux Ubuntu 18.04.5 LTS
* How did you install PyMC3: (conda/pip) pip, but on anaconda

**Comment by ckrapu** [comment]
This occurred because `pm.math.switch` requires its arguments to be broadcastable against each other. Since `mu_1` and `mu_2` had shape of `(2,2)`, neither dimension could be broadcasted against `tau>idx` which had shape of `(100,)`. You can fix this with the following:
```
    mu_ = pm.math.switch(tau > idx, mu_1[...,None], mu_2[...,None])
```

**Comment by MrNeither** [comment]
Thanks a lot!
