### ISSUE TITLE
import  pymc3 ocurrs an error 'Dataset' has no attribute 'unify_chunks'"

### ISSUE THREAD

**Issue by zh-12345** [pymc-devs/pymc#4175]
when i import  pymc3 ocurrs an error 'Dataset' has no attribute 'unify_chunks'"
i am looking forward your help and reply,thank you !

```python
[Your code here]
```

**Please provide the full traceback.**
```python
Traceback (most recent call last):
  File "E:/yanyanyanyan/knowledgegraph/BYESIAN_TEST/1013test.py", line 4, in <module>
    import pymc3 as pm
  File "D:\anadota\lib\site-packages\pymc3\__init__.py", line 41, in <module>
    from .distributions import *
  File "D:\anadota\lib\site-packages\pymc3\distributions\__init__.py", line 15, in <module>
    from . import timeseries
  File "D:\anadota\lib\site-packages\pymc3\distributions\timeseries.py", line 22, in <module>
    from pymc3.util import get_variable_name
  File "D:\anadota\lib\site-packages\pymc3\util.py", line 20, in <module>
    import arviz
  File "D:\anadota\lib\site-packages\arviz\__init__.py", line 16, in <module>
    from .data import *
  File "D:\anadota\lib\site-packages\arviz\data\__init__.py", line 3, in <module>
    from .converters import convert_to_dataset, convert_to_inference_data
  File "D:\anadota\lib\site-packages\arviz\data\converters.py", line 6, in <module>
    from .inference_data import InferenceData
  File "D:\anadota\lib\site-packages\arviz\data\inference_data.py", line 52, in <module>
    class InferenceData:
  File "D:\anadota\lib\site-packages\arviz\data\inference_data.py", line 859, in InferenceData
    unify_chunks = _extend_xr_method(xr.Dataset.unify_chunks)
AttributeError: type object 'Dataset' has no attribute 'unify_chunks'
```

when i only import arviz ,it occurred the same error  "File "D:\anadota\lib\site-packages\arviz\data\inference_data.py", line 859, in InferenceData
    unify_chunks = _extend_xr_method(xr.Dataset.unify_chunks)
AttributeError: type object 'Dataset' has no attribute 'unify_chunks'"

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version:  1.0.5
* Python Version:   3.7
* Operating system:  windows
* How did you install PyMC3: (conda/pip)    conda

**Comment by zh-12345** [comment]
i  have solved.
