### ISSUE TITLE
Data type incompatibility : int64 in output of Bernouilli distribution

### ISSUE THREAD

**Issue by Vaunorage** [pymc-devs/pymc#4198]
I recently tried to make a model with pymc3, however when I use the 

```
with pm.Model() as neural_network:
    t_input = pm.Data('t_input', X_train)
    t_f_output = pm.Data('t_f_output', Yf_train)
    t_cf_output = pm.Data('t_cf_output', Ycf_train)

    r_input = pm.Data('r_input', concate_input_train)
    r_output = pm.Data('r_output', T_train)

    # r
    weights_in_out = DenseLayer('w_in_out', shape=(concate_input_train.shape[-1], 1))

    # t
    sigma_1 = pm.Normal("sigma_out_1", 0.0, 200.0)
    sigma_2 = pm.Normal("sigma_out_2", 0.0, 200.0)

    phi_in_1 = DenseLayer('phi_in_1', shape=(X_train.shape[-1], n_phi_hidden))
    phi_1_2 = DenseLayer('phi_1_2', shape=(n_phi_hidden, n_phi_hidden))
    phi_2_out = DenseLayer('phi_out', shape=(n_phi_hidden, n_phi_out))

    h1_in_1 = DenseLayer('h1_in_1', shape=(n_phi_out, h_hidden))
    h1_out = DenseLayer('h1_out', shape=(h_hidden, 1))

    h2_in_1 = DenseLayer('h2_in_1', shape=(n_phi_out, h_hidden))
    h2_out = DenseLayer('h2_out', shape=(h_hidden, 1))

    phi_act_1 = pm.math.dot(t_input, phi_in_1)
    phi_act_2 = pm.math.dot(phi_act_1, phi_1_2)
    phi_act_out = pm.math.dot(phi_act_2, phi_2_out)

    act_out = pm.math.sigmoid(pm.math.dot(r_input, weights_in_out))
    out_r = pm.Bernoulli('out_r', act_out, observed=r_output, total_size=T_train.shape[0])
    out_r_diag = pm.math.dot(out_r, out_r.T)

    h1_select = pm.math.dot(out_r_diag, phi_act_out)
    h1_act_1 = pm.math.dot(h1_select, h1_in_1)
    h1_act_out = pm.math.dot(h1_act_1, h1_out)
    out_hf = pm.Normal('out_hf', mu=h1_act_out, sigma=sigma_1, observed=Yf_train, total_size=Yf_train.shape[0])

    h2_select = pm.math.dot(out_r_diag.T, phi_act_out)
    h2_act_1 = pm.math.dot(h2_select, h2_in_1)
    h2_act_out = pm.math.dot(h2_act_1, h1_out)
    out_hcf = pm.Normal('out_hcf', mu=h2_act_out, sigma=sigma_2, observed=Ycf_train, total_size=Ycf_train.shape[0])

from pymc3.theanof import set_tt_rng, MRG_RandomStreams

set_tt_rng(MRG_RandomStreams(42))

with neural_network:
    inference = pm.ADVI()
    approx = pm.fit(n=70000, method=inference)
```

**Traceback.**
```python
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_useless_fill,local_useless_alloc,local_subtensor_make_vector,local_useless_elemwise,local_useless_inc_subtensor,local_useless_slice,local_subtensor_of_alloc,local_useless_inc_subtensor_alloc,local_useless_rebroadcast,local_join_1,local_join_empty,local_join_make_vector,local_useless_switch,local_useless_tile,local_useless_split,local_useless_reshape,local_useless_elemwise_comparison,local_useless_reduce,local_view_op,local_merge_alloc,local_useless_topk)
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{int64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\opt.py", line 2074, in process_node
    remove=remove)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 569, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 518, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\fg.py", line 486, in replace
    ". The type of the replacement must be the same.", old, new)
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 1673548647176 Elemwise{Cast{int64}}.0
  Op Elemwise{Cast{int64}}(r_output)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  LocalOptGroup(local_useless_fill,local_useless_alloc,local_subtensor_make_vector,local_useless_elemwise,local_useless_inc_subtensor,local_useless_slice,local_subtensor_of_alloc,local_useless_inc_subtensor_alloc,local_useless_rebroadcast,local_join_1,local_join_empty,local_join_make_vector,local_useless_switch,local_useless_tile,local_useless_split,local_useless_reshape,local_useless_elemwise_comparison,local_useless_reduce,local_view_op,local_merge_alloc,local_useless_topk). The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(float64, matrix)> 'out_r'   
   |Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
     |r_output [id C] <TensorType(float64, matrix)>
  New Graph:
  Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
ERROR (theano.gof.opt): Optimization failure due to: local_view_op
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{int64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\opt.py", line 2074, in process_node
    remove=remove)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 569, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 518, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\fg.py", line 486, in replace
    ". The type of the replacement must be the same.", old, new)
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 1673548647176 Elemwise{Cast{int64}}.0
  Op Elemwise{Cast{int64}}(r_output)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  local_view_op. The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(float64, matrix)> 'out_r'   
   |Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
     |r_output [id C] <TensorType(float64, matrix)>
  New Graph:
  Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
ERROR (theano.gof.opt): Optimization failure due to: local_view_op
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{int64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\opt.py", line 2074, in process_node
    remove=remove)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 569, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 518, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\fg.py", line 486, in replace
    ". The type of the replacement must be the same.", old, new)
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 1673548647176 Elemwise{Cast{int64}}.0
  Op Elemwise{Cast{int64}}(r_output)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  local_view_op. The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(float64, matrix)> 'out_r'   
   |Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
     |r_output [id C] <TensorType(float64, matrix)>
  New Graph:
  Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
ERROR (theano.gof.opt): Optimization failure due to: local_view_op
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{int64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\opt.py", line 2074, in process_node
    remove=remove)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 569, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 518, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\fg.py", line 486, in replace
    ". The type of the replacement must be the same.", old, new)
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 1673548647176 Elemwise{Cast{int64}}.0
  Op Elemwise{Cast{int64}}(r_output)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  local_view_op. The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(float64, matrix)> 'out_r'   
   |Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
     |r_output [id C] <TensorType(float64, matrix)>
  New Graph:
  Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
ERROR (theano.gof.opt): Optimization failure due to: local_view_op
ERROR (theano.gof.opt): node: ViewOp(Elemwise{Cast{int64}}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\opt.py", line 2074, in process_node
    remove=remove)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 569, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\toolbox.py", line 518, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\fg.py", line 486, in replace
    ". The type of the replacement must be the same.", old, new)
theano.gof.toolbox.BadOptimization: BadOptimization Error 
  Variable: id 1673548647176 Elemwise{Cast{int64}}.0
  Op Elemwise{Cast{int64}}(r_output)
  Value Type: <class 'NoneType'>
  Old Value:  None
  New Value:  None
  Reason:  local_view_op. The type of the replacement must be the same.
  Old Graph:
  ViewOp [id A] <TensorType(float64, matrix)> 'out_r'   
   |Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
     |r_output [id C] <TensorType(float64, matrix)>
  New Graph:
  Elemwise{Cast{int64}} [id B] <TensorType(int64, matrix)> ''   
Hint: relax the tolerance by setting tensor.cmp_sloppy=1
  or even tensor.cmp_sloppy=2 for less-strict comparison
█Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
NotImplementedError: type(x) is not double or float
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-5ac61fb38272>", line 7, in <module>
    approx = pm.fit(n=70000, method=inference)
  File "C:\ProgramData\miniconda\lib\site-packages\pymc3\variational\inference.py", line 840, in fit
    return inference.fit(n, **kwargs)
  File "C:\ProgramData\miniconda\lib\site-packages\pymc3\variational\inference.py", line 151, in fit
    state = self._iterate_with_loss(0, n, step_func, progress, callbacks)
  File "C:\ProgramData\miniconda\lib\site-packages\pymc3\variational\inference.py", line 212, in _iterate_with_loss
    e = step_func()
  File "C:\ProgramData\miniconda\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\miniconda\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\miniconda\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\miniconda\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
NotImplementedError: type(x) is not double or float
Apply node that caused the error: Gemm{inplace}(Dot22.0, TensorConstant{1.0}, Dot22.0, Dot22.0, TensorConstant{1.0})
Toposort index: 494
Inputs types: [TensorType(float64, matrix), TensorType(float64, scalar), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, scalar)]
Inputs shapes: [(80, 4), (), (80, 80), (80, 4), ()]
Inputs strides: [(32, 8), (), (640, 8), (32, 8), ()]
Inputs values: ['not shown', array(1.), 'not shown', 'not shown', array(1.)]
Outputs clients: [[Dot22(Gemm{inplace}.0, phi_out_vi_replacement.T), Gemm{inplace}(Elemwise{Composite{Switch(i0, (i1 * i2 * i3 * i4), i5)}}[(0, 3)].0, TensorConstant{1.0}, Dot22.0, Gemm{inplace}.0, TensorConstant{1.0})]]
HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version: 3.7
* Operating system: windows 10
* How did you install PyMC3: (conda/pip) pip install pymc3

**Comment by ricardoV94** [comment]
Closing due to inactivity
