### ISSUE TITLE
Fix string representation for Bounded distributions

### ISSUE THREAD

**Issue by KoljaBauer** [pymc-devs/pymc#4216]
## Description of your problem

I am trying to render a pym3 model as a graph. Calling `pymc3.model_to_graphviz(model)` with a model that contains Bounded variables (variables with a distribution wrapped by a bounded distribution) leads to an error:

```python
import pymc3

with pymc3.Model(name="test") as model:
        var = pymc3.Bound(pymc3.Normal, lower=1)('test_var', mu=1, sigma=1)
        img = pymc3.model_to_graphviz(model)
```

**Please provide the full traceback.**
```python
Traceback (most recent call last):
  File "./replicate_bug.py", line 13, in <module>
    test_graphviz()
  File "./replicate_bug.py", line 9, in test_graphviz
    img = pymc3.model_to_graphviz(model)
  File "/home/new_env/lib/python3.8/site-packages/pymc3/model_graph.py", line 233, in model_to_graphviz
    return ModelGraph(model).make_graph()
  File "/home/new_env/lib/python3.8/site-packages/pymc3/model_graph.py", line 213, in make_graph
    self._make_node(var_name, graph)
  File "/home/new_env/lib/python3.8/site-packages/pymc3/model_graph.py", line 149, in _make_node
    label = str(v).replace(" ~ ", "\n~\n")
  File "/home/new_env/lib/python3.8/site-packages/pymc3/model.py", line 83, in __str__
    return self._str_repr(formatting="plain", **kwargs)
  File "/home/new_env/lib/python3.8/site-packages/pymc3/model.py", line 77, in _str_repr
    return self.distribution._str_repr(name=name, dist=dist, formatting=formatting)
  File "/home/new_env/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 176, in _str_repr
    param_values = [
  File "/home/new_env/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 177, in <listcomp>
    get_repr_for_variable(getattr(dist, x), formatting=formatting) for x in param_names
AttributeError: '_ContinuousBounded' object has no attribute 'distribution'
```

Graphviz was installed by executing the following steps:
```
git clone https://gitlab.com/graphviz/graphviz.git
cd graphviz
./autogen.sh
./configure
make
make install
cd ..
pip install graphviz
```

## Proposed solution:
In method `_str_repr` of `distribution.py`, replace 
```
param_values = [
            get_repr_for_variable(getattr(dist, x), formatting=formatting) for x in param_names
        ]
```
with
```
param_values = []
        for x in param_names:
            if hasattr(dist, x):
                if getattr(dist, x) is None:
                    param_values.append("")
                else:
                    param_values.append(get_repr_for_variable(getattr(dist, x), formatting=formatting))
            else:
                param_values.append("")
```
and additionally:
In method `_distr_name_for_repr` of `distribution.py`, add:
```
#If the distribution is Bounded, print the wrapped distribution
if(self.__class__.__name__ == "_ContinuousBounded"):
    return "Bound " + self._wrapped.__class__.__name__
```
 

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: Theano-PyMC==1.0.10
* Python Version: Python 3.8.6
* Operating system: Fedora
* How did you install PyMC3: pip install git+https://github.com/pymc-devs/pymc3

**Comment by twiecki** [comment]
Thanks for the report and proposed fix @KoljaBauer, want to do a PR?

**Comment by AlexAndorra** [comment]
As Thomas said, thanks for reporting and proposing a fix @KoljaBauer !
I'm also pinging @Spaak here, as he did a pretty in-depth PR about `str` representations recently

**Comment by Spaak** [comment]
I third the thanks for the report and proposing a fix @KoljaBauer! :)

As for the fix, I think it's probably better to fix this at the level of `_Bounded` (overriding), rather than change the generic parent code in `Distribution` to account for this special case. (I'd be happy to fix it, or let me know if you want to have a go at it yourself @KoljaBauer).

**Comment by KoljaBauer** [comment]
@Spaak Thank you for addressing it so quick!
