### ISSUE TITLE
Type errors in float32 tests on MacOS

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#4274]
## Description of your problem

Test failures on MacOS on `float32` type tests.  These may be issues in Theano compilation.

Originally reported in #3811

**Please provide a minimal, self-contained, and reproducible example.**
``` bash
pytest pymc3/tests/test_types.py::TestType::test_float32
```

and 

``` bash
pytest pymc3/tests/test_types.py::TestType::test_float32_MLDA
```

## Full backtraces

`test_float32`:
```
Traceback (most recent call last):
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 11 (NPY_FLOAT32) got 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rpg/src/pymc3/pymc3/parallel_sampling.py", line 135, in run
    self._start_loop()
  File "/Users/rpg/src/pymc3/pymc3/parallel_sampling.py", line 189, in _start_loop
    point, stats = self._compute_point()
  File "/Users/rpg/src/pymc3/pymc3/parallel_sampling.py", line 214, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "/Users/rpg/src/pymc3/pymc3/step_methods/arraystep.py", line 190, in step
    apoint, stats = self.astep(self.bij.map(point))
  File "/Users/rpg/src/pymc3/pymc3/step_methods/metropolis.py", line 216, in astep
    accept = self.delta_logp(q, q0)
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 989, in __call__
    storage_map=getattr(self.fn, "storage_map", None),
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/gof/link.py", line 343, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 11 (NPY_FLOAT32) got 12
Apply node that caused the error: Elemwise{Composite{(i0 * (i1 + (-sqr(i2))))}}(TensorConstant{0.5}, TensorConstant{-1.8378772}, InplaceDimShuffle{}.0)
Toposort index: 11
Inputs types: [TensorType(float32, scalar), TensorType(float32, scalar), TensorType(float32, scalar)]
Inputs shapes: [(), (), ()]
Inputs strides: [(), (), ()]
Inputs values: [array(0.5, dtype=float32), array(-1.8378772, dtype=float32), array(2.11641728)]
Outputs clients: [[MakeVector{dtype='float32'}(__logp_x, __logp_obs)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
"""

The above exception was the direct cause of the following exception:
pymc3.parallel_sampling.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 11 (NPY_FLOAT32) got 12
```

`test_float32_MLDA`:

```
pymc3.parallel_sampling.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 11 (NPY_FLOAT32) got 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rpg/src/pymc3/pymc3/parallel_sampling.py", line 135, in run
    self._start_loop()
  File "/Users/rpg/src/pymc3/pymc3/parallel_sampling.py", line 189, in _start_loop
    point, stats = self._compute_point()
  File "/Users/rpg/src/pymc3/pymc3/parallel_sampling.py", line 214, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "/Users/rpg/src/pymc3/pymc3/step_methods/arraystep.py", line 190, in step
    apoint, stats = self.astep(self.bij.map(point))
  File "/Users/rpg/src/pymc3/pymc3/step_methods/mlda.py", line 733, in astep
    q = self.bij.map(self.proposal_dist(q0_dict))
  File "/Users/rpg/src/pymc3/pymc3/step_methods/mlda.py", line 1104, in __call__
    tune=self.subsampling_rate,
  File "/Users/rpg/src/pymc3/pymc3/step_methods/mlda.py", line 1043, in subsample
    for it, (trace, _) in enumerate(sampling):
  File "/Users/rpg/src/pymc3/pymc3/sampling.py", line 1007, in _iter_sample
    point, stats = step.step(point)
  File "/Users/rpg/src/pymc3/pymc3/step_methods/arraystep.py", line 190, in step
    apoint, stats = self.astep(self.bij.map(point))
  File "/Users/rpg/src/pymc3/pymc3/step_methods/mlda.py", line 153, in astep
    q_new, stats = super().astep(q0)
  File "/Users/rpg/src/pymc3/pymc3/step_methods/metropolis.py", line 836, in astep
    accept = self.delta_logp(q, q0)
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 989, in __call__
    storage_map=getattr(self.fn, "storage_map", None),
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/gof/link.py", line 343, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.7/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
TypeError: expected type_num 11 (NPY_FLOAT32) got 12
Apply node that caused the error: Elemwise{Composite{(i0 * (i1 + (-sqr(i2))))}}(TensorConstant{0.5}, TensorConstant{-1.8378772}, InplaceDimShuffle{}.0)
Toposort index: 11
Inputs types: [TensorType(float32, scalar), TensorType(float32, scalar), TensorType(float32, scalar)]
Inputs shapes: [(), (), ()]
Inputs strides: [(), (), ()]
Inputs values: [array(0.5, dtype=float32), array(-1.8378772, dtype=float32), array(0.99960138)]
Outputs clients: [[MakeVector{dtype='float32'}(__logp_x, __logp_obs)]]
```

## Versions and main components

* PyMC3 Version: edbafaad72edfb04901417e8dd477471c516182d
* Theano Version: theano-pymc==1.0.11 on  and python 3.7.7
* Python Version: 3.7.7
* Operating system: MacOS 10.15.7
* How did you install PyMC3: `pip install -e .`

More information to follow...

**Comment by rpgoldman** [comment]
Would like to collect information about Theano settings but ... the Theano docs are gone, AFAICT.

**Comment by Spaak** [comment]
Do we know whether this is a regression w.r.t. 3.9.3? If so, it would be good to get it fixed for 3.10, otherwise I wouldn't block on it.

**Comment by MarcoGorelli** [comment]
> Do we know whether this is a regression w.r.t. 3.9.3? If so, it would be good to get it fixed for 3.10, otherwise I wouldn't block on it.

The original issue (#3811) dates back to February, so I guess it's not a regression (but I've not checked)

**Comment by rpgoldman** [comment]
I'm not at all sure that #3811 refers to the same issues causing test failures. In fact, I tend to doubt it. If I have time this weekend, I will checkout an old copy of PyMC3 and see if this issue arises there.

**Comment by rpgoldman** [comment]
I just tested on v3.9.3, and I see the same error. So this is not a blocker for 3.10 release.

**Comment by rpgoldman** [comment]
When I look at `theano.config` I see this:
```
cxx (<class 'str'>)
    Doc:  The C++ compiler to use. Currently only g++ is supported, but supporting additional compilers should not be too difficult. If it is empty, no C++ code is compiled.
    Value:  /usr/bin/clang++
```

So ... that looks like either (a) the docstring is out-of-date or (b) I'm using the wrong compiler, and should be using the GNU C++ compiler (in my case from brew).

**Comment by rpgoldman** [comment]
I installed using the Conda environment (`pymc3-dev-py38`), and that made things generally work, but the `float32` failures above persist.

**Comment by rpgoldman** [comment]
Tested with PyMC3 on `master` and with Theano-PyMC v. 1.1.0 and these tests still fail.

**Comment by ricardoV94** [comment]
Closing tentatively as it may be stale
