### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by GISerWang** [pymc-devs/pymc#4304]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
ImportError: DLL load failed: 找不到指定的模块。

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
```

**Please provide the full traceback.**
```python
import pymc3 as pm
```
**Please provide any additional information below.**
Traceback (most recent call last):
  File "C:/Users/wpx/PycharmProjects/untitled1/1.one.py", line 4, in <module>
    import pymc3 as pm
  File "D:\Users\wpx\Anaconda3\lib\site-packages\pymc3\__init__.py", line 41, in <module>
    from .distributions import *
  File "D:\Users\wpx\Anaconda3\lib\site-packages\pymc3\distributions\__init__.py", line 19, in <module>
    from .posterior_predictive import fast_sample_posterior_predictive
  File "D:\Users\wpx\Anaconda3\lib\site-packages\pymc3\distributions\posterior_predictive.py", line 28, in <module>
    from ..backends.base import MultiTrace
  File "D:\Users\wpx\Anaconda3\lib\site-packages\pymc3\backends\__init__.py", line 137, in <module>
    from ..backends.hdf5 import HDF5
  File "D:\Users\wpx\Anaconda3\lib\site-packages\pymc3\backends\hdf5.py", line 16, in <module>
    import h5py
  File "D:\Users\wpx\Anaconda3\lib\site-packages\h5py\__init__.py", line 26, in <module>
    from . import _errors
ImportError: DLL load failed: 找不到指定的模块。

## Versions and main components

* PyMC3 Version:3.9.3
* Theano Version: 1.0.5
* Python Version: 3.6 
* Operating system:Win10 x64
* How did you install PyMC3: (conda/pip)  pip

**Comment by michaelosthege** [comment]
This kind of error is typical for a broken environment or activation context.

If you're using VS Code to run the script, make sure to switch from PowerShell to `cmd`-mode in the dropdown at the top-right of the terminal view.

If the above did not help, I recommend to create a fresh conda environment instead of using the Anaconda distribution. You can use the commands from this gist: https://gist.github.com/michaelosthege/b95d57ae8817eb1cfd19aa30beac2da6

**Comment by michaelosthege** [comment]
Closing this because it seems to be unrelated to PyMC3. Feel free to reopen if you find that it is..
