### ISSUE TITLE
SMC-ABC update_weights_beta unstable with small epsilon

### ISSUE THREAD

**Issue by basnijholt** [pymc-devs/pymc#4369]
## Description of your problem

When using SMC-ABC (code below) and a small epsilon in the `Simulator` the algorithm that sets `SMC.weights` (`SMC.update_weights_beta`) becomes unstable.

Using the interactive debugger after the traceback pasted below:
```
ipdb> self.weights.sum()
1.0000004109817149
```

I have opened a PR with a suggested solution https://github.com/pymc-devs/pymc3/pull/4370.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import pymc3 as pm

def f(a, b):
    x_vec = np.linspace(-2, 2, 100)
    return a + b * x_vec


x_vec = np.linspace(-2, 2, 100)
np.random.seed(0)
y = f(-1, 2) + 1e-9 * np.random.normal(size=len(x_vec))

with pm.Model() as model:
    a = pm.Uniform("a", -5, 5)
    b = pm.Uniform("b", -5, 5)
    pm.Simulator(
        "simulation",
        f,
        params=(a, b),
        epsilon=1e-09,
        observed=y,
    )
    trace, sim_data = pm.sample_smc(
        chains=5,
        draws=200,
        kernel="ABC",
        parallel=True,
        save_sim_data=True,
    )
```

**Please provide the full traceback.**
```python
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gscratch/home/a-banijh/miniconda3/envs/split_cv_mod/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/gscratch/home/a-banijh/miniconda3/envs/split_cv_mod/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/gscratch/home/a-banijh/miniconda3/envs/split_cv_mod/lib/python3.8/site-packages/pymc3/smc/sample_smc.py", line 270, in sample_smc_int
    smc.resample()
  File "/gscratch/home/a-banijh/miniconda3/envs/split_cv_mod/lib/python3.8/site-packages/pymc3/smc/smc.py", line 183, in resample
    resampling_indexes = np.random.choice(
  File "mtrand.pyx", line 932, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-43-6c41818b81f9> in <module>
     21         observed=y,
     22     )
---> 23     trace, sim_data = pm.sample_smc(
     24         chains=5,
     25         draws=200,

~/miniconda3/envs/split_cv_mod/lib/python3.8/site-packages/pymc3/smc/sample_smc.py in sample_smc(draws, kernel, n_steps, start, tune_steps, p_acc_rate, threshold, save_sim_data, save_log_pseudolikelihood, model, random_seed, parallel, chains, cores)
    189         loggers = [_log] + [None] * (chains - 1)
    190         pool = mp.Pool(cores)
--> 191         results = pool.starmap(
    192             sample_smc_int, [(*params, random_seed[i], i, loggers[i]) for i in range(chains)]
    193         )

~/miniconda3/envs/split_cv_mod/lib/python3.8/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    370         `func` and (a, b) becomes func(a, b).
    371         '''
--> 372         return self._map_async(func, iterable, starmapstar, chunksize).get()
    373 
    374     def starmap_async(self, func, iterable, chunksize=None, callback=None,

~/miniconda3/envs/split_cv_mod/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

~/miniconda3/envs/split_cv_mod/lib/python3.8/multiprocessing/pool.py in worker()
    123         job, i, func, args, kwds = task
    124         try:
--> 125             result = (True, func(*args, **kwds))
    126         except Exception as e:
    127             if wrap_exception and func is not _helper_reraises_exception:

~/miniconda3/envs/split_cv_mod/lib/python3.8/multiprocessing/pool.py in starmapstar()
     49 
     50 def starmapstar(args):
---> 51     return list(itertools.starmap(args[0], args[1]))
     52 
     53 #

~/miniconda3/envs/split_cv_mod/lib/python3.8/site-packages/pymc3/smc/sample_smc.py in sample_smc_int()
    268             _log.info(f"Stage: {stage:3d} Beta: {smc.beta:.3f}")
    269         smc.update_proposal()
--> 270         smc.resample()
    271         smc.mutate()
    272         smc.tune()

~/miniconda3/envs/split_cv_mod/lib/python3.8/site-packages/pymc3/smc/smc.py in resample()
    181     def resample(self):
    182         """Resample particles based on importance weights."""
--> 183         resampling_indexes = np.random.choice(
    184             np.arange(self.draws), size=self.draws, p=self.weights
    185         )

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

ValueError: probabilities do not sum to 1

```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: '3.10.0'
* Theano Version: '1.0.12'
* Python Version: 3.8.6
* Operating system: CentOS
* How did you install PyMC3: conda

Tagging @aloctavodia because he wrote most of the code.

**Comment by aloctavodia** [comment]
Hi @basnijholt,soory again for the delay I went to vacations and get completely disconnected from PyMC, haha.

I know this in an example with the specific purpose of making SMC fails, but just in case you or others might find it useful I want to mention than the value of epsilon you are using is too low, in my experience setting epsilon requires some problem specific tuning but in general you can use the scale of the data as reference. To find a working value of epsilon you can try first with the standard deviation of the data. This is most likely a too large epsilon, but can be useful at the beginning of the modeling effort as this will provide a very crude and relative quick answer, so you can maybe fix modeling or coding error faster. Then you can try with lower values.  Like one half the standard deviation of even 1/10 could work well. Then based on your knowledge of the problem diagnostics like rank_plots and the cost of the computation you can settle of a value of epsilon that works for you.
