### ISSUE TITLE
GCC error on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [pymc-devs/pymc#4543]
This example:
```
mport warnings

import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pymc3 as pm
import theano.tensor as tt

warnings.simplefilter(action="ignore", category=FutureWarning)


az.style.use("arviz-darkgrid")
print(f"Running on PyMC3 v{pm.__version__}")
print(f"Running on ArviZ v{az.__version__}")

with pm.Model() as model:
    # Model definition
    pass

with pm.Model() as model:
    mu = pm.Normal("mu", mu=0, sigma=1)
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))

print(model.basic_RVs)
```

fails with g++10 as Theano compiler:
```
$ python3.7 ex.py 
Running on PyMC3 v3.11.2
Running on ArviZ v0.11.2

You can find the C code in this temporary file: /tmp/theano_compilation_error_n1ei668g
library ine is not found.
Traceback (most recent call last):
  File "ex.py", line 22, in <module>
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))
  File "/usr/local/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 122, in __new__
    return model.Var(name, dist, data, total_size, dims=dims)
  File "/usr/local/lib/python3.7/site-packages/pymc3/model.py", line 1182, in Var
    model=self,
  File "/usr/local/lib/python3.7/site-packages/pymc3/model.py", line 1828, in __init__
    self.logp_elemwiset = distribution.logp(data)
  File "/usr/local/lib/python3.7/site-packages/pymc3/distributions/continuous.py", line 535, in logp
    return bound((-tau * (value - mu) ** 2 + tt.log(tau / np.pi / 2.0)) / 2.0, sigma > 0)
  File "/usr/local/lib/python3.7/site-packages/theano/tensor/var.py", line 120, in __sub__
    return theano.tensor.basic.sub(self, other)
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 253, in __call__
    compute_test_value(node)
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 126, in compute_test_value
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 634, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 601, in make_c_thunk
    input_storage=node_input_storage, output_storage=node_output_storage
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1204, in make_thunk
    input_storage, output_storage, storage_map
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1142, in __compile__
    storage_map,
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1634, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/cmodule.py", line 1191, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1550, in compile_cmodule
    preargs=preargs,
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/cmodule.py", line 2547, in compile_str
    f"Compilation failed (return status={status}): {compile_stderr}"
Exception: ("Compilation failed (return status=1): /usr/home/yuri/.theano/compiledir_FreeBSD-12.2-STABLE-amd64-64bit-ELF-amd64-3.7.9-64/tmpfqn5za4d/mod.cpp: In member function 'int {anonymous}::__struct_compiled_op_m0e9615f803ec8c44c2a79c8c9c2edf7a4b7a75d590486f4c4d0461a990e698bc::run()':. /usr/home/yuri/.theano/compiledir_FreeBSD-12.2-STABLE-amd64-64bit-ELF-amd64-3.7.9-64/tmpfqn5za4d/mod.cpp:459:60: error: expected primary-expression before '{' token.   459 |                             #pragma omp parallel for if(n>={int(config.openmp_elemwise_minsize)}).       |                                                            ^. At global scope:. cc1plus: note: unrecognized command-line option '-Wno-c++11-narrowing' may have been intended to silence earlier diagnostics. ", 'FunctionGraph(Elemwise{sub,no_inplace}(TensorConstant{[-0.712547...60759815]}, <TensorType(float64, (True,))>))')
```

and it also fails with clang-10 as Theano compiler:
```$ python3.7 ex.py 
Running on PyMC3 v3.11.2
Running on ArviZ v0.11.2
WARNING (theano.link.c.cmodule): Your Theano flag `cxx` seems not to be the g++ compiler. So we disable the compiler optimization specific to g++ that tell to compile for a specific CPU. At worst, this could cause slow down.
         You can add those parameters to the compiler yourself via the Theano flag `gcc__cxxflags`.
WARNING (theano.link.c.cmodule): Your Theano flag `cxx` seems not to be the g++ compiler. So we disable the compiler optimization specific to g++ that tell to compile for a specific CPU. At worst, this could cause slow down.
         You can add those parameters to the compiler yourself via the Theano flag `gcc__cxxflags`.

You can find the C code in this temporary file: /tmp/theano_compilation_error_fhp2ihwt
Traceback (most recent call last):
  File "ex.py", line 22, in <module>
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))
  File "/usr/local/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 122, in __new__
    return model.Var(name, dist, data, total_size, dims=dims)
  File "/usr/local/lib/python3.7/site-packages/pymc3/model.py", line 1182, in Var
    model=self,
  File "/usr/local/lib/python3.7/site-packages/pymc3/model.py", line 1828, in __init__
    self.logp_elemwiset = distribution.logp(data)
  File "/usr/local/lib/python3.7/site-packages/pymc3/distributions/continuous.py", line 535, in logp
    return bound((-tau * (value - mu) ** 2 + tt.log(tau / np.pi / 2.0)) / 2.0, sigma > 0)
  File "/usr/local/lib/python3.7/site-packages/theano/tensor/var.py", line 120, in __sub__
    return theano.tensor.basic.sub(self, other)
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 253, in __call__
    compute_test_value(node)
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 126, in compute_test_value
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 634, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/usr/local/lib/python3.7/site-packages/theano/graph/op.py", line 601, in make_c_thunk
    input_storage=node_input_storage, output_storage=node_output_storage
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1204, in make_thunk
    input_storage, output_storage, storage_map
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1142, in __compile__
    storage_map,
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1634, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/cmodule.py", line 1191, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/basic.py", line 1550, in compile_cmodule
    preargs=preargs,
  File "/usr/local/lib/python3.7/site-packages/theano/link/c/cmodule.py", line 2547, in compile_str
    f"Compilation failed (return status={status}): {compile_stderr}"
Exception: ("Compilation failed (return status=1): /usr/home/yuri/.theano/compiledir_FreeBSD-12.2-STABLE-amd64-64bit-ELF-amd64-3.7.9-64/tmp3px309w9/mod.cpp:459:65: error: use of undeclared identifier 'config'.                             #pragma omp parallel for if(n>={int(config.openmp_elemwise_minsize)}).                                                                 ^. 1 error generated.. ", 'FunctionGraph(Elemwise{sub,no_inplace}(TensorConstant{[ 4.727600..08059e-01]}, <TensorType(float64, (True,))>))')
```

Version: 3.11.2
OS: FreeBSD 12.2

**Comment by twiecki** [comment]
@yurivict I don't think this has anything to do with the model or guide but your installation. Do other models work fine? How did you install? Using conda?

**Comment by yurivict** [comment]
I install through the FreeBSD port.

**Comment by twiecki** [comment]
We strongly recommend installation through conda because of MKL, which I think could be the problem here.

**Comment by ricardoV94** [comment]
Closing due to inactivity
