### ISSUE TITLE
RecursionError when using Data with categorical data and GLM

### ISSUE THREAD

**Issue by muraiki** [pymc-devs/pymc#4669]
When using `pm.Data` as the source for GLM and where the predictor is categorical, constructing the model fails with: `patsy.PatsyError: Error evaluating factor: RecursionError: maximum recursion depth exceeded in comparison`

```python
import pandas as pd
import pymc3 as pm
import pymc3.glm as glm
import arviz as az

sourcedata = pd.DataFrame({
    'x': ['1', '7', '8'],
    'y': [10, 5, 2]
})

model = pm.Model()
ordered_levels = ['8', '7', '1']
with model:
    family = pm.glm.families.StudentT()
    
    data = pm.Data('data', sourcedata)
    
    glm.GLM.from_formula(
        'y ~ C(x, levels=ordered_levels)',
        data=data,
        family=family
    )
    
    trace = pm.sample(1000, cores=4, return_inferencedata=True, random_seed=42)
    ppc = pm.sample_posterior_predictive(trace, random_seed=42)
```

If I don't use `pm.Data`, everything works fine.

```python
import pandas as pd
import pymc3 as pm
import pymc3.glm as glm
import arviz as az

sourcedata = pd.DataFrame({
    'x': ['1', '7', '8'],
    'y': [10, 5, 2]
})

model = pm.Model()
ordered_levels = ['8', '7', '1']
with model:
    family = pm.glm.families.StudentT()
    
    glm.GLM.from_formula(
        'y ~ C(x, levels=ordered_levels)',
        data=sourcedata,
        family=family
    )
    
    trace = pm.sample(1000, cores=4, return_inferencedata=True, random_seed=42)
    ppc = pm.sample_posterior_predictive(trace, random_seed=42)
```

## Traceback:
```python
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/compat.py", line 36, in call_and_wrap_exc
    return f(*args, **kwargs)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 166, in eval
    + self._namespaces))
  File "<string>", line 1, in <module>
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 481, in __getitem__
    if includes_bool(arg):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  [Previous line repeated 9930 more times]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 445, in includes_bool
    if not isinstance(args_el, theano.tensor.Variable) and isinstance(
  File "/Users/censored/.pyenv/versions/3.7.10/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-c70e18feef8e>", line 21, in <module>
    family=family
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/pymc3/glm/linear.py", line 222, in from_formula
    y, x = patsy.dmatrices(formula, data, eval_env=eval_env)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/highlevel.py", line 310, in dmatrices
    NA_action, return_type)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/highlevel.py", line 165, in _do_highlevel_design
    NA_action)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/highlevel.py", line 70, in _try_incr_builders
    NA_action)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/build.py", line 696, in design_matrix_builders
    NA_action)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/build.py", line 443, in _examine_factor_types
    value = factor.eval(factor_states[factor], data)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 566, in eval
    data)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 551, in _eval
    inner_namespace=inner_namespace)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/compat.py", line 43, in call_and_wrap_exc
    exec("raise new_exc from e")
  File "<string>", line 1, in <module>
patsy.PatsyError: Error evaluating factor: RecursionError: maximum recursion depth exceeded in comparison
    y ~ C(x, levels=ordered_levels)
    ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2061, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'PatsyError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3357, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3454, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2064, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1084, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 823, in format_records
    if r[0].f_locals.get("__tracebackhide__", 0) and i != lastrecord:
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 66, in get
    return self[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 481, in __getitem__
    if includes_bool(arg):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  [Previous line repeated 9938 more times]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 445, in includes_bool
    if not isinstance(args_el, theano.tensor.Variable) and isinstance(
  File "/Users/censored/.pyenv/versions/3.7.10/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2061, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'RecursionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3166, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3376, in run_ast_nodes
    self.showtraceback()
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2064, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1084, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 823, in format_records
    if r[0].f_locals.get("__tracebackhide__", 0) and i != lastrecord:
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 66, in get
    return self[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 481, in __getitem__
    if includes_bool(arg):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  [Previous line repeated 9939 more times]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 445, in includes_bool
    if not isinstance(args_el, theano.tensor.Variable) and isinstance(
  File "/Users/censored/.pyenv/versions/3.7.10/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2061, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'RecursionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 538, in execute_request
    user_expressions, allow_stdin,
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2895, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2945, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2064, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1084, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/IPython/core/ultratb.py", line 823, in format_records
    if r[0].f_locals.get("__tracebackhide__", 0) and i != lastrecord:
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 66, in get
    return self[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/patsy/eval.py", line 48, in __getitem__
    return d[key]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 481, in __getitem__
    if includes_bool(arg):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 449, in includes_bool
    if includes_bool(el):
  [Previous line repeated 9943 more times]
  File "/Users/censored/.pyenv/versions/3.7.10/envs/bi_aa/lib/python3.7/site-packages/theano/tensor/var.py", line 445, in includes_bool
    if not isinstance(args_el, theano.tensor.Variable) and isinstance(
  File "/Users/censored/.pyenv/versions/3.7.10/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

## Versions and main components

* PyMC3 Version: 3.11.2
* Aesara Version: I'm not sure how to figure this out.
* Python Version: 3.7.10
* Operating system: macOS 10.15.7
* How did you install PyMC3: pip

**Comment by ferrine** [comment]
pm.Data converts everything to tensor. There is no more dataframe structure.

**Comment by twiecki** [comment]
As discussed in #4680 and #4681 we will remove the glm submodule so won't fix that here. @muraiki can you use bambi instead?
