### ISSUE TITLE
Alert about error

### ISSUE THREAD

**Issue by sensiang705** [pymc-devs/pymc#4735]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
ImportError: cannot import name 'sigmoid' from 'aesara.tensor.nnet' (/root/tutorial-env/lib/python3.8/site-packages/aesara/tensor/nnet/__init__.py)
```

**Please provide the full traceback.**
```python
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/__init__.py", line 41, in <module>
    from pymc3 import gp, ode, sampling
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/gp/__init__.py", line 16, in <module>
    from pymc3.gp.gp import TP, Latent, LatentKron, Marginal, MarginalKron, MarginalSparse
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/gp/gp.py", line 25, in <module>
    from pymc3.distributions import draw_values
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/distributions/__init__.py", line 15, in <module>
    from pymc3.distributions import shape_utils, timeseries, transforms
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/distributions/timeseries.py", line 21, in <module>
    from pymc3.distributions import distribution, multivariate
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/distributions/distribution.py", line 47, in <module>
    from pymc3.model import (
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/model.py", line 43, in <module>
    from pymc3.math import flatten_list
  File "/root/tutorial-env/lib/python3.8/site-packages/pymc3/math.py", line 81, in <module>
    from aesara.tensor.nnet import sigmoid
ImportError: cannot import name 'sigmoid' from 'aesara.tensor.nnet' (/root/tutorial-env/lib/python3.8/site-packages/aesara/tensor/nnet/__init__.py)
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Aesara Version:
* Python Version: 3.8.5
* Operating system: Ubuntu
* How did you install PyMC3: (conda/pip) pip3 install git+https://github.com/pymc-devs/pymc3

**Comment by ricardoV94** [comment]
@sensiang705 Thanks for reporting. We are aware of that, our master branch will soon be updated and this will be fixed.
