### ISSUE TITLE
Installation Issue on macOS

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#4762]
## Description of your problem

After many attempts to reinstall PyMC3 in either Python3.8 or Python3.9, I always end up with the error below. I tried installing `v4`, but I still get the same error. I also tried following the steps outlined [here](https://stackoverflow.com/questions/63592445/ld-unsupported-tapi-file-type-tapi-tbd-in-yaml-file), but to no avail.

**Please provide the full traceback.**
```Python 3.8.10 (default, May 19 2021, 11:01:55) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc3 as pm

You can find the C code in this temporary file: /var/folders/wd/mvn7fc5s33s6zd4ttj9fvtd40000gn/T/theano_compilation_error_rgw49ia1
Traceback (most recent call last):
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/gof/lazylinker_c.py", line 76, in <module>
    raise ImportError(
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/gof/lazylinker_c.py", line 99, in <module>
    raise ImportError(
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/pymc3/__init__.py", line 38, in <module>
    __set_compiler_flags()
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/pymc3/__init__.py", line 33, in __set_compiler_flags
    import theano
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/gof/lazylinker_c.py", line 139, in <module>
    cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
  File "/Users/larryshamalama/anaconda3/envs/py38/lib/python3.8/site-packages/theano/gof/cmodule.py", line 2410, in compile_str
    raise Exception('Compilation failed (return status=%s): %s' %
Exception: Compilation failed (return status=1): ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64. clang-10: error: linker command failed with exit code 1 (use -v to see invocation). 
```

Any tips or pointers? Thanks ahead!

## Versions and main components

* PyMC3 Version: error persists after installing PyMC3 versions 3.9.3, 3.11.2 or 4.0
* Aesara/Theano Version: Don't know, couldn't import the library
* Python Version: 3.8.10
* Operating system: macOS Catalina (Version 10.15.7)
* How did you install PyMC3: conda

**Comment by larryshamalama** [comment]
Either solution ended up working after (re/un)installing many times:

- creating a conda virtual environment as detailed [here](https://github.com/pymc-devs/pymc3/blob/main/CONTRIBUTING.md);
- explicitly requesting `conda install pymc3=3.11.2` (although this didn't work at some point of my many trial and errors)...
