### ISSUE TITLE
Theano MissingInputError: using pymc3Sampler() but encountering "theano.graph.fg.MissingInputError"

### ISSUE THREAD

**Issue by german34** [pymc-devs/pymc#4789]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

Hello, I am trying to run a pymc3 sampler in the same manner provided by an example in the pypesto documentation. However, I am using a different 2d objective function and was wondering if I could get some help. I would greatly appreciate it! I will provide the details below but let me know if there are any additional details I needed.

I already had anaconda3 installed on my windows. So i just create a conda environment with python (I tried both python 3.7 & 3.8) and install the pymc3 and theano modules using pip3/pip. I've tried several different versions of both pymc3/theano and managed to import them successfully. I currently have the latest versions of pymc3 and theano installed (3.11.0 and 1.0.5 respectively).  The following are my installation steps:

conda create -n sample python=3.7 (or 3.8)
conda install mkl-service libpython m2w64-toolchain scipy
pip3 install pymc3 --no-cache
pip3 install pypesto --no-cache

I will attach my script as suggested
**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import scipy as sp
import scipy.optimize as so
from scipy.stats import multivariate_normal

import pypesto
import pypesto.sample as sample
from pypesto import Objective

A = np.array([[2.0, 0.0], [0.0, 1.0]])
b = np.array([2.0, 1.0])
x_init = np.array([3.4302, 2.915])
x_true = np.array([1.0, 1.0])
temp = lambda x: A.dot(x) - b
f = lambda x: .5 * np.linalg.norm(temp(x))
A_t = A.transpose()
K = np.dot(A_t, A)
df = lambda x: K.dot(x) - A_t.dot(b)


def obj1(x):
    # f_val = f(x)
    # grad = df(x)
    return (f(x), df(x))


objfun = lambda x: obj1(x)
dim_full = 2
lb = -10 * np.ones((dim_full, 1))
ub = 10 * np.ones((dim_full, 1))
x_names = ['x1', 'x2']
# step_fcn = pymc3.step_methods.hmc.hmc.HamiltonianMC
objective = pypesto.Objective(fun=objfun, grad=True, hess=False)
problem1 = pypesto.Problem(objective=objective, lb=lb, ub=ub, x_names=x_names)
sampler = sample.AdaptiveMetropolisSampler()
print('function val: ', objfun(x_init))
sampler2 = sample.Pymc3Sampler()
result2 = sample.sample(problem1, 100, sampler2, x0=np.array([0, 0]))
print('Done sampling!')
```

**Please provide the full traceback.**
```python
Sampling 1 chain for 1_000 tune and 100 draw iterations (1_000 + 100 draws total) took 7 seconds.
Traceback (most recent call last):
  File "samplingPymc3.py", line 70, in <module>
    result2 = sample.sample(problem1, 100, sampler2, x0=np.array([0,0]))
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\pypesto\sample\sample.py", line 68, in sample
    sampler.sample(n_samples=n_samples)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\pypesto\sample\pymc3.py", line 102, in sample
    **self.options)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\pymc3\sampling.py", line 637, in sample
    idata = arviz.from_pymc3(trace, **ikwargs)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\arviz\data\io_pymc3.py", line 559, in from_pymc3
    density_dist_obs=density_dist_obs,
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\arviz\data\io_pymc3.py", line 163, in __init__
    self.observations, self.multi_observations = self.find_observations()
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\arviz\data\io_pymc3.py", line 176, in find_observations
    multi_observations[key] = val.eval() if hasattr(val, "eval") else val
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\graph\basic.py", line 554, in eval
    self._fn_cache[inputs] = theano.function(inputs, self)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\compile\function\__init__.py", line 350, in function
    output_keys=output_keys,
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\compile\function\pfunc.py", line 532, in pfunc
    output_keys=output_keys,
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\compile\function\types.py", line 1978, in orig_function
    name=name,
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\compile\function\types.py", line 1584, in __init__
    fgraph, additional_outputs = std_fgraph(inputs, outputs, accept_inplace)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\compile\function\types.py", line 188, in std_fgraph
    fgraph = FunctionGraph(orig_inputs, orig_outputs, update_mapping=update_mapping)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\graph\fg.py", line 162, in __init__
    self.import_var(output, reason="init")
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\graph\fg.py", line 330, in import_var
    self.import_node(var.owner, reason=reason)
  File "C:\Users\germa\anaconda3\envs\sampling\lib\site-packages\theano\graph\fg.py", line 383, in import_node
    raise MissingInputError(error_msg, variable=var)
theano.graph.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute sigmoid(x2_interval__), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by ricardoV94** [comment]
Seems like this issue should be taken on the pypesto side. Not sure what it's doing under the hood, but it seems it's trying to use `x2` instead of the transformed variable `x2_interval__`.
