### ISSUE TITLE
Jax backend fails with more than 1 chain

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5000]
```python
with pm.Model() as m:
    x = pm.Normal('x')
    trace = pm.sampling_jax.sample_numpyro_nuts(chains=2)
```

<details>

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/link/utils.py in streamline_default_f()
    187                 ):
--> 188                     thunk()
    189                     for old_s in old_storage:

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/link/basic.py in thunk(fgraph, fgraph_jit, thunk_inputs, thunk_outputs)
    704         ):
--> 705             outputs = fgraph_jit(*[x[0] for x in thunk_inputs])
    706 

    [... skipping hidden 12 frame]

/tmp/tmp_0eu2f81 in jax_funcified_fgraph()
      2 def jax_funcified_fgraph():
----> 3     x, auto_566 = _sample(auto_564)
      4     return x, auto_566

~/pymc3/pymc3/sampling_jax.py in _sample(*inputs)
    149 
--> 150         pmap_numpyro.run(seed, init_params=current_state, extra_fields=("num_steps",))
    151         samples = pmap_numpyro.get_samples(group_by_chain=True)

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/infer/mcmc.py in run(self, rng_key, extra_fields, init_params, *args, **kwargs)
    571             elif self.chain_method == "parallel":
--> 572                 states, last_state = pmap(partial_map_fn)(map_args)
    573             else:

    [... skipping hidden 9 frame]

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/infer/mcmc.py in _single_chain_mcmc(self, init, args, kwargs, collect_fields)
    377         )
--> 378         collect_vals = fori_collect(
    379             lower_idx,

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/util.py in fori_collect(lower, upper, body_fun, init_val, transform, progbar, return_last_val, collection_size, thinning, **progbar_opts)
    336     elif num_chains > 1:
--> 337         progress_bar_fori_loop = progress_bar_factory(upper, num_chains)
    338         _body_fn_pbar = progress_bar_fori_loop(_body_fn)

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/util.py in progress_bar_factory(num_samples, num_chains)
    188     for chain in range(num_chains):
--> 189         tqdm_bars[chain] = tqdm_auto(range(num_samples), position=chain)
    190         tqdm_bars[chain].set_description("Compiling.. ", refresh=True)

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
    241         total = self.total * unit_scale if self.total else self.total
--> 242         self.container = self.status_printer(self.fp, total, self.desc, self.ncols)
    243         self.container.pbar = proxy(self)

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/tqdm/notebook.py in status_printer(_, total, desc, ncols)
    114         if IProgress is None:  # #187 #451 #558 #872
--> 115             raise ImportError(
    116                 "IProgress not found. Please update jupyter and ipywidgets."

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/tmp/ipykernel_535244/1704754477.py in <module>
      1 with pm.Model() as m:
      2     x = pm.Normal('x')
----> 3     trace = pm.sampling_jax.sample_numpyro_nuts(chains=2)

~/pymc3/pymc3/sampling_jax.py in sample_numpyro_nuts(draws, tune, chains, target_accept, random_seed, model, progress_bar, keep_untransformed)
    225     print("Sampling...", file=sys.stdout)
    226 
--> 227     *mcmc_samples, leapfrogs_taken = _sample()
    228     tic3 = pd.Timestamp.now()
    229 

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/compile/function/types.py in __call__(self, *args, **kwargs)
    974         try:
    975             outputs = (
--> 976                 self.fn()
    977                 if output_subset is None
    978                 else self.fn(output_subset=output_subset)

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/link/utils.py in streamline_default_f()
    190                         old_s[0] = None
    191             except Exception:
--> 192                 raise_with_op(fgraph, node, thunk)
    193 
    194         f = streamline_default_f

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/link/utils.py in raise_with_op(fgraph, node, thunk, exc_info, storage_map)
    524         # Some exception need extra parameter in inputs. So forget the
    525         # extra long error message in that case.
--> 526     raise exc_value.with_traceback(exc_trace)
    527 
    528 

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/link/utils.py in streamline_default_f()
    186                     thunks, order, post_thunk_old_storage
    187                 ):
--> 188                     thunk()
    189                     for old_s in old_storage:
    190                         old_s[0] = None

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/link/basic.py in thunk(fgraph, fgraph_jit, thunk_inputs, thunk_outputs)
    703             thunk_outputs=thunk_outputs,
    704         ):
--> 705             outputs = fgraph_jit(*[x[0] for x in thunk_inputs])
    706 
    707             for o_node, o_storage, o_val in zip(fgraph.outputs, thunk_outputs, outputs):

    [... skipping hidden 12 frame]

/tmp/tmp_0eu2f81 in jax_funcified_fgraph()
      1 
      2 def jax_funcified_fgraph():
----> 3     x, auto_566 = _sample(auto_564)
      4     return x, auto_566
      5 

~/pymc3/pymc3/sampling_jax.py in _sample(*inputs)
    148         )
    149 
--> 150         pmap_numpyro.run(seed, init_params=current_state, extra_fields=("num_steps",))
    151         samples = pmap_numpyro.get_samples(group_by_chain=True)
    152         leapfrogs_taken = pmap_numpyro.get_extra_fields(group_by_chain=True)["num_steps"]

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/infer/mcmc.py in run(self, rng_key, extra_fields, init_params, *args, **kwargs)
    570                 states, last_state = _laxmap(partial_map_fn, map_args)
    571             elif self.chain_method == "parallel":
--> 572                 states, last_state = pmap(partial_map_fn)(map_args)
    573             else:
    574                 assert self.chain_method == "vectorized"

    [... skipping hidden 9 frame]

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/infer/mcmc.py in _single_chain_mcmc(self, init, args, kwargs, collect_fields)
    376             else collection_size // self.thinning
    377         )
--> 378         collect_vals = fori_collect(
    379             lower_idx,
    380             upper_idx,

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/util.py in fori_collect(lower, upper, body_fun, init_val, transform, progbar, return_last_val, collection_size, thinning, **progbar_opts)
    335         )
    336     elif num_chains > 1:
--> 337         progress_bar_fori_loop = progress_bar_factory(upper, num_chains)
    338         _body_fn_pbar = progress_bar_fori_loop(_body_fn)
    339         last_val, collection, _, _ = fori_loop(

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/numpyro/util.py in progress_bar_factory(num_samples, num_chains)
    187     finished_chains = []
    188     for chain in range(num_chains):
--> 189         tqdm_bars[chain] = tqdm_auto(range(num_samples), position=chain)
    190         tqdm_bars[chain].set_description("Compiling.. ", refresh=True)
    191 

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
    240         unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
    241         total = self.total * unit_scale if self.total else self.total
--> 242         self.container = self.status_printer(self.fp, total, self.desc, self.ncols)
    243         self.container.pbar = proxy(self)
    244         self.displayed = False

~/miniconda3/envs/pymc4/lib/python3.9/site-packages/tqdm/notebook.py in status_printer(_, total, desc, ncols)
    113         # Prepare IPython progress bar
    114         if IProgress is None:  # #187 #451 #558 #872
--> 115             raise ImportError(
    116                 "IProgress not found. Please update jupyter and ipywidgets."
    117                 " See https://ipywidgets.readthedocs.io/en/stable"

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
Apply node that caused the error: NumPyroNUTS(TensorConstant{(2,) of 1...1991746926})
Toposort index: 0
Inputs types: [TensorType(float64, vector)]
Inputs shapes: []
Inputs strides: []
Inputs values: []
Outputs clients: [['output'], ['output']]

Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File "/home/ricardo/miniconda3/envs/pymc4/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3169, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/ricardo/miniconda3/envs/pymc4/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/ricardo/miniconda3/envs/pymc4/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_535244/1704754477.py", line 3, in <module>
    trace = pm.sampling_jax.sample_numpyro_nuts(chains=2)
  File "/home/ricardo/pymc3/pymc3/sampling_jax.py", line 182, in sample_numpyro_nuts
    numpyro_samples = NumPyroNUTS(
  File "/home/ricardo/miniconda3/envs/pymc4/lib/python3.9/site-packages/aesara/graph/op.py", line 271, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/ricardo/pymc3/pymc3/sampling_jax.py", line 66, in make_node
    outputs = [
  File "/home/ricardo/pymc3/pymc3/sampling_jax.py", line 67, in <listcomp>
    TensorType(v.dtype, self.samples_bcast + list(v.broadcastable))() for v in inputs

HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.
```

</details>

**Comment by ricardoV94** [comment]
Just needed to install ipywidgets xD
