### ISSUE TITLE
Theano Issue with NumPy 1.22.0

### ISSUE THREAD

**Issue by aliakbars** [pymc-devs/pymc#5310]
## BLAS issue with the latest release of NumPy

Had this issue directly after importing `pymc3` or `theano`.

<details><summary>Complete error traceback</summary>

```python
Traceback (most recent call last):
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/configparser.py", line 238, in fetch_val_for_key
    return self._theano_cfg.get(section, option)
  File "/Users/ali.septiandri/anaconda/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/ali.septiandri/anaconda/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/configparser.py", line 354, in __get__
    val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/configparser.py", line 242, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas__ldflags'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/pymc3/__init__.py", line 23, in <module>
    import theano
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/__init__.py", line 83, in <module>
    from theano import scalar, tensor
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/tensor/__init__.py", line 20, in <module>
    from theano.tensor import nnet  # used for softmax, sigmoid, etc.
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/tensor/nnet/__init__.py", line 3, in <module>
    from . import opt
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/tensor/nnet/opt.py", line 32, in <module>
    from theano.tensor.nnet.conv import ConvOp, conv2d
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/tensor/nnet/conv.py", line 20, in <module>
    from theano.tensor import blas
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/tensor/blas.py", line 163, in <module>
    from theano.tensor.blas_headers import blas_header_text, blas_header_version
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/tensor/blas_headers.py", line 1016, in <module>
    if not config.blas__ldflags:
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/configparser.py", line 358, in __get__
    val_str = self.default()
  File "/Users/ali.septiandri/anaconda/lib/python3.8/site-packages/theano/link/c/cmodule.py", line 2621, in default_blas_ldflags
    blas_info = numpy.distutils.__config__.blas_opt_info
AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'
```

</details>

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4
* Aesara/Theano Version: 1.1.2
* Python Version: 3.8
* Operating system: macOS Big Sur
* How did you install PyMC/PyMC3: conda

**Comment by ricardoV94** [comment]
Thanks for reporting. I think this was the issue we solved for Aesara in https://github.com/aesara-devs/aesara/pull/716

**Comment by treszkai** [comment]
@ricardoV94 Will this be fixed in the theano-pymc package as well, on which `pymc3<4` depends? Until it's released, is there a better workaround than a `numpy<1.22.0` constraint or requirement?

**Comment by michaelosthege** [comment]
Most likely there won't be another release of Theano-PyMC because we don't have enough manpower to keep maintaining it next to its successor.
For example, the conda feedstock is archived: https://github.com/conda-forge/theano-pymc-feedstock

Option A is a "fix" by pinning `numpy <1.22.0` for the upcoming `v3.11.5` (a PR to the `v3` branch, but it looks like noone opened one yet).

Option B is a "dirty hack" of monkey-patching that renamed `numpy.distutils.__config__.blas_opt_info` attribute before the first `import theano` line.
Possibly this could be done in the PyMC `__init__.py` if it's not too dirty.
If you want to try that workaround and report back if it does the trick, this could be a better alternative than option A.

**Comment by twiecki** [comment]
I think that hack would be fine.

**Comment by treszkai** [comment]
@michaelosthege Option B sounds great and works fine; see my implementation here: https://github.com/treszkai/best/blob/master/best/__init__.py#L6-L21

Same could be done in PyMC3.

**Comment by jkillian** [comment]
Thank you for this fix! Would it be possible for there to be a release of pymc v3 so make this change easier to pick up?
