### ISSUE TITLE
MissingInputError upon completion of `sample_numpyro_nuts`

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#5384]
## Description of your problem

Running a model with `sample_numpyro_nuts` samples to completion,  but then fails before returning the trace:

<details><summary>Complete error traceback</summary>

```python
MissingInputError                         Traceback (most recent call last)
<ipython-input-26-9a9cb2e2e693> in <module>()
      2 
      3     try:
----> 4         trace = sample_numpyro_nuts(1000, tune=2000, chains=1, target_accept=0.95)
      5     except NameError:
      6         trace = pm.sample(1000, tune=2000, cores=4, target_accept=0.95)

3 frames
/usr/local/lib/python3.7/dist-packages/pymc/sampling_jax.py in sample_numpyro_nuts(draws, tune, chains, target_accept, random_seed, model, var_names, progress_bar, keep_untransformed, chain_method)
    230     mcmc_samples = {}
    231     for v in vars_to_sample:
--> 232         fgraph = FunctionGraph(model.value_vars, [v], clone=False)
    233         optimize_graph(fgraph, include=["fast_run"], exclude=["cxx_only", "BlasOpt"])
    234         jax_fn = jax_funcify(fgraph)

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in __init__(self, inputs, outputs, features, clone, update_mapping, memo, copy_inputs, copy_orphans)
    165 
    166         for output in outputs:
--> 167             self.import_var(output, reason="init")
    168         for i, output in enumerate(outputs):
    169             self.clients[output].append(("output", i))

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in import_var(self, var, reason, import_missing)
    335         # Imports the owners of the variables
    336         if var.owner and var.owner not in self.apply_nodes:
--> 337             self.import_node(var.owner, reason=reason, import_missing=import_missing)
    338         elif (
    339             var.owner is None

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in import_node(self, apply_node, check, reason, import_missing)
    400                                 "for more information on this error."
    401                             )
--> 402                             raise MissingInputError(error_msg, variable=var)
    403 
    404         for node in new_nodes:

MissingInputError: Input 1 (x_std) of the graph (indices start from 0), used to compute Elemwise{mul,no_inplace}(InplaceDimShuffle{x}.0, x_std), was not provided and not given a value. Use the Aesara flag exception_verbosity='high', for more information on this error.
 
Backtrace when that variable is created:

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-6bb22e74edec>", line 9, in <module>
    x_std = pm.Data('x_std', (df_clean.stuff_plus.values - mean_stuff) / std_stuff, mutable=True)
  File "/usr/local/lib/python3.7/dist-packages/pymc/data.py", line 648, in Data
    x = aesara.shared(arr, name, **kwargs)
```

</details>

The error appears to be related to a covariate input:

```python
    x_std = pm.Data('x_std', (df_clean.stuff_plus.values - mean_stuff) / std_stuff, mutable=True)

    ...

    # Failure rate
    rate = pm.Deterministic('rate', lambda0[age_ind] * at.exp(beta*x_std))
```

I can't submit this model as a reproducible example due to its proprietary nature, but will try and generate a simpler reproducible example.

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b2
* Aesara/Theano Version: 2.3.4
* Python Version: 3.7.12
* Operating system: Colab (linux)
* How did you install PyMC/PyMC3: pip

**Comment by ricardoV94** [comment]
There is a bug I didn't have time to patch yet. Can you try to flip all the `clone=False` in the `FunctionGraph`s to `clone=True`, and see if that fixes it?

https://github.com/pymc-devs/pymc/blob/eb5177a5bb97a437870727906fc52acf29dc53d2/pymc/sampling_jax.py#L77
https://github.com/pymc-devs/pymc/blob/eb5177a5bb97a437870727906fc52acf29dc53d2/pymc/sampling_jax.py#L126
https://github.com/pymc-devs/pymc/blob/eb5177a5bb97a437870727906fc52acf29dc53d2/pymc/sampling_jax.py#L232

**Comment by fonnesbeck** [comment]
Unfortunately, this does not avoid the exception (note that `clone=True` now):

```python
---------------------------------------------------------------------------
MissingInputError                         Traceback (most recent call last)
<ipython-input-14-af7ddd597e4f> in <module>()
      2 
      3     try:
----> 4         trace = sample_numpyro_nuts(100, tune=200, chains=1, target_accept=0.95)
      5     except NameError:
      6         trace = pm.sample(1000, tune=2000, cores=4, target_accept=0.95)

3 frames
/usr/local/lib/python3.7/dist-packages/pymc/sampling_jax.py in sample_numpyro_nuts(draws, tune, chains, target_accept, random_seed, model, var_names, progress_bar, keep_untransformed, chain_method)
    230     mcmc_samples = {}
    231     for v in vars_to_sample:
--> 232         fgraph = FunctionGraph(model.value_vars, [v], clone=True)
    233         optimize_graph(fgraph, include=["fast_run"], exclude=["cxx_only", "BlasOpt"])
    234         jax_fn = jax_funcify(fgraph)

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in __init__(self, inputs, outputs, features, clone, update_mapping, memo, copy_inputs, copy_orphans)
    165 
    166         for output in outputs:
--> 167             self.import_var(output, reason="init")
    168         for i, output in enumerate(outputs):
    169             self.clients[output].append(("output", i))

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in import_var(self, var, reason, import_missing)
    335         # Imports the owners of the variables
    336         if var.owner and var.owner not in self.apply_nodes:
--> 337             self.import_node(var.owner, reason=reason, import_missing=import_missing)
    338         elif (
    339             var.owner is None

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in import_node(self, apply_node, check, reason, import_missing)
    400                                 "for more information on this error."
    401                             )
--> 402                             raise MissingInputError(error_msg, variable=var)
    403 
    404         for node in new_nodes:

MissingInputError: Input 1 (x_std) of the graph (indices start from 0), used to compute Elemwise{mul,no_inplace}(InplaceDimShuffle{x}.0, x_std), was not provided and not given a value. Use the Aesara flag exception_verbosity='high', for more information on this error.
 
Backtrace when that variable is created:

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-6bb22e74edec>", line 9, in <module>
    x_std = pm.Data('x_std', (df_clean.stuff_plus.values - mean_stuff) / std_stuff, mutable=True)
  File "/usr/local/lib/python3.7/dist-packages/pymc/data.py", line 648, in Data
    x = aesara.shared(arr, name, **kwargs)
```

**Comment by ricardoV94** [comment]
Can you try without the shared data?

**Comment by fonnesbeck** [comment]
It does not seem to matter; same error when I just use a numpy array.

**Comment by ricardoV94** [comment]
That concludes the easy ideas. Will need an example to be able to investigate

**Comment by fonnesbeck** [comment]
This was auto-closed by my PR; re-opening.

**Comment by ricardoV94** [comment]
@fonnesbeck did you find this problem again? If not, shall we close this issue?

**Comment by fonnesbeck** [comment]
I did not solve the issue, but moved on for expediency to get my model working. Feel free to close it, in any case.
