### ISSUE TITLE
Runtime Exception with NUTS

### ISSUE THREAD

**Issue by rusty-robin** [pymc-devs/pymc#5531]
## Description

Running NUTS on a regression model runs into RuntimeError during sampling

Is this expected? Is it due to some issue in my program or is this a bug? 

### Program:

```Python
import numpy as np
import pymc3 as pm
import theano

import numpy as np

np.random.seed(211944424)

data = dict()
data['x'] =theano.shared(np.array([[0.3127,0.7185,0.9494,0.5597,0.7358,0.1210,0.6191,0.5667,0.4503,0.5986],[0.0269,0.7518,0.9182,0.6499,0.4869,0.3073,0.8153,0.6999,0.0878,0.1670],[0.7447,0.5607,0.0876,0.7848,0.5527,0.6284,0.2125,0.6352,0.8686,0.7983],[0.1576,0.0972,0.6508,0.7716,0.6274,0.1363,0.7613,0.2494,0.3428,0.9261],[0.7717,0.4577,0.0172,0.8652,0.8721,0.1606,0.9938,0.0563,0.5016,0.5695],[0.1718,0.2058,0.9203,0.6626,0.5851,0.1158,0.4355,0.0705,0.7436,0.2993],[0.3664,0.5945,0.0679,0.5061,0.9727,0.2606,0.8866,0.7922,0.8299,0.4857],[0.1521,0.6116,0.8895,0.8145,0.8965,0.3734,0.5860,0.2676,0.9310,0.6909],[0.6845,0.6834,0.3010,0.4828,0.8348,0.3919,0.4748,0.6864,0.1595,0.2750],[0.1263,0.8909,0.6362,0.1842,0.4666,0.9637,0.3681,0.4188,0.3020,0.7719]]).astype("float64"))
data['weight'] =theano.shared(np.array([3.9238,3.1421,6.5905,2.8718,1.7819,1.4975,0.1834,7.6811,5.0964,2.7595]).astype("float64"))
data['y'] =theano.shared(np.array([14.3773,22.0280,21.5997,24.4789,25.8981,15.0056,20.0997,17.3859,20.7086,22.1846]).astype("float64"))


with pm.Model() as model:
    w=pm.Normal('w',1.0,10.0, shape=(10,))
    b=pm.Weibull('b',93.19563293457031,46.43210220336914)
    obs1=pm.Logistic('obs1',data['x']*w+b,1.0, observed=data['y'])
    

    with model:
        samples = pm.sample(1000, chains=4, tune=1000, step=None)
```

### Output:

```Python
pymc3file.py:30: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  samples = pm.sample(1000, chains=4, tune=1000, step=None)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [b, w]
???
projects/pymc/pymc3/step_methods/hmc/quadpotential.py:237: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
projects/pymc/pymc3/step_methods/hmc/quadpotential.py:210: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
pymc3.parallel_sampling.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "projects/pymc/pymc3/parallel_sampling.py", line 140, in run
    self._start_loop()
  File "projects/pymc/pymc3/parallel_sampling.py", line 194, in _start_loop
    point, stats = self._compute_point()
  File "projects/pymc/pymc3/parallel_sampling.py", line 219, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "projects/pymc/pymc3/step_methods/arraystep.py", line 283, in step
    apoint, stats = self.astep(array)
  File "projects/pymc/pymc3/step_methods/hmc/base_hmc.py", line 152, in astep
    self.potential.raise_ok(self._logp_dlogp_func._ordering.vmap)
  File "projects/pymc/pymc3/step_methods/hmc/quadpotential.py", line 290, in raise_ok
    raise ValueError("\n".join(errmsg))
ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `b_log__`.ravel()[0] is zero.
The derivative of RV `w`.ravel()[0] is zero.
The derivative of RV `w`.ravel()[1] is zero.
The derivative of RV `w`.ravel()[2] is zero.
The derivative of RV `w`.ravel()[3] is zero.
The derivative of RV `w`.ravel()[4] is zero.
The derivative of RV `w`.ravel()[5] is zero.
The derivative of RV `w`.ravel()[6] is zero.
The derivative of RV `w`.ravel()[7] is zero.
The derivative of RV `w`.ravel()[8] is zero.
The derivative of RV `w`.ravel()[9] is zero.
"""

The above exception was the direct cause of the following exception:

ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `b_log__`.ravel()[0] is zero.
The derivative of RV `w`.ravel()[0] is zero.
The derivative of RV `w`.ravel()[1] is zero.
The derivative of RV `w`.ravel()[2] is zero.
The derivative of RV `w`.ravel()[3] is zero.
The derivative of RV `w`.ravel()[4] is zero.
The derivative of RV `w`.ravel()[5] is zero.
The derivative of RV `w`.ravel()[6] is zero.
The derivative of RV `w`.ravel()[7] is zero.
The derivative of RV `w`.ravel()[8] is zero.
The derivative of RV `w`.ravel()[9] is zero.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pymc3file.py", line 30, in <module>
    samples = pm.sample(1000, chains=4, tune=1000, step=None)
  File "projects/pymc/pymc3/sampling.py", line 582, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "projects/pymc/pymc3/sampling.py", line 1538, in _mp_sample
    for draw in sampler:
  File "projects/pymc/pymc3/parallel_sampling.py", line 501, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)
  File "projects/pymc/pymc3/parallel_sampling.py", line 368, in recv_draw
    raise error from old_error
RuntimeError: Chain 2 failed.

```

## Versions and main components

* PyMC/PyMC3 Version: v3.11.4
* Theano Version: 1.1.2
* Python Version: 3.7.11
* Operating system: Ubuntu 18.04
* How did you install PyMC/PyMC3:  pip install git+https://github.com/pymc-devs/pymc@v3.11.4

**Comment by ricardoV94** [comment]
It's probably due to underflow / bad model specification. Do you mind opening an issue on our [Discourse](https://discourse.pymc.io/) instead? We try to keep Github for code development issues only.

**Comment by rusty-robin** [comment]
Sure, I can do that.  In this case, the model is quite simple though. Do you think there is something wrong with this?
