### ISSUE TITLE
Representation for empty model raises ValueError

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5568]
```python
import pymc as pm
pm.Model().str_repr()
```

```python
Traceback (most recent call last):
  File "/home/ricardo/miniconda3/envs/roche_preclinical_hd/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-fa2b838ad5d3>", line 1, in <module>
    pm.Model().str_repr()
  File "/home/ricardo/Documents/Projects/pymc/pymc/printing.py", line 82, in str_for_model
    maxlen = str(max(len(x) for x in names))
ValueError: max() arg is an empty sequence
```

**Comment by sagartomar** [comment]
Hi, I would like to work on this. For an empty model is it ok to just return an empty string?
