### ISSUE TITLE
Boolean Value in ScanOp self.truncate_gradient

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pymc#5697]
## Description of your problem
I am trying to use a scan op to implement a state space model in PyMC. During sampling, an error is raised indicating that a boolean and an integer are being compared in the computational graph. This appears to occur on line 2304 of aesara\scan\op.py, when checking for truncation of the gradients; self.truncate_gradient = False when the error occurs. It seems it should be 0?

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc as pm
import aesara
from aesara import tensor as at
import numpy as np

epsilons = np.random.normal(loc=np.zeros(2),
                            scale=np.array([1, 0.01]),
                            size=(100, 2))

states = np.zeros((100, 2))
data = np.zeros(100)
transition = np.array([[1.0, 1.0],
                       [0.0, 1.0]])
design = np.array([[1.0, 0.0]])

for t in range(1, 100):
    states[t, :] = states[t - 1, :] @ transition + epsilons[t, :]
    data[t] = design @ states[t]

def step_statespace(epsilon, x, A):
    x_ = at.dot(A, x) + epsilon
    return x_

coords = {'time': np.arange(100),
          'states': ['level', 'trend']}

with pm.Model(coords=coords) as statespace_test:
    sigma_level = pm.HalfNormal('sigma_level', sigma=1.00)
    sigma_trend = pm.HalfNormal('sigma_trend', sigma=0.05)

    x0 = pm.Normal('x0',
                   mu=np.zeros(2),
                   sigma=np.array([2.0, 0.01]),
                   dims=['states'])

    epsilons = pm.Normal('epsilons',
                         mu=np.zeros(2),
                         sigma=at.stack([sigma_level, sigma_trend]),
                         dims=['time', 'states'])

    A = at.as_tensor_variable(transition)

    F = at.as_tensor_variable(design)

    state_history, _ = aesara.scan(fn=step_statespace,
                                   sequences=dict(input=epsilons, taps=[0]),
                                   outputs_info=dict(initial=x0, taps=[-1]),
                                   non_sequences=[A])

    hidden_states = pm.Deterministic('hidden_states', state_history, dims=['time', 'states'])
    observed_states = pm.Deterministic('observed_states', (F * hidden_states).sum(axis=-1), dims=['time'])

    sigma_observed = pm.HalfNormal('sigma_height', sigma=5.0)

    height = pm.Normal('data_hat',
                       mu=observed_states,
                       sigma=sigma_observed,
                       observed=data,
                       dims=['time'])

    ssm_prior = pm.sample_prior_predictive(var_names=['data_hat', 'hidden_states'])

with statespace_test:
    ssm_trace = pm.sample()

```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
Traceback (most recent call last):
  File "C:/Users/Jesse/Python Projects/pymc/statespace.py", line 67, in <module>
    nile_trace = pm.sample(cores=1, init='jitter+adapt_diag')
  File "C:\Users\Jesse\Python Projects\pymc\pymc\sampling.py", line 472, in sample
    step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
  File "C:\Users\Jesse\Python Projects\pymc\pymc\sampling.py", line 206, in assign_step_methods
    tg.grad(model_logpt, var)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 630, in grad
    rval = _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1434, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1434, in <listcomp>
    rval = [access_grad_cache(elem) for elem in wrt]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1387, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1059, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1059, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1387, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1059, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1059, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1387, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1059, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1059, in <listcomp>
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1387, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\gradient.py", line 1214, in access_term_cache
    input_grads = node.op.L_op(inputs, node.outputs, new_output_grads)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\scan\op.py", line 2304, in L_op
    grad_steps = minimum(grad_steps, self.truncate_gradient)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\graph\op.py", line 294, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\tensor\elemwise.py", line 462, in make_node
    inputs = [as_tensor_variable(i) for i in inputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\tensor\elemwise.py", line 462, in <listcomp>
    inputs = [as_tensor_variable(i) for i in inputs]
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\tensor\__init__.py", line 42, in as_tensor_variable
    return _as_tensor_variable(x, name, ndim, **kwargs)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Jesse\miniconda3\envs\pymc-dev-py38\lib\site-packages\aesara\tensor\basic.py", line 176, in _as_tensor_bool
    raise TypeError(
TypeError: Cannot cast True or False as a tensor variable. Please use np.array(True) or np.array(False) if you need these constants. This error might be caused by using the == operator on Variables. v == w does not do what you think it does, use aesara.tensor.eq(v, w) instead.
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b4
* Aesara/Theano Version: 2.5.1
* Python Version: 3.8.12
* Operating system: Windows 10
* How did you install PyMC/PyMC3:  conda

**Comment by ricardoV94** [comment]
Hi, thanks for reporting. This was a Aesara bug that we just fixed yesterday: https://github.com/aesara-devs/aesara/pull/892

It should work for you if you define `truncate_gradient=-1` when you define the scan

**Comment by jessegrabowski** [comment]
Understood, thank you. Sorry for not checking the Aesara issues before posting here. I'll be sure to do that in the future.

**Comment by ricardoV94** [comment]
No worries. If you had posted this some time earlier we would have been able to fix it immediately. It was a great coincidence in time that we fixed it yesterday!
