### ISSUE TITLE
`RecursionError` when using `DensityDist` in v4

### ISSUE THREAD

**Issue by ColtAllen** [pymc-devs/pymc#5730]
## Description of your problem

I'm currently rewriting the [`lifetimes`](https://github.com/CamDavidsonPilon/lifetimes) library in `pymc` v4.0.0, but encountering an issue when using `DensityDist()`:

```python
import pymc as pm
import aesara.tensor as at
import numpy as np
from lifetimes.datasets import load_cdnow_summary

# Use lifetimes dataset generator to create toy data for testing.
rfm_df= load_cdnow_summary(index_col=[0])

def logp(rfm_df, a, b, alpha, r):

    x = rfm_df["frequency"].to_numpy()
    t_x = rfm_df["recency"].to_numpy()
    T = rfm_df["T"].to_numpy()

    # Flag instances where frequency > 0 for switch statement.
    int_vec = np.vectorize(int)
    x_zero = int_vec(x > 0)

    d1 = at.gammaln(r + x) - at.gammaln(r) + at.gammaln(a + b) + at.gammaln(b + x) - at.gammaln(b) - at.gammaln(a + b + x)
    d2 = r * at.log(alpha) - (r + x) * at.log(alpha + t_x)
    c3 = ((alpha + t_x)/(alpha + T))**(r+x)
    c4 = a/(b+x-1)

    loglikelihood = at.sum(d1 + d2 + at.log(c3 + c4 * at.switch(x_zero, 1, 0)))

    return loglikelihood

with pm.Model() as model:

    n = rfm_df.shape[0]

    # hyper priors for the Gamma params
    a = pm.HalfNormal(name="a", sigma=10)
    b = pm.HalfNormal(name="b", sigma=10)

    # hyper priors for the Beta params
    alpha = pm.HalfNormal(name="alpha", sigma=10)
    r = pm.HalfNormal(name="r", sigma=10)

    lam = pm.Gamma(name="lam", alpha=r, beta=alpha, shape=n)
    p = pm.Beta(name="p", alpha=a, beta=b, shape=n)

    dist_params = [a, b, alpha, r]

    likelihood = pm.DensityDist(
        "likelihood",
        *dist_params,
        logp=logp,
        observed = rfm_df
    )


with model:
    idata_full = pm.sample(
        tune=3000,
        draws=6000,
        chains=4,
        target_accept=0.95,
        return_inferencedata=True
    )
```

**Please provide the full traceback.**

When running in a Jupyter notebook on Python 3.8.1, with `pip install pymc --pre`:

<details><summary>Jupyter notebook error traceback</summary>

```python
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-37-f7561eda1caa> in <module>
     79
     80 with model:
---> 81     idata_full = pm.sample(
     82         tune=3000,
     83         draws=6000,

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/pymc/sampling.py in sample(draws, step, init, n_init, initvals, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, **kwargs)
    470
    471     initial_points = None
--> 472     step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    473
    474     if isinstance(step, list):

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/pymc/sampling.py in assign_step_methods(model, step, methods, step_kwargs)
    196     # variables
    197     selected_steps = defaultdict(list)
--> 198     model_logpt = model.logpt()
    199
    200     for var in model.value_vars:

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/pymc/model.py in logpt(self, vars, jacobian, sum)
    761         rv_logps: List[TensorVariable] = []
    762         if rv_values:
--> 763             rv_logps = joint_logpt(list(rv_values.keys()), rv_values, sum=False, jacobian=jacobian)
    764             assert isinstance(rv_logps, list)
    765

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/pymc/distributions/logprob.py in joint_logpt(var, rv_values, jacobian, scaling, transformed, sum, **kwargs)
    221
    222     transform_opt = TransformValuesOpt(transform_map)
--> 223     temp_logp_var_dict = factorized_joint_logprob(
    224         tmp_rvs_to_values, extra_rewrites=transform_opt, use_jacobian=jacobian, **kwargs
    225     )

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/aeppl/joint_logprob.py in factorized_joint_logprob(rv_values, warn_missing_rvs, extra_rewrites, **kwargs)
    184         q_rv_inputs = remapped_vars[len(q_value_vars) :]
    185
--> 186         q_logprob_vars = _logprob(
    187             node.op,
    188             q_value_vars,

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/functools.py in wrapper(*args, **kw)
    872                             '1 positional argument')
    873
--> 874         return dispatch(args[0].__class__)(*args, **kw)
    875
    876     funcname = getattr(func, '__name__', 'singledispatch function')

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/pymc/distributions/distribution.py in density_dist_logp(op, value_var_list, *dist_params, **kwargs)
    811             _dist_params = dist_params[3:]
    812             value_var = value_var_list[0]
--> 813             return logp(value_var, *_dist_params)
    814
    815         @_logcdf.register(rv_type)

<ipython-input-37-f7561eda1caa> in logp(rfm_df, a, b, alpha, r)
     33
     34     n = rfm_df.shape[0]
---> 35     x = rfm_df["frequency"].to_numpy()
     36     t_x = rfm_df["recency"].to_numpy()
     37     T = rfm_df["T"].to_numpy()

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/aesara/tensor/var.py in __getitem__(self, args)
    482                 # indexing, it is safe to throw an error if we encounter
    483                 # any of these difficult cases.
--> 484                 if includes_bool(arg):
    485                     raise TypeError(
    486                         "TensorType does not support Python bools "

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/aesara/tensor/var.py in includes_bool(args_el)
    450             if not isinstance(args_el, Variable) and isinstance(args_el, Iterable):
    451                 for el in args_el:
--> 452                     if includes_bool(el):
    453                         return True
    454             return False

... last 1 frames repeated, from the frame below ...

/anaconda/envs/azureml_py38_pytorch/lib/python3.8/site-packages/aesara/tensor/var.py in includes_bool(args_el)
    450             if not isinstance(args_el, Variable) and isinstance(args_el, Iterable):
    451                 for el in args_el:
--> 452                     if includes_bool(el):
    453                         return True
    454             return False

RecursionError: maximum recursion depth exceeded in comparison

```

</details>

Running this in a python script produces a similar, albeit truncated error trace. This script was ran in an environment created from an older version of [https://github.com/pymc-devs/pymc/blob/main/conda-envs/environment-dev-py39.yml](https://github.com/pymc-devs/pymc/blob/main/conda-envs/environment-dev-py39.yml):

<details><summary>Python script error traceback</summary>

```
Traceback (most recent call last):
  File "/anaconda/envs/lifetimes-dev/lib/python3.9/site-packages/aesara/tensor/var.py", line 452, in includes_bool
    if includes_bool(el):
  File "/anaconda/envs/lifetimes-dev/lib/python3.9/site-packages/aesara/tensor/var.py", line 452, in includes_bool
    if includes_bool(el):
  File "/anaconda/envs/lifetimes-dev/lib/python3.9/site-packages/aesara/tensor/var.py", line 452, in includes_bool
    if includes_bool(el):
  [Previous line repeated 995 more times]
  File "/anaconda/envs/lifetimes-dev/lib/python3.9/site-packages/aesara/tensor/var.py", line 450, in includes_bool
    if not isinstance(args_el, Variable) and isinstance(args_el, Iterable):
  File "/anaconda/envs/lifetimes-dev/lib/python3.9/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```
</details>

**Please provide any additional information below.**

The error trace suggests a boolean issue with the `at.switch` and/or `pymc.math.switch` statements, but the full likelihood function for the same model runs just fine:

```
def logp_full(rfm_df, lam, p):

    x = rfm_df["frequency"].to_numpy()
    t_x = rfm_df["recency"].to_numpy()
    T = rfm_df["T"].to_numpy()

    # Flag instances where frequency > 0 for switch statement.
    int_vec = np.vectorize(int)
    x_zero = int_vec(x > 0)

    log_term_a = x * at.log(1 - p) + x * at.log(lam) - t_x * lam
    term_b_1 = -lam * (T - t_x)
    term_b_2 = at.log(p) - at.log(1 - p)
    log_term_b = at.switch(x_zero, at.logaddexp(term_b_1, term_b_2), term_b_1)
    loglikelihood = at.sum(log_term_a) + at.sum(log_term_b)

    return loglikelihood
```

I don't think this is an `aesara` issue because both functions tested successfully prior to use in a `pymc.Model()` context. This code also ran fine in `theano` and `pymc3` before adapting it to v4. It is my understanding `pymc.DensityDist()` is somewhat of a problem child; if there are alternative methods for writing custom likelihood functions, please let me know. Thank you!

## Versions and main components

- PyMC Version: v4.0.0b6
- Aesara Version: 2.5.1
- Python Version: 3.8.1 & 3.9.12
- Operating system: Ubuntu 18.04.1
- How did you install PyMC/PyMC3: Both `pip` and `conda` installs were tested python 3.8 and 3.9, respectively.

**Comment by ricardoV94** [comment]
Those pandas and numpy calls in the likelihood are probably leading problems. The inputs to the DensityDist likelihood are all going to be TensorVariables or TensorConstants and no longer pandas series or dataframes.

**Comment by ColtAllen** [comment]
> Those pandas and numpy calls in the likelihood are probably leading problems. The inputs to the DensityDist likelihood are all going to be TensorVariables or TensorConstants and no longer pandas series or dataframes.

Thanks for such a quick response. Would the preferred way to do this involve creating an `aesara` [Op](https://aesara.readthedocs.io/en/latest/library/graph/op.html#aesara.graph.op.Op) for the custom likelihood? I had to provide a pandas DF or numpy array for the  'observed' argument for `DensityDist` because it no longer accepts dictionaries like it did with `pymc3`, and I'm not sure how to specify the inputs otherwise.

**Comment by ricardoV94** [comment]
You can pass x, t_x and T either as inputs or an observed matrix, whichever makes more sense.

If your Densitydist does not really behave like a distribution you can use `pm.Potential` instead without the need to do this function encapsulation.

Also I am not sure what that `np.vectorize` is doing? Are you casting the data? If so you should use `.astype`.

If you keep having problems do you mind opening a topic in our discourse? https://discourse.pymc.io/ as we try to keep GitHub issues for bugs / development only.

**Comment by ColtAllen** [comment]
> Also I am not sure what that `np.vectorize` is doing?

It creates a boolean vector for the `aesara.tensor.switch` statement. I'll create an external utility method so this isn't being done inside `logp`.

> If you keep having problems do you mind opening a topic in our discourse? https://discourse.pymc.io/ as we try to keep GitHub issues for bugs / development only.

Sorry for the rookie mistake; I'll keep this in mind in the future and reopen this issue if any bugs or documentation revisions arise from a discourse discussion.
