### ISSUE TITLE
Pymc4 crashes with Regression Model

### ISSUE THREAD

**Issue by rusty-robin** [pymc-devs/pymc#5861]
Hi,

Running the following program causes PyMC4 to crash. However, Stan produces results for the same model. There are three large values in the data (y) like `1.1321e25, 1.7744e26`, which may be causing problems with PyMC4. Since the likelihood dist is Gaussian, I was expecting this to work. Is this indicative of a bug/instability? Or am I missing something?

Please let me know if you need more info.

```python
import pymc as pm
import aesara
import arviz as az
import matplotlib.pyplot as plt
import os
import json
import random
import sys
import numpy as np
curpath=os.path.dirname(os.path.abspath(sys.argv[0]))



random.seed(193229742)
np.random.seed(2055442459)

data = dict()
data['x'] =aesara.shared(np.array([0.0970,2.1020,0.5840,1.0394,3.4375,1.3102,1.2863,4.5382,1.2539,2.9319,4.7777,4.5937,4.0403,0.7749,1.8342,1.5008,3.9557,1.6095,0.5602,4.7997,1.6436,4.5236,1.9404,1.1508,3.1447,3.3551,0.2669,3.2483,2.5293,0.1596,2.8992,2.5016,4.7589,2.5648,1.9871,0.3201,4.4863,0.5675,0.8897,0.5689,0.5621,0.5701,0.7998,0.3166,4.8490,2.7849,2.6858,4.2393,1.4939,1.7230,0.4202,0.3591,2.5912,3.9753,3.5417,0.3198,2.7192,1.9892,1.9525,4.7293,1.7719,3.7889,2.3613,4.6994,2.0155,3.8840,0.8289,2.1164,1.3342,1.4850,0.5512,0.3919,2.4001,3.1949,4.9759,1.4158,0.6088,2.1599,0.3643,0.6800,2.4031,1.7706,3.7669,4.1080,4.9707,1.9139,4.7615,3.3075,3.6872,4.0946,0.3447,2.7292,0.2768,3.7641,3.3987,0.1833,4.9353,1.9730,2.2034,2.8598]).astype("float64"))
data['y'] =aesara.shared(np.array([4.9404,45.0399,14.6792,23.7890,71.7504,29.2036,28.7251,93.7642,28.0774,61.6389,98.5535,94.8738,0.2094,18.4976,39.6836,33.0162,82.1149,35.1902,14.2033,98.9948,35.8724,1.1321e25,41.8081,26.0160,65.8950,70.1028,8.3385,67.9659,53.5864,6.1922,60.9839,53.0324,98.1783,54.2960,42.7421,9.4019,92.7252,3.7643e26,20.7931,14.3781,14.2424,14.4019,18.9951,9.3322,99.9797,58.6983,56.7166,87.7854,32.8781,37.4594,11.4034,10.1829,54.8241,82.5061,1.7744e26,9.3964,57.3845,42.7835,42.0501,97.5864,38.4374,78.7779,50.2264,96.9873,43.3109,80.6796,19.5773,45.3275,29.6839,32.6994,14.0248,10.8371,51.0026,66.8986,102.5188,31.3158,15.1756,46.1974,10.2855,16.6008,51.0629,38.4128,78.3385,85.1597,102.4138,41.2770,2946.2122,69.1497,76.7434,84.8919,9.8933,57.5845,8.5367,78.2816,70.9734,6.6665,101.7066,42.4600,47.0682,60.1959]).astype("float64"))


with pm.Model() as model:
    w=pm.Normal('w',10,1)
    b=pm.Normal('b',1,1)
    sigma=pm.Gamma('sigma',1,2)
    obs1=pm.Normal('obs1',w*data['x']+b,sigma, observed=data['y'])
    

    with model:
        step = pm.step_methods.hmc.nuts.NUTS(max_treedepth=10,target_accept=0.8,step_scale=0.25)
        samples = pm.sample(draws=1000, chains=4, tune=1000, step=step, init="auto", jitter_max_retries=10)

```

Output:
```python
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [w, b, sigma]
pymc/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
pymc/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
pymc/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
pymc/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
pymc/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
pymc/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
pymc/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
pymc/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
pymc.parallel_sampling.RemoteTraceback:
"""
Traceback (most recent call last):
  File "pymc/pymc/parallel_sampling.py", line 129, in run
    self._start_loop()
  File "pymc/pymc/parallel_sampling.py", line 182, in _start_loop
    point, stats = self._compute_point()
  File "pymc/pymc/parallel_sampling.py", line 207, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "pymc/pymc/step_methods/arraystep.py", line 286, in step
    return super().step(point)
  File "pymc/pymc/step_methods/arraystep.py", line 208, in step
    step_res = self.astep(q)
  File "pymc/pymc/step_methods/hmc/base_hmc.py", line 165, in astep
    self.potential.raise_ok(q0.point_map_info)
  File "pymc/pymc/step_methods/hmc/quadpotential.py", line 308, in raise_ok
    raise ValueError("\n".join(errmsg))
ValueError: Mass matrix contains zeros on the diagonal.
The derivative of RV `w`.ravel()[[0]] is zero.
The derivative of RV `b`.ravel()[[0]] is zero.
The derivative of RV `sigma_log__`.ravel()[[]] is zero.
"""

The above exception was the direct cause of the following exception:

ValueError: Mass matrix contains zeros on the diagonal.
The derivative of RV `w`.ravel()[[0]] is zero.
The derivative of RV `b`.ravel()[[0]] is zero.
The derivative of RV `sigma_log__`.ravel()[[]] is zero.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pymc4file.py", line 32, in <module>
    samples = pm.sample(draws=1000, chains=4, tune=1000, step=step, init="auto", jitter_max_retries=10)
  File "pymc/pymc/sampling.py", line 607, in sample
    mtrace = _mp_sample(**sample_args, **parallel_args)
  File "pymc/pymc/sampling.py", line 1535, in _mp_sample
    for draw in sampler:
  File "pymc/pymc/parallel_sampling.py", line 464, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)
  File "pymc/pymc/parallel_sampling.py", line 353, in recv_draw
    raise error from old_error
RuntimeError: Chain 0 failed.
```

Results from Stan:
```
                    Mean     MCSE   StdDev        5%       50%       95%    N_Eff  N_Eff/s    R_hat
lp__            -1.3e+18  0.0e+00  0.0e+00  -1.3e+18  -1.3e+18  -1.3e+18  2.0e+00  1.2e-01     -nan
accept_stat__    8.8e-01  1.6e-02  3.1e-01   4.8e-02   1.0e+00   1.0e+00  3.8e+02  2.3e+01  1.0e+00
stepsize__       7.2e-13     -nan  1.3e-13   5.1e-13   7.8e-13   8.3e-13     -nan     -nan  1.6e+14
treedepth__      1.0e+01     -nan  1.7e-13   1.0e+01   1.0e+01   1.0e+01     -nan     -nan  1.0e+00
n_leapfrog__     1.0e+03     -nan  1.8e-11   1.0e+03   1.0e+03   1.0e+03     -nan     -nan  1.0e+00
divergent__      0.0e+00     -nan  0.0e+00   0.0e+00   0.0e+00   0.0e+00     -nan     -nan     -nan
energy__         1.3e+18  0.0e+00  0.0e+00   1.3e+18   1.3e+18   1.3e+18  2.0e+00  1.2e-01     -nan
w                1.7e+00  1.6e-14  2.2e-14   1.7e+00   1.7e+00   1.7e+00  2.0e+00  1.2e-01  1.0e+00
b                4.0e-01  6.0e-02  8.5e-02   2.7e-01   4.8e-01   4.8e-01  2.0e+00  1.2e-01  1.5e+14
sigma            4.4e+17     -nan  0.0e+00   4.4e+17   4.4e+17   4.4e+17     -nan     -nan     -nan
```

Environment:
```
python 3.7
Ubuntu 18.04
Pymc 4.0.0
aesara 2.6.6
jax 0.3.13
jaxlib 0.3.10
```

**Comment by twiecki** [comment]
This looks like a mis-specified model. Even Stan has R_hat values that indicate the same problem. I'm going to close this because it's not a PyMC error and invite you to post this question (ideally with the model) on discourse.pymc.io. The normal likelihood does not work well with outliers.
