### ISSUE TITLE
SMC fails with p_acc_rate

### ISSUE THREAD

**Issue by Huzaifg** [pymc-devs/pymc#5918]
sample_smc fails with p_acc_rate and IMH kernel.
```python
idata = pm.sample_smc(kernel = pm.smc.IMH,draws = ndraws,parallel=True,cores=8,return_inferencedata=True,progressbar = True,p_acc_rate = 0.9)
```

**Traceback**

<details><summary>

</summary>

```python
/home/huzaifa/research/tutorials/vd_8dof_st2.py:152: FutureWarning: The argument parallel is deprecated, use the argument cores instead.
  idata = pm.sample_smc(kernel = pm.smc.IMH,draws = ndraws,parallel=True,cores=8,return_inferencedata=True,progressbar = True,p_acc_rate = 0.9)
Initializing SMC sampler...
Sampling 8 chains in 8 jobs
multiprocessing.pool.RemoteTraceback: ----------------------------------------------------------------| 0.00% [0/100 00:00<00:00]
"""
Traceback (most recent call last):
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/smc/sample_smc.py", line 439, in _apply_args_and_kwargs
    return fn(*args, **kwargs)
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/smc/sample_smc.py", line 351, in _sample_smc_int
    smc = kernel(
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/smc/smc.py", line 348, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'p_acc_rate'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/huzaifa/research/tutorials/vd_8dof_st2.py", line 211, in <module>
    main()
  File "/home/huzaifa/research/tutorials/vd_8dof_st2.py", line 152, in main
    idata = pm.sample_smc(kernel = pm.smc.IMH,draws = ndraws,parallel=True,cores=8,return_inferencedata=True,progressbar = True,p_acc_rate = 0.9)
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/smc/sample_smc.py", line 227, in sample_smc
    results = run_chains_parallel(
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/smc/sample_smc.py", line 408, in run_chains_parallel
    results = _starmap_with_kwargs(
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/smc/sample_smc.py", line 435, in _starmap_with_kwargs
    return pool.starmap(_apply_args_and_kwargs, args_for_starmap)
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/huzaifa/miniconda3/envs/pymc-dev-py39/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'p_acc_rate'
```

</details>

## Versions and main components

* PyMC Version: 4.0.0 
* Aesara/Theano Version: 2.5.1
* Python Version: 3.9
* Operating system: Linux
* How did you install PyMC/PyMC3: conda

**Comment by aloctavodia** [comment]
Hi @Huzaifg, thanks for taking the time to report this. The `p_acc_rate`  argument has been removed. #5914 updates the docstring
