### ISSUE TITLE
The model could not be unpickled while sampling

### ISSUE THREAD

**Issue by CorentinPhilippe-Taylor** [pymc-devs/pymc#5934]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import pymc as pm
import aesara
import aesara.tensor as at


@aesara.compile.ops.as_op(itypes=[at.lvector, at.dvector], otypes=[at.dmatrix])
def remove_names(names, ages):
    output = []
    output.append(ages)
    return output

with pm.Model() as m:
    N = 100

    names_others = pm.DiscreteUniform("names_others", 0, 5, shape=N)
    ages_others = pm.Normal("ages_others", mu=55.2, sigma=3.5, shape=N)

    mu = pm.Deterministic('mu', remove_names(names_others, ages_others))

    trace = pm.sample(tune=1000, cores= 4, return_inferencedata=False)
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 119, in _unpickle_step_method
    self._step_method = cloudpickle.loads(self._step_method)
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/aesara/compile/ops.py", line 222, in load_back
    obj = getattr(module, name)
AttributeError: module '__main__' has no attribute 'remove_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 127, in run
    self._unpickle_step_method()
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 121, in _unpickle_step_method
    raise ValueError(unpickle_error)
ValueError: The model could not be unpickled. This is required for sampling with more than one core and multiprocessing context spawn or forkserver.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
ValueError: The model could not be unpickled. This is required for sampling with more than one core and multiprocessing context spawn or forkserver.
...
--> 353     raise error from old_error
    354 elif msg[0] == "writing_done":
    355     proc._readable = True

RuntimeError: Chain 0 failed.
```

</details>

**Please provide any additional information below.**
I'm trying to sample a model which is using a deterministic variable but the sampling is failing. The Aesara Variable of the deterministic function is the output of the function remove_names and I assume this is from where the problem is coming. 
Is there a way for the deterministic function to take the output of another function as an argument ? If yes, what am I doing wrong ?

## Versions and main components

* PyMC/PyMC3 Version: 4.0.1
* Aesara/Theano Version: 2.7.3
* Python Version: 3.10.5
* Operating system: Mac OS M1
* How did you install PyMC/PyMC3: conda

**Comment by ricardoV94** [comment]
Try to define your custom op in a separate module and import it in the module/notebook where you sample.

Pickling sometimes fails when pickled objects are defined in the same context.

**Comment by CorentinPhilippe-Taylor** [comment]
Thanks a lot. It worked.
