### ISSUE TITLE
Sampling in numba mode fails with scalar RVs

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5937]
```python
import aesara
aesara.config.mode = "NUMBA"
import pymc as pm

with pm.Model():
    x = pm.Normal("x") # does not work
    #x = pm.Normal("x", shape=1) # works
    pm.sample(chains=1, cores=1)
```

Trace:
```
"""
Traceback (most recent call last):
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 129, in run
    self._start_loop()
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 182, in _start_loop
    point, stats = self._compute_point()
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 207, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/step_methods/arraystep.py", line 286, in step
    return super().step(point)
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/step_methods/arraystep.py", line 208, in step
    step_res = self.astep(q)
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/step_methods/hmc/base_hmc.py", line 156, in astep
    start = self.integrator.compute_state(q0, p0)
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/step_methods/hmc/integration.py", line 47, in compute_state
    logp, dlogp = self._logp_dlogp_func(q)
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/model.py", line 411, in __call__
    grads_raveled = DictToArrayBijection.map(
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/blocking.py", line 61, in map
    vars_info = tuple((v, k, v.shape, v.dtype) for k, v in var_dict.items())
  File "/Users/twiecki/miniforge3/envs/pymc4/lib/python3.10/site-packages/pymc/blocking.py", line 61, in <genexpr>
    vars_info = tuple((v, k, v.shape, v.dtype) for k, v in var_dict.items())
AttributeError: 'float' object has no attribute 'shape'
```

**Comment by bherwerth** [comment]
It seems to me the problem is at the level of the underlying `aesara` function.

The line where the example fails is the following: 
https://github.com/pymc-devs/pymc/blob/f9e0dfd6b898ec5085ffaf85b031b65305b1e3f0/pymc/blocking.py#L61

With the help of the debugger, I find that `type(v)` is float in numba mode. In `aesara`'s default mode, however, it is a `0d` numpy array.

The underlying inconsistency seems to be in `aesara` in numba vs default mode:

```python
import aesara
aesara.config.mode = "NUMBA"
import aesara.tensor as at

x = at.scalar(name="x")
f = aesara.function([x], 2*x)
print(repr(f(10)))  # prints 20.0
```

vs

```python

import aesara
import aesara.tensor as at

x = at.scalar(name="x")
f = aesara.function([x], 2*x)
print(repr(f(10))) # prints array(20.)
```

I can get the pymc example running in numba mode, when I insert the following line before l.61 in `blocking.py`:
```python
var_dict = {k: np.asarray(v) for k, v in var_dict.items()}
```

This might be a temporary fix at the level of `pymc`, but maybe it would be better to fix this in `aesara` eventually?

**Comment by twiecki** [comment]
@bherwerth great find, I opened an aesara issue.

**Comment by twiecki** [comment]
Should be fixed once we update aesara https://github.com/aesara-devs/aesara/issues/1063.
