### ISSUE TITLE
Problem while concatenated a Normal distribution with a Dirac

### ISSUE THREAD

**Issue by CorentinPhilippe-Taylor** [pymc-devs/pymc#5950]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import pymc as pm
import function_concat as fc

with pm.Model() as m:
    N = 100

    ALICE_NAME      = np.int64(0)
    ALICE_AGE       = np.float64(25.0)

    alice_name      = pm.DiracDelta("alice_name",ALICE_NAME, shape=1)
    alice_age       = pm.DiracDelta("alice_age", ALICE_AGE, shape=1)

    names_others     = pm.DiscreteUniform("names_others", 0, 5, shape=N)
    ages_others      = pm.Normal("ages_others", mu=55.2, sigma=3.5, shape=N)

    names     = pm.math.concatenate((names_others, alice_name),  axis=0)
    ages      = pm.math.concatenate((ages_others, alice_age),  axis=0)

    mu = pm.Deterministic('mu', fc.remove_names(names, ages))

    trace = pm.sample()
```
function_concat.py file
```python
import aesara
import aesara.tensor as at
import numpy as np

@aesara.compile.ops.as_op(itypes=[at.lvector, at.dvector], otypes=[at.dmatrix])
def remove_names(names, ages):
    output = []
    output.append(ages)
    return np.array(output)
```
**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:258: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py:237: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 129, in run
    self._start_loop()
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 182, in _start_loop
    point, stats = self._compute_point()
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/parallel_sampling.py", line 207, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/compound.py", line 45, in step
    point, state = method.step(point)
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/arraystep.py", line 286, in step
    return super().step(point)
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/arraystep.py", line 208, in step
    step_res = self.astep(q)
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/base_hmc.py", line 165, in astep
    self.potential.raise_ok(q0.point_map_info)
  File "/Users/corentinphilippe-taylor/opt/anaconda3/envs/privugger_environment/lib/python3.10/site-packages/pymc/step_methods/hmc/quadpotential.py", line 308, in raise_ok
    raise ValueError("\n".join(errmsg))
ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `alice_age`.ravel()[[0]] is zero.
The derivative of RV `ages_others`.ravel()[[ 1  7  9 10 12 22 23 25 28 29 41 44 53 54 56 57 62 64 65 71 72 74 91 92]] is zero.
"""
...
--> 353     raise error from old_error
    354 elif msg[0] == "writing_done":
    355     proc._readable = True

RuntimeError: Chain 2 failed.
```

**Please provide any additional information below.**
I think pretty much everything is in the title. The program releases me this error while I'm trying to create a deterministic variable with a variable concatenated with a Normal distribution and a DiracDelta. This problem does not happen if instead of a normal distribution it's a DiscreteUniform or a Bernoulli.

## Versions and main components

* PyMC/PyMC3 Version: PyMC 4.0.1
* Aesara/Theano Version: Theano 2.7.3
* Python Version: 3.10.5
* Operating system: Mac OS M1
* How did you install PyMC/PyMC3: conda

**Comment by ricardoV94** [comment]
You should not sample Diracdelta distributions, there is no sampler that copes with them. Instead you should just use numerical constants (numpy arrays or python integers/ floats).
