### ISSUE TITLE
test failure with PyMC 2.3.3 and PyTables 3.1.0dev

### ISSUE THREAD

**Issue by jseabold** [pymc-devs/pymc#600]
Trying to use the hdf5 background after a MemoryError was produced using pickle. I'm on the 0672add version of PyTables and the revision de78445 of PyMC. This is the test failure (with deprecation warnings left in).

```
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:276: PendingDeprecationWarning: openFile() is pending deprecation, use open_file() instead. You may use the pt2to3 tool to update your source code.
  self._h5file = tables.openFile(self.dbname, self.mode)
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:561: PendingDeprecationWarning: listNodes() is pending deprecation, use list_nodes() instead. You may use the pt2to3 tool to update your source code.
  groups = self._h5file.listNodes("/")
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:293: PendingDeprecationWarning: listNodes() is pending deprecation, use list_nodes() instead. You may use the pt2to3 tool to update your source code.
  "/") if gr._v_name[
./home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:404: PendingDeprecationWarning: createGroup() is pending deprecation, use create_group() instead. You may use the pt2to3 tool to update your source code.
  i))
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:408: PendingDeprecationWarning: createGroup() is pending deprecation, use create_group() instead. You may use the pt2to3 tool to update your source code.
  'Group storing objects.')
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:444: PendingDeprecationWarning: createTable() is pending deprecation, use create_table() instead. You may use the pt2to3 tool to update your source code.
  expectedrows=length)
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:510: PendingDeprecationWarning: createVLArray() is pending deprecation, use create_vlarray() instead. You may use the pt2to3 tool to update your source code.
  filters=self.filter)
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:309: PendingDeprecationWarning: walkNodes() is pending deprecation, use walk_nodes() instead. You may use the pt2to3 tool to update your source code.
  for node in db._h5file.walkNodes(chain, classname='VLArray'):
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:328: PendingDeprecationWarning: _f_listNodes() is pending deprecation, use _f_list_nodes() instead. You may use the pt2to3 tool to update your source code.
  for k in db._chains[-1]._f_listNodes():
../home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:584: PendingDeprecationWarning: setAttr() is pending deprecation, use set_attr() instead. You may use the pt2to3 tool to update your source code.
  table.setAttr(name, object)
/home/skipper/.local/lib/python2.7/site-packages/pymc/database/hdf5.py:591: PendingDeprecationWarning: createArray() is pending deprecation, use create_array() instead. You may use the pt2to3 tool to update your source code.
  self._h5file.createArray(group, name, object, description)
.....F.............S.......................................................................................................0            x
1    (x_pow_2)
dtype: object
 [-----------------100%-----------------] 1000 of 1000 complete in 0.2 sec............
======================================================================
FAIL: None (pymc.tests.test_database.TestHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/skipper/.local/lib/python2.7/site-packages/pymc/tests/test_database.py", line 229, in test_yrestore_state
    assert_equal(sm.accepted + sm.rejected, 75)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 331, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 15.0
 DESIRED: 75
```

Is there an example that I can run to see if I can get it to work? An error from an example (different from the one I get in my code).

```
[~/src/pymc/pymc/examples/gp/more_examples/Duffy] (2.3)
|10 $ python mcmc.py 
Traceback (most recent call last):
  File "mcmc.py", line 36, in <module>
    DuffySampler.use_step_method(pm.gp.GPEvaluationGibbs, DuffySampler.sp_sub_b, DuffySampler.V_b, DuffySampler.tilde_fb)
  File "/home/skipper/.local/lib/python2.7/site-packages/pymc/MCMC.py", line 106, in use_step_method
    new_method = step_method_class(*args, **kwds)
  File "/home/skipper/.local/lib/python2.7/site-packages/pymc/gp/step_methods.py", line 230, in __init__
    self.children_no_data.remove(eps_p_f)
KeyError: <pymc.PyMCObjects.Deterministic 'tilde_fb' at 0x7fea56371190>
Closing remaining open files: duffydb.hdf5... done
```

Traceback for my code [available here](http://pastebin.com/kyWaiWLk).

**Comment by jseabold** [comment]
Upgraded to PyMC 3.1.1 release tag and current head of PyMC 2.3 branch 4b5d8bb. Still have the example failure. The test failure is gone. Still have the same traceback from my code.

**Comment by fonnesbeck** [comment]
Can you try building from the 2.3 branch? I can't replicate from there.

If that fixes it, I will get a 2.3.4 release out asap.

**Comment by jseabold** [comment]
Yeah I built with the latest 2.3 HEAD the example fails, the test passes. I thought I posted replication code for the other problem to this issue too... Let me see if I can recreate. What HDF5 version are you using? PyTables version?

**Comment by jseabold** [comment]
Here it is again. Don't know what happened.

```
import numpy as np
from pymc import (Poisson, Normal, Gamma, deterministic, MCMC, Slicer, 
                  AdaptiveMetropolis)


def load_dta():
    t = np.arange(1, 85.)
    obs_t = np.random.randint(1, 84, size=134)
    X = np.random.randn(134, 83, 5)
    fail = np.random.randint(0, 2, size=134)
    return t, obs_t, X, fail


def cox_model():
    (t, obs_t, X, fail) = load_dta()

    T = len(t) - 1
    nsubj = len(obs_t)

    # risk set equals one if obs_t >= t
    Y = np.array([[int(obs >= time) for time in t] for obs in obs_t])
    # counting process. jump = 1 if obs_t \in [t[j], t[j+1])
    dN = np.array([[Y[i,j]*int(t[j+1] >= obs_t[i])*fail[i] for i in range(nsubj)] for j in range(T)])

    c = Gamma('c', .0001, .00001, value=.1)
    r = Gamma('r', .001, .0001, value=.1)
    dL0_star = r*np.array([t[j+1] - t[j] for j in range(T)])
    mu = dL0_star * c # prior mean hazard
    dL0 = Gamma('dL0', mu, c, value=np.ones(T)) #intensity

    beta = Normal('beta', np.zeros(X.shape[-1]), np.ones(X.shape[-1])*.00001,               
                  value = np.ones(X.shape[-1]) * .1)

    @deterministic
    def idt(b1=beta, dl0=dL0):
        # assume X is of shape nsubj x T x K (for K covariates)
        fitted = np.exp(np.dot(X, b1))
        mu_ = np.transpose(Y[:,:T] * fitted * dl0)
        return mu_

    dn_like = Poisson('dn_like', idt, value=dN, observed=True)

    return locals()

variables = cox_model()
m = MCMC(variables, db='hdf5', dbname='cox.hdf5')
m.sample(500, burn=100, thin=10)
```

**Comment by jseabold** [comment]
SQLite also fails for the above complaining about the shape of `idt`.

**Comment by jseabold** [comment]
Following the source, workaround is just to do `dn_like.keep_trace = False`. I imagine it has something to do with `dn_like` being a 2d array? Mostly a guess.

**Comment by jseabold** [comment]
This, however, led to another problem. Related to the `keep_trace` hack?

```
>>> m.beta.summary()
Could not generate output statistics for beta
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-26868ee7101c> in <module>()
----> 1 m.beta.summary()

/home/skipper/.local/lib/python2.7/site-packages/pymc/Node.pyc in summary(self, alpha, start, batches, chain, roundto)
    300             batches=batches,
    301             chain=chain)
--> 302         size = np.size(statdict['mean'])
    303 
    304         print_('\n%s:' % self.__name__)

TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jseabold** [comment]
The traceback is swallowed but there's an `IndexError: 'tuple index out of range'` being raised from pymc.database.base.batchsd when calling `m.beta.stats()`.

**Comment by jseabold** [comment]
Ah, ok, that was just a matter of the default batches being too high for this run. I can't imagine that was my issue in my real code which ran for many iterations.

**Comment by jseabold** [comment]
It looks like there's a few reshape errors (for this model) that I can patch. Is there a way to turn off `keep_trace` for the deterministic decorated `idt` as well? That'll get me farther along.

**Comment by jseabold** [comment]
To answer, yes, the keyword is `trace` not `keep_trace`. I'll see if these changes can get me all the way there and report back.

**Comment by jseabold** [comment]
Until I have time to run the test suite to make sure these changes are general (I suspect they're not) and look at the shape issues with idt and dn_like, I'll park the diff here.

```
|2 $ git diff
diff --git a/pymc/Node.py b/pymc/Node.py
index d672224..8fc147d 100644
--- a/pymc/Node.py
+++ b/pymc/Node.py
@@ -331,7 +331,7 @@ class Variable(Node):
             m = str(round(statdict['mean'][index], roundto))
             sd = str(round(statdict['standard deviation'][index], roundto))
             mce = str(round(statdict['mc error'][index], roundto))
-            hpd = str(statdict[interval][index].squeeze().round(roundto))
+            hpd = str(statdict[interval][:,index].squeeze().round(roundto))

             # Build up string buffer of values
             valstr = m
diff --git a/pymc/database/base.py b/pymc/database/base.py
index 03c8af2..4bc368e 100644
--- a/pymc/database/base.py
+++ b/pymc/database/base.py
@@ -169,7 +169,6 @@ class Trace(object):
         quantiles : tuple or list
           The desired quantiles to be calculated. Defaults to (2.5, 25, 50, 75, 
         """
-
         try:
             trace = np.squeeze(
                 np.array(
@@ -186,6 +185,7 @@ class Trace(object):
                     self.__name__)
                 return

+            batches = min(n, batches)
             return {
                 'n': n,
                 'standard deviation': trace.std(0),  
```

**Comment by fonnesbeck** [comment]
Thanks, will peek a this tonight.

**Comment by fonnesbeck** [comment]
Actually, I had fixed the shape issue in 2e5d59899 -- I will add the batches statement as well, so this will be taken care of.

**Comment by jseabold** [comment]
Great I'll give it a try.

**Comment by Miles-Garnsey** [comment]
I am also experiencing the same issue, it only seems to have started subsequent to me trying to use the Pickle and sqlite databases, but now is happening using even the RAM database.

It may also be related to a lack of RAM (32 bit machine - don't ask), but checking the resource monitor it appears that there is a fair bit, and I'm not seeing any spiking behaviour. 

I am on pymc 2.3.4, python 2.7 on a 32 bit windows 7 box. 

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-5-1282343e6e22> in <module>()
----> 1 MDL.sample(2e4, burn=1000)
      2 pymc.Matplot.plot(MDL)

C:\Anaconda\lib\site-packages\pymc\MCMC.pyc in sample(self, iter, burn, thin, tune_interval, tune_throughout, save_interval, burn_till_tuned, stop_tuning_after, verbose, progress_bar)
    275 
    276         # Run sampler
--> 277         Sampler.sample(self, iter, length, verbose)
    278 
    279     def _loop(self):

C:\Anaconda\lib\site-packages\pymc\Model.pyc in sample(self, iter, length, verbose)
    241         if length is None:
    242             length = iter
--> 243         self.db._initialize(self._funs_to_tally, length)
    244 
    245         # Put traces on objects

C:\Anaconda\lib\site-packages\pymc\database\base.pyc in _initialize(self, funs_to_tally, length)
    252                         db=self)
    253 
--> 254             self._traces[name]._initialize(self.chains, length)
    255 
    256         self.trace_names.append(list(funs_to_tally.keys()))

C:\Anaconda\lib\site-packages\pymc\database\ram.pyc in _initialize(self, chain, length)
     68 
     69         elif value.dtype is not None:
---> 70             self._trace[chain] = zeros((length,) + shape(value), value.dtype)
     71 
     72         # Otherwise, if it's an array, read off its value's dtype.

MemoryError: ```
