### ISSUE TITLE
Dirichlet with "dims" instead of "shape" produces many warnings

### ISSUE THREAD

**Issue by JonAnCla** [pymc-devs/pymc#6217]
## Description of your problem

(as always, thanks for the amazing library :))

Using a Dirichlet distribution with "dims" instead of "shape" arg produces lots of warnings about not being able to infer shape.

The model does run though.

If I replace Dirichlet with Beta with same dims, or specify shape arg instead of "dims" arg, no warnings are generated.

I suspect the issue is a combination of:
- Dirichlet distribution has something funny going on with how it works out its shape when it is given "dims" arg
- sharedvar.value (instead of get_value - .value is deprecated) is used somewhere within aesara - though attempting to fix that caused an Exception to occur instead and the model then did not run - see aesara-devs/aesara#1255 which I posted for this yesterday

Sample code that generates the issue below

```python
with pymc.Model() as model:
    model.add_coord(name = 'time_window_dim',
                     values = [0, 1],
                     mutable = True)
    model.add_coord(name = 'type_dim',
                     values = ['A', 'B', 'C', 'D'],
                     mutable = True)
    
    years = pymc.MutableData('years',
                             numpy.array([[1, 2, 2, 1]]*2, dtype = float),
                             dims = ('time_window_dim', 'type_dim'))
    rates = pymc.Dirichlet('rates',
                           a = numpy.ones(4),
                           dims = ('time_window_dim', 'type_dim',))
    
    compounded_rates = rates*years
    
    pymc.find_MAP()  # pymc.sample() produces endless warnings of the same type listed in traceback below
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
/..../aesara/tensor/rewriting/shape.py:169: UserWarning: Failed to infer_shape from Op Elemwise{true_div,no_inplace}.
Input shapes: [(time_window_dim, TensorConstant{1}), (TensorConstant{1}, TensorConstant{1})]
Exception encountered during infer_shape: <class 'Exception'>
Exception message: sharedvar.value does not exist anymore. Use sharedvar.get_value() or sharedvar.set_value() instead.
Traceback: Traceback (most recent call last):
  File "/..../aesara/tensor/rewriting/shape.py", line 145, in get_node_infer_shape
    o_shapes = shape_infer(
  File "/..../aesara/tensor/elemwise.py", line 834, in infer_shape
    out_shape = aesara.tensor.broadcast_shape(*i_shapes, arrays_are_shapes=True)
  File "/..../aesara/tensor/extra_ops.py", line 1459, in broadcast_shape
    return broadcast_shape_iter(arrays, **kwargs)
  File "/..../aesara/tensor/extra_ops.py", line 1492, in broadcast_shape_iter
    array_shapes = [
  File "/..../aesara/tensor/extra_ops.py", line 1494, in <listcomp>
    + tuple(
  File "/..../aesara/tensor/extra_ops.py", line 1496, in <genexpr>
    if getattr(sh, "value", sh) == 1
  File "/..../aesara/compile/sharedvalue.py", line 207, in _value_get
    raise Exception(
Exception: sharedvar.value does not exist anymore. Use sharedvar.get_value() or sharedvar.set_value() instead.

  warn(msg)
/..../aesara/tensor/rewriting/shape.py:169: UserWarning: Failed to infer_shape from Op Elemwise{mul,no_inplace}.
Input shapes: [(TensorConstant{1}, TensorConstant{1}), (time_window_dim, TensorConstant{1})]
Exception encountered during infer_shape: <class 'Exception'>
Exception message: sharedvar.value does not exist anymore. Use sharedvar.get_value() or sharedvar.set_value() instead.
Traceback: Traceback (most recent call last):
  File "/..../aesara/tensor/rewriting/shape.py", line 145, in get_node_infer_shape
    o_shapes = shape_infer(
  File "/..../aesara/tensor/elemwise.py", line 834, in infer_shape
    out_shape = aesara.tensor.broadcast_shape(*i_shapes, arrays_are_shapes=True)
  File "/..../aesara/tensor/extra_ops.py", line 1459, in broadcast_shape
    return broadcast_shape_iter(arrays, **kwargs)
  File "/..../aesara/tensor/extra_ops.py", line 1492, in broadcast_shape_iter
    array_shapes = [
  File "/..../aesara/tensor/extra_ops.py", line 1494, in <listcomp>
    + tuple(
  File "/..../aesara/tensor/extra_ops.py", line 1496, in <genexpr>
    if getattr(sh, "value", sh) == 1
  File "/..../aesara/compile/sharedvalue.py", line 207, in _value_get
    raise Exception(
Exception: sharedvar.value does not exist anymore. Use sharedvar.get_value() or sharedvar.set_value() instead.

  warn(msg)
```

</details>

## Versions and main components

* PyMC/PyMC3 Version: 4.2.2
* Aesara/Theano Version: 2.8.7
* Python Version: 3.10.2
* Operating system: Ubuntu 20.04
* How did you install PyMC/PyMC3: pip

**Comment by ricardoV94** [comment]
Closing this as it was solved upstream in Aesara
