### ISSUE TITLE
5.0.1 auto-build on conda-forge fails ModuleNotFoundError: No module named 'pytensor.graph.replace'

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#6409]
### Describe the issue:

https://github.com/conda-forge/pymc-feedstock/pull/70

From:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=632169&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

```
import: 'pymc'
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/test_tmp/run_test.py", line 2, in <module>
    import pymc
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/__init__.py", line 49, in <module>
    from pymc import _version, gp, ode, sampling
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/gp/__init__.py", line 15, in <module>
    from pymc.gp import cov, mean, util
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/gp/util.py", line 30, in <module>
    from pymc.distributions.distribution import Distribution
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/distributions/__init__.py", line 15, in <module>
    from pymc.distributions.logprob import (  # isort:skip
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/distributions/logprob.py", line 25, in <module>
    from pymc.logprob.abstract import assign_custom_measurable_outputs
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/logprob/__init__.py", line 48, in <module>
    import pymc.logprob.transforms
  File "/home/conda/feedstock_root/build_artifacts/pymc-suite_1671632408232/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pymc/logprob/transforms.py", line 50, in <module>
    from pytensor.graph.replace import clone_replace
ModuleNotFoundError: No module named 'pytensor.graph.replace'
```

### Reproduceable code example:

```python
asdf
```

### PyMC version information:

5.0.1

**Comment by michaelosthege** [comment]
looks like this was fixed in the feedstock
