### ISSUE TITLE
BUG: Bambi logistic regression fails on M1 silicon

### ISSUE THREAD

**Issue by tarmojuristo** [pymc-devs/pymc#6415]
### Describe the issue:

Running a logistic regression in Bambi with default settings fails. However, if `chains=1` is set in `model.fit()` then everything works fine.

### Reproduceable code example:

```python
import bambi as bmb
import numpy as np

data = bmb.load_data("adults")

age_mean = np.mean(data["age"])
age_std = np.std(data["age"])

data["age"] = (data["age"] - age_mean) / age_std

model = bmb.Model("income['>50K'] ~ sex + age", data, family="bernoulli")
fitted = model.fit(draws=1000)
```

### Error message:

```shell
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, sex, age]
Traceback (most recent call last):000 00:00<? Sampling 4 chains, 0 divergences]
  File "/Users/tarmo/Desktop/SALK/streamlit-model/example.py", line 12, in <module>
    fitted = model.fit(draws=1000)
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/bambi/models.py", line 271, in fit
    return self.backend.run(
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/bambi/backend/pymc.py", line 98, in run
    result = self._run_mcmc(
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/bambi/backend/pymc.py", line 289, in _run_mcmc
    idata = pm.sample(
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/pymc/sampling/mcmc.py", line 529, in sample
    mtrace = _mp_sample(**sample_args, **parallel_args)
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/pymc/sampling/mcmc.py", line 1019, in _mp_sample
    for draw in sampler:
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/pymc/sampling/parallel.py", line 449, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/site-packages/pymc/sampling/parallel.py", line 320, in recv_draw
    msg = ready[0].recv()
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/tarmo/mambaforge/envs/pymc/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

### PyMC version information:

PyMC 5.0.1
PyTensor 2.8.11
Python 3.10
MacOS Ventura 13.0.1 on M1
mambaforge

**Comment by twiecki** [comment]
Does a super simple model
```
with pm.Model():
    x = pm.Normal("x")
    pm.sample()
```

also produce that error?

**Comment by tarmojuristo** [comment]
> 

no, this works fine. also the [bambi t-test example](https://bambinos.github.io/bambi/notebooks/t-test.html) samples without problems.

**Comment by tomicapretto** [comment]
@tarmojuristo could you try with this example?

```python

import numpy as np
import pymc as pm

size = 100
rng = np.random.default_rng(1234)
x = rng.normal(size=size)
g = rng.choice(list("ABC"), size=size)
y = rng.integers(0, 1, size=size, endpoint=True)

g_levels, g_idxs = np.unique(g, return_inverse=True)
coords = {"group": g_levels}

with pm.Model(coords=coords) as model:
    coef_x = pm.Normal("x")
    coef_g = pm.Normal("g", dims="group")
    p = pm.math.softmax(coef_x + coef_g[g_idxs])
    pm.Bernoulli("y", p=p, observed=y)
    idata = pm.sample()
```

**Comment by tarmojuristo** [comment]
all good: Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 1 seconds.

**Comment by tomicapretto** [comment]
If you agree, I can give you a couple of examples you can try until we find the broken part. 

What if you do 

```python
import bambi as bmb
import numpy as np
import pymc as pm

data = bmb.load_data("adults")

age_mean = np.mean(data["age"])
age_std = np.std(data["age"])

data["age"] = (data["age"] - age_mean) / age_std

model = bmb.Model("income['>50K'] ~ sex + age", data, family="bernoulli")
model.build()
with model.backend.model:
    idata = pm.sample()
```

**Comment by tarmojuristo** [comment]
this one fails with the same error

**Comment by tomicapretto** [comment]
Ok! Later today I'll give another chunk of PyMC code to test. I'll try to reproduce the PyMC model created by Bambi more closely

**Comment by tarmojuristo** [comment]
> Make sure to avoid model code on the 0th indent level. This can lead to recursion problems with multiprocessing depending on the OS-dependent fork/spawn setting.
> 
> Just wrap everything in a simple `run()` function:
> 
> ```python
> def run():
>     # do stuff
> 
> 
> if __name__ == "__main__":
>     run()
> ```

Thanks, this is a useful tip - definitely avoids some trouble on my intel-based macbook - but on M1 the above example still fails, even when wrapped into a function.

**Comment by ivanmkc** [comment]
+1, I get this error as well when using a Jupyter notebook.

**Comment by tomicapretto** [comment]
```python
import bambi as bmb
import pandas as pd
import numpy as np
import pymc as pm
import pytensor.tensor as pt

from formulae import design_matrices

data = bmb.load_data("adults")

age_mean = np.mean(data["age"])
age_std = np.std(data["age"])

data["age"] = (data["age"] - age_mean) / age_std

def logit(x):
    """Logit function that ensures result is in (0, 1)"""
    eps = np.finfo(float).eps
    result = pt.sigmoid(x)
    result = pt.switch(pt.eq(result, 0), eps, result)
    result = pt.switch(pt.eq(result, 1), 1 - eps, result)
    return result

dm = design_matrices("income['>50K'] ~ sex + age", data)
y = np.array(dm.response)
X = np.array(dm.common)

coords = {"sex_dim": ["Male"]}
with pm.Model(coords=coords) as pm_model:
    eta = 0
    intercept = pm.Normal("intercept", mu=0, sigma=4.34)
    sex = pt.atleast_1d(pm.Normal("sex", mu=0, sigma=5.31, dims="sex_dim"))
    age = pt.atleast_1d(pm.Normal("age", mu=0, sigma=2.5, shape=None))
    
    # Concatenate parameters
    coefs = pt.concatenate([sex, age])
    
    # Create linear predictor
    eta += intercept 
    eta += pt.dot(X[:, 1:], coefs) # drop first column because that's for the intercept

    # Use inverse of link function
    p = logit(eta)

    pm.Bernoulli("income", p=p, observed=y)
```

This resembles much more closely what's happening under the hood. Could you run it and let me know if it works or fails?

```python
pm.model_to_graphviz(pm_model)
```

![image](https://user-images.githubusercontent.com/25507629/216043438-63b59e24-f230-4c27-9d6d-96579a51a1e0.png)

**Comment by tomicapretto** [comment]
Now I think we can try "removing" parts that may be conflicting. I would start with the `dims` for `sex` or the replacing the custom `logit` function with `pt.sigmoid`

**Comment by tarmojuristo** [comment]
`pt.sigmoid(eta)` gives the same EOF error.

I am not quite sure how should I remove dims here though.

**Comment by tomicapretto** [comment]
Try 

```python
    sex = pm.Normal("sex", mu=0, sigma=5.31)
    age = pm.Normal("age", mu=0, sigma=2.5)
    coefs = pt.stack([sex, age])
```

and 
```python
    sex = pt.atleast_1d(pm.Normal("sex", mu=0, sigma=5.31))
    age = pt.atleast_1d(pm.Normal("age", mu=0, sigma=2.5))
    coefs = pt.concatenate([sex, age])
```

**Comment by davipatti** [comment]
(Potentially related / helpful)

I was getting an identical `EOFError` whilst using pymc 5.1.1 directly to implement a survival model. For testing I had generated a dataset with 10,000 observations. Reducing the number of observations to 1,000 resolved the `EOFError` and allowed me to sample from the model.

**Comment by tomicapretto** [comment]
@tarmojuristo is this still a problem?

**Comment by tomicapretto** [comment]
@jvparidon does it happen to you in the following cases too?

1. Using a Python script, put the sampling statement inside the following condition

```python
if __name__ == "__main__":
    with model:
        idata = pm.sample()
```

2. Using a Jupyter Notebook?

**Comment by jvparidon** [comment]
Neither of those fixes the problem. What _does_ work is passing `mp_ctx='forkserver'` as an argument to the `.fit()`. That changes the multiprocessing context for `pm.sample()` from `fork` to `forkserver`. Unfortunately I'm not familiar enough with the multiprocessing internals to know _why_ that fixes things or if there are any risks to changing the multiprocessing context.

**Comment by tomicapretto** [comment]
I'm sorry but I'm not familiar with that either. Do you think we could write that model in PyMC and, if the issue persists, we open an issue in the PyMC repository?

**Comment by jvparidon** [comment]
I'll try to create a minimal working example in PyMC this weekend and do a little poking around to see if switching to `forkserver` for the multiprocessing context breaks anything obvious. I'll make sure to loop you in if I open an issue or PR.

**Comment by tomicapretto** [comment]
@jvparidon if you have the bambi model and some data that can be used, I could do it for you :)

**Comment by tomicapretto** [comment]
> I'm sorry but I'm not familiar with that either. Do you think we could write that model in PyMC and, if the issue persists, we open an issue in the PyMC repository?

Just realize we're in the PyMC repo :sweat_smile:

**Comment by jvparidon** [comment]
Yeah, as it turns out it _is_ a PyMC issue so that's convenient.
