### ISSUE TITLE
ERROR (aesara.graph.opt): Optimization failure due to: constant_folding

### ISSUE THREAD

**Issue by arainboldt** [pymc-devs/pymc#6449]
### Describe the issue:

getting the below error

### Reproduceable code example:

```python
import pymc as pm

with pm.Model() as model_1:
    pl_fe = pm.Normal("pl_fe", mu=0, sigma=100)
    key_fe = pm.Normal("key_fe", mu=0, sigma=100)
    comp_fe = pm.Normal("comp_fe", mu=0, sigma=100)

    n2_t = pm.Deterministic("n2_t", pm.math.constant(124 // 2))
    n3_t = pm.Deterministic("n3_t", pm.math.constant(300))

    key2_fe = pm.Normal("key2_fe", mu=key_fe, sigma=20 / n2_t)
    key3_fe = pm.Normal("key3_fe", mu=key_fe, sigma=20 / n3_t)
    
    diff2_fe = pm.Deterministic("diff2_fe", key2_fe - pl_fe)
    diff3_fe = pm.Deterministic("diff3_fe", key3_fe - comp_fe)
    
    go3 = pm.Deterministic("go3", diff2_fe > 0.1)
    est = pm.Deterministic("est", diff3_fe > 0.05)
    trace_1 = pm.sample(SAMPLES//SPEEDUP, tune=TUNE_SAMPLES//SPEEDUP, return_inferencedata=False, random_seed=DEFAULT_RS)
```

### Error message:

```shell
ERROR (aesara.graph.opt): Optimization failure due to: constant_folding
ERROR (aesara.graph.opt): node: Elemwise{Cast{float64}}(TensorConstant{20})
ERROR (aesara.graph.opt): TRACEBACK:
ERROR (aesara.graph.opt): Traceback (most recent call last):
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/graph/opt.py", line 1861, in process_node
    replacements = lopt.transform(fgraph, node)
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/graph/opt.py", line 1066, in transform
    return self.fn(fgraph, node)
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/tensor/basic_opt.py", line 2784, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1198, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1133, in __compile__
    thunk, module = self.cthunk_factory(
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1629, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 1228, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1538, in compile_cmodule
    module = c_compiler.compile_str(
  File "/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 2639, in compile_str
    raise CompileError(
aesara.link.c.exceptions.CompileError: Compilation failed (return status=1):
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=tigerlake -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -msha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mno-sgx -mbmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mavx512f -mno-avx512er -mavx512cd -mno-avx512pf -mno-prefetchwt1 -mclflushopt -mxsavec -mxsaves -mavx512dq -mavx512bw -mavx512vl -mavx512ifma -mavx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mclwb -mno-mwaitx -mno-clzero -mpku -mrdpid -mgfni -mshstk -mavx512vbmi2 -mavx512vnni -mvaes -mvpclmulqdq -mavx512bitalg -mavx512vpopcntdq -mmovdiri -mmovdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite --param l1-cache-size=48 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=tigerlake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/numpy/core/include -I/usr/include/python3.8 -I/home/andrew/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/aesara/link/c/c_code -L/usr/lib -fvisibility=hidden -o /home/andrew/.aesara/compiledir_Linux-5.14--oem-x86_64-with-glibc2.29-x86_64-3.8.10-64/tmp3zy_ij50/m2cde54be1dc2f3cdfc238fb89abd4712076f922adcbb6fb22b17b62cfab0ad6a.so /home/andrew/.aesara/compiledir_Linux-5.14--oem-x86_64-with-glibc2.29-x86_64-3.8.10-64/tmp3zy_ij50/mod.cpp -lpython3.8
/home/andrew/.aesara/compiledir_Linux-5.14--oem-x86_64-with-glibc2.29-x86_64-3.8.10-64/tmp3zy_ij50/mod.cpp:1:10: fatal error: Python.h: No such file or directory
    1 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.

```
```


### PyMC version information:

pymc: 4.1.4
ubuntu 20.04
python 3.8.16


### Context for the issue:

_No response_

**Comment by ricardoV94** [comment]
Do you see this problem when running a python script directly from the terminal (instead of an IPython/ Jupyter environment) ?

**Comment by ricardoV94** [comment]
Closing, let us know if the issue persisted
