### ISSUE TITLE
BUG: sample_numpyro_nuts raises an XLARuntimeError

### ISSUE THREAD

**Issue by AlexRodis** [pymc-devs/pymc#6532]
### Describe the issue:

After a recent batch on linux updates `sample_numpyro_nuts` not longer works with a gpu setup. Instead it raises the an XLARuntimeError

The CPU default which comes with `pymc` works fine, its the GPU that has the issue. jax seems to register the gpu just fine:
```
import jax
jax.default_backend()
# 'gpu'
jax.devices()
# [StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)]
```

Reporting here because `jax` itself seems to be functioning normally

### Reproduceable code example:

```python
import pymc
import numpy
from pymc.sampling.jax import sample_numpyro_nuts

x=np.linspace(1,10)
y=2*x
with pymc.Model() as model:
    w = pymc.Normal('w',0,2)
    f = pymc.Deterministic('f', w*x)
    y_obs =pymc.Normal('y_obs', mu = f, sigma=1, observed=y)

with model:
  idata=sample_numpyro_nuts()
# Raises an error
```

### Error message:

```shell
-02-18 13:11:12.819931: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded runtime CuDNN library: 8.4.1 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-02-18 13:11:12.970054: E external/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:627) dnn != nullptr 
*** Begin stack trace ***
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	_PyObject_MakeTpCall
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	PyEval_EvalCode
	
	
	
	_PyRun_SimpleFileObject
	_PyRun_AnyFileObject
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	_start
*** End stack trace ***

Traceback (most recent call last):
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/test.py", line 13, in <module>
    idata = sample_numpyro_nuts()
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/pymc/sampling/jax.py", line 638, in sample_numpyro_nuts
    map_seed = jax.random.PRNGKey(random_seed)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/random.py", line 136, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/prng.py", line 267, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/prng.py", line 570, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/core.py", line 343, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/core.py", line 346, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/core.py", line 789, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/prng.py", line 582, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/prng.py", line 587, in random_seed_impl_base
    return seed(seeds)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/prng.py", line 822, in threefry_seed
    lax.shift_right_logical(seed, lax_internal._const(seed, 32)))
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 511, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/core.py", line 343, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/core.py", line 346, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/core.py", line 789, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 123, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 202, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 355, in _xla_callable_uncached
    return computation.compile(_allow_propagation_to_outputs=allow_prop).unsafe_call
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 3254, in compile
    executable = self._compile_unloaded(
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 3225, in _compile_unloaded
    return UnloadedMeshExecutable.from_hlo(
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 3512, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 1095, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/Olive Oil/cudnn_test/venv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 1040, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:627) dnn != nullptr
```

### PyMC version information:

pymc version = 5.0.2
pytensor version = 2.9.1

### Context for the issue:

When working with most non-trivial models i.e. Neural Networks and Multioutput Gaussian Processes the default sampler is simply too slow to be practically usefull. For these for these cases `sample_numpyro_nuts` is pretty much necessary

**Comment by ricardoV94** [comment]
Sounds like an issue in your installation of Jax. PyMC does not have anything to do with it's installation.

Can you use numpyro directly or do you find the same issues?

**Comment by AlexRodis** [comment]
I can import it but beyond that it have no idea what numpyro itself does. Some other things I have tried:
* reinstalling pymc
* reinstalling jax and jaxlib
* reinstalling numpyro
* running in different environtments (vscode and directly from the console)

It seems artificially downgrading `jax` and `jaxlib` to these exact versions works, which seems strange:
```
jax==0.4.1
jaxlib==0.4.1+cuda11.cudnn86
```
Regardless, considering the massive performance boosts from `sample_numpyro_nuts` I think a pymc version packaged wtih gpu support would be incredibly helpful for many users

**Comment by ricardoV94** [comment]
Numpyro implements NUTS sampling in JAX, you can try to run their starting example to see if the problem is on the PyMC side or just your local installation: https://num.pyro.ai/en/stable/getting_started.html

**Comment by AlexRodis** [comment]
The same error appears on this line:
```
rng_key = random.PRNGKey(0)
```

**Comment by ricardoV94** [comment]
That means Jax is not properly installed on your end. It has nothing to do with PyMC

**Comment by AlexRodis** [comment]
Alright, then I'll close this. For future reference setting `XLA_PYTHON_CLIENT_PREALLOCATE=false` on the notebook (not the shell), prior to any imports and explicitly using these version seems to fix the issue:
```
jax==0.4.1
jaxlib==0.4.1+cuda11.cudnn86
```
