### ISSUE TITLE
BUG: VI for BNN demo does not work

### ISSUE THREAD

**Issue by murphyk** [pymc-devs/pymc#6553]
### Describe the issue:

I am trying to run https://www.pymc.io/projects/examples/en/latest/variational_inference/bayesian_neural_network_advi.html
When running `neural_network = construct_nn(X_train, Y_train)` I get the error
```
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding...
```

### Reproduceable code example:

```python
Just run https://www.pymc.io/projects/examples/en/latest/variational_inference/bayesian_neural_network_advi.html
on a fresh install.
```

### Error message:

```shell
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Subtensor{int64}(TensorConstant{[2 5]}, ScalarConstant{0})
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/graph/rewriting/basic.py", line 1925, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/graph/rewriting/basic.py", line 1084, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/tensor/rewriting/basic.py", line 1141, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/link/c/op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/link/c/op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
              ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/link/c/basic.py", line 1202, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
                                                             ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages/pytensor/link/c/basic.py", line 1122, in __compile__
    thunk, module = self.cthunk_factory(
                    ^^^^^^^^^^^^^^^^^^^^
...
              ^~~~~~~~~~
1 error generated.
```

### PyMC version information:

pm '5.0.2'

pytensor '2.9.1'

Installed on my macbook pro following https://www.pymc.io/projects/docs/en/latest/installation.html

```
conda create -c conda-forge -n pymc_env "pymc>=4"
conda activate pymc_env
```

Note: if I `pip install pytensor` in colab, the code works.
So I tried `pip install pytensor` in my conda environment, but it's a no-op (see output below)
```
pymc_env) kpmurphy@kpmurphy-macbookpro1 ~ % pip install pytensor
Requirement already satisfied: pytensor in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (2.9.1)
Requirement already satisfied: setuptools>=48.0.0 in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (67.4.0)
Requirement already satisfied: scipy>=0.14 in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (1.10.1)
Requirement already satisfied: numpy>=1.17.0 in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (1.24.2)
Requirement already satisfied: filelock in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (3.9.0)
Requirement already satisfied: etuples in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (0.3.8)
Requirement already satisfied: logical-unification in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (0.4.5)
Requirement already satisfied: miniKanren in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (1.0.3)
Requirement already satisfied: cons in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (0.4.5)
Requirement already satisfied: typing-extensions in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from pytensor) (4.4.0)
Requirement already satisfied: toolz in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from logical-unification->pytensor) (0.12.0)
Requirement already satisfied: multipledispatch in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from logical-unification->pytensor) (0.6.0)
Requirement already satisfied: six in /opt/anaconda3/envs/pymc_env/lib/python3.11/site-packages (from multipledispatch->logical-unification->pytensor) (1.16.0)
```

**Comment by twiecki** [comment]
Looks like a pytensor bug, @ricardoV94 any ideas?

**Comment by ricardoV94** [comment]
I think it's a Mac installation issue, there were a couple of threads on discourse, but I don't have their link. CC @jessegrabowski?

**Comment by jessegrabowski** [comment]
[Here's an identical problem reported ](https://discourse.pymc.io/t/pytensor-compilation-error/11047/7?u=jessegrabowski)with my solutions underneath.

There's also [this thread ](https://discourse.pymc.io/t/unlinked-header-file-in-new-pymc5-install/11402)that solved some OSX C compiler stuff a slightly different way.

I'm pretty sure it all reduces to 1) install X-Code Command Line Tools and 2) Add the compiler to path, but there seems to be some heterogeneity in how people do (2).
