### ISSUE TITLE
Fix arbitrary distribution example in PyMC overview

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#6603]
### Describe the issue:

Suppose there are three independent normal variables and their means are 0 and their standard deviations have independent logarithmic priors. Suppose we have one observation for each, 1.0, 1e6 and 1e-4. Sampling causes PyMC to raise `pymc.exceptions.SamplingError`.

How the logarithmic priors are specified is based on the first example in the section ['Arbitrary Distributions'](https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/pymc_overview.html#arbitrary-distributions) of the notebook 'Introductory Overview of PyMC'.

The error occurs if there are _three_ variables, as in the reproduceable code example, but not if there are _two_, as in
```python3
import pymc as pm


def abs_log_minus(tensor):
    return -pm.math.log(pm.math.abs(tensor))


with pm.Model():
    std = pm.CustomDist("std", logp=abs_log_minus, shape=(2,))
    pm.Normal("y", 0, std, observed=[1.0, 1e6])
    pm.sample(random_seed=0)
```

### Reproduceable code example:

```python
import pymc as pm


def abs_log_minus(tensor):
    return -pm.math.log(pm.math.abs(tensor))


with pm.Model():
    std = pm.CustomDist("std", logp=abs_log_minus, shape=(3,))
    pm.Normal("y", 0, std, observed=[1.0, 1e6, 1e-4])
    pm.sample(random_seed=0)
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/jdawson/Documents/PyMC-bug/./bug.py", line 12, in <module>
    pm.sample(random_seed=0)
  File "/home/jdawson/Documents/PyMC-bug/.venv/lib/python3.11/site-packages/pymc/sampling/mcmc.py", line 619, in sample
    model.check_start_vals(ip)
  File "/home/jdawson/Documents/PyMC-bug/.venv/lib/python3.11/site-packages/pymc/model.py", line 1779, in check_start_vals
    raise SamplingError(
pymc.exceptions.SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'std': array([ 0.17563482,  0.95619595, -0.09898284])}

Initial evaluation results:
{'std': 4.1, 'y': -inf}
```

### PyMC version information:

* PyMC 5.1.2
* PyTensor 2.10.1
* Python 3.11
* Ubuntu 20.04.5 LTS

PyMC was installed with
`pip install pymc`

**Comment by ricardoV94** [comment]
Closing this as it's a user question and a Discourse topic was opened already. 

I answered there, it isn't a bug just a model issue (negative sigma). Feel free to continue the discussion on Discourse.

**Comment by JDawson-Camlin** [comment]
@ricardoV94, I used PyMC as the documentation I linked to above [instructs](https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/pymc_overview.html#arbitrary-distributions).
```python
import pytensor.tensor as at

with pm.Model() as model:
    alpha = pm.Uniform('intercept', -100, 100)
    
    # Create custom densities
    beta = pm.DensityDist('beta', logp=lambda value: -1.5 * at.log(1 + value**2))
    eps = pm.DensityDist('eps', logp=lambda value: -at.log(at.abs_(value)))
    
    # Create likelihood
    like = pm.Normal('y_est', mu=alpha + beta * X, sigma=eps, observed=Y)
```
Since I used PyMC as the documentation instructs and it does not work, there is a bug, in either the [code](https://github.com/pymc-devs/pymc/blob/main/pymc/distributions/continuous.py#L522) or the [documentation](https://github.com/pymc-devs/pymc/blob/main/docs/source/learn/core_notebooks/pymc_overview.ipynb) and this issue ought to be reopened.

**Comment by ricardoV94** [comment]
That overview still has other problems like the use of `self` in the `logp` method just some lines below...
