### ISSUE TITLE
TestHDF5 in 2.3.4: tight dependency on recent tables in the tests

### ISSUE THREAD

**Issue by yarikoptic** [pymc-devs/pymc#665]
Few of my builds for neurodebian failed with

```
======================================================================
ERROR: test suite for <class 'pymc.tests.test_database.TestHDF5'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 469, in try_run
    return func()
  File "/tmp/buildd/pymc-2.3.4+ds/build/lib.linux-x86_64-2.7/pymc/tests/test_database.py", line 311, in setUpClass
    dbmode='w')
  File "/tmp/buildd/pymc-2.3.4+ds/build/lib.linux-x86_64-2.7/pymc/MCMC.py", line 82, in __init__
    **kwds)
  File "/tmp/buildd/pymc-2.3.4+ds/build/lib.linux-x86_64-2.7/pymc/Model.py", line 207, in __init__
    self._assign_database_backend(db)
  File "/tmp/buildd/pymc-2.3.4+ds/build/lib.linux-x86_64-2.7/pymc/Model.py", line 574, in _assign_database_backend
    self.db = module.Database(**self._db_args)
  File "/tmp/buildd/pymc-2.3.4+ds/build/lib.linux-x86_64-2.7/pymc/database/hdf5.py", line 276, in __init__
    self._h5file = tables.open_file(self.dbname, self.mode)
AttributeError: 'module' object has no attribute 'open_file'
```

```
pymc_2.3.4+ds-1~nd13.10+1_amd64.build:AttributeError: 'module' object has no attribute 'open_file'
pymc_2.3.4+ds-1~nd13.10+1_i386.build:AttributeError: 'module' object has no attribute 'open_file'
pymc_2.3.4+ds-1~nd70+1_amd64.build:AttributeError: 'module' object has no attribute 'open_file'
pymc_2.3.4+ds-1~nd70+1_i386.build:AttributeError: 'module' object has no attribute 'open_file'
```

with pytables as old as 2.3.1-3  on wheezy (nd70) so might be nice if test was skipped on those elderly deployments. Cheers

**Comment by twiecki** [comment]
Moved to https://github.com/pymc-devs/pymc/issues/8.
