### ISSUE TITLE
BUG: arviz.plot_lm fails on pymc models

### ISSUE THREAD

**Issue by pdb5627** [pymc-devs/pymc#6704]
### Describe the issue:

Posterior plots using `arviz.plot_lm` fails on a basic pymc model from the example. This was previously reported in #6446.

After some digging, I believe that `arviz.plot_lm` fails to work because it sets `skip_dims` based on the variable plotted as y and then applies the same `skip_dims` to y_hat, whereas the dimensions get named differently. For example, for a variable "y", the dimension in the `idata.observed_data` is named `y_dim_0` but in `idata.posterior_predictive` it is named `y_dim_2`.

I don't know whether it is pymc or arviz that sets the dimension names and whether it is reasonable for arviz to expect the dimensions in the different groups of idata to be named the same. Maybe this is an arviz bug rather than a pymc bug.

Renaming the dimension in `idata.posterior_predictive` is enough to get `arviz.plot_lm` to work.

### Reproduceable code example:

```python
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pymc as pm

print(f"Running on PyMC v{pm.__version__}")
print(f"Running on arviz v{az.__version__}")

# Initialize random number generator
RANDOM_SEED = 8927
rng = np.random.default_rng(RANDOM_SEED)


# True parameter values
alpha, sigma = 1, 1
beta = [1, 2.5]

# Size of dataset
size = 100

# Predictor variable
X = np.random.randn(size)

# Simulate outcome variable
y_obs = alpha + beta[0] * X + rng.normal(size=size) * sigma


basic_model = pm.Model()

with basic_model:
    # Input data
    x = pm.MutableData("x", X)

    # Priors for unknown model parameters
    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta = pm.Normal("beta", mu=0, sigma=10)
    sigma = pm.HalfNormal("sigma", sigma=1)

    # Expected value of outcome
    y_model = pm.Deterministic('y_model', alpha + beta * x)

    # Likelihood (sampling distribution) of observations
    y = pm.Normal("y", mu=y_model, sigma=sigma, observed=y_obs)
    
    
    idata = pm.sample()
    idata.extend(pm.sample_posterior_predictive(idata))
    
    try:
        az.plot_lm(x='x', y='y', y_model='y_model', y_hat='y', idata=idata, kind_pp='hdi')
        print('Success!!')
    except TypeError as e:
        print('Error!!')
        print(e)
        print('Renaming dimension of idata.posterior_predictive["y"]  y_dim_2 to y_dim_0 and trying again')
        idata.posterior_predictive['y'] = idata.posterior_predictive['y'].rename({'y_dim_2': 'y_dim_0'})
        az.plot_lm(x='x', y='y', y_model='y_model', y_hat='y', idata=idata, kind_pp='hdi')
        print('Success after renaming dimension of y in idata.posterior_predictive')
        plt.show()
```

### Error message:

```shell
<details>
Traceback (most recent call last):
  File "/home/pdb5627/pymc-dev/bug_demo.py", line 52, in <module>
    az.plot_lm(x='x', y='y', y_model='y_model', y_hat='y', idata=idata, kind_pp='hdi')
  File "/home/pdb5627/pymc-dev/src/arviz/arviz/plots/lmplot.py", line 354, in plot_lm
    ax = plot(**lmplot_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pdb5627/pymc-dev/src/arviz/arviz/plots/backends/matplotlib/lmplot.py", line 111, in plot_lm
    plot_hdi(x_plotters, y_hat_plotters, ax=ax_i, **y_hat_fill_kwargs)
  File "/home/pdb5627/pymc-dev/src/arviz/arviz/plots/hdiplot.py", line 168, in plot_hdi
    raise TypeError(msg.format(x_shape, hdi_shape))
TypeError: Dimension mismatch for x: (100,) and hdi: (1000, 2). Check the dimensions of y andhdi_kwargs to make sure they are compatible
</details>
```

### PyMC version information:

<details>
PyMC v5.3.1+2.g5cf7efe2
arviz v0.16.0.dev0
pytensor 2.11.2
xarray 2023.4.2
Python 3.11.3
Ubuntu 22.04 LTS

Pymc and arviz both installed in miniconda environment via pip from git. Dependencies installed from conda.
</details>

### Context for the issue:

I might be wrong, but it seems like `arviz.plot_lm` should work out-of-the-box with simple pymc models.

**Comment by pdb5627** [comment]
I found that `arviz.plot_lm` works if the dimension of the variables is named when they are created, as such:

```python
basic_model = pm.Model()

with basic_model:
    # Input data
    x = pm.MutableData("x", X, dims='observation')

    # Priors for unknown model parameters
    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta = pm.Normal("beta", mu=0, sigma=10)
    sigma = pm.HalfNormal("sigma", sigma=1)

    # Expected value of outcome
    y_model = pm.Deterministic('y_model', alpha + beta * x, dims='observation')

    # Likelihood (sampling distribution) of observations
    y = pm.Normal("y", mu=y_model, sigma=sigma, observed=y_obs, dims='observation')
```

I don't know that this means there isn't a bug (or at least unexpected behavior) somewhere, but the workaround is easy once one knows to do it.
