### ISSUE TITLE
Investigate failing glm tests

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#671]
No idea why this happens (statmodels gets correclty installed) and I can't reproduce locally. Anyone else?

`````` ======================================================================

ERROR: pymc.tests.test_examples.test_examples1('pymc.examples.glm_linear',)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

self.test(*self.arg)

File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_examples.py", line 13, in check_example

example = __import__(example_name, fromlist='dummy')

File "/home/travis/build/pymc-devs/pymc/pymc/examples/glm_linear.py", line 10, in <module>

sys.exit(0)

SystemExit: 0

-------------------- >> begin captured stdout << ---------------------

Example requires statsmodels

--------------------- >> end captured stdout << ----------------------

======================================================================

ERROR: pymc.tests.test_examples.test_examples1('pymc.examples.glm_robust',)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

self.test(*self.arg)

File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_examples.py", line 13, in check_example

example = __import__(example_name, fromlist='dummy')

File "/home/travis/build/pymc-devs/pymc/pymc/examples/glm_robust.py", line 10, in <module>

sys.exit(0)

SystemExit: 0

-------------------- >> begin captured stdout << ---------------------

Example requires statsmodels```
``````

**Comment by kyleam** [comment]
I'd guess that this is because the statsmodels import is failing due to [this change](https://github.com/scipy/scipy/commit/40e6c840c1957d08dfc7b5916c99d317fa1ca2e6) on scipy's end. There's already a [statsmodels issue](https://github.com/statsmodels/statsmodels/issues/2184) open for this.

```
In [1]: import statsmodels.api as sm
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6030a6549dc0> in <module>()
----> 1 import statsmodels.api as sm

/usr/lib/python3.4/site-packages/statsmodels/api.py in <module>()
     13 from .discrete.discrete_model import (Poisson, Logit, Probit,
     14                                       MNLogit, NegativeBinomial)
---> 15 from .tsa import api as tsa
     16 from .duration.hazard_regression import PHReg
     17 from .nonparametric import api as nonparametric

/usr/lib/python3.4/site-packages/statsmodels/tsa/api.py in <module>()
      3 from . import vector_ar as var
      4 from .arima_process import arma_generate_sample, ArmaProcess
----> 5 from .vector_ar.var_model import VAR
      6 from .vector_ar.svar_model import SVAR
      7 from .vector_ar.dynamic import DynamicVAR

/usr/lib/python3.4/site-packages/statsmodels/tsa/vector_ar/var_model.py in <module>()
     21 from statsmodels.tools.decorators import cache_readonly
     22 from statsmodels.tools.tools import chain_dot
---> 23 from statsmodels.tools.linalg import logdet_symm
     24 from statsmodels.tsa.tsatools import vec, unvec
     25

/usr/lib/python3.4/site-packages/statsmodels/tools/linalg.py in <module>()
     21 #from numpy import matrix as Matrix
     22 from numpy.linalg import LinAlgError
---> 23 from scipy.linalg import calc_lwork
     24
     25

ImportError: cannot import name 'calc_lwork'
```

**Comment by twiecki** [comment]
Thanks @kyleam.

**Comment by twiecki** [comment]
I suppose there's nothing for us to do but wait then so I'll close this.
