### ISSUE TITLE
BUG: value error in pm.set_data()

### ISSUE THREAD

**Issue by wzeng96** [pymc-devs/pymc#6774]
### Describe the issue:

Hi,

I'm working on to build a hierarchical bayesian model with PyMC. I have the trained model saved, however, when I tried to make prediction using the saved model, it always give me this "Value error" saying the array is not in the same length. There's no nans and I already convert the data into `np.asarray()` before putting it into `pm.set_data()`. Could someone help me take a look at this? Any help would be greatly appreciated!

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.`

Thank you.

### Reproduceable code example:

```python
import sys
import logging
import multiprocessing as mp

import pymc as pm
import pandas as pd
import numpy as np
import arviz as az
import pytensor.tensor as pt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn import metrics
from sklearn.preprocessing import StandardScaler,LabelBinarizer
import pickle

def main() -> int:
    logging.basicConfig(stream=sys.stdout, level=logging.INFO)
    logging.info(f"try prediction with updated pymc package")
    mp.set_start_method('forkserver', force=True)

    X_train = pd.read_csv('X_train.csv')
    X_test = pd.read_csv('X_test.csv')
    y_train = pd.read_csv('y_train.csv')
    y_test = pd.read_csv('y_test.csv')
    assay_info_train = pd.read_csv('assay_info_train.csv')
    assay_info_test = pd.read_csv('assay_info_test.csv')
    X4_bayes = X_train
    X_train_v, X_validation, y_train_v, y_validation, assay_info_train_v, assay_info_validation = train_test_split(X_train, y_train, assay_info_train, test_size = 0.2, random_state=42)


    X4_bayes = np.asarray(X4_bayes, dtype="float64")
    print(X4_bayes.shape)

    factorized_protocols = pd.factorize(assay_info_train.ProtocolName)

    print(y_train)
    Y4_bayes = list(y_train['Outcome'])
    coords_simulated = {
        'obs_id': np.arange(X4_bayes.shape[0]),
        'chem_descrip': np.arange(X4_bayes.shape[1]),
        'protocol':list(factorized_protocols[1]),
        'params':['beta_{0}'.format(i) for i in range(X4_bayes.shape[1])]
    }


    organisms = pd.factorize(assay_info_train.drop_duplicates().Organism)
    tissues_4 = pd.factorize(assay_info_train.drop_duplicates().Tissue_Type4)
    tissues_2 = pd.factorize(assay_info_train.drop_duplicates().Tissue_Type2)
    gender = pd.factorize(assay_info_train.drop_duplicates().Gender)
    cell_type = pd.factorize(assay_info_train.drop_duplicates().Cell_Type)


    print('start model setup')
    with pm.Model(coords=coords_simulated) as assay_level_model:
        x = pm.Data('x', X4_bayes, mutable = True)
        protocol_idx = pm.Data("protocol_idx", list(factorized_protocols[0]), mutable=True)
        organism_idx = pm.Data("organism_idx", organisms[0], mutable=True)
        tissue_2_idx = pm.Data("tissue_2_idx", tissues_2[0], mutable=True)
        tissue_4_idx = pm.Data("tissue_4_idx", tissues_4[0], mutable=True)
        gender_idx = pm.Data("gender_idx", gender[0], mutable=True)
        cell_type_idx = pm.Data("cell_type_idx", cell_type[0], mutable=True)

        # prior stddev in intercepts & slopes (variation across protocol):
        sd_dist = pm.Exponential.dist(1.0)
        
        # get back standard deviations and rho:
        chol, corr, stds = pm.LKJCholeskyCov("chol", n=X4_bayes.shape[1], eta=2.0, sd_dist=sd_dist, compute_corr=True)
        
        #hyperpriors and priors for average betas:
        beta_list = []
        for i in range(X4_bayes.shape[1]):
            gbeta = pm.Normal("g_beta_{0}".format(i), mu=0.0, sigma=10.0, shape=6)

            mu_gbeta = gbeta[0] + gbeta[1] * organism_idx + gbeta[2] * tissue_2_idx + gbeta[3] * tissue_4_idx + gbeta[4] * gender_idx + gbeta[5] * cell_type_idx
            sigma_beta = pm.Exponential('sigma_beta_{0}'.format(i),1.0) ## pass the saved lambda from the logistic regression
            betas = pm.Normal('beta_{0}'.format(i), mu=mu_gbeta,sigma=sigma_beta,dims="protocol")
            beta_list.append(betas)

        #population of varying protocol effects:
        beta_protocol = pm.MvNormal("beta_protocol", mu=pt.stack(beta_list, axis=1), chol=chol,dims=('protocol', 'params'))
        
        #Expected value per protocol:
        theta = beta_protocol[protocol_idx,0]* x[:,0]

        for i in range(1,X4_bayes.shape[1]):
            theta += beta_protocol[protocol_idx,i] * x[:,i]

        p = 1.0 / (1.0 + pt.exp(-theta))
        likelihood = pm.Bernoulli('likelihood', p, observed=Y4_bayes, shape = p.shape)
        

    print('Done model setup')
    logging.info('Running model')
    with assay_level_model:
        tr_assay = pd.read_pickle("tr_assay_full_model_40features.pkl")  
    print('read saved trained model')



    print('generate testing data')
    predictors_out_of_sample = X_validation.copy()
    print(predictors_out_of_sample)
    X_validation = np.asarray(X_validation, dtype='float')
    print(X_validation.shape)
    outcomes_out_of_sample = y_validation
    print(outcomes_out_of_sample.shape)


    RANDOM_SEED = 10
    protocol_pred = pd.factorize(assay_info_test.ProtocolName)


    organisms = pd.factorize(assay_info_validation.drop_duplicates().Organism)
    tissues_4 = pd.factorize(assay_info_validation.drop_duplicates().Tissue_Type4)
    tissues_2 = pd.factorize(assay_info_validation.drop_duplicates().Tissue_Type2)
    gender = pd.factorize(assay_info_validation.drop_duplicates().Gender)
    cell_type = pd.factorize(assay_info_validation.drop_duplicates().Cell_Type)

    print('run prediction on current model')
    with assay_level_model:
        pm.set_data(
            new_data = {'x': X_validation,
                        "protocol_idx": list(protocol_pred[0]),
                        "organism_idx": organisms,
                        "tissue_2_idx": tissues_2,
                        "tissue_4_idx": tissues_4,
                        "gender_idx": gender,
                        "cell_type_idx": cell_type
                        }
        )

        posterior_predictive = pm.sample_posterior_predictive(
            tr_assay, var_names=["likelihood"], random_seed=RANDOM_SEED
        )


    return 0

if __name__=="__main__":
    sys.exit(main())
```

### Error message:

```shell
Traceback (most recent call last):
  File "/spin1/home/linux/zengw6/Tox21/PyMC_model_script_numpyro_prediction.py", line 215, in <module>
    sys.exit(main())
             ^^^^^^
  File "/spin1/home/linux/zengw6/Tox21/PyMC_model_script_numpyro_prediction.py", line 164, in main
    pm.set_data(
  File "/gpfs/gsfs8/users/zengw6/conda/envs/pymc/lib/python3.11/site-packages/pymc/model.py", line 2048, in set_data
    model.set_data(variable_name, new_value, coords=coords)
  File "/gpfs/gsfs8/users/zengw6/conda/envs/pymc/lib/python3.11/site-packages/pymc/model.py", line 1187, in set_data
    values = convert_observed_data(values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/gsfs8/users/zengw6/conda/envs/pymc/lib/python3.11/site-packages/pymc/pytensorf.py", line 134, in convert_observed_data
    ret = np.asarray(data)
          ^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

### PyMC version information:

PyMC: 5.4.1
PyTensor: 2.12.1
Aesara: 2.9.0
Python: 3.11.3
Installation: conda

**Comment by ricardoV94** [comment]
Try to pass all data in `pm.set_data` as numpy arrays (I see a list)

**Comment by wzeng96** [comment]
Thank you @ricardoV94 ! I fixed the error, I'll close this issue.
