### ISSUE TITLE
BUG: failed to import pymc on macOS ventura 13.4 using conda env

### ISSUE THREAD

**Issue by EAly** [pymc-devs/pymc#6785]
### Describe the issue:

I've installed pymc v=5.3.0 using mamba in a conda env.
when I try to import pymc, i get the error below:

### Reproduceable code example:

```python
import pymc as pm
```

### Error message:

```shell
<details>
Traceback (most recent call last):
  File "/Users/ea/Documents/codex/BayesModPy/main.py", line 1, in <module>
    import pymc as pm
  File "/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/pymc/__init__.py", line 47, in <module>
    __set_compiler_flags()
  File "/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/pymc/__init__.py", line 30, in __set_compiler_flags
    import pytensor
  File "/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/pytensor/__init__.py", line 119, in <module>
    from pytensor import scalar, tensor
  File "/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/pytensor/scalar/__init__.py", line 2, in <module>
    from .math import *
  File "/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/pytensor/scalar/math.py", line 12, in <module>
    import scipy.special
  File "/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/__init__.py", line 663, in <module>
    from . import _ufuncs
ImportError: dlopen(/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/_ufuncs.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib
  Referenced from: <F5A79DC7-F649-345A-B2A0-4A30409A5D3E> /Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/_ufuncs.cpython-311-darwin.so
  Reason: tried: '/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/liblapack.3.dylib' (no such file), '/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/../../../../liblapack.3.dylib' (no such file), '/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/liblapack.3.dylib' (no such file), '/Users/ea/miniconda3/envs/bayespython/lib/python3.11/site-packages/scipy/special/../../../../liblapack.3.dylib' (no such file), '/Users/ea/miniconda3/envs/bayespython/bin/../lib/liblapack.3.dylib' (no such file), '/Users/ea/miniconda3/envs/bayespython/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)
</details>
```

### PyMC version information:

pymc version: 5.3.0
pytensor version: 2.11.1
python version : 3.11.4
operating system: macOS ventura 13.4
pymc installed using: mamba install -c conda-forge "pymc>=4"

**Comment by fonnesbeck** [comment]
That's an odd one. You can try installing scipy again using `--force-reinstall` to see if that makes a difference. Might also try updating all your conda packages.

**Comment by EAly** [comment]
Thanks @fonnesbeck for your reply, that solved the issue.
