### ISSUE TITLE
RTD is broken

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#7384]
### Description

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
with pm.Model() as model_1:
    a = pm.Normal("a", 0.0, 10.0)
    b = pm.Normal("b", 0.0, 10.0)

    mu = a + b * predictor_scaled
    sigma = pm.Exponential("sigma", 1.0)

    pm.Normal("obs", mu=mu, sigma=sigma, observed=outcome_scaled)
    idata = pm.sample_prior_predictive(draws=50, random_seed=rng)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 9[0m
[1;32m      6[0m sigma [38;5;241m=[39m pm[38;5;241m.[39mExponential([38;5;124m"[39m[38;5;124msigma[39m[38;5;124m"[39m, [38;5;241m1.0[39m)
[1;32m      8[0m pm[38;5;241m.[39mNormal([38;5;124m"[39m[38;5;124mobs[39m[38;5;124m"[39m, mu[38;5;241m=[39mmu, sigma[38;5;241m=[39msigma, observed[38;5;241m=[39moutcome_scaled)
[0;32m----> 9[0m idata [38;5;241m=[39m [43mpm[49m[38;5;241;43m.[39;49m[43msample_prior_predictive[49m[43m([49m[43mdraws[49m[38;5;241;43m=[39;49m[38;5;241;43m50[39;49m[43m,[49m[43m [49m[43mrandom_seed[49m[38;5;241;43m=[39;49m[43mrng[49m[43m)[49m

[0;31mTypeError[0m: sample_prior_predictive() got an unexpected keyword argument 'draws'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 419, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 440, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 497, in read_doc
    publisher.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/sphinx/io.py", line 107, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/myst_nb/sphinx_.py", line 146, in parse
    with create_client(
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/myst_nb/core/execute/base.py", line 79, in __enter__
    self.start_client()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/myst_nb/core/execute/direct.py", line 48, in start_client
    raise ExecutionError(str(self.path)) from result.err
myst_nb.core.execute.base.ExecutionError: /home/docs/checkouts/readthedocs.org/user_builds/pymc/checkouts/7383/docs/source/learn/core_notebooks/posterior_predictive.ipynb

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc/conda/7383/lib/python3.11/site-packages/myst_nb/core/execute/direct.py", line 48, in start_client
    raise ExecutionError(str(self.path)) from result.err
myst_nb.core.execute.base.ExecutionError: /home/docs/checkouts/readthedocs.org/user_builds/pymc/checkouts/7383/docs/source/learn/core_notebooks/posterior_predictive.ipynb
The full traceback has been saved in /tmp/sphinx-err-h29i6cea.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by ricardoV94** [comment]
@twiecki is this related to https://github.com/pymc-devs/pymc/pull/7370#issuecomment-2185832329 ?

**Comment by twiecki** [comment]
> From here? #7383

Yes.

**Comment by ricardoV94** [comment]
I think it's working for a while now?
