### ISSUE TITLE
BUG: jax.core.Shape is deprecated

### ISSUE THREAD

**Issue by dooleyb1** [pymc-devs/pymc#7464]
### Describe the issue:

Hi there,

I'm trying to extend my model to use blackjax as the NUTS sampler `nuts_sampler="blackjax"` and am experiencing some errors from JAX / PyMC. The model runs fine when I remove the `nuts_sampler` param.

```
JAX Version: 0.4.30
```

I'm running the model on AWS SageMaker on using a Docker image (see Dockerfile below) running on an `ml.g5.2xlarge` instance (NVIDIA A10G GPU). 

```

+---------------------------------------------------------------------------------------+
--
\| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     \|
\|-----------------------------------------+----------------------+----------------------+
\| GPU  Name                 Persistence-M \| Bus-Id        Disp.A \| Volatile Uncorr. ECC \|
\| Fan  Temp   Perf          Pwr:Usage/Cap \|         Memory-Usage \| GPU-Util  Compute M. \|
\|                                         \|                      \|               MIG M. \|
\|=========================================+======================+======================\|
\|   0  NVIDIA A10G                    On  \| 00000000:00:1E.0 Off \|                    0 \|
\|  0%   25C    P8               9W / 300W \|      0MiB / 23028MiB \|      0%      Default \|
\|                                         \|                      \|                  N/A \|
+-----------------------------------------+----------------------+----------------------+
+---------------------------------------------------------------------------------------+
\| Processes:                                                                            \|
\|  GPU   GI   CI        PID   Type   Process name                            GPU Memory \|
\|        ID   ID                                                             Usage      \|


```

### Reproduceable code example:

```python
import os
import pymc as pm
import pytensor.tensor as pt
from utils import get_env_int, get_env_float, custom_encode
import logging
import jax

from pymc.sampling.jax import sample_blackjax_nuts

logger = logging.getLogger(__name__)

def maxdiff_logp(best, worst, utilities):
    n_respondents, n_questions = best.shape
    
    idx_respondents = pt.arange(n_respondents).reshape((n_respondents, 1))
    idx_questions = pt.arange(n_questions).reshape((1, n_questions))
    
    best_util = utilities[idx_respondents, idx_questions, best]
    worst_util = utilities[idx_respondents, idx_questions, worst]
    
    # Sum over all attributes except the best and worst
    other_utils = pt.sum(utilities, axis=2) - best_util - worst_util
    
    # Add a small constant for numerical stability
    epsilon = 1e-10
    exp_best = pt.exp(best_util)
    exp_worst = pt.exp(worst_util)
    exp_other = pt.exp(other_utils)
    
    denominator = pt.maximum(exp_best + exp_worst + exp_other, epsilon)
    log_prob = best_util - pt.log(denominator)
    
    return pt.sum(log_prob)

def run_hb_model(best_choices, worst_choices, attributes, respondent_ids, survey_id):

    logger.info(f"JAX Version: {jax.__version__}")

    logger.info(f"JAX Devices:")
    jax.devices()

    logger.info(f"JAX Default Backend:")
    jax.default_backend()
    
    chains = get_env_int('CHAINS', 8)
    iter_warmup = get_env_int('ITER_WARMUP', 1000)
    iter_sampling = get_env_int('ITER_SAMPLING', 1000)
    max_treedepth = get_env_int('MAX_TREEDEPTH', 15)
    target_accept = get_env_float('TARGET_ACCEPT', 0.95)

    n_attributes = len(attributes)
    n_respondents = len(respondent_ids)
    n_questions = best_choices.shape[1]

    # Convert inputs to PyTensor tensors
    best_choices = pt.as_tensor_variable(best_choices).astype('int64')
    worst_choices = pt.as_tensor_variable(worst_choices).astype('int64')

    try:
        with pm.Model() as maxdiff_model:
            # Hyperpriors
            mu = pm.Normal('mu', mu=0, sigma=1, shape=n_attributes)
            sigma = pm.HalfNormal('sigma', sigma=1, shape=n_attributes)
            
            # Non-centered individual-level parameterization
            beta_offset = pm.Normal('beta_offset', mu=0, sigma=1, shape=(n_respondents, n_attributes))
            beta = pm.Deterministic('beta', mu + sigma * beta_offset)
            
            # Reshape beta to match the dimensions of best_choices and worst_choices
            beta_reshaped = pt.tile(beta[:, None, :], (1, n_questions, 1))

            # Likelihood
            likelihood = maxdiff_logp(best_choices, worst_choices, beta_reshaped)
            pm.Potential('likelihood', likelihood)

            trace = pm.sample(
                draws=iter_sampling, 
                tune=iter_warmup, 
                chains=chains,
                cores=chains,
                random_seed=custom_encode(survey_id),
                nuts=dict(target_accept=target_accept, max_treedepth=max_treedepth),
                init='jitter+adapt_diag',
                return_inferencedata=True,
                nuts_sampler="blackjax" # Newly added, failure occurs
            )

        model_params = {
            'chains': chains,
            'iter_sampling': iter_sampling,
            'iter_warmup': iter_warmup,
        }

        return trace, model_params
    
    except Exception as e:
        logger.error(f"An error occurred while building or sampling the model: {str(e)}")
        logger.error("Traceback:")
        import traceback
        traceback.print_exc()
        return None, None
```

### Error message:

```shell
<details>
An error occurred while building or sampling the model: jax.core.Shape is deprecated. Use Shape = Sequence[int | Any].

Traceback (most recent call last):
  File "/opt/ml/processing/code/hb_model.py", line 118, in run_hb_model
    trace = pm.sample(
  File "/usr/local/lib/python3.10/dist-packages/pymc/sampling/mcmc.py", line 660, in sample
    return _sample_external_nuts(
  File "/usr/local/lib/python3.10/dist-packages/pymc/sampling/mcmc.py", line 332, in _sample_external_nuts
    idata = pymc_jax.sample_blackjax_nuts(
  File "/usr/local/lib/python3.10/dist-packages/pymc/sampling/jax.py", line 377, in sample_blackjax_nuts
    import blackjax
  File "/usr/local/lib/python3.10/dist-packages/blackjax/__init__.py", line 6, in <module>
    from .adaptation.chees_adaptation import chees_adaptation
  File "/usr/local/lib/python3.10/dist-packages/blackjax/adaptation/__init__.py", line 1, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/blackjax/adaptation/chees_adaptation.py", line 9, in <module>
    import optax
  File "/usr/local/lib/python3.10/dist-packages/optax/__init__.py", line 17, in <module>
    from optax import contrib
  File "/usr/local/lib/python3.10/dist-packages/optax/contrib/__init__.py", line 17, in <module>
    from optax.contrib.cocob import cocob
  File "/usr/local/lib/python3.10/dist-packages/optax/contrib/cocob.py", line 25, in <module>
    from optax._src import base
  File "/usr/local/lib/python3.10/dist-packages/optax/_src/base.py", line 19, in <module>
    import chex
  File "/usr/local/lib/python3.10/dist-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/usr/local/lib/python3.10/dist-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/usr/local/lib/python3.10/dist-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/usr/local/lib/python3.10/dist-packages/chex/_src/pytypes.py", line 53, in <module>
    Shape = jax.core.Shape
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 52, in getattr
    raise AttributeError(message)
</details>
```

### PyMC version information:

```
JAX Version: 0.4.30
```

```
# requirements.txt
numpy==1.23.5
pandas
boto3
gunicorn
pymc==5.6.1
arviz
scipy==1.10.1
requests
blackjax
pytensor
opt-einsum==3.3.0
tensorflow[and-cuda]
```

```
# Dockerfile
FROM nvcr.io/nvidia/jax:24.04-py3

# Set the working directory in the container
WORKDIR /opt/ml/processing/code

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  curl \
  vim \
  python3-dev \
  python3-pip \ 
  libblas-dev \
  liblapack-dev \
  && rm -rf /var/lib/apt/lists/*

ENV PYTENSOR_FLAGS="blas__ldflags=-lblas"
ENV XLA_FLAGS=""

RUN python3 -V

RUN pip install --upgrade pip

# Install NumPy with BLAS support
RUN pip install --no-cache-dir numpy==1.23.5

RUN pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# Copy requirements.txt into the container
COPY requirements.txt /opt/ml/processing/code/

# Install Python packages from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /opt/ml/processing/code
COPY . /opt/ml/processing/code

# Make the script executable
RUN chmod +x /opt/ml/processing/code/model.py

# Set the working directory for the processing script
WORKDIR /opt/ml/processing/code

ENTRYPOINT ["python", "/opt/ml/processing/code/model.py"]
```

**Comment by ricardoV94** [comment]
This seems like an issue in the optax package, so fsr removed from PyMC

**Comment by dooleyb1** [comment]
Seems it was a mismatch across multiple dependency versions. Managed to align them to get this fixed.
