### ISSUE TITLE
Revert travis to theano master

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#803]
Once https://github.com/Theano/Theano/issues/3319 is fixed, we should revert https://github.com/pymc-devs/pymc3/commit/3bde2af1be924bc51eb85d6f25e9328ea52b0969

Otherwise raises these errors:

```
======================================================================
ERROR: pymc3.tests.test_plots.test_plots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_plots.py", line 20, in test_plots
    h = find_hessian(start)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tuning/scaling.py", line 61, in find_hessian
    H = model.fastd2logp(vars)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 77, in fastd2logp
    return self.model.fastfn(hessian(self.logpt, vars))
  File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 230, in fastfn
    f = self.makefn(outs, mode, *args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 202, in makefn
    mode=mode, *args, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/function.py", line 316, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/pfunc.py", line 525, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/function_module.py", line 1526, in orig_function
    defaults)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/function_module.py", line 1390, in create
    input_storage=input_storage_lists)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/link.py", line 607, in make_thunk
    output_storage=output_storage)[:3]
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/vm.py", line 1025, in make_all
    no_recycling))
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 757, in make_thunk
    on_unused_input='ignore')
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/function.py", line 316, in function
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/pfunc.py", line 525, in pfunc
    output_keys=output_keys)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/function_module.py", line 1526, in orig_function
    defaults)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/compile/function_module.py", line 1390, in create
    input_storage=input_storage_lists)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/link.py", line 607, in make_thunk
    output_storage=output_storage)[:3]
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/vm.py", line 994, in make_all
    order = self.schedule(fgraph)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/link.py", line 374, in schedule
    return fgraph.toposort()
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/fg.py", line 645, in toposort
    order = graph.io_toposort(fg.inputs, fg.outputs, ords)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/graph.py", line 853, in io_toposort
    deps_cache=deps_cache)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/theano/gof/graph.py", line 785, in general_toposort
    raise ValueError('graph contains cycles')
ValueError: ('The following error happened while compiling the node', for{cpu,scan_fn}(Shape_i{0}.0, Subtensor{int64:int64:int8}.0, Shape_i{0}.0, Elemwise{exp}.0, Elemwise{gt,no_inplace}.0, Elemwise{exp}.0, Elemwise{abs_,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Elemwise{Composite{(Switch(i0, (-i1), i2) + log(i3))}}.0, InplaceDimShuffle{}.0), '\n', 'graph contains cycles')
```

**Comment by twiecki** [comment]
@nouiz This just happened starting yesterday without any changes on our end. Is it possible that this is caused by some change in theano master?

**Comment by DeliciousHair** [comment]
Any progress on this yet? Perhaps I should start digging through the errors to find the offending code...

**Comment by twiecki** [comment]
Not yet, we have to get the theano-devs' attention (ping @nouiz ;)). I have the feeling it's an up-stream problem and thus should be addressed there. Someone reported the problem running theano tests too: https://groups.google.com/forum/#!topic/theano-users/TNSWhKHylAI

**Comment by basveeling** [comment]
@twiecki I had the same issue, but after reinstalling scipy and numpy (both were already up to date) the error was gone.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/3344 contain a tmp fix to this.
