### ISSUE TITLE
Cannot construct a ufunc with more than 32 variables

### ISSUE THREAD

**Issue by PaulSorenson** [pymc-devs/pymc#850]
Not sure if this is a pymc3 or Theano thing but this is what I see from after grabbing the latest pymc3 and Theano from git just now.

```
import pymc3 as pm

with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sd=1)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-4deabab7431b> in <module>()
      2 
      3 with pm.Model() as model:
----> 4     mu = pm.Normal('mu', mu=0, sd=1)

/usr/local/lib/python3.4/site-packages/pymc3/distributions/distribution.py in __new__(cls, name, *args, **kwargs)
     20             data = kwargs.pop('observed', None)
     21             dist = cls.dist(*args, **kwargs)
---> 22             return model.Var(name, dist, data)
     23         elif name is None:
     24             return object.__new__(cls) #for pickle

/usr/local/lib/python3.4/site-packages/pymc3/model.py in Var(self, name, dist, data)
    224         if data is None:
    225             if getattr(dist, "transform", None) is None:
--> 226                 var = FreeRV(name=name, distribution=dist, model=self)
    227                 self.free_RVs.append(var)
    228             else:

/usr/local/lib/python3.4/site-packages/pymc3/model.py in __init__(self, type, owner, index, name, distribution, model)
    436             self.tag.test_value = np.ones(
    437                 distribution.shape, distribution.dtype) * distribution.default()
--> 438             self.logp_elemwiset = distribution.logp(self)
    439             self.model = model
    440 

/usr/local/lib/python3.4/site-packages/pymc3/distributions/continuous.py in logp(self, value)
    171 
    172         return bound(
--> 173             (-tau * (value - mu) ** 2 + log(tau / pi / 2.)) / 2.,
    174             tau > 0,
    175             sd > 0

/usr/local/lib/python3.4/site-packages/theano/tensor/var.py in __sub__(self, other)
    145         # and the return value in that case
    146         try:
--> 147             return theano.tensor.basic.sub(self, other)
    148         except (NotImplementedError, AsTensorError):
    149             return NotImplemented

/usr/local/lib/python3.4/site-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    552                 # compute output value once with test inputs to validate graph
    553                 thunk = node.op.make_thunk(node, storage_map, compute_map,
--> 554                         no_recycling=[])
    555                 thunk.inputs = [storage_map[v] for v in node.inputs]
    556                 thunk.outputs = [storage_map[v] for v in node.outputs]

/usr/local/lib/python3.4/site-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
   1000         self.update_self_openmp()
   1001         return super(OpenMPOp, self).make_thunk(node, storage_map,
-> 1002                                                 compute_map, no_recycling)
   1003 
   1004 

/usr/local/lib/python3.4/site-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
    737                 logger.debug('Trying CLinker.make_thunk')
    738                 outputs = cl.make_thunk(input_storage=node_input_storage,
--> 739                                         output_storage=node_output_storage)
    740                 fill_storage, node_input_filters, node_output_filters = outputs
    741 

/usr/local/lib/python3.4/site-packages/theano/gof/cc.py in make_thunk(self, input_storage, output_storage, keep_lock)
   1071         cthunk, in_storage, out_storage, error_storage = self.__compile__(
   1072             input_storage, output_storage,
-> 1073             keep_lock=keep_lock)
   1074 
   1075         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

/usr/local/lib/python3.4/site-packages/theano/gof/cc.py in __compile__(self, input_storage, output_storage, keep_lock)
   1013                                     input_storage,
   1014                                     output_storage,
-> 1015                                     keep_lock=keep_lock)
   1016         return (thunk,
   1017                 [link.Container(input, storage) for input, storage in

/usr/local/lib/python3.4/site-packages/theano/gof/cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, keep_lock)
   1439             module = self.compile_cmodule()
   1440         else:
-> 1441             module = get_module_cache().module_from_key(
   1442                 key=key, lnk=self, keep_lock=keep_lock)
   1443 

/usr/local/lib/python3.4/site-packages/theano/gof/cc.py in get_module_cache(init_args)
     83     be forwarded to the ModuleCache constructor as keyword arguments.
     84     """
---> 85     return cmodule.get_module_cache(config.compiledir, init_args=init_args)
     86 
     87 

/usr/local/lib/python3.4/site-packages/theano/gof/cmodule.py in get_module_cache(dirname, init_args)
   1388         init_args = {}
   1389     if _module_cache is None:
-> 1390         _module_cache = ModuleCache(dirname, **init_args)
   1391         atexit.register(_module_cache._on_atexit)
   1392     elif init_args:

/usr/local/lib/python3.4/site-packages/theano/gof/cmodule.py in __init__(self, dirname, check_for_broken_eq, do_refresh)
    615 
    616         if do_refresh:
--> 617             self.refresh()
    618 
    619     age_thresh_use = 60 * 60 * 24 * 24    # 24 days

/usr/local/lib/python3.4/site-packages/theano/gof/cmodule.py in refresh(self, age_thresh_use, delete_if_problem, cleanup)
    722                     try:
    723                         with open(key_pkl, 'rb') as f:
--> 724                             key_data = pickle.load(f)
    725                     except EOFError:
    726                         # Happened once... not sure why (would be worth

/usr/local/lib/python3.4/site-packages/theano/tensor/elemwise.py in __setstate__(self, d)
    516         elif self.scalar_op.nin > 0:
    517             self.ufunc = numpy.frompyfunc(self.scalar_op.impl,
--> 518                     self.scalar_op.nin, self.scalar_op.nout)
    519         self._rehash()
    520 

ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 37 and outputs = 1)
```

**Comment by jsalvatier** [comment]
I don't see how you could be creating a ufunc with 32 ops here. Not sure why it should be creating a ufunc at all for that matter.

Can you ask the same question on the theano issue list?

**Comment by PaulSorenson** [comment]
As an exercise I just rebuilt my environment in Python 3.5 with fresh packages from PyPi then latest Theano and pymc3 from github and problem has gone away.

For now I am going to assume this is some weirdness with my environment and will hopefully go back and investigate in 3.4

**Comment by twiecki** [comment]
I'm running into the same issue in the `getting_started` notebook on the cell

``` python
from pymc3.glm import glm

with Model() as model_glm:
    glm('y ~ x1 + x2', df)
```

**Comment by twiecki** [comment]
I wonder if this might be related to numpy 1.10.

**Comment by twiecki** [comment]
https://github.com/Theano/Theano/issues/3052

**Comment by twiecki** [comment]
This PR fixed it for me: https://github.com/Theano/Theano/pull/3532

**Comment by twiecki** [comment]
The theano fix was merged. I updated travis to use theano master https://github.com/pymc-devs/pymc3/commit/04c0ab4cd858855438f47c0e6e2c65c6b3f1d9d4. This issue should be fixed now.

**Comment by jghigginson78** [comment]
I note that this issue is closed but I get the error trying to run code that worked well before I updated packages about 10 days ago. I am now using the most recent versions of pymc3 and Theano. Can you advise what else I should do?

**Comment by fonnesbeck** [comment]
You are using a recnet build of Theano from master? Try clearing your ~/.theano directory. It sometimes holds on to compiled code.

**Comment by jghigginson78** [comment]
Thanks Chris. That seems to have done the trick

**Comment by DeliciousHair** [comment]
I'm getting this issue now trying to use the example on the 'getting-started' page:

```
import numpy as np
from pymc3 import *
import theano.tensor as tt
from scipy.optimize import fmin_powell

np.random.seed(42)
theta_true = (25, 0.5)
X = 100 * np.random.random(20)
Y = theta_true[0] + theta_true[1] * X

# add scatter to points
X = np.random.normal(X, 10)
Y = np.random.normal(Y, 10)

with Model() as model:
    alpha = Uniform('intercept', -100, 100)

    # Create custom densities
    beta = DensityDist('beta', lambda value: -1.5 * tt.log(1 + value**2), testval=0)
    eps = DensityDist('eps', lambda value: -tt.log(tt.abs_(value)), testval=1)

    # Create likelihood
    like = Normal('y_est', mu=alpha + beta * X, sd=eps, observed=Y)

    # Go to town!
    start = find_MAP(fmin=fmin_powell)
    step = NUTS(scaling=start)
    trace = sample(50000, step, start=start)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7fa21bff0c90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 50 and outputs = 1)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7fa21bff0c90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 38 and outputs = 1)

 [-----------------100%-----------------] 50000 of 50000 complete in 74.5 sec
```

Interestingly however, this example manages to charge through regardless of the numerous errors, but I don't know if they are any good--I did not try it previously so don't have have a baseline to compare to, but it doesn't seem to converge terribly well.

I've upgraded to the most current build of both pymc3 and theano, and have wiped out my `~/.theano` directory as well. Also recently upgraded to the most current numpy version:

```
In [2]: np.__version__
Out[2]: '1.10.1'
```

Any suggestions?

(I should also mention that this issue is appearing when trying to use theano in this manner, using the provided densities and distributions does not seem to invoke this problem)

**Comment by fonnesbeck** [comment]
I can't replicate the problem above; the model runs fine for me, so it likely means your environment isn't what you think it is. Are you using Anaconda? If so, can you create a clean environment and try it there?

**Comment by DeliciousHair** [comment]
No anaconda, no.  Environment sounds quite likely then, I'll try a few things to see if I can track down what I may have broken. Thanks!

**Comment by DeliciousHair** [comment]
Just in case anyone else finds this, the problem was due to the fact that cython was not upgraded with scipy and / or numpy for some reason, which in turn seems to have propagated the breakage through without telling me. Upgrading that (and reinstalling everything else) fixed everything nicely.

**Comment by twiecki** [comment]
Thanks for the info @DeliciousHair. Glad it's working.
