### ISSUE TITLE
Problems creating a new step method

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#861]
I am trying to learn how PyMC3 works, and failing ;-). 
As an exercise I am attempting to create a new step method by modifying metropolis.py
Essentially I want to take the proposed new value (q), do a new perturbation and then use the metropolis criteria to accept/reject that value. 

inside the function `astep()` I have

``` python
algo = self.delta_logp(q,q0)
otro = self.test(algo)
print(algo, otro) # check if the function works
q_new = metrop_select(otro, q, q0)
```

my test function looks like this:

``` python
def test(logp, vars, shared):
    dlogp = theano.grad(logp, vars)
    f = theano.function([vars], z)
    f.trust_input = True
    return f
```

if  `z= dlogp` I get the gradient of logp (as expected)
if  `z= vars` I get the that the output (otro) and the input (algo) variables are the same (as expected)
but if  `z= vars-dlogp` I get the error `TypeError: can't multiply sequence by non-int of type 'list'`

I also tried with a different test function

``` python
def test(logp, vars, shared):
    [dlogp], a = join_nonshared_inputs([gradient(logp, vars)], vars, shared)
    z = a - dlogp# * 0.0001 
    f = theano.function([a], z)
    f.trust_input = True
    return f
```

Now I get the following error:

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
TypeError: Number of dimensions lower than expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 47, in <module>
    trace = pm.sample(100, step, start=start)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/sampling.py", line 155, in sample
    return sample_func(*sample_args)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/sampling.py", line 164, in _sample
    for i, strace in enumerate(sampling):
  File "/usr/local/lib/python3.4/dist-packages/pymc3/sampling.py", line 246, in _iter_sample
    point = step.step(point)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/arraystep.py", line 118, in step
    apoint = self.astep(bij.map(point))
  File "/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/mcm.py", line 128, in astep
    otro = self.test(algo)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 206, in raise_with_op
    raise exc_type(exc_value).with_traceback(exc_trace)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
TypeError: Number of dimensions lower than expected
Apply node that caused the error: Shape_i{0}(inarray)
Inputs types: [TensorType(float64, vector)]
Inputs shapes: [()]
Inputs strides: [()]
Inputs values: [array(-6.5229534804823)]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

I would really appreciate if someone could point me how to do this properly and what I am doing wrong. Thanks in advance.

**Comment by twiecki** [comment]
I'm a bit puzzled at what you're trying to do and what the variables mean. Shouldn't the step-method just contain proposals that are numpy vectors?

**Comment by aloctavodia** [comment]
Is just an example, nothing serious. I am doing an steepest descent step. I
need the value of the variables you are sampling and the gradient at that
point.
