### ISSUE TITLE
as_op not accepting multiple inputs (AttributeError: 'int' object has no attribute 'type')

### ISSUE THREAD

**Issue by DeliciousHair** [pymc-devs/pymc#878]
Maybe not the best place to be asking, but I'm at a loss to figure out what I'm doing wrong...

I need to define my own distribution for a project, and unfortunately I need to use an operation not supported directly by `theano`; an incomplete gamma function specifically.  The one provided by `scipy.special.gammaincc` works perfectly for my needs, and seems fast enough so I was going to go with that instead of resorting to FORTRAN, except I need to call it as `gammaincc(val, mu)` which means I need to send two values to my `logp` method, which seems to break everything.

To demonstrate what I'm having trouble with, here is a pointless demo that captures my problem.  It's jibberish, but it does capture the behaviour that's got me stumped.

```
from pymc3 import *
from pymc3.distributions import Continuous
import theano.tensor as tt
from theano.compile.ops import as_op

class ThisWorks(Continuous):
    def __init__(self, mu, *args, **kwargs):
        super(ThisWorks, self).__init__(*args, **kwargs)
        self.mu = mu

    def logp(self, val):
        mu = self.mu
        return my_logp(val + mu)

@as_op(itypes=[tt.dscalar], otypes=[tt.dvector])
def my_logp(a):
    return a

with Model() as model:
    demo = ThisWorks('demo', mu=10, testval=10)
```

while this falls over:

```
class ThisFails(Continuous):
    def __init__(self, mu, *args, **kwargs):
        super(ThisFails, self).__init__(*args, **kwargs)
        self.mu = mu

    def logp(self, val):
        mu = self.mu
        return my_logp(val, mu)

@as_op(itypes=[tt.dscalar, tt.dscalar], otypes=[tt.dscalar])
def my_logp(a, b):
    return a + b

with Model() as model:
    demo = ThisFails('demo', mu=10, testval=10)


AttributeError                            Traceback (most recent call last)
<ipython-input-43-46875bf49e2b> in <module>()
     13 
     14 with Model() as model:
---> 15     demo = SomeDist('demo', mu=10, testval=10)

/usr/local/lib/python2.7/dist-packages/pymc3/distributions/distribution.pyc in __new__(cls, name, *args, **kwargs)
     22             data = kwargs.pop('observed', None)
     23             dist = cls.dist(*args, **kwargs)
---> 24             return model.Var(name, dist, data)
     25         elif name is None:
     26             return object.__new__(cls) #for pickle

/usr/local/lib/python2.7/dist-packages/pymc3/model.pyc in Var(self, name, dist, data)
    224         if data is None:
    225             if getattr(dist, "transform", None) is None:
--> 226                 var = FreeRV(name=name, distribution=dist, model=self)
    227                 self.free_RVs.append(var)
    228             else:

/usr/local/lib/python2.7/dist-packages/pymc3/model.pyc in __init__(self, type, owner, index, name, distribution, model)
    436             self.tag.test_value = np.ones(
    437                 distribution.shape, distribution.dtype) * distribution.default()
--> 438             self.logp_elemwiset = distribution.logp(self)
    439             self.model = model
    440 

<ipython-input-43-46875bf49e2b> in logp(self, val)
      6     def logp(self, val):
      7         mu = self.mu
----> 8         return my_logp(val, mu)
      9 
     10 @as_op(itypes=[tt.dscalar, tt.dscalar], otypes=[tt.dscalar])

/usr/local/lib/python2.7/dist-packages/theano/gof/op.pyc in __call__(self, *inputs, **kwargs)
    505         """
    506         return_list = kwargs.pop('return_list', False)
--> 507         node = self.make_node(*inputs, **kwargs)
    508 
    509         if config.compute_test_value != 'off':

/usr/local/lib/python2.7/dist-packages/theano/compile/ops.pyc in make_node(self, *inputs)
    486     def make_node(self, *inputs):
    487         assert len(inputs) == len(self.itypes)
--> 488         assert all(inp.type == it for inp, it in zip(inputs, self.itypes))
    489         return theano.Apply(self, inputs, [o() for o in self.otypes])
    490 

/usr/local/lib/python2.7/dist-packages/theano/compile/ops.pyc in <genexpr>((inp, it))
    486     def make_node(self, *inputs):
    487         assert len(inputs) == len(self.itypes)
--> 488         assert all(inp.type == it for inp, it in zip(inputs, self.itypes))
    489         return theano.Apply(self, inputs, [o() for o in self.otypes])
    490 

AttributeError: 'int' object has no attribute 'type'
```

Note that in the second case I have done `@as_op(itypes=[tt.dscalar, tt.dscalar], otypes=[tt.dscalar])` which seems correct to me from the documentation.

Stumped...

**Comment by fonnesbeck** [comment]
In your example, the argument `mu` you have added is a Python primitive, so it does not have a Theano data type. How about this?

``` python
class ThisFails(Continuous):
    def __init__(self, mu, *args, **kwargs):
        super(ThisFails, self).__init__(*args, **kwargs)
        self.mu = shared(float(mu))

    def logp(self, val):
        return my_logp(val, self.mu)

@as_op(itypes=[tt.dscalar, tt.dscalar], otypes=[tt.dscalar])
def my_logp(a, b):
    return a + b

with Model() as model:
    demo = ThisFails('demo', mu=10, testval=10)
```

**Comment by DeliciousHair** [comment]
Ah, I think that may have done it--and I think I even understand the answer as well.  Thanks!

**Comment by fonnesbeck** [comment]
That's excellent news!

**Comment by DeliciousHair** [comment]
Doh!  OK, it makes sense, but there is a further hitch...

I'm doing something like this:

```
with model:                          
    mu = Gamma('mu', alpha=alpha, beta=beta)
    X_obs = MyNewDistribution('X_obs', mu=mu, observed=X)
.
.
.
TypeError:  Shared variable constructor needs numeric values and not symbolic variables.
```

which also makes sense.  Except I don't really see a way around this. Sorry, I'm not at all familiar with the workings of theano, if there isn't an 'obvious' fix, could you perhaps point me to the relevant documentation?

Thanks again!

(FWIW, I'm going through all this as my data is best described by a 'continuous Poisson distribution', which is rather cleanly laid out in http://ac.inf.elte.hu/Vol_039_2013/137_39.pdf The lack of an incomplete gamma function is a pain, but I've sorted out that part. Now just to get it play nice with theano...)

**Comment by twiecki** [comment]
```
======================================================================
ERROR: test_column_names (pymc3.tests.test_stats.TestDfSummary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_stats.py", line 350, in test_column_names
    ds = df_summary(self.mtrace, batches=3)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 336, in df_summary
    if varnames is None:
UnboundLocalError: local variable 'varnames' referenced before assignment
======================================================================
ERROR: test_column_names_custom_function (pymc3.tests.test_stats.TestDfSummary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_stats.py", line 365, in test_column_names_custom_function
    ds = df_summary(self.mtrace, batches=3, stat_funcs=[customf])
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 336, in df_summary
    if varnames is None:
UnboundLocalError: local variable 'varnames' referenced before assignment
======================================================================
ERROR: test_column_names_custom_function_extend (pymc3.tests.test_stats.TestDfSummary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_stats.py", line 373, in test_column_names_custom_function_extend
    stat_funcs=[customf], extend=True)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 336, in df_summary
    if varnames is None:
UnboundLocalError: local variable 'varnames' referenced before assignment
======================================================================
ERROR: test_column_names_decimal_hpd (pymc3.tests.test_stats.TestDfSummary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_stats.py", line 356, in test_column_names_decimal_hpd
    ds = df_summary(self.mtrace, batches=3, alpha=0.001)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 336, in df_summary
    if varnames is None:
UnboundLocalError: local variable 'varnames' referenced before assignment
======================================================================
ERROR: test_value_alignment (pymc3.tests.test_stats.TestDfSummary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_stats.py", line 380, in test_value_alignment
    ds = df_summary(mtrace, batches=3)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 336, in df_summary
    if varnames is None:
UnboundLocalError: local variable 'varnames' referenced before assignment
```
