### ISSUE TITLE
theano errors with NUTS sampling in super simple model

### ISSUE THREAD

**Issue by tachim** [pymc-devs/pymc#926]
Here's the model:

``` python
    x = pm.Uniform('x', lower=0, upper=1)
    #x = pm.Normal('x', 1, 1)
    x2 = pm.Potential('x2', -x ** 2)

    start = model.test_point
    step = pm.NUTS(vars=model.vars)
    pm.summary(pm.sample(5000, step, start), vars=['x'])
```

A ton of these errors show up when running the above:

```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f6e510fee50>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f6e510fee50>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/afs/cs.stanford.edu/u/tachim/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/afs/cs.stanford.edu/u/tachim/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/afs/cs.stanford.edu/u/tachim/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/afs/cs.stanford.edu/u/tachim/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/afs/cs.stanford.edu/u/tachim/anaconda/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 51 and outputs = 1)
```

**Comment by fonnesbeck** [comment]
You should be able to fix this by installing Theano from master. See #850

**Comment by tachim** [comment]
Thanks - that did the trick.
